### ISSUE TITLE
Change Application Name

### ISSUE THREAD

**Issue by larasawalha90** [MicrosoftDocs/entra-docs#10]
Customer is trying to implement the conditional access suggested in the article but cannot find the application "Microsoft Azure management".

The application mentioned above changed to "Windows Azure Service Management API" (appId: 797f4846-ba00-4fd7-ba43-dac1f8f63013).

Can you please update it so customers don't get confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22df42c6-831d-ba42-8224-27176e8fd7d9
* Version Independent ID: 15299b18-e361-9e9f-f836-f37a466dcae0
* Content: [Require MFA for Azure management with Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-azure-management)
* Content Source: [docs/identity/conditional-access/howto-conditional-access-policy-azure-management.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/howto-conditional-access-policy-azure-management.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by RamanathanChinnappan-MSFT** [comment]
@larasawalha90
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Flagging @MicrosoftGuyJFlo for visibility

**Comment by RamanathanChinnappan-MSFT** [comment]
@larasawalha90 
Thanks for your feedback! We will investigate and update as appropriate.
