### ISSUE TITLE
There's no page TOC on the right side

### ISSUE THREAD

**Issue by copdips** [MicrosoftDocs/entra-docs#100]
Hello,

Microsoft documentation has a very beautiful look, but it seems that we only have the global navigatiion on the left side, but we do not have the in page TOC on the right side, which makes the in page navigation difficult, could you please add it ? 

![image](https://github.com/MicrosoftDocs/entra-docs/assets/13083856/6243b917-101f-456d-8c94-0283604f6b80)

I attach below screenshot of a [fastapi doc example](https://fastapi.tiangolo.com/deployment/docker/) to show you what I would like to see in red:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/13083856/d75c0537-fc72-4127-898d-0ab1e09c39cb)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7efb7b80-263b-5a15-f8f4-356354586e34
* Version Independent ID: 643bac5c-10c6-e034-f596-fddb89cc1133
* Content: [Glossary of terms in the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/developer-glossary)
* Content Source: [docs/identity-platform/developer-glossary.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/developer-glossary.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by ManoharLakkoju-MSFT** [comment]
@copdips 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Hello @copdips - Thank you for your feedback. The example you showed here is controlled by the Microsoft Learn platform and we don’t have control over where the page subheadings and links appear on the page. Previously, it was on the right side like the example you showed. However, the platform team moved the subheadings and links to the top of the article and the right side is now a Recommendations section. 

We will pass along your feedback to our platform team. They’re continually making feature updates and improvements to the Learn platform so you may very well see the subheadings get moved back to the right in future. 

#please-close
