### ISSUE TITLE
parameter InviteRedirectUrl is required for command New-MgInvitation 

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/entra-docs#1006]
you mentioned this in this documentation [Tutorial: Bulk invite Microsoft Entra B2B collaboration users](https://docs.azure.cn/en-us/entra/external-id/tutorial-bulk-invite)

but you did not mention it here [Tutorial: Use PowerShell to bulk invite Microsoft Entra B2B collaboration users](https://docs.azure.cn/en-us/entra/external-id/bulk-invite-powershell)

https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/bulk-invite-powershell.md

---
#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: 8984951b-7ece-4964-ed6e-5266174d2ffb
* Version Independent ID: 163b743d-fd7f-9c50-f01c-79a4521c5236
* Content: [Tutorial for bulk inviting B2B collaboration users - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/bulk-invite-powershell)
* Content Source: [docs/external-id/bulk-invite-powershell.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/bulk-invite-powershell.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by chucklu** [comment]
anyone knows where can I submit issue for command [New-MgInvitation](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mginvitation?view=graph-powershell-1.0)?
this documentation should remove the [] for the required parameter , as [] means optional parameter.  This documentation [New-AzureADMSInvitation]( https://learn.microsoft.com/bs-latn-ba/powershell/module/Azuread/new-azureadmsinvitation?view=azureadps-2.0-preview) is a good example

**Comment by TPavanBalaji** [comment]
@chucklu 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@chucklu 
I'm going to assign this to the document author so they can take a look at it accordingly.

@csmulligan 
please review it.

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue. Have also notified the content dev. Thank you.

#please-close
