### ISSUE TITLE
Installation folder in docs renamed 

### ISSUE THREAD

**Issue by crmhh** [MicrosoftDocs/entra-docs#101]
You have renamed the installation folder to Entra Connect:
"Navigate to the $env:ProgramFiles"\Microsoft Entra Connect" folder."

In an up to date system the correct (default) folder is: "C:\Program Files\Microsoft Azure Active Directory Connect"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f01328-ebfa-31af-4e67-6de92c8f924e
* Version Independent ID: a990551f-e6c9-dede-308a-b5578fb7ee1e
* Content: [Microsoft Entra Connect - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sso-faq#how-can-i-disable-seamless-sso-)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sso-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sso-faq.yml)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ManoharLakkoju-MSFT** [comment]
@crmhh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@billmath 
Can you please check and add your comments on this doc update request as applicable.

**Comment by billmath** [comment]
This is fixed.  Thanks for catching.

#please-close
