### ISSUE TITLE
Step #7 in Register passkey in Authenticator app on android device is incorrect

### ISSUE THREAD

**Issue by anandanthony** [MicrosoftDocs/entra-docs#1014]
I was following the steps mentioned in the article - https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-register-passkey-authenticator?tabs=Android#same-device-registration-using-direct-sign-in-to-authenticator-android.

It seems that the latest android version on my device does not show the `Additional providers` section to add the Authenticator app. This is blocker to add a passkey. Please update the documentation. The android version on my device is 14.

---
#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: bf0a2fcb-d5f4-6916-eb36-e84776a8b6c4
* Version Independent ID: bf0a2fcb-d5f4-6916-eb36-e84776a8b6c4
* Content: [Register passkeys in Authenticator on Android and iOS devices in MySecurityInfo (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-register-passkey-authenticator?tabs=Android#same-device-registration-using-direct-sign-in-to-authenticator-android)
* Content Source: [docs/identity/authentication/how-to-register-passkey-authenticator.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-register-passkey-authenticator.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@anandanthony 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@anandanthony 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue. 

#please-close
