### ISSUE TITLE
Missing Licenses (SKUs) from Table and CSV

### ISSUE THREAD

**Issue by ckarawani** [MicrosoftDocs/entra-docs#1019]
The following License SKUS are missing from both the table and csv export hosted at 
https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv

* `PHONESYSTEM_VIRTUALUSER_FACULTY` - `0e142028-345e-45da-8d92-8bfd4093bbb9` - Microsoft Teams Phone Resource Account for Faculty
* `MCOCAP_FACULTY` - `420c7602-7f70-4895-9394-d3d679ea36fb` - Microsoft Teams Shared Devices for Faculty
*  `MCOPSTN_5` - `11dee6af-eca8-419f-8061-6864517c1875` - Microsoft 365 Domestic Calling Plan (120 Minutes)
*  `Microsoft_Teams_Calling_Plan_pay_as_you_go_(country_zone_1)` - `dbd31205-338e-4dec-903d-44402e305e32` - Microsoft Teams Calling Plan pay-as-you-go (country zone 1 - UK/Canada)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by PesalaPavan** [comment]
@ckarawani 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by ckarawani** [comment]
hey @PesalaPavan sure thing!

The csv doc is linked from the documentation page at https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/33da52cd-ac73-46bb-9b01-862d08e2b4b4">

The markdown document is for that page is here:
https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md

I would have opened a PR but the .csv that is linked does not seem to be in version control

**Comment by Naveenommi-MSFT** [comment]
@ckarawani 
Thank you for bringing this to our attention.
I've delegated this to content author @Nicholak-MS, who will review it and offer their insightful opinions.

Note: Thanks for your feedback and your contribution to Azure docs.
Feedback for this repository is moving away from GitHub to a system specific to the Microsoft Learn platform. Issues for this repository will soon be disabled, and additional comments from GitHub will no longer be possible. However, we are now tracking and triaging this issue in the new feedback system.
To learn more about our feedback systems, please see [Provide feedback for Microsoft Learn content](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fcontentuserfeedback&data=05%7C02%7Cv-ommikumar%40microsoft.com%7C2469fb0ee4e14243d7ff08dcaa6acfb0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638572622992825118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=kC5WOp10fV1oVhsLEFTHEzjLo6HeVUbxU%2Fe%2F5z8TTU8%3D&reserved=0).

**Comment by mattgies** [comment]
+1 to MCOPSTN_5. It appears that the docs have the same plan listed, but with a different String ID and Sku GUID

Docs currently have:
- String ID: "MCOPSTN5"
- Sku GUID: "54a152dc-90de-4996-93d2-bc47e670fc06"

From my Teams tenant I see:
- String ID: "MCOPSTN_5"
- Sku GUID: "11dee6af-eca8-419f-8061-6864517c1875"

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue. Have also notified PM.

#please-close
