### ISSUE TITLE
Dynamic membership AND vs OR

### ISSUE THREAD

**Issue by SerolfDivad** [MicrosoftDocs/entra-docs#102]
[Enter feedback here]

So I'm looking at the example:

> user.memberof -any (group.objectId -in ['groupId', 'groupId'])

I assume that the "-any" operator is performing an "OR" operation? I tried creating a dynamic rule using the "-all" operator and I got an error. Is that not allowed? I am trying to populate a dynamic group with individuals who are memberw of two other groups, but they MUST be members of BOTH  groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a30c67d5-6cc0-16f3-db2a-8244d7344aa3
* Version Independent ID: ab230d40-68c6-3a1f-c4c3-12d4a76e42df
* Content: [Group membership for Microsoft Entra dynamic groups with memberOf - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-rule-member-of)
* Content Source: [docs/identity/users/groups-dynamic-rule-member-of.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-dynamic-rule-member-of.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ManoharLakkoju-MSFT** [comment]
@SerolfDivad 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @SerolfDivad 
You are correct that the `-any` operator performs an "OR" operation. It means that if a user is a member of any of the groups listed in the `['groupId', 'groupId']` array, then they will be included in the dynamic group.

Regarding your question about the `-all` operator, it performs an "AND" operation. This means that a user must be a member of all the groups listed in the array to be included in the dynamic group. However, according to the documentation, the `-all` operator is not currently supported for the `memberOf` attribute. This is likely why you received an error when you tried to create a dynamic rule using the `-all` operator. If you need to create a dynamic group that includes users who are members of two specific groups, you can use the `-any` operator to create a rule that includes both groups. For example:

`user.memberof -any (group.objectId -eq 'groupId1' -or group.objectId -eq 'groupId2')`

This rule will include users who are members of either `groupId1` or `groupId2`, but not users who are only members of one of the groups.

**Comment by Naveenommi-MSFT** [comment]
@SerolfDivad 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by SerolfDivad** [comment]
I'm sorrym bit I get a "Failed to save group" error when I try that syntax.

**Comment by Naveenommi-MSFT** [comment]
@SerolfDivad 
If still you need help with this, please log a case here: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. Thank you.
