### ISSUE TITLE
Document is incorrect. 

### ISSUE THREAD

**Issue by michaelitrn2** [MicrosoftDocs/entra-docs#103]
I just had a support case with Microsoft and Verified the documentation is incorrect as the user who initiates verification must be a member of the Global Administrator role in the Microsoft Entra ID. Document should be updated as follow:

The user who initiates verification must be authorized to make changes both to the app registration in Microsoft Entra ID and to the CPP account in Partner Center. The user who initiates the verification must have one of the required roles in both Microsoft Entra ID and Partner Center.

In Microsoft Entra ID, this user must be a member of one of the following [role](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference): Global Administrator.

In Partner Center, this user must have one of the following [roles](https://learn.microsoft.com/en-us/partner-center/permissions-overview):  Global Administrator (a shared role that's mastered in Microsoft Entra ID).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f83478f0-0faa-2e10-37f2-819ad2351445
* Version Independent ID: 3ffd5b35-a3d7-5dca-dc8b-acec1d85ec3c
* Content: [Publisher verification overview - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/publisher-verification-overview)
* Content Source: [docs/identity-platform/publisher-verification-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/publisher-verification-overview.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by ManoharLakkoju-MSFT** [comment]
@michaelitrn2 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@michaelitrn2 
I've delegated this to @rwike77, a content author, to review and share their valuable insights.

**Comment by rwike77** [comment]
@michaelitrn2  Thanks for reporting this.  I talked to engineering and got the following:  

We have made no changes to the role requirements. There are some scenarios in which it is simpler for the user initiated to have Global Admin rights (guest users come to mind) but it is not a requirement to have Global Admin over the other supported roles.  

Can you share any errors you encountered or details that led you to create a support incident?   Adding @xurobertMSFT

**Comment by rwike77** [comment]
@michaelitrn2  I haven't heard back, I'm going to close this issue now.  Feel free to reopen if you have additional information  Thanks.  #please-close
