### ISSUE TITLE
MSAL.js 3.0 missing from Entra documentation

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/entra-docs#1030]
I've been recently looking into using the MSAL.js library to enable Entra ID AuthN/AuthZ in one of the applications I am working on. I found it very confusing that I barely see any reference to 3.0 of the library in the docs. Here are two examples in the docs that only reference 1.0 and 2.0.

https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-app-configuration?tabs=javascript2
https://learn.microsoft.com/en-us/entra/identity-platform/msal-js-initializing-client-applications

And from the following, it seems that 3.0 of the library has been GA'ed for almost a year.

https://devblogs.microsoft.com/identity/msal-js-v3-release/

Are the doc updates for 3.0 still in progress? Or is MSAL.js 3.0 not recommended for production use?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6e5855-ef79-2759-6773-f3a44886cb14
* Version Independent ID: 73154754-ea03-f123-3506-9173f7472322
* Content: [Configure single-page app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-app-configuration?tabs=javascript2)
* Content Source: [docs/identity-platform/scenario-spa-app-configuration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-spa-app-configuration.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by PesalaPavan** [comment]
@felixtsem5 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@felixtsem5 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@OwenRichards1 please review it.

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue.

#please-close
