### ISSUE TITLE
Steps to Configure a custom signing key that will work with multi-tenant apps are unclear

### ISSUE THREAD

**Issue by mbuotidem** [MicrosoftDocs/entra-docs#104]
My use case is that I want to configure a multi-tenant app such that users in other Azure tenants can sign in to my SAAS app, but I also want them to be able to set specific custom claims using the steps defined here : https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization#view-or-edit-claims.

As it stands, I meandered through the steps, and kinda got there, but I'm not sure. I'm able to set the custom claim on the enterprise in my tenant, and see it show up in the JWT. However, when I try from my test tenant, I encounter the error `AADSTS50146: This application is required to be configured with an application-specific signing key. It is either not configured with one, or the key has expired or is not yet valid.` 

Therefore, I'm left wondering if a. I configured something wrong because the documentation was unclear, or b. I completely misunderstood the documentation and what I'm trying to do isn't even supported. It would be nice if the documentation covered the multi-tenant use case in greater detail than it currently does and succinctly explains in a step by step manner what one needs to do set it up properly.  When I use Microsoft graph to call `https://graph.microsoft.com/v1.0/servicePrincipals/service-principal-object-id`, I can see that both `keyCredentials` and `passwordCredentials` keys  are populated in my tenant, but are empty lists in my test tenant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33741171-b5be-f59f-804a-a2fd252a399c
* Version Independent ID: c393e85e-a879-e98b-1a1a-cd4f85af6c42
* Content: [Customize app JSON Web Token (JWT) claims (Preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization)
* Content Source: [docs/identity-platform/jwt-claims-customization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/jwt-claims-customization.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by ManoharLakkoju-MSFT** [comment]
@mbuotidem 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@mbuotidem 
Thank you for bringing this to our attention.
I've delegated this to content author @cilwerner, who will review it and offer their insightful opinions.

**Comment by CelesteDG** [comment]
Flagging @cilwerner - Chris, please review this issue assigned to you.

**Comment by cilwerner** [comment]
@mbuotidem, yes, odd that it works for Microsoft Graph, but not your own SaaS app. You're right, the multi-tenant scenario needs to be clearer. What sort of certificate are you using? A self signed one for testing or from a trusted authority. 

I'm also looping @rahul-nagraj who may also have insights on this. @rahul-nagraj, I take it there's a missing step here in the doc or prerequisites, rather than a case of this is not possible.

**Comment by rahul-nagraj** [comment]
Hi @mbuotidem,
Did you check out the section on security considerations for JWT claims: https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization#security-considerations

It specifically talks about the error which you are getting and sets out guidelines on how to configure customer signing key for multi-tenant apps. 
Please let us know if you have any further quesitons.

**Comment by mbuotidem** [comment]
@cilwerner 
>What sort of certificate are you using? A self signed one for testing or from a trusted authority.

I'm using a self signed certificate created either using openssl  or via calling the graph endpoint `addTokenSigningCertificate`. Was I wrong to use either of those? 

@rahul-nagraj 
>Did you check out the section on security considerations for JWT claims

Yes, I read and re-read that entire page multiple times, and I followed the steps under the configure a custom signing key to request one passing in my `keyCredentials` and `passwordCredentials` and and still got the error. I should have clarified that in my initial post. 

I'm going to redo the steps from scratch this weekend and maybe even record a video to show exactly what I do and how the error comes up. My understanding was that if I configured the custom signing key, I shouldn't have that error. 

Also, something that wasn't clear to me is, the HTTP PATCH request to add a custom signing key to a service principal in my account - only I need to do that as the creator of the SAAS multitenant app, right? The end users who install the app in their own Azure tenant's shouldn't need to do anything, correct?

**Comment by cilwerner** [comment]
For testing purposes, then using a self signed certificate is fine. But when in production, I wouldn't recommend it for software being used by external users, and instead go through a certificate authority (but that's a different issue).

Not sure if videos can be uploaded here, but if you use screenshots, **_you must ensure_** to remove any sensitive information like secret values, tenant and client IDs.

**Comment by cilwerner** [comment]
Hi @mbuotidem, have you had any success in your last attempt?
