### ISSUE TITLE
SSPR Connectivity - Details for European Customers

### ISSUE THREAD

**Issue by heikobischoff** [MicrosoftDocs/entra-docs#1044]
For European customers, Self-Service Password Reset (SSPR) utilizes Service Bus, initially hosted in West Europe and North Europe.

Service Bus Subnets:
* 40.87.128.0/19 (ssprdedicatedsbprodneu.servicebus.windows.net)
* 20.105.128.0/17 (ssprdedicatedsbprodweu.servicebus.windows.net)
* These subnets have been allowed through the firewall.
* IP addresses were extracted from the Microsoft Azure IP Ranges and Service Tags for Public Cloud documentation.

Issue:
SSPR suddenly stopped functioning as it attempted to connect to ssprdedicatedsbprodfra-1.servicebus.windows.net (20.111.28.147). The fallback to previously working endpoints, verified via heartbeat according to application logs, failed. This necessitated the deactivation and reactivation of the feature.
The new endpoint ins France has not been allowed through the firewall.

Desired Outcome:
A more detailed statement regarding the specific endpoints that need to be reachable is required. The current statement, “*.servicebus.windows.net”, could potentially allow connections to endpoints outside of Europe.

It would be highly beneficial to have a comprehensive list of Service Bus endpoints used for SSPR today and in the future, including their assigned IP ranges.

Affected article: [SSPR Writeback Network Connectivity](https://learn.microsoft.com/en-us/entra/identity/authentication/troubleshoot-sspr-writeback#confirm-network-connectivity)

 
---

#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: a6c7b290-3f3e-70c9-7524-80d7364dd763

* Version Independent ID: d12b324f-57b2-9fd8-a433-b25644424171

* Content: [Troubleshoot self-service password reset writeback - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/troubleshoot-sspr-writeback#confirm-network-connectivity)

* Content Source: [docs/identity/authentication/troubleshoot-sspr-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/troubleshoot-sspr-writeback.md)

* Service: **entra-id**

* Sub-service: **authentication**

* GitHub Login: @Justinha

* Microsoft Alias: **justinha**
Troubleshoot self-service password reset writeback - Microsoft Entra ID | Microsoft Learn
Learn how to troubleshoot common problems and resolution steps for self-service password reset writeback in Microsoft Entra ID

**Comment by TPavanBalaji** [comment]
@heikobischoff 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue. Also notified the content developer. Thank you.

#please-close
