### ISSUE TITLE
Need additional instructions on how to publish to Azure App Service and other platforms.

### ISSUE THREAD

**Issue by kiwigringo** [MicrosoftDocs/entra-docs#105]
[Enter feedback here]
Document works fine for local development, but seems incomplete, as publishing to Azure App Service generates an error because certificate is missing, but instructions aren't provided on how to publish app with Entra authentication.

Azure App Service has its own Authentication option which can also use Entra authentication, but seems to conflict with these instructions, and because it seems to be specific to App Services, isn't helpful for developing locally then publishing, as authentication configured in App Services doesn't appear to be available locally, but following instructions to use Entra authentication as per this guide does work locally for testing, but should also work on publish from Visual Studio, if guide is completed to include steps on how to maintain local development and published versions of app, both on App Service and other platforms.

It might also be helpful to provide some guidelines on when to configure authentication through App Registration under Identity, and when to use Authentication under App Services.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e3d9337-8e8d-8cd0-3298-06e61ceab21d
* Version Independent ID: d979e41b-017e-abcf-fd5e-0fc1629320bc
* Content: [Quickstart: Sign in users and call the Microsoft Graph API from an ASP.NET Core web app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-web-app-aspnet-core-sign-in)
* Content Source: [docs/identity-platform/quickstart-web-app-aspnet-core-sign-in.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/quickstart-web-app-aspnet-core-sign-in.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by ManoharLakkoju-MSFT** [comment]
@kiwigringo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@kiwigringo 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by cilwerner** [comment]
Hi @kiwigringo, have you checked out the following tutorial series on App Service? https://learn.microsoft.com/en-us/entra/identity-platform/multi-service-web-app-authentication-app-service

**Comment by cilwerner** [comment]
@kiwigringo, did that linked document help with your issue? If so, let me know and I can add a link to that article in the text to make it easier for others, and I can close the issue.

**Comment by kiwigringo** [comment]
@cilwerner The linked document helps, although I think it's not specific about setting up keys. The sample app run locally uses a self-signed certificate, however to run on Azure App Service requires a certificate, so a link to documentation on this would be helpful. Also, it would be useful to include in the documentation what level of subscription allows certificates, as the free plan which developers might use for testing doesn't appear to support them.

**Comment by cilwerner** [comment]
Thanks for the feedback! I'll look into it and add a couple of useful links in there.
