### ISSUE TITLE
The Connectivity Analyzer client does not seem to exist anymore

### ISSUE THREAD

**Issue by Rhywden** [MicrosoftDocs/entra-docs#106]
Basically, the docs make mention of a tool that seemingly does not exist anymore:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/84586/e42aa154-9e20-48de-b88d-f2afb3c7cb56)

when I click on the highlighted link I instead land on this page where I can't find anything related to SAML testing:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/84586/2a9b296d-7bb5-4bdf-9a31-c8226c0c2717)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c01ec6a-ab66-33b1-8e6f-6437e8f4f660
* Version Independent ID: 2f64f95f-9403-bc88-ac72-5ce56f9d50c3
* Content: [Microsoft Entra Connect: Use a SAML 2.0 Identity Provider for Single Sign On - Azure - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ManoharLakkoju-MSFT** [comment]
@Rhywden 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Rhywden 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by ManoharLakkoju-MSFT** [comment]
@billmath 
Could you Please review this and update as appropriate.

**Comment by Rhywden** [comment]
It would also be great if you could include at least some pointers as to where Windows stores logs regarding login attempts because without this tool and the logs, a mere "Something went wrong" makes troubleshooting literally impossible and your own support simply says: "3rd party? Won't support!" even when it's the Windows side where the problem resides.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
