### ISSUE TITLE
Lacking instructions on how to run the user flow.

### ISSUE THREAD

**Issue by mvrius** [MicrosoftDocs/entra-docs#108]
Hi,

After creating an user flow, the next step would be to test it and run it.

The documentation does not provide any instructions on how to run the user flows.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a5b75b2-1997-a166-40b6-243d0b1d8e66
* Version Independent ID: 53180cc2-558c-8861-6967-66de977ff8c4
* Content: [Create a sign-up and sign-in user flow - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-user-flow-sign-up-sign-in-customers)
* Content Source: [docs/external-id/customers/how-to-user-flow-sign-up-sign-in-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-user-flow-sign-up-sign-in-customers.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by ManoharLakkoju-MSFT** [comment]
@mvrius
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@mvrius
I've delegated this to @msmimart, a content author, to review and share their valuable insights.

**Comment by msmimart** [comment]
Hi @mvrius, we're currently updating this documentation and will be including this information in the near future. Please stay tuned. Thanks again for your feedback! #please-close
