### ISSUE TITLE
What is the difference between Quick Access and Per-App Access?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/entra-docs#109]
Hello MSFT,

What is the difference between these 2 in terms of functionality and what are the use cases to use one over the other? 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b72d7f72-e1e1-2210-25d6-7afcba3abe20
* Version Independent ID: dfc55a75-7d5c-00c3-7b7e-0914d624e114
* Content: [How to configure Per-app Access using Global Secure Access applications - Global Secure Access](https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-configure-per-app-access)
* Content Source: [docs/global-secure-access/how-to-configure-per-app-access.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/global-secure-access/how-to-configure-per-app-access.md)
* Service: **network-access**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by ManoharLakkoju-MSFT** [comment]
@SB-o-matic 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@SB-o-matic 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by SB-o-matic** [comment]
Apologies for the delay @ManoharLakkoju-MSFT. I used the _add feedback for this page_ link right form the article so surprised you cannot already tell from your end. Here are the articles I am referring to:

Per-App Access - [https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-configure-per-app-access](url)
Quick Access - [https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-configure-quick-access](url)

**Comment by ManoharLakkoju-MSFT** [comment]
@shlipsey3 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@SB-o-matic .
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by shlipsey3** [comment]
Please review the "About Private Access" article, as it explains the difference between the two.

https://learn.microsoft.com/en-us/entra/global-secure-access/concept-private-access

**Comment by SB-o-matic** [comment]
So is it correct to say that quick access allows you group everything within your internal network into one simple representation of IP addresses and FQDNs whereas per app access allows you be more granular and apply a different set of policies for particular internal resources?

**Comment by shlipsey3** [comment]
Yup! The main distinction is that Quick Access should be for things that you always wanted tunneled through the service. Per App access is for apps/services that are dependent upon a person's role, for example. Or if you want to apply a specific Conditional Access policy.

**Comment by SB-o-matic** [comment]
Thank you so much!

**Comment by shlipsey3** [comment]
Of course!
#please-close
