### ISSUE TITLE
Directory schema extension got GA?

### ISSUE THREAD

**Issue by skmkzyk** [MicrosoftDocs/entra-docs#110]
Based on my observations in the Azure Portal and Entra Admin Center, it appears that the Directory schema extension may have reached General Availability (GA). If this is indeed the case, I believe it would be beneficial to update the relevant documentation accordingly.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/34650736/ee7687a3-fbee-42ec-861e-64f67667df7d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb1f59c6-312d-7e5c-3c70-175bfb6006ff
* Version Independent ID: dd701916-2f00-e62e-686c-a2fc384861d8
* Content: [Add attributes to token claims - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-add-attributes-to-token#to-add-a-custom-attribute-to-the-token-as-a-claim)
* Content Source: [docs/external-id/customers/how-to-add-attributes-to-token.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-add-attributes-to-token.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by Naveenommi-MSFT** [comment]
@skmkzyk 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@skmkzyk 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@msmimart 
Can you please check and add your comments on this doc update request as applicable.

**Comment by msmimart** [comment]
@skmkzyk you're correct, thanks so much for pointing this out. An update will be published shortly. #please-close
