### ISSUE TITLE
Microsoft Admin Portals app cannot be add in Cross-Tenant Access Policies (inbound and outbound)

### ISSUE THREAD

**Issue by gu1llaume-b** [MicrosoftDocs/entra-docs#111]
Hi,

I have noticed that the Microsoft Admin portals application cannot be added in the inbound access trust settings for an organization in Microsoft Entra ID. While adding other applications, like the Windows Azure Service Management API, works perfectly, adding the Microsoft Admin portals apps return the following error when trying to save the B2B collaboration inbound access policy: "Cross-tenant access settings, Found invalid target for Applications"

![image](https://github.com/MicrosoftDocs/entra-docs/assets/61277439/9ea03299-278a-4436-9a53-1203eee6ed2c)

The Audit Log returns the following:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/61277439/004b94b3-178d-4fd4-84ee-22b45c16414d)

Is this the expected behavior? Why is it failing for that application in particular? This app suits perfectly our use case and would therefore like to have this working. I didn't see any limitations or remarks about this app in particular in the documentation.

### Step to reproduce

1. In **Entra ID** > **External Identities** > **Cross-tenant access settings**
2. Add an organization and modify its inbound access settings or adapt the inbound access setting of an existing organization
3. Under **B2B collaboration**, select **Customize settings**:
    - Under **external users and groups**, select **Allow access** and **All _Organization_ users and groups**
    - Under **Applications**, select **Allow access** and select **Select applications**. Then, click on **Add Microsoft applications**, search for **Microsoft Admin Portals**, select it and add it.
4. Click on **Save**
5. The error as show above is returned

Thank you in advance,

Guillaume

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c150664-0126-912e-699b-f97c64ee6b4d
* Version Independent ID: 3a89e05c-e28c-2097-c76d-52d2b9240b2a
* Content: [Configure B2B collaboration cross-tenant access - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/cross-tenant-access-settings-b2b-collaboration)
* Content Source: [docs/external-id/cross-tenant-access-settings-b2b-collaboration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/cross-tenant-access-settings-b2b-collaboration.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by Naveenommi-MSFT** [comment]
@gu1llaume-b 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@gu1llaume-b 

I would recommend contacting Azure support to obtain more information about the limitations and requirements for adding applications to the inbound access trust settings in Entra ID. They can provide you with more detailed information and guidance on how to proceed.
https://azure.microsoft.com/en-us/support/community/. 

In the meantime, you may want to consider using other applications that are supported by Entra ID for your use case, or exploring alternative solutions for managing cross-tenant access and collaboration.

I hope this helps. Let me know if you have any further questions or concerns.

**Comment by gu1llaume-b** [comment]
@AjayBathini-MSFT 

Thank you for your answer. I have posted a question in the Azure Community Q&A.
https://learn.microsoft.com/en-us/answers/questions/1465971/microsoft-admin-portals-app-cannot-be-add-in-cross
