### ISSUE TITLE
Missing enumeration for security features

### ISSUE THREAD

**Issue by itazlin** [MicrosoftDocs/entra-docs#112]
On the paragraph (https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-mfa-registration-campaign#user-experience) at Step 2 there are missing security features. The sentence is as follows: Note that users might also be prompted to set up other security features, such as . 

after "such as" there should be more information.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c8810aa-a874-83bd-1ce6-42617b75557e
* Version Independent ID: c5c460d5-e255-40a5-a8bf-2d930d39c392
* Content: [How to run a registration campaign to set up Microsoft Authenticator - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-mfa-registration-campaign)
* Content Source: [docs/identity/authentication/how-to-mfa-registration-campaign.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-mfa-registration-campaign.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @mjsantani
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@itazlin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@itazlin 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

@mjsantani 
Could you Please review this and update as appropriate.
