### ISSUE TITLE
Entra External Id WPF Client doesn't support .NET Framework?

### ISSUE THREAD

**Issue by dmeatte-aq** [MicrosoftDocs/entra-docs#113]
This document says the preq is .NET 7 or later to use the wpf client with Entra External Ids.  The MSAL.net docs say that [.Net Framework is supported](https://learn.microsoft.com/en-us/entra/msal/dotnet/#supported-platforms-and-application-architectures).  Why does the document state there is a .net 7 requirement?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec23179-ddc5-09e6-6419-3f0dd98e5616
* Version Independent ID: 26a3160c-3032-80e8-31e0-3f8375697d21
* Content: [Sign in users in a sample WPF desktop application - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/sample-desktop-wpf-dotnet-sign-in)
* Content Source: [docs/external-id/customers/sample-desktop-wpf-dotnet-sign-in.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/sample-desktop-wpf-dotnet-sign-in.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @SHERMANOUKO
* Microsoft Alias: **shermanouko**

**Comment by Naveenommi-MSFT** [comment]
@dmeatte-aq 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dmeatte-aq 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@SHERMANOUKO 
Can you please check and add your comments on this doc update request as applicable.

**Comment by dmeatte-aq** [comment]
Thanks. The overview page ([GitHub](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/samples-ciam-all.md#desktop), [Live](https://learn.microsoft.com/en-us/entra/external-id/customers/samples-ciam-all?tabs=apptype)) also doesn't list WPF.

**Comment by SHERMANOUKO** [comment]
@dmeatte-aq did you try to build with a previous version? Which version did you use and did you encounter any errors?

**Comment by dmeatte-aq** [comment]
@SHERMANOUKO , I didn't build the app. I only read the docs and I'm asking about the conflict.

**Comment by SHERMANOUKO** [comment]
The tutorial is built using .NET 7 and should work with .NET 7+. That means that to follow through the tutorial as is, one should use .NET 7. This makes it easy for you to finish the Quickstart and learn the ley concepts that the QuickStart is teaching. 

I would think it's not really a conflict but just an approach used to follow the Quickstart article.

**Comment by dmeatte-aq** [comment]
I'm looking to use it with .net 4.8, not 7. My question is why does it say only .net 7 when the main library it uses works with ,net framework?

**Comment by SHERMANOUKO** [comment]
It says .NET 7 because the sample that has been used in that Quickstart article is built on .NET 7

**Comment by dmeatte-aq** [comment]
Ah. I guess that makes sense when you're only considering the sample code. The doc doesn't make clear that the preeqs are for the sample.

**Comment by SHERMANOUKO** [comment]
I'll work on updating that.

Thank you for your feedback ad taking time to help us improve our documentation.

**Comment by SHERMANOUKO** [comment]
#please-close
