### ISSUE TITLE
Document more details on client apps support for Dynamics 365

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/entra-docs#114]
Section - Require approved client app
List of client apps that support this setting.
It is listed "Microsoft Dynamics 365" , but it is not clear which one is it? Customer Service? Business Central ? etc.
Please be more specific about which exactly mobile application from Dynamics 365 portfolio supports, and which do not support.
I guess, that Dynamics 365 Business Central is not supported, but Dynamics 365 Customer Service is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd934939-4dbb-3a92-f996-56b9557f49ac
* Version Independent ID: 3cda6b81-26e8-c9ac-e768-d912636a461b
* Content: [Grant controls in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-grant#require-approved-client-app)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-grant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-grant.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by ManoharLakkoju-MSFT** [comment]
@hkusulja 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@hkusulja 
The Dynamics 365 mobile apps, including the Dynamics 365 Customer Service app and the Dynamics 365 Business Central app, do support the "Require approved client app" setting in Conditional Access policies. The list of client apps that support this setting can be found in the following Microsoft documentation: https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-conditional-access-conditions#client-apps. I hope this clears up any confusion. Let me know if you have any other questions.

**Comment by SaibabaBalapur-MSFT** [comment]
@hkusulja 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by hkusulja** [comment]
@SaibabaBalapur-MSFT the Dynamics 365 Business Central app is not supported.
Please write exact names of the apps in a list.

**Comment by SaibabaBalapur-MSFT** [comment]
@hkusulja 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by SaibabaBalapur-MSFT** [comment]
@MicrosoftGuyJFlo
Can you please check and add your comments on this doc update request as applicable.

**Comment by MicrosoftGuyJFlo** [comment]
This would need to be asked of the Dynamics application team. As noted in the doc approved client app is being retired in March 2026.

For app protection policies we support Microsoft Dynamics 365 for Phones and Microsoft Dynamics 365 Sales.

#please-close
