### ISSUE TITLE
Application enforced restrictions

### ISSUE THREAD

**Issue by sfaisalm** [MicrosoftDocs/entra-docs#115]
I think this para is old as with new Idle timeout policy which applies to more cloud apps, same control is supported for managed/umanaged device as in below article, when we apply app enforced restrictions, it applies to more apps and not only Sharepoint and Email
https://learn.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps?view=o365-worldwide
. This control only supports Office 365, SharePoint Online, and Exchange Online as selected cloud apps

Thanks
Syed Faisal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 609a0eda-f113-8b77-67ee-c5e8bd94cbac
* Version Independent ID: 7468d74e-9a7e-2a11-ba35-da46103a1b80
* Content: [Session controls in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-session)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-session.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-session.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by ManoharLakkoju-MSFT** [comment]
@sfaisalm 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@sfaisalm 
I'm going to assign this to the document author so they can take a look at it accordingly

@MicrosoftGuyJFlo 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sfaisalm** [comment]
> @sfaisalm I'm going to assign this to the document author so they can take a look at it accordingly
> 
> @MicrosoftGuyJFlo Can you please check and add your comments on this doc update request as applicable.

Thanks!

**Comment by MicrosoftGuyJFlo** [comment]
Adding link to information in liked private repo PR. Should publish later today.
