### ISSUE TITLE
Incorrect Values

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/entra-docs#118]
This step is wrong:
_e. Copy the value from the Namespace textbox._

You can't use just the namespace...you need the claim full name (namespace + the claim name)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cbfa13a7-4d2d-b203-d7fa-760833a745cb
* Version Independent ID: 72ff67dc-732d-478e-1595-9d4bd6737714
* Content: [Tutorial: Microsoft Entra SSO integration with Tableau Cloud - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/tableauonline-tutorial#configure-azure-ad-sso)
* Content Source: [docs/identity/saas-apps/tableauonline-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/tableauonline-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by ManoharLakkoju-MSFT** [comment]
@danmyhre 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@danmyhre Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
