### ISSUE TITLE
Unclear usage for IIF function for HR provisioning

### ISSUE THREAD

**Issue by AlienusPL** [MicrosoftDocs/entra-docs#120]
In [IFF function section](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/functions-for-customizing-application-data#known-limitations-and-workarounds-for-iif-function) is stated that IIF cannot be used with IsNullOrEmpty function as quote :"If the source attribute used within the IIF function is empty or null, the condition check fails." and below is unsupported:

IIF(IsNullOrEmpty([country]),"Other",[country])

But in [Troubleshoot HR user creation issues](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/hr-user-creation-issues), documentation says that IIF with IsNullOrEmpty should be used as an issue resolution:

IIF(IsNullOrEmpty([BusinessTitle]),"N/A",[BusinessTitle])

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8685339-06af-5bb1-64da-80c16878b0bf
* Version Independent ID: 1ee0d812-00de-90cc-f5e2-d53e3b610bf0
* Content: [Reference for writing expressions for attribute mappings in Microsoft Entra Application Provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/functions-for-customizing-application-data#switch)
* Content Source: [docs/identity/app-provisioning/functions-for-customizing-application-data.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/functions-for-customizing-application-data.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by ManoharLakkoju-MSFT** [comment]
@AlienusPL 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@AlienusPL 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@kenwith 
Can you please check and add your comments on this doc update request as applicable.

**Comment by kenwith** [comment]
Thank you for the feedback. I am sending this to the product team to get clarity and will update the article.

**Comment by lorieide** [comment]
This issue has been updated, as we've updated the guidance to use the Switch function instead to check for empty or null values and pass a nonblank literal value, as is demonstrated in the following code snippet:
Switch([BusinessTitle],[BusinessTitle],"","N/A"). 
#please-close
