### ISSUE TITLE
ClaimsTransformations not ClaimsTransformation

### ISSUE THREAD

**Issue by urbantom** [MicrosoftDocs/entra-docs#121]
I must admit I haven't verified the source code, but according to my empirical observations, the JSON used to specify the claim policy should use the ClaimsTransformations element name, not ClaimsTransformation.  I think it should be clearly explained in the article.  Using the form ClaimsTransformation in the article suggests the singular form should be used as the element name.  As AzureAD returns only the message "Status: 400 (BadRequest): Property definition has an invalid value" with no details, this little improvement can save a lot of time for troubleshooting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 279745bc-589e-cdd1-e247-9de19a95ae6a
* Version Independent ID: 3f0a11b7-2151-ffa0-39fb-9a57f8299760
* Content: [Claims mapping policy type - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-claims-mapping-policy-type)
* Content Source: [docs/identity-platform/reference-claims-mapping-policy-type.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-claims-mapping-policy-type.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by ManoharLakkoju-MSFT** [comment]
@urbantom 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by urbantom** [comment]
[https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-claims-mapping-policy-type.md#claims-transformation](url)

**Comment by ManoharLakkoju-MSFT** [comment]
@urbantom 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@urbantom 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
