### ISSUE TITLE
DisplayName rather than Name

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/entra-docs#122]
https://learn.microsoft.com/en-us/entra/identity/users/licensing-groups-resolve-problems#duplicate-proxy-addresses

Because of the Exchange Online change, the code should be updated.

Duplicate proxy addresses section
current:  
Get-Recipient -Filter "EmailAddresses -eq 'user@contoso.onmicrosoft.com'" | fl Name, RecipientType,Emailaddresses

better: 
Get-Recipient -Filter "EmailAddresses -eq 'user@contoso.onmicrosoft.com'" | fl DisplayName, RecipientType,Emailaddresses

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb0fc0fc-b772-de61-258a-a6fd4ea9711c
* Version Independent ID: 04e86827-c8da-a01a-2cb5-aeb2fbcef610
* Content: [Resolve group license assignment problems - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-groups-resolve-problems)
* Content Source: [docs/identity/users/licensing-groups-resolve-problems.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-groups-resolve-problems.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by ManoharLakkoju-MSFT** [comment]
@mprentice22153 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@mprentice22153 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
