### ISSUE TITLE
Missing Product SKUs

### ISSUE THREAD

**Issue by doubleyousee** [MicrosoftDocs/entra-docs#123]
The Following Product SKUs are missing from this table:

930cc132-4d6b-4d8c-8818-587d17c50d56 - PROJECTPREMIUM_FACULTY - Project Plan 5 for faculty
c2cda955-3359-44e5-989f-852ca0cfa02f - MCOMEETADV_FACULTY - Microsoft 365 Audio Conferencing for faculty

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by Nicholak-MS** [comment]
These two SKUs have been added to the online table and the downloadable CSV. The updates will publish later today. 

Thanks

**Comment by Nicholak-MS** [comment]
#please-close
