### ISSUE TITLE
What does "The rules can include up to 5000 users per policy" mean?

### ISSUE THREAD

**Issue by MithunChopda** [MicrosoftDocs/entra-docs#124]
The documentation mentions "The rules can include up to 5000 users per policy.". Can you elaborate what this limitation means?

An auto assignment policy can have multiple Rules. If I have to assign a Package to more than 8000 eligible users, is the recommendation to create two rule for the same package to circumvent the 5000 limit? Or does it mean something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3abca3ac-e865-30f7-af10-88a8bbb28334
* Version Independent ID: 37220ae8-c01b-4243-abd6-761cd7958f67
* Content: [Configure an automatic assignment policy for an access package in entitlement management - Microsoft Entra - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-access-package-auto-assignment-policy)
* Content Source: [docs/id-governance/entitlement-management-access-package-auto-assignment-policy.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/entitlement-management-access-package-auto-assignment-policy.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **owinfrey**

**Comment by ManoharLakkoju-MSFT** [comment]
@MithunChopda 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@MithunChopda 
The limitation of 5000 users per policy means that a single policy can only evaluate up to 5000 users to determine if they meet the criteria for automatic assignment. If you have more than 5000 users who need to be evaluated, you will need to create additional policies with different rules to cover all the users. 

In your case, if you have to assign a package to more than 8000 eligible users, you can create two rules for the same package to circumvent the 5000 limit. You can create two policies with different rules that cover different sets of users, and both policies can be assigned to the same access package. 

It's important to note that during this preview, you can have at most one automatic assignment policy in an access package. So, if you need to create multiple policies for the same access package, you will need to wait until this limitation is lifted.

**Comment by SaibabaBalapur-MSFT** [comment]
@MithunChopda 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
