### ISSUE TITLE
How multiple Conditional Access authentication strength policies are evaluated for registering security info

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/entra-docs#125]
I've tested the part "How multiple Conditional Access authentication strength policies are evaluated for registering security info", but when I try to register a FIDO key using a TAP (not using WHFB), I'll end up in a loop where I cannot register any method.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/38911727/7ee9189a-351f-4db2-8d44-ff0c04a95a2c)

The sign in fails on the first CA policy, so it seems that the register security info policy is not preferred over other authentication strength policies that target All cloud apps.

Am I holding it wrong?

![image](https://github.com/MicrosoftDocs/entra-docs/assets/38911727/2278d447-8631-487f-b08c-74d6b5b4dc3b)
 
The device is compliant, so I'd expect that I can access my Sign-in portal with TAP and a compliant device. 
I'm using password only to sign-in into my compliant device, so bypassing WHFB for a moment. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14d95746-1fc3-daba-85ac-c07ce9f67ab4
* Version Independent ID: ee143f12-672f-455b-cc9b-4c8c3def0a17
* Content: [Overview of Microsoft Entra authentication strength - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-strengths#how-multiple-conditional-access-authentication-strength-policies-are-evaluated-for-registering-security-info)
* Content Source: [docs/identity/authentication/concept-authentication-strengths.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-strengths.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @InbarckMS
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@BakkerJan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@BakkerJan 
I'm going to assign this to the document author so they can take a look at it accordingly.

@InbarckMS 
Please review it.
