### ISSUE TITLE
Need Solution for dynamic redirect url configuration

### ISSUE THREAD

**Issue by bhahu** [MicrosoftDocs/entra-docs#129]
how to setup dynamic redirectURL in configuration for onedrive filepicker where as its only accepting static redirecturl? My site URL will be like www.domain.com/abc/abc/123 (everything changes dynamically after .com)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f7ced07-0b71-715f-749b-180567591c72
* Version Independent ID: 8c533d7b-a058-3f1a-c296-9c0305f85f13
* Content: [Understanding the Microsoft Entra app manifest - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest?WT.mc_id=Portal-Microsoft_AAD_RegisteredApps)
* Content Source: [docs/identity-platform/reference-app-manifest.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-app-manifest.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by AjayBathini-MSFT** [comment]
@bhahu 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@bhahu 
To set up a dynamic redirect URL for OneDrive file picker, you can use the wildcard character (*) in the redirect URL. This will allow you to specify a dynamic URL that matches a pattern. 

For example, if your site URL is `www.domain.com/abc/abc/123`, you can set the redirect URL to `https://www.domain.com/*/123`. This will match any URL that starts with `https://www.domain.com/` followed by any number of segments, and ends with `/123`.

To configure this in the app manifest, you can add the following to the `replyUrlsWithType` property:

```
"replyUrlsWithType": [
    {
        "url": "https://www.domain.com/*/123",
        "type": "Web"
    }
]
```

Make sure to replace `www.domain.com` with your actual domain name, and adjust the pattern to match your specific URL structure.

**Comment by bhahu** [comment]
@SaibabaBalapur-MSFT www.domain.com/* I need to configure. Because after www.domain.com/ everything is dynamic for example www.domain.com/bla/bla/numbers

**Comment by SaibabaBalapur-MSFT** [comment]
@bhahu I understand. In that case, you can use the wildcard character (*) in the redirect URL to match any URL that starts with `https://www.domain.com/` and ends with a forward slash, regardless of what comes after it.

Here's an example of how to set up a wildcard redirect URL for your domain:

`https://www.domain.com/*/`

This will match any URL that starts with `https://www.domain.com/` and ends with a forward slash, regardless of what comes after it. The `*` character acts as a wildcard, allowing any value to be used in place of the forward slash.

You can then configure your app registration in the Azure portal to use this redirect URL. When the user is redirected back to your app after authenticating with OneDrive, the URL will match the wildcard pattern and be accepted as a valid redirect URL.

Note that using a wildcard redirect URL can be less secure than using a static URL, as it allows for more flexibility in the redirect URL. You should carefully consider the security implications of using a wildcard URL before implementing it in your app.

Still issue present, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. [Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by bhahu** [comment]
Hi @SaibabaBalapur-MSFT Can you tell me where and How can I add https://www.domain.com/*/ in portal?

**Comment by SaibabaBalapur-MSFT** [comment]
@bhahu we have create duplicate case query  as you required how can you add https://www.domain.com/*/ in portal? 
Please follow up below case Id for further update. 
https://github.com/MicrosoftDocs/entra-docs/issues/157
