### ISSUE TITLE
Sync time and explanation too vague or missing important information

### ISSUE THREAD

**Issue by mardahl** [MicrosoftDocs/entra-docs#13]
I am not seeing the promised 2minute sync time from AD to Entra ID.
In fact the audit and provision logs show about 10 minutes between each update.
And in tenants with around 20k objects in scope for sync, a full sync can take two hours, and the size of the agent machine does not seem to impact this in any way.
I NEED a deep dive article explaining how this service does it's magic.

Secondly, it seems odd that a "delta sync" can only be kicked off from powershell or via Graph API, when there is a button for full sync in the portal. Both options would help. And a CLEAR indication that a sync is currently running would also be nice on the front page of any given configuration.

A specifically odd thing I have noticed, is that you can update attributes like the users primary SMTP address in the on-prem for an entire OU, but it can take over an hour for those changes to get synced, even thought it might only have been 100 users, and they will come into Entra ID and the provisioning loss in a slow drip, and then all of a sudden like a ketchup bottle, they all appear.
Sure there is a logical explanation. but having to provision them on demand, and beating the speed of the normal sync, just makes no sense to me at all.
Please add an on-demand OU sync feature instead so we can do an effective update during our M&A projects, where domain cutover etc. demands a quick attribute sync.

Please feel free to reach out for examples etc. I have many agents running in disjoint domains for M&A scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42038cf7-555b-5351-0380-b20ac50c4863
* Version Independent ID: 7267c4b4-0770-9fb4-4e45-e8342ca4a850
* Content: [Microsoft Entra Cloud Sync FAQ - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/reference-cloud-sync-faq)
* Content Source: [docs/identity/hybrid/cloud-sync/reference-cloud-sync-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/reference-cloud-sync-faq.yml)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MarileeTurscak-MSFT** [comment]
@mardahl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@mardahl 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
