### ISSUE TITLE
Erroneous images when zoomed

### ISSUE THREAD

**Issue by gnic67** [MicrosoftDocs/entra-docs#131]
When I click on the topmost image to zoom in, the zoomed image is actually the bottom one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12739084-4ac9-6850-9be5-88877a28e4b2
* Version Independent ID: b0f5fb6b-ae55-22aa-6a53-972c52212d6f
* Content: [Tutorial: Register a Single-page application with the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-single-page-app-react-register-app)
* Content Source: [docs/identity-platform/tutorial-single-page-app-react-register-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-single-page-app-react-register-app.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by Naveenommi-MSFT** [comment]
@gnic67
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@OwenRichards1
Could you please update the document with the correct screenshot where applicable.

**Comment by SaibabaBalapur-MSFT** [comment]
@gnic67 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by OwenRichards1** [comment]
@gnic67 Thanks for highlighting this error - I have now updated to the correct image.
