### ISSUE TITLE
Is it possible to develop a custom HR Connector to ingest Hiring Record for Inbound Provisioning?

### ISSUE THREAD

**Issue by MithunChopda** [MicrosoftDocs/entra-docs#132]
The documentation in this app assumes the source HR systems would be Workday or SuccessFactor which already have connectors published in gallery for Inbound User Provisioning.

Is there an option for developers to build similar HR connectors for other On-Premise or Cloud HR apps? One options is to use the API driven inbound provisioning. However, this option doesn't allow packaging the data import functionality from source HR app. It needs to be built outside of the app integration using Logic Apps or something else.

The experience I am looking to build is similar to Workday or SuccessFactors but one for a different Cloud HR system, and package the import package as part of connector probably. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4799808f-5315-db72-9f0e-d83ed12141f8
* Version Independent ID: d612c880-bb2e-158d-0b31-a980ddce8d82
* Content: [Plan cloud HR application to Microsoft Entra user provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/plan-cloud-hr-provision)
* Content Source: [docs/identity/app-provisioning/plan-cloud-hr-provision.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/plan-cloud-hr-provision.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Naveenommi-MSFT** [comment]
@MithunChopda 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @MithunChopda this Microsoft has not provided a way to build similar HR connectors for other On-Premise or Cloud HR apps. However, you can use the API driven inbound provisioning option, which allows you to build custom connectors for your HR app. This option requires building the data import functionality outside of the app integration using Logic Apps or something else.

If you want to package the import package as part of the connector, you may need to explore other options or work with Microsoft to see if they have any recommendations. It's also worth noting that the documentation you provided assumes that the source HR systems are Workday or SuccessFactors, so it's possible that the process may be different for other HR systems.

I hope this helps! Let me know if you have any other questions.

**Comment by SaibabaBalapur-MSFT** [comment]
@MithunChopda 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by MithunChopda** [comment]
Why does this sound like a Chat-GPT generated response?

**Comment by SaibabaBalapur-MSFT** [comment]
@MithunChopda 
No, Still if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
