### ISSUE TITLE
Proposal on inserting a screenshot with relevant change in groups-discover-groups.md

### ISSUE THREAD

**Issue by JoeyC-Dev** [MicrosoftDocs/entra-docs#134]
As defined in the article "[Make major changes to Microsoft Learn documentation](https://learn.microsoft.com/en-us/contribute/content/how-to-write-major-edits)", "adding new images or updating images" is considered as major change. As defined in "[issue template](https://github.com/MicrosoftDocs/azure-docs/blob/main/ISSUE_TEMPLATE)", it is required to "submit an issue that describes the details of the proposed large change".

**Purposed change**
Insert a screenshot under the note. If approved, I will submit a PR for it:
> Alternatively, you can use the Groups pane to bring group under Privileged Identity Management.

Screenshot: https://github.com/MicrosoftDocs/azure-docs/blob/ed81183c98c620e5dbebb44358b4782cc12954b0/articles/aks/media/managed-aad-pim/enable-pim-group.png  

Because there will be a screenshot here, I will also move this statement outside of the note, so it does not look weird. (Besides there are already two notes and one important part stacking there)

**Other**
I did not realise that this is `entra-docs` until I saw the issue number only contains 3 numbers. Is the rule from `azure-docs` still applying here?  
Thanks.
  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 581995d1-f559-25db-9e0a-ca8bdefd9bea
* Version Independent ID: d7736935-34b8-acb1-9025-76bd24b52645
* Content: [Bring groups into Privileged Identity Management - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/groups-discover-groups)
* Content Source: [docs/id-governance/privileged-identity-management/groups-discover-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/groups-discover-groups.md)
* Service: **active-directory**
* Sub-service: **pim**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@JoeyC-Dev 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@JoeyC-Dev 
I've assigned this issue to the author who will investigate and update as appropriate.
