### ISSUE TITLE
Screenshots do not show the "Show keep user signed in" section discussed

### ISSUE THREAD

**Issue by nemkoitsupport** [MicrosoftDocs/entra-docs#135]
Screenshots do not show the "Show keep user signed in" section discussed

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 244f6b9a-42f2-73d1-7c8b-6fe219de24ae
* Version Independent ID: 18939379-a92e-9832-d83d-bf8c25bc182e
* Content: [Manage the 'Stay signed in' prompt in Microsoft Entra ID - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-manage-stay-signed-in-prompt)
* Content Source: [docs/fundamentals/how-to-manage-stay-signed-in-prompt.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-manage-stay-signed-in-prompt.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by Naveenommi-MSFT** [comment]
@nemkoitsupport 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@nemkoitsupport 
Thank you for bringing this to our attention.
I've delegated this to content author @shlipsey3, who will review it and offer their insightful opinions.

**Comment by shlipsey3** [comment]
Hey great catch! Thanks @nemkoitsupport 

I found the screenshot I meant to add and will get that swapped out right away. Thanks!

**Comment by shlipsey3** [comment]
Thanks again @nemkoitsupport - I've swapped out that screenshot.

#please-close
