### ISSUE TITLE
DID:ion Trust Method No Longer Supported by MSFT Entra Verified ID?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/entra-docs#136]
Hello Team,

There is no longer an option to choose between the did:web and did:ion trust method when onboarding the tenant into the Verified ID service. All onboarding attempts use the did:web method by default. Seems the interface has changed and the first screenshot as shown below is no longer the case. How to use did:ion going forward?

I am using the walkthrough found here: [https://www.linkedin.com/pulse/entering-world-decentralized-identity-verifiable-philippe-beraud](url)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/44109318/a9976cce-ebdb-4763-a296-bff116b3cac0)

**Here is how things look now**

![image](https://github.com/MicrosoftDocs/entra-docs/assets/44109318/0b0956a7-88c3-4efa-bf12-8a795dae1952)

**Used the Verified ID Admin API and it seems like did:ion is no longer supported.**

![image](https://github.com/MicrosoftDocs/entra-docs/assets/44109318/e2f8583c-a156-4bbe-bf6a-cb520bbe93d0)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f84b158e-eebc-7d96-0992-8864316ddf5c
* Version Independent ID: 8909ba9b-bf26-fb5c-29f0-76244984e75a
* Content: [Tutorial - Manual Microsoft Entra Verified ID setup - Microsoft Entra Verified ID](https://learn.microsoft.com/en-us/entra/verified-id/verifiable-credentials-configure-tenant)
* Content Source: [docs/verified-id/verifiable-credentials-configure-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/verified-id/verifiable-credentials-configure-tenant.md)
* Service: **decentralized-identity**
* Sub-service: **verifiable-credentials**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@SB-o-matic 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@barclayn
Can you please check and add your comments on this doc update request as applicable.

**Comment by SB-o-matic** [comment]
Hey @barclayn , any insight? Appreciate any help.

**Comment by SB-o-matic** [comment]
Any updates please? @SaibabaBalapur-MSFT @Naveenommi-MSFT @barclayn

**Comment by SB-o-matic** [comment]
Is there anyone else that can help here there is a very important deviation from what the documentation advertises, and it will be very useful to know if this deviation is an omission or is something that will become permanent.

**Comment by SaibabaBalapur-MSFT** [comment]
@barclayn
Please review it.

**Comment by barclayn** [comment]
@SB-o-matic this is documented in https://learn.microsoft.com/en-us/entra/verified-id/whats-new#december-2023  #please-close

**Comment by SB-o-matic** [comment]
Can we get an explanation as to why did:ion was removed? I think decentralization is very key here and there is an appeal that ION, a decentralized Layer 2 running on Bitcoin (the most secure, decentralized network in the world) has to the community at large. I think MSFT should seriously consider this appeal. And if you have, at least let us know why there has been a deviation from what was previously advertised.

**Comment by SB-o-matic** [comment]
#please-open #please-reopen.

**Comment by SB-o-matic** [comment]
Can we please get some sort of explanation or reasoning?

**Comment by SB-o-matic** [comment]
Please provide some explanation about this removal. This is quite unfair.
