### ISSUE TITLE
Error code AADSTS1004008 details are missing.

### ISSUE THREAD

**Issue by Nikunjksanghavi** [MicrosoftDocs/entra-docs#137]
Hi Team, we are getting an AADSTS1004008 error for the Azure AD OpenID scenario,
we don't have a clue why this issue is happening, 

also while searching in documentation we did not find any reference.
https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes?source=docs

please refer to the screenshot of the API call
![image](https://github.com/MicrosoftDocs/entra-docs/assets/6330523/1c143d10-ca4e-4670-a007-847167589e21)
please help.

Thanks.
Nikunj

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a826ee6f-f457-7109-9f77-67c57977d4e7
* Version Independent ID: 11766f27-492e-a579-dced-8a42528cbb47
* Content: [Microsoft Entra authentication & authorization error codes - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes?source=docs)
* Content Source: [docs/identity-platform/reference-error-codes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-error-codes.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by Naveenommi-MSFT** [comment]
@Nikunjksanghavi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@Nikunjksanghavi 
Thank you for bringing this to our attention.
I've delegated this to content author @rwike77, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@rwike77 
Could you please review add comments on this, update as appropriate.

**Comment by rwike77** [comment]
@Nikunjksanghavi  Hi, I can't see the complete request in your screen shot.  Are you adding a "client_id" query parameter?  Something like this:
http s://login.microsoftonline.com/{tenant-id}/discovery/v2.0/keys?client_id={clientid/appid}

I'm able to repro using the client_id query parameter.  Looks like only the "appid" query parameter is [officially supported](https://learn.microsoft.com/entra/identity-platform/access-tokens#validate-the-signature).

When I use appid it works for me:
http s://login.microsoftonline.com/{tenant-id}/discovery/v2.0/keys?appid={clientid/appid}

You can find a similar issue here:  https://learn.microsoft.com/en-us/answers/questions/1163810/where-can-i-find-the-jwks-uri-for-azure-ad

Hope that helps.

**Comment by rwike77** [comment]
@Nikunjksanghavi  I haven't heard back, I'll close this issue now.  I hope the info I provided works for you.  Feel free to reopen if necessary.  Thanks.  #please-close
