### ISSUE TITLE
All the tenant management API links are incorrect

### ISSUE THREAD

**Issue by kleggMS** [MicrosoftDocs/entra-docs#138]
The current API links all point to very old Azure Stack links and not the correct API docs for customer tenants. E.g. this is the correct link for Create: **https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/create?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b07430c-4ce2-114e-051b-a488c6596903
* Version Independent ID: 54be2749-8822-f561-56e4-b597aedeed0a
* Content: [Tenant management with Azure REST API - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/azure-rest-api-operations-tenant-management)
* Content Source: [docs/external-id/customers/azure-rest-api-operations-tenant-management.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/azure-rest-api-operations-tenant-management.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @garrodonnell
* Microsoft Alias: **godonnell**

**Comment by Naveenommi-MSFT** [comment]
@kleggMS 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@garrodonnell
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@kleggMS 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by garrodonnell** [comment]
All links have been update now in this PR https://github.com/MicrosoftDocs/entra-docs-pr/pull/2231

#please-close
