### ISSUE TITLE
CA policies allow to select directory roles that can't or shouldn't be used

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/entra-docs#139]
According to the documention, "directory roles" is defined as follows:
> Allows administrators to select specific [built-in Microsoft Entra directory roles](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference) used to determine policy assignment. For example, organizations may create a more restrictive policy on users actively assigned the Global Administrator role. Other role types aren't supported, including administrative unit-scoped roles and custom roles.

However, for the conditional access policies there are roles listed that according to "build-in Microsoft Entra directory roles"
can't or shouldn't be used or are deprecated:
<img width="887" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/62641471/44ac7bb9-6eef-4649-bfb5-abe3129a2bef">

Why can these roles be selected for CA policies? Shouldn't they be hidden the same way they are hidden in the Portal?
What happens when the role "User" ist selected?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cae7bc92-8489-ff66-9ce0-b4fab08eb7b8
* Version Independent ID: 55dfcb5c-62cd-8485-7d55-de3459cb2854
* Content: [Users and groups in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-users-groups)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-users-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-users-groups.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@joergrenn 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
#reassign:@MicrosoftGuyJFlo
#label:"assigned-to-author", "awaiting-product-team-response"

**Comment by MicrosoftGuyJFlo** [comment]
Email out to the Product and Engineering teams.

**Comment by MicrosoftGuyJFlo** [comment]
@joergrenn Even though these roles are listed as deprecated or cant be used they still appear in the Graph API, so Conditional Access shows them to allow Administrators to choose to protect the roles with policy if they choose.

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"awaiting-product-team-response"

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
