### ISSUE TITLE
Clarification about token for testing

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/entra-docs#140]
What token is this line referring to?
**_The token generated by the Microsoft Entra provisioning service should only be used for testing. It shouldn't be used in production environments._** 

Is it talking about the testing token from the /scim/token endpoint if the SCIM provisioning server ? If so, this token is not from the Microsoft Entra provisioning service, but from the SCIM application if the **ASPNETCORE_ENVIRONMENT** property is set to **_Development_** ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 271dc426-fb47-7441-d627-ec11f8c7a6ea
* Version Independent ID: 4cb8bfc8-4748-e501-425a-e4c2da0f5f5a
* Content: [Tutorial - Develop a SCIM endpoint for user provisioning to apps from Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups#handling-endpoint-authentication)
* Content Source: [docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Naveenommi-MSFT** [comment]
@LijuV-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @LijuV-MSFT 
The line you mentioned is not referring to any specific token. It is just a general statement that the token generated by the Microsoft Entra provisioning service should only be used for testing and not in production environments. 

Regarding your question about the /scim/token endpoint, you are correct that this token is not from the Microsoft Entra provisioning service, but from the SCIM application if the ASPNETCORE_ENVIRONMENT property is set to Development.

**Comment by LijuV-MSFT** [comment]
thank you.
