### ISSUE TITLE
Why should we NOT use the Entra bearer token?

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/entra-docs#141]
Based on my understanding, we have three options for the OAuth 2.0 bearer token included as part of requests from the Microsoft Entra provisioning service:

**- Self-signed token**
- Set the ASPNETCORE_ENVIRONMENT property to Development of the SCIM application and make a request to the {host}/scim/token endpoint of the application to generate a self-signed token.
- Use this token in the Secret Token field of the enterprise app's provisioning configuration.
**- Long-lived bearer token**
- If you have an OAuth bearer token from an issuer other than Microsoft Entra ID, then copy the required OAuth bearer token into the optional Secret Token field
**- Entra bearer token**
- Leave the Secret Token field blank. Microsoft Entra ID includes an OAuth bearer token with each request. 

However,  it says [here ](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups#integrate-your-scim-endpoint-with-the-microsoft-entra-provisioning-service)that It's not recommended to leave this field blank and rely on a token generated by Microsoft Entra ID. This option is primarily available for testing purposes.

Why is the Entra bearer token is not recommended?
This leaves a long-lived bearer token as the only option in production.
What do most customers do here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 271dc426-fb47-7441-d627-ec11f8c7a6ea
* Version Independent ID: 4cb8bfc8-4748-e501-425a-e4c2da0f5f5a
* Content: [Tutorial - Develop a SCIM endpoint for user provisioning to apps from Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups)
* Content Source: [docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Naveenommi-MSFT** [comment]
@LijuV-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@LijuV-MSFT The reason why the Entra bearer token is not recommended is that it is not secure to rely on a token generated by Microsoft Entra ID for production purposes. This option is primarily available for testing purposes. Leaving the Secret Token field blank and relying on the Entra bearer token can pose a security risk as it is a long-lived token that can be used to access your organization's resources. 

Most customers use the long-lived bearer token option in production. This option requires an OAuth bearer token from an issuer other than Microsoft Entra ID, which is more secure than relying on the Entra bearer token. You can copy the required OAuth bearer token into the optional Secret Token field to use this option. 

I hope this helps! Let me know if you have any other questions.

**Comment by SaibabaBalapur-MSFT** [comment]
@LijuV-MSFT 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
