### ISSUE TITLE
ADAL for desktop apps no longer works

### ISSUE THREAD

**Issue by ppoirier1** [MicrosoftDocs/entra-docs#142]
Attempting to authenticate from a desktop app using AuthenticationContext.AcquireTokenAsync now returns an error message saying the browser is out of date.  The browser is the current version of Edge though that's irrelevant since it appears ADAL is the agent here.  Worked fine in December 2023, not now.
![browser err](https://github.com/MicrosoftDocs/entra-docs/assets/7011158/d216d844-7d3a-484b-9296-f8310b655c93)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d686df6b-2d78-779b-d09c-d6c3e41e4adf
* Version Independent ID: 832e4900-0aeb-c414-be10-b93ee5c1a79d
* Content: [Migrate to the Microsoft Authentication Library (MSAL) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/msal-migration)
* Content Source: [docs/identity-platform/msal-migration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/msal-migration.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @Dickson-Mwendia
* Microsoft Alias: **dmwendia**

**Comment by ppoirier1** [comment]
I think I figured out the problem:

1. Log out of the azure account on the browser then log back in
2. After completing multi-factor authentication, it takes you to a page asking you to verify your MFA methods
3. Click "confirm" then you're logged in
4. Now go back and log in through the desktop app and it works

The MFA confirmation shouldn't block ADAL authentication.  Actually doesn't matter whether the app is using ADAL or MSAL, neither works.

**Comment by Naveenommi-MSFT** [comment]
@ppoirier1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@ppoirier1 
Glad to know you have self-resolved the issue.
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
