### ISSUE TITLE
Link to NPS health check script is invalid

### ISSUE THREAD

**Issue by vpandey01** [MicrosoftDocs/entra-docs#146]
The NPS Extension Health Check Script link (https://learn.microsoft.com/en-us/samples/azure-samples/azure-mfa-nps-extension-health-check/azure-mfa-nps-extension-health-check/) gives a 404.

It should be updated to: https://github.com/Azure-Samples/azure-mfa-nps-extension-health-check

<img width="834" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/137679723/28b80329-eb31-4597-b400-96658ebee13c">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a61a7e9a-44bf-7bdc-f810-87e2fd6792e1
* Version Independent ID: 71d11105-b83e-952e-d107-1ff9a7c8d107
* Content: [Use Microsoft Entra multifactor authentication with NPS - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension)
* Content Source: [docs/identity/authentication/howto-mfa-nps-extension.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-nps-extension.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@vpandey01 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by ManoharLakkoju-MSFT** [comment]
@vpandey01 
Thanks for pointing this out. Required changes have been made and visible in the document itself..
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
