### ISSUE TITLE
Azure AD (Connect) mentions in the visuals

### ISSUE THREAD

**Issue by Daynvheur** [MicrosoftDocs/entra-docs#148]
Hello World,
The visuals used as reference in the page mention Azure AD Connect and Azure AD.
I sort of understand those may be obsolete as of Microsoft Entra connect and Microsoft Entra availability.

Feel free to ignore this Issue if you want Azure AD (+Connect) people keeping some reference sheet for their actual implementation.

Have a nice day.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86ed5438-9076-fa6f-d42a-e9bef29beb6e
* Version Independent ID: f6490079-8f4a-f621-623b-d500b52abef8
* Content: [What is Microsoft Entra Connect and Connect Health. - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-azure-ad-connect)
* Content Source: [docs/identity/hybrid/connect/whatis-azure-ad-connect.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/whatis-azure-ad-connect.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@Daynvheur 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Daynvheur 

Thank you for your feedback. You are correct that the visuals used as reference in the page mention Azure AD Connect and Azure AD, which may be obsolete as of Microsoft Entra connect and Microsoft Entra availability.

However, it is important to note that Azure AD Connect is still a valid solution for synchronizing on-premises directories with Azure AD. Microsoft Entra connect and Microsoft Entra availability are newer solutions that provide additional features and capabilities, but Azure AD Connect is still widely used and supported.

And the documents have been updating by replacing Microsoft Entra.It will take some time to update everywhere as you mentioned in the visuals or screenshots.
