### ISSUE TITLE
AADConnect might need a rephrase

### ISSUE THREAD

**Issue by Daynvheur** [MicrosoftDocs/entra-docs#149]
Hi,
The "AADConnect sync" might need a rephrase as "Entra Connect sync", since it's no longer referring to "Azure Active Directory Connect sync".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42ce8623-6117-dd4d-781a-69eabbc5134d
* Version Independent ID: 1b7502ce-8dc9-86c1-d768-d8e4fdad08f0
* Content: [Microsoft Entra Connect Sync: Understand and customize synchronization - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sync-whatis)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sync-whatis.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sync-whatis.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@Daynvheur 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Daynvheur 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
