### ISSUE TITLE
When -IncludeAdminSdHolders parameter is set, it does not apply correct permissions to admin users

### ISSUE THREAD

**Issue by sethicle** [MicrosoftDocs/entra-docs#15]
For business that is syncing the Domain Admins to Entra AD (i know this is not recommended) the scripts (and the Entra Ad Connect Tool Trouble-shooter) do not apply the correct permissions to the adminsdholder object.

it seems to just be applying the same permissions as the root directory (where all the normal user objects reside with inheritance) however the domain admin/protected accounts are using adminsdholder for its permission template. this is of course by design however when the permissions get applied to this object (and ultimately copied to the admins ACLS) it is putting the applies to as Descendant User Objects. 

It appears though the admin accounts are NOT descendant objects of the AdminSDHolder Object so when the ACL is copied across to the admin user objects it copies it exactly as what adminsdholder has and the permissions do not allow for write access as the ACL isnt applying to this object but rather to descendant objects.

when setting AdminSDHolder to read and write for this object only (for read and write attributes) and apply to the accounts (by manually running sdprop via LDP, the correct permisssions apply and i am able to sync.

hope this makes sense for your team.

Thanks,
Seth

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfe7c261-f83a-6980-26db-3dd281936a9b
* Version Independent ID: 152fe879-8685-bb18-84b2-9a0f6b45b63c
* Content: [Microsoft Entra Connect: Configure AD DS Connector Account Permissions  - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-configure-ad-ds-connector-account)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-configure-ad-ds-connector-account.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-configure-ad-ds-connector-account.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by RamanathanChinnappan-MSFT** [comment]
@sethicle 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@sethicle 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by sethicle** [comment]
It may want to be noted in documentation that this permission is to be set manually on the accounts to ensure syncing with Entra AD? 

I do note that this is not recommended and iw I'll be adjusting this in the new year to not be DA users however if AdminSDHolder is selected the script should set the correct permissions since the documentation states that it should be set to Yes to update if you wish to sync DA users.

Thanks,
Seth

**Comment by SaibabaBalapur-MSFT** [comment]
@sethicle 
Based on the provided document, it seems that the permission needs to be set manually on the accounts to ensure syncing with Entra AD. However, it is not recommended to set the permission on DA users. If you want to sync DA users, you can set the AdminSDHolder to Yes to update the permissions. The script should set the correct permissions if you follow the instructions in the documentation. If you have any further questions or concerns, please let me know.
