### ISSUE TITLE
Tidak ada 

### ISSUE THREAD

**Issue by Putrirahmann8** [MicrosoftDocs/entra-docs#150]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06201faf-0037-3647-4e91-bb0af80d4812
* Version Independent ID: 1b397d76-ecfe-046e-a4c4-0fe5293bceb3
* Content: [What is entitlement management? - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-overview)
* Content Source: [docs/id-governance/entitlement-management-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/entitlement-management-overview.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by AjayBathini-MSFT** [comment]
@Putrirahmann8 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by AjayBathini-MSFT** [comment]
@Putrirahmann8 
Based on that shared information we are not able to understand your query/feedback completely. Could you please elaborate the query for better understanding. That way, we are able to make sure your feedback is addressed by the right team.
