### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/entra-docs#154]
what are the permissions (role) required?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84b26750-880c-8f14-1628-436293de915e
* Version Independent ID: 518b727f-79e8-b5c2-bcb3-ff4de3444c6f
* Content: [Configure Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-mfasettings)
* Content Source: [docs/identity/authentication/howto-mfa-mfasettings.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-mfasettings.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@SquirrelAssassin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @SquirrelAssassin 
This document you provided explains how to configure MFA settings in Azure AD, but it does not mention the specific permissions or roles required to do so. However, in general, to configure MFA settings in Azure AD, you need to have the Global Administrator or User Administrator role assigned to your account. These roles have the necessary permissions to manage Azure AD users and their authentication settings, including MFA.

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by SaibabaBalapur-MSFT** [comment]
@SquirrelAssassin 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
