### ISSUE TITLE
Nested groups and Enterprise Applications

### ISSUE THREAD

**Issue by epomatti** [MicrosoftDocs/entra-docs#156]
This bullet point from the list of unsupported features:

> We currently don't support:
> - Assigning apps to nested groups.

Not sure it is the same scenario, but I was able to add/assign a nested group to an enterprise application.

However, if instead I try to add the parent group to the Enterprise Application, then it shows a warning about cascading the permissions to the nested groups:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/6530769/6f424e87-01c1-4e93-81af-2014ecf90456)

If I understand, the limitation is that permissions from a parent group won't cascade to nested groups, but you can add/assign nested groups to the enterprise applications, and direct memberships will receive the assignment.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8e8f086-fb5c-4fe3-10d3-cf6c5557559d
* Version Independent ID: 3188422c-1f0d-f99c-ad0c-19b22a75e1fb
* Content: [How to manage groups - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-manage-groups)
* Content Source: [docs/fundamentals/how-to-manage-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-manage-groups.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by AjayBathini-MSFT** [comment]
@epomatti 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@shlipsey3 
Can you please check and add your comments on this doc update request as applicable.

**Comment by shlipsey3** [comment]
Been a minute since I've looked at nested groups, but the idea is that only the parent group gets the assignment, whether you assign the app to the group or the other way around. The nested group won't get the assignment regardless of how it's assigned. I'll look into adding some clarifying language. Thanks!

**Comment by AjayBathini-MSFT** [comment]
@epomatti 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by epomatti** [comment]
@AjayBathini-MSFT I understand clarification will be added to the documentation. Up to you if you want to keep this opened or not.
