### ISSUE TITLE
Confirm doc availability in Azure China

### ISSUE THREAD

**Issue by alexchen2016** [MicrosoftDocs/entra-docs#158]
Hi team,

Can you help to confirm whether SAML 2.0 supported in Azure China and whether this doc can be used in Azure China? 
Thanks.

Regards
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c01ec6a-ab66-33b1-8e6f-6437e8f4f660
* Version Independent ID: 2f64f95f-9403-bc88-ac72-5ce56f9d50c3
* Content: [Microsoft Entra Connect: Use a SAML 2.0 Identity Provider for Single Sign On - Azure - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp#azure-ad-saml-20-protocol-requirements)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@alexchen2016 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @alexchen2016 
Azure China is a separate sovereign cloud and has its own set of documentation and requirements. 

The documentation you provided is for Azure AD and is not specific to Azure China. It is possible that some of the information in the documentation may not be applicable to Azure China. 

To confirm whether SAML 2.0 is supported in Azure China and to obtain the relevant documentation, I recommend checking the Azure China documentation or contacting Azure China support. You can find more information on Azure China support here: https://www.azure.cn/support/
