### ISSUE TITLE
Typo in "Microsoft Entra Privilegd Identity Management"

### ISSUE THREAD

**Issue by hklaassens-ydentic** [MicrosoftDocs/entra-docs#16]
"Privilegd" should of course be "Privileged". There are three instances of this typo, I'm sure you'll have no trouble ctrl+f-ing the offenders.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 065f3268-d37c-3282-9d4a-2e7dfa0dd0b0
* Version Independent ID: 4076d45d-44fa-84f0-aa9c-04e4a5c4dfb7
* Content: [How to rename Azure Active Directory (Azure AD) - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-rename-azure-ad#update-the-naming-in-your-content)
* Content Source: [docs/fundamentals/how-to-rename-azure-ad.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-rename-azure-ad.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by RamanathanChinnappan-MSFT** [comment]
@hklaassens-ydentic 
Thanks for your feedback! We will investigate and update as appropriate.
