### ISSUE TITLE
What about POST for the AuthnRequest?

### ISSUE THREAD

**Issue by barbj** [MicrosoftDocs/entra-docs#161]
I asked in this question: [Does Azure SAML IDP require that the service provider use “HTTP redirect” binding to verify signatures on authnrequest ?](https://learn.microsoft.com/en-us/answers/questions/1165933/does-azure-saml-idp-require-that-the-service-provi?comment=question) and now I will ask here (because this is the article in contention) and the Q was never directly answered for 1y.

Is HTTP-Redirect a requirement for the AuthnRequest, or was it just used in service of the example.  Is HTTP-POST binding also supported for the AuthnRequest (Redirect is the default and POST is configurable)?  Because Azure AD supports HTTP-POST binding for the AuthnRequest, my take is that Redirect is in service of the example, but I'm putting words in your mouth.  You need to put words in your Entra mouth.  

This document is causing much confusion all over.  Supremely for the many SPs that only support HTTP-POST binding for the AuthnRequest, then have to have discussions with customers who then point directly at this Entra page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62bb99a4-4092-0202-48bf-4e61ee424faf
* Version Independent ID: a066de9a-42fb-2fcc-683d-2ffdc45fdf3d
* Content: [Single sign-on SAML protocol - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-saml-protocol)
* Content Source: [docs/identity-platform/single-sign-on-saml-protocol.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/single-sign-on-saml-protocol.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by AjayBathini-MSFT** [comment]
@barbj 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@barbj 
I'm going to assign this to the document author so they can take a look at it accordingly

@OwenRichards1 
Can you please check and add your comments on this doc update request as applicable.

**Comment by barbj** [comment]
Hi @OwenRichards1 

I found this doc:
[Use a SAML 2.0 Identity Provider (IdP) for Single Sign On](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp?source=recommendations)

This example is for an Entra ID connection to a back-end SAML IdP.  This information holds merit for the query to Entra ID at hand.

This process allows POST binding only for the authRequest: [Supported Bindings](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp?source=recommendations#supported-bindings)

<hr/>

<img width="859" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/24277731/8f21dca9-322b-492f-a08d-dc56e3b57803">

<hr/>

Note that this doc specifically says *requires* POST binding and the other doc is ambiguous.

> This document contains detailed requirements on the protocol and message formatting that your SAML 2.0 identity provider must implement to federate with Microsoft Entra ID to enable sign-on to one or more Microsoft cloud services (such as Microsoft 365). The SAML 2.0 relying party (SP-STS) for a Microsoft cloud service used in this scenario is Microsoft Entra ID.

In this example, the stated example provider is ADFS.

Given the [original doc in question](https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-saml-protocol) and [this one](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp?source=recommendations), we have two conclusions:
- Entra ID couldn't be used as its own back-end IdP
- Entra ID is putting requirements on other IdPs that it refuses to meet itself.

The following would make no sense:
- Entra ID is only supports POST binding for the authnRequests from its SP
- Entra ID only supports Redirect binding for the authnRequests to its IdP

<hr/>

Since this makes no sense, I suspect that Entra ID, just like Azure, can be configured for POST binding for inbound authnRequests.  Can you fix the [doc that implies otherwise](https://learn.microsoft.com/en-us/entra/identity-platform/single-sign-on-saml-protocol)?  And how do you do it?  Customers continually trip on this issue (because Redirect is the default), and now that there is a page that implies that Redirect is required, SPs are in a bind.

<hr/>

Here are the instructions for setting up a SAML provider in Entra ID:
[Set up a SAML 2.0 provider with Microsoft Entra ID](https://learn.microsoft.com/en-us/power-pages/security/authentication/saml2-settings-azure-ad)

I understand that setup examples can be fast path and might not mention all configuration options; I have many of those myself.  However, my articles point off to other pages that describe everything else that you can do with the specific SSO runtime and how to do it. 

<hr/>

Good luck on your investigation.

**Comment by ArturZezulaHCL** [comment]
Here: https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts750054-saml-request-not-present#resolution is stated that 
"The application needs to send the SAML request encoded into the location header using HTTP redirect binding."

Is there option in Entra ID to use HTTP Post Binding?
