### ISSUE TITLE
PowerShell examples to add members to Admin Unit have incomplete URL

### ISSUE THREAD

**Issue by jpawlowski** [MicrosoftDocs/entra-docs#163]
Hello,

The examples of the PowerShell section have an incomplete `-Uri` parameter, so the commands won't work.
The actual last part of the URI should be `/members/$ref`, not `/members/`.

It is correct for the other examples in the Microsoft Graph API section below.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43480033-c11c-c89d-bbaf-7d9790000782
* Version Independent ID: 4ff490a6-474c-1305-29b7-d728de56d7b2
* Content: [Add users, groups, or devices to an administrative unit - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/admin-units-members-add#powershell)
* Content Source: [docs/identity/role-based-access-control/admin-units-members-add.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/admin-units-members-add.md)
* Service: **active-directory**
* Sub-service: **roles**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@jpawlowski 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@jpawlowski 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
