### ISSUE TITLE
New Windows 365 High Spec SKUs Missing

### ISSUE THREAD

**Issue by seanlillis** [MicrosoftDocs/entra-docs#165]
The new high spec Windows 365 SKUs seem to be missing from this list: https://learn.microsoft.com/en-us/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell?view=o365-worldwide

Also, the corresponding CSV file: https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv

Can these be added please?

LicenseSKU        : Windows_365_Enterprise_16_vCPU,_64_GB,_1_TB
LicenseID         : 44ac0b13-905a-4f95-9945-db084cfdfcc6

LicenseSKU        : Windows_365_Enterprise_16_vCPU,_64_GB,_512_GB
LicenseID         : 1f4eb439-ec97-4dbf-9171-704fd4970f97

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc0555a1-2410-5679-03f3-e5768a1dc9cd
* Version Independent ID: e3d2444e-22f6-f697-03a4-9edb8226b72e
* Content: [View Microsoft 365 licenses and services with PowerShell - Microsoft 365 Enterprise](https://learn.microsoft.com/en-us/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell?view=o365-worldwide)
* Content Source: [microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/enterprise/view-licenses-and-services-with-microsoft-365-powershell.md)
* Service: **microsoft-365-enterprise**
* GitHub Login: @kelleyvice-msft
* Microsoft Alias: **kvice**

**Comment by AjayBathini-MSFT** [comment]
@seanlillis 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by seanlillis** [comment]
@AjayBathini-MSFT, the document has still not been updated, why has the issue been closed?
