### ISSUE TITLE
Switch function is referenced with the use of IsPresent and against it

### ISSUE THREAD

**Issue by fedgalnebu** [MicrosoftDocs/entra-docs#167]
In the article there is an example using the Switch function with IsPresent, and then a Caution box advising against the use of IsPresent and/or IsNullOrEmpty.
This is quiet confusing and testing is not conclusive as of which is the correct way to implement complex logic in this regard, in my case for a SSFF integration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8685339-06af-5bb1-64da-80c16878b0bf
* Version Independent ID: 1ee0d812-00de-90cc-f5e2-d53e3b610bf0
* Content: [Reference for writing expressions for attribute mappings in Microsoft Entra Application Provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/functions-for-customizing-application-data#switch)
* Content Source: [docs/identity/app-provisioning/functions-for-customizing-application-data.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/functions-for-customizing-application-data.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by RamanathanChinnappan-MSFT** [comment]
@fedgalnebu
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@fedgalnebu 
I understand your confusion. The caution box you mentioned is advising against using IsPresent and/or IsNullOrEmpty functions in attribute mappings, as they can lead to unexpected results. However, the Switch function is a valid and useful function for implementing complex logic in attribute mappings. 

The Switch function is used to return a single value based on evaluated conditions. The expressions are evaluated from left to right, and the value associated with the first expression to evaluate to True is returned. If none of the expressions are True, Switch returns a Nothing. 

So, if you need to implement complex logic in attribute mappings, you can use the Switch function with appropriate expressions and values. However, it is recommended to avoid using IsPresent and/or IsNullOrEmpty functions in attribute mappings. 

I hope this helps clarify your doubts. Let me know if you have any further questions.

**Comment by fedgalnebu** [comment]
Hi Saibaba, thank you for your response.
I would argue that the discretional use of IsPresent nested on a Swithc function is confusing. In the docs you have an example:
[cid:ca663202-a057-40a6-bf57-12f4335526f4]
If it's advised against the use of nested IsPresent, but there are valid uses, then it would be useful to have clear documentation of those uses. If not, one can end up developing functions with unexpected results.

Regdards,
Federico


________________________________

**Comment by SaibabaBalapur-MSFT** [comment]
@fedgalnebu 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@kenwith 
Can you please check and add your comments on this doc update request as applicable.
