### ISSUE TITLE
Update example to replace to-be-deprecated MSOnline cmdlets

### ISSUE THREAD

**Issue by CaffeinatedComa** [MicrosoftDocs/entra-docs#171]
This page includes an example using PowerShell cmdlets from the MSOnline module that is being formally deprecated on March 30, 2024. This needs to be updated to include the Microsoft Graph equivalent operation, for forward compatibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb129d2-9594-bf0c-5946-982f0ed0d888
* Version Independent ID: 6522b038-6853-3552-55c8-f174cf56573d
* Content: [Enable per-user multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-userstates)
* Content Source: [docs/identity/authentication/howto-mfa-userstates.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-userstates.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RamanathanChinnappan-MSFT** [comment]
@CaffeinatedComa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@CaffeinatedComa 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@CaffeinatedComa thanks for flagging this. That script has no Graph PS equivalent, so we removed it. #please-close
