### ISSUE TITLE
SSH certificate based authentication using AAD

### ISSUE THREAD

**Issue by sschandran** [MicrosoftDocs/entra-docs#175]
In the diagram that talks about the SSH authentication flow with AZ CLI,  how is the certificate validated in the VM. I see step 8 that looks like a request to Azure AD from the VM. Could you provide more details on how the requests looks like.
Is it possible to do SSH certificate based authentication  using Azure AD on a non-VM host? Could you provide links to that if available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbc788cf-2460-3a99-a770-796471df0293
* Version Independent ID: b84f1579-fd1b-f0e4-a46a-27ba15a58baa
* Content: [SSH authentication with Microsoft Entra ID - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/auth-ssh)
* Content Source: [docs/architecture/auth-ssh.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/auth-ssh.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by AjayBathini-MSFT** [comment]
@sschandran 

Thank you for your question. In the SSH authentication flow with AZ CLI diagram, the certificate is validated in the VM by the SSH daemon running on the VM. When the SSH daemon receives the SSH certificate from the client, it checks the certificate against the authorized keys file to determine if the certificate is valid and if the user is authorized to access the VM.

In step 8 of the diagram, the VM sends a request to Azure AD to validate the certificate. This request is made using the OpenID Connect protocol, which allows the VM to authenticate the user and obtain an access token that can be used to access Azure AD resources.

The request to Azure AD includes the SSH certificate and other information about the user and the VM. The certificate is validated by Azure AD using the public key of the certificate authority that issued the certificate. If the certificate is valid, Azure AD returns an access token to the VM, which can be used to access Azure AD resources.

Regarding your question about doing SSH certificate-based authentication using Azure AD on a non-VM host, it is possible to use Azure AD to authenticate SSH connections to non-VM hosts using the SSH Certificate Authentication feature in Azure AD. This feature allows you to use SSH certificates to authenticate users and authorize access to non-VM hosts.

To use SSH Certificate Authentication with non-VM hosts, you will need to configure the SSH daemon on the host to accept SSH certificates and configure Azure AD to issue SSH certificates to users. You can find more information on how to configure SSH Certificate Authentication in Azure AD in the following documentation:

https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-certificate-based-authentication
