### ISSUE TITLE
Wrong code in example of client certificate

### ISSUE THREAD

**Issue by SWarnberg** [MicrosoftDocs/entra-docs#176]
I think the code configuration when specifying a certificate is wrong. It says **ClientCredentials** when it should be **ClientCertificates**.

In the document:

```
   "ClientCredentials": [
      {
        "SourceType": "KeyVault",
        "KeyVaultUrl": "https://msidentitywebsamples.vault.azure.net",
        "KeyVaultCertificateName": "MicrosoftIdentitySamplesCert"
      }
   ]
```

According to https://github.com/AzureAD/microsoft-identity-web/wiki/Using-certificates:

```
    "ClientCertificates": [
      {
        "SourceType": "KeyVault",
        "KeyVaultUrl": "https://msidentitywebsamples.vault.azure.net",
        "KeyVaultCertificateName": "MicrosoftIdentitySamplesCert"
      }
     ]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f81a334a-eccc-b862-1a45-e58d151b8621
* Version Independent ID: cee85377-c930-2e20-715d-004e5431a92f
* Content: [Configure a web app that calls web APIs - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-app-call-api-app-configuration?tabs=aspnetcore)
* Content Source: [docs/identity-platform/scenario-web-app-call-api-app-configuration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-web-app-call-api-app-configuration.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@SWarnberg 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@SWarnberg 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
