### ISSUE TITLE
Confirm whether google cloud supported in Azure China or not

### ISSUE THREAD

**Issue by alexchen2016** [MicrosoftDocs/entra-docs#178]
Hi team,

There is an item "Google Cloud" in "Supported scenarios" section in this article. 
Can you help to confirm whether "Google Cloud" supported or not in Azure China? Thanks.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/13617729/eb5ef22b-8cfd-41c8-a33c-81714116fad5)

Regards
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf644d11-51ae-8ef0-34c8-d471a47d5cf1
* Version Independent ID: d5e3190b-f287-6542-fd2b-f8fe9066c23e
* Content: [Workload identity federation - Microsoft Entra Workload ID](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation)
* Content Source: [docs/workload-id/workload-identity-federation.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/workload-id/workload-identity-federation.md)
* Service: **active-directory**
* Sub-service: **workload-identities**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by AjayBathini-MSFT** [comment]
@alexchen2016 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@rwike77
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@alexchen2016 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by johnnyyuelee008** [comment]
@rwike77  
cloud you feedback it ? the cx still wating the result. thanks.

**Comment by alexchen2016** [comment]
@rwike77, Any update?

**Comment by alexchen2016** [comment]
@rwike77, @ManoharLakkoju-MSFT, Any update?

**Comment by ManoharLakkoju-MSFT** [comment]
@rwike77 
Kindly please review this.

**Comment by rwike77** [comment]
@alexchen2016  Hi, I've added an engineering PM to our email thread internally.  I'll update this issue when I've gotten an answer.

**Comment by rwike77** [comment]
Got confirmation from engineering.  Currently, this is not supported in East Asia.  #please-close
