### ISSUE TITLE
Fix cmd to export cert

### ISSUE THREAD

**Issue by gu-aalvarez** [MicrosoftDocs/entra-docs#180]
[Enter feedback here]
Hey, I tried running the command to export the cert and was running into issues.

I believe this because the command may be missing some of the cert location details which causes errors.

I did the following which worked, I believe others should know as well.

_After running previous commands_
```
$thumbprint = $cert.Thumbprint

$mypwd = ConvertTo-SecureString -String {myPassword} -Force -AsPlainText  ## Replace {myPassword}

Export-PfxCertificate -Cert "Cert:\CurrentUser\My\$thumbprint" -FilePath "C:\Users\admin\Desktop\$certname.pfx" -Password $mypwd  ## Specify your preferred location
```

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc9bed86-d11a-8f1f-4e58-dfa693f0c8df
* Version Independent ID: 65163c9f-40ad-ea33-e589-cc5a9b7b2d77
* Content: [Create a self-signed public certificate to authenticate your application - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/howto-create-self-signed-certificate)
* Content Source: [docs/identity-platform/howto-create-self-signed-certificate.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/howto-create-self-signed-certificate.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by ManoharLakkoju-MSFT** [comment]
@gu-aalvarez 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@henrymbuguakiarie
Can you please check and add your comments on this doc update request as applicable.
