### ISSUE TITLE
Unclear sentence

### ISSUE THREAD

**Issue by david-williams-wwt** [MicrosoftDocs/entra-docs#181]
The following sentence makes absolutely no sense to me. The subject is 'the consent screen' and the verb 'request' is not in a singular form, so they don't match. I'm not sure what the sentence means.

"When triggering a consent screen using known client applications and .default, the consent screen shows permissions for both the client to the middle tier API, and also request whatever permissions are required by the middle-tier API."

I would suggest you hire people with English language degrees to write your training and documentation. They should be native speakers, so that common mistakes made by speakers of English as a second language are not promoted. 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d91ee0b-7926-c0ad-aca2-48958c81acf3
* Version Independent ID: 9fa490aa-49e4-8034-83c2-d6c8517834da
* Content: [Microsoft identity platform and OAuth2.0 On-Behalf-Of flow - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-on-behalf-of-flow)
* Content Source: [docs/identity-platform/v2-oauth2-on-behalf-of-flow.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-oauth2-on-behalf-of-flow.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by ManoharLakkoju-MSFT** [comment]
@david-williams-wwt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@david-williams-wwt 

I apologize for the confusion caused by the sentence. It seems to contain a grammatical error that makes it difficult to understand. 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
