### ISSUE TITLE
Teams service administrator as Catalog owner? 

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/entra-docs#183]
Dear Team! 

"Teams service administrator" is assigned as Catalog owner? No such entra ID role exists. Please update to confirm which role applies. I assume it's just the Teams Administrator? but you know what they say about assumptions. 

Teams Administrator | Can manage the Microsoft Teams service. 
Teams Communications Administrator | Can manage calling and meetings features within the Microsoft Teams service.
Teams Communications Support Engineer | Can troubleshoot communications issues within Teams using advanced tools.
Teams Communications Support Specialist | Can troubleshoot communications issues within Teams using basic tools. 
Teams Devices Administrator

Cheers
Joshua

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e42fb095-d0d2-bcc8-9048-615027626c22
* Version Independent ID: 54e26c06-0d56-b390-b257-82d584506bd2
* Content: [Delegation and roles in entitlement management - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-delegate)
* Content Source: [docs/id-governance/entitlement-management-delegate.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/entitlement-management-delegate.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**[Teams Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#teams-administrator)	Can manage the Microsoft Teams service.	69091246-20e8-4a56-aa4d-066075b2a7a8
[Teams Communications Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#teams-communications-administrator)	Can manage calling and meetings features within the Microsoft Teams service.	baf37b3a-610e-45da-9e62-d9d1e5e8914b
[Teams Communications Support Engineer](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#teams-communications-support-engineer)	Can troubleshoot communications issues within Teams using advanced tools.	f70938a0-fc10-4177-9e90-2178f8765737
[Teams Communications Support Specialist](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#teams-communications-support-specialist)	Can troubleshoot communications issues within Teams using basic tools.	fcf91098-03e3-41a9-b5ba-6f0ec8188a12
[Teams Devices Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#teams-devices-administrator)

**Comment by RamanathanChinnappan-MSFT** [comment]
@JBines 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@JBines 
I'm going to assign this to the document author so they can take a look at it accordingly

@OWinfreyATL 
Can you please check and add your comments on this doc update request as applicable.

**Comment by OWinfreyATL** [comment]
Hey @JBines 

Good call out and your assumption would be correct. The Teams adminsitrator would be the role to have. We will be going through the documents in the coming weeks to make sure our suggested roles are current :)

thanks again!

#please-close

**Comment by JBines** [comment]
I was also thinking maybe some might be confused which teams administrator is applied I think that's why 'service' might have been added to begin with but maybe it's clear enough. I can't think of a better way to write it but maybe you have some ideas. Thanks for the follow up.
