### ISSUE TITLE
Missing Reply URL Information

### ISSUE THREAD

**Issue by tleepa** [MicrosoftDocs/entra-docs#185]
This page is missing details on the "Reply URL (ACS)", which is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ebad160-aa6c-cfc6-35b4-1c330b423363
* Version Independent ID: 6e5a6ead-582e-2a24-71e2-ed3fc5641ec1
* Content: [Tutorial: Microsoft Entra single sign-on (SSO) integration with Palo Alto Networks - GlobalProtect - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/palo-alto-networks-globalprotect-tutorial)
* Content Source: [docs/identity/saas-apps/palo-alto-networks-globalprotect-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/palo-alto-networks-globalprotect-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by RamanathanChinnappan-MSFT** [comment]
@tleepa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@tleepa 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
