### ISSUE TITLE
Restoring an application in Azure AD.

### ISSUE THREAD

**Issue by apatil155** [MicrosoftDocs/entra-docs#186]
The ObjectID of an application is different in enterprise applications and app registrations. Running the restore command using the ObjectID will only restore the application in the registered application. We need to run the restore command using the Application ID to restore the application as an enterprise application.

These details will help users to understand the difference between an application using OIDC and SAML for authentication.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49f59a37-d380-b534-fd24-995e89b0d7b2
* Version Independent ID: 6ae0b7e9-3673-21b6-709e-0d36024bdf99
* Content: [Restore a soft deleted enterprise application - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/restore-application?tabs=http)
* Content Source: [docs/identity/enterprise-apps/restore-application.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/restore-application.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by Naveenommi-MSFT** [comment]
@apatil155 
Thank you for bringing this to our attention.
I've delegated this to content author @omondiatieno, who will review it and offer their insightful opinions.

@omondiatieno 
Could you please review add comments on this, update as appropriate.

**Comment by omondiatieno** [comment]
Hi @apatil155, thank you for raising the issue. I'll update the article to make it clearer when to use a service principal ID and when to use an app ID.
