### ISSUE TITLE
A few issues we found that added hours to the process

### ISSUE THREAD

**Issue by JeffreyRosenberg** [MicrosoftDocs/entra-docs#189]
In the section where you download the certificate, you do not mention downloading the XML settings.  Later, when you upload XML settings, the only ones you have downloaded are from AWS and are not the right ones to upload to AWS.  You need to mention downloading the MS XML settings and importing those into AWS.

When you instruct us to have the accounts made, you create an Entra account B.Simon@contoso.com and an AWS account B.Simon (with email address B.Simon@contoso.com).  When the two accounts don't match, even if emails match, the SSO does not work.  It goes all the way through and then fails with a "Something went wrong. Looks like this code isn't right" message. If the AWS account is made with B.Simon@contoso.com as the name as well as the email address, it works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8e131bf-99d7-a850-a597-ac02b9f6c3a9
* Version Independent ID: a27625d3-cf35-ffaf-5734-d1a2bbcdd60c
* Content: [Tutorial: Microsoft Entra SSO integration with AWS IAM Identity Center (successor to AWS Single Sign-On) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/aws-single-sign-on-tutorial?source=recommendations)
* Content Source: [docs/identity/saas-apps/aws-single-sign-on-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/aws-single-sign-on-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by AjayBathini-MSFT** [comment]
@JeffreyRosenberg 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@JeffreyRosenberg 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd 
Can you please check and add your comments on this doc update request as applicable.

**Comment by v-hgampala** [comment]
Document updated as suggested, issue resolved.
#please-close
