### ISSUE TITLE
Can't find app Microsoft Azure Management

### ISSUE THREAD

**Issue by Damian-C22** [MicrosoftDocs/entra-docs#19]
[Enter feedback here]
Hi
Last time Microsoft change how we can find appliaction when creating CAP policy. In the past the name was DisplayName - now is Name. 
So for Microsoft Azure Management app to add to CAP Policy we have to use the name "Windows Azure Service Management API". Can you change your articles ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22df42c6-831d-ba42-8224-27176e8fd7d9
* Version Independent ID: 15299b18-e361-9e9f-f836-f37a466dcae0
* Content: [Require MFA for Azure management with Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-azure-management)
* Content Source: [docs/identity/conditional-access/howto-conditional-access-policy-azure-management.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/howto-conditional-access-policy-azure-management.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Damian-C22
Thanks for your feedback! We will investigate and update as appropriate.
