### ISSUE TITLE
OIDC

### ISSUE THREAD

**Issue by henriqueTr25** [MicrosoftDocs/entra-docs#192]
The step 
5.1 Using OpenID Connect identity provider
I think this step is outdated or it does not work with Microsoft Entra B2C (preview) tenant

I have a tenant Entra B2C and a Microsoft Entra Id tenant. Mu azure function is in Microsoft Entra Id tenant and the App Registration is in Entra B2C. I followed up this steps from this page and everything works fine, until this step, that I receive an error message AADSTS1100001: Non-retryable error has occurred. when try to login.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00b5cb48-d4b9-4baa-3aa2-0c9d096db9fb
* Version Independent ID: 00b5cb48-d4b9-4baa-3aa2-0c9d096db9fb
* Content: [Create attribute collection events (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-attribute-collection?context=%2Fentra%2Fexternal-id%2Fcustomers%2Fcontext%2Fcustomers-context&tabs=start-continue%2Csubmit-continue)
* Content Source: [docs/identity-platform/custom-extension-attribute-collection.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-attribute-collection.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@henriqueTr25 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @henrique

To troubleshoot the issue, I would recommend checking the following:

1. Ensure that the App Registration in your Entra B2C tenant has been configured correctly and that the client ID and client secret have been entered correctly in your Azure Function's configuration.
3. Check that the redirect URI in your App Registration matches the redirect URI in your Azure Function's configuration.
4. Verify that the scopes requested by your Azure Function match the scopes configured in your App Registration. 
5. Check that the user flow you are using in your App Registration is compatible with the OpenID Connect protocol.

If you have checked all of the above and are still experiencing issues, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by Naveenommi-MSFT** [comment]
@henriqueTr25 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
