### ISSUE TITLE
Incorrect Scope for Custom Role creation

### ISSUE THREAD

**Issue by Smerqq** [MicrosoftDocs/entra-docs#193]
Under the section "Create a role using PowerShell" the command `Connect-MgGraph -Scopes "RoleManagement.Read.All"` does not grant enough permission to create a custom role.

When using the `New-MgRoleManagementDirectoryRoleDefinition` command, you will receive an insufficient privileges error. 

The command and scope should be `Connect-MgGraph -Scopes "RoleManagement.ReadWrite.Directory"`

This scope grants the correct permissions to Microsoft Graph Command Line Tools.

When testing, make sure that Microsoft Graph Command Line Tools does not already have the RoleManagement.ReadWrite.Directory permissions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 649bef7e-a492-d5b1-183a-be12c8994a51
* Version Independent ID: d79544a5-4b92-185e-0bcc-83660ecee475
* Content: [Create custom roles in Microsoft Entra role-based access control - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-create)
* Content Source: [docs/identity/role-based-access-control/custom-create.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/custom-create.md)
* Service: **active-directory**
* Sub-service: **roles**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Smerqq 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Smerqq 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@rolyon 
Can you please check and add your comments on this doc update request as applicable.

**Comment by rolyon** [comment]
Hi @Smerqq
Thanks for taking the time to provide your feedback. We updated the scopes in the doc.
https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-create
thanks

**Comment by rolyon** [comment]
#please-close
