### ISSUE TITLE
Microsoft identity platform authentication libraries

### ISSUE THREAD

**Issue by SAEED2ALAHMARI** [MicrosoftDocs/entra-docs#196]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b787325-589c-b5f5-f530-7f1fe12e075e
* Version Independent ID: 6d678569-0ebe-f2ef-ecd7-69cc62b4b7be
* Content: [Microsoft identity platform authentication libraries - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-v2-libraries#single-page-application-spa)
* Content Source: [docs/identity-platform/reference-v2-libraries.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-v2-libraries.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by RamanathanChinnappan-MSFT** [comment]
@SAEED2ALAHMARI 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@SAEED2ALAHMARI 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by SaibabaBalapur-MSFT** [comment]
@SAEED2ALAHMARI 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
