### ISSUE TITLE
There is a spelling error.

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/entra-docs#197]
See the word combination "performedusing"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62f978ec-9661-d804-bcc5-d4af11287414
* Version Independent ID: beba2bc9-c45b-1d0f-7bbe-bcb7c0f5d8e7
* Content: [Microsoft Graph PowerShell examples for group licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-powershell-graph-examples)
* Content Source: [docs/identity/users/licensing-powershell-graph-examples.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-powershell-graph-examples.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Jmartinez589
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Jmartinez589 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
