### ISSUE TITLE
Verify howto-vm-sign-in-azure-ad-windows.md

### ISSUE THREAD

**Issue by russelljt** [MicrosoftDocs/entra-docs#2]
References to **Azure Windows VM Sign-In** appear to be outdated. Cloud App with appid of 372140e0-b3b7-4226-8ef9-d57986796201 now shows as **Microsoft Azure Windows Virtual Machine Sign-In**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7e4fdb9-a3d4-e97b-de30-9904868b87a5
* Version Independent ID: fbade46e-55b3-3c50-9cff-6ec88ee5ee6e
* Content: [Group-based licensing additional scenarios - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-group-advanced)
* Content Source: [docs/identity/users/licensing-group-advanced.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-group-advanced.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@russelljt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
#reasssign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
This has been addressed. #please-close
