### ISSUE TITLE
Questions on Microsoft-managed Conditional Access Policies

### ISSUE THREAD

**Issue by matthewjlevy** [MicrosoftDocs/entra-docs#20]
Hi there, I would like to know a couple of things that are not documented about Microsoft-managed policies. Perhaps a FAQ page would be useful.

1. If I as an admin set a Microsoft-managed policy to "Off" in the 90 day review period, will it be left off indefinately or will Microsoft "nudge" me to enable it again sometime in the future?
2. Will Microsoft run the analysis on my tenant for the same risk going forward? So if I duplicate the Microsoft-managed policy to mitigate the risk and then in say 18 months time, I delete that policy or another admin accidentally deletes the policy, will the Microsoft-managed policy return as a recommendation to the tenant?
3. I guess this is somewhat related to 1 and 2 above. Will the Microsoft-managed policy, once in my tenant in whatever state it finds itself to be in after the 90 days remain tagged as "Microsoft Managed" even after I have either edited it or duplicated it?

Thanks for helping with some questions I think customers are going to be asking.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 363f6ddc-5e98-73d8-bf28-e94a1f49cd7f
* Version Independent ID: 363f6ddc-5e98-73d8-bf28-e94a1f49cd7f
* Content: [Secure your resources with Microsoft-managed Conditional Access policies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/managed-policies#what-if-i-want-to-make-more-changes)
* Content Source: [docs/identity/conditional-access/managed-policies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/managed-policies.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by RamanathanChinnappan-MSFT** [comment]
@matthewjlevy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
While I can't comment on future ideas or roadmaps...

1. If you turn it off, we will leave it off. 
2. The Microsoft-managed policy can't be deleted so it will be there.
3. The original will remain tagged as Microsoft-managed. You are welcome to clone or create your own policy based on these.

#please-close
