### ISSUE TITLE
Escape characters in output?

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/entra-docs#202]
Looks like someone is using unneeded escape characters in the document which are shown in output. 

Examples:
GRP\\_JAPAN\\_My Group\\_Engineering
\\[Department\\]
Grp\\_Name, \\#Name, and \\_Name.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3fb85a8-d842-f101-909e-86751922da43
* Version Independent ID: 0c99b5ef-753e-1085-a682-c55ea4059207
* Content: [Enforce a group naming policy in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-naming-policy)
* Content Source: [docs/identity/users/groups-naming-policy.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-naming-policy.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by SaibabaBalapur-MSFT** [comment]
@velden 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@velden 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
