### ISSUE TITLE
Incorrect Steps

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/entra-docs#209]
Steps 5 and 6 under the 'Configure Microsoft Entra SSO' do not make sense. 

Step 5 says: "On the Basic SAML Configuration section, the user does not have to perform any step as the app is already pre-integrated with Azure." 
However that is incorrect since the Identifier field is not filled in and is a required field. This is the primary reason for submitting feedback on this article.

Step 6 says: "Click Set additional URLs and perform the following step if you wish to configure the application in SP initiated mode:" 
This is a small issue, but there isn't a 'Set additional URL' to click. The Sign-On URL is already ready for editing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a32e07b5-d627-4bc3-1a6e-834d2e8405cf
* Version Independent ID: dfab2d22-e68d-8adb-01dd-63fee27602c0
* Content: [Tutorial: Microsoft Entra SSO integration with Navan - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/navan-tutorial)
* Content Source: [docs/identity/saas-apps/navan-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/navan-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by SaibabaBalapur-MSFT** [comment]
@DontNeedNoGit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@DontNeedNoGit 
Thank you for bringing this to our attention.
I've delegated this to content author @jeevansd, who will review it and offer their insightful opinions.

@jeevansd 
Could you please review add comments on this, update as appropriate.

**Comment by v-hgampala** [comment]
@DontNeedNoGit, thanks for raising the issue!
the identifier field is auto populating once you edit the configuration and please click the save button so, the identifier value will not be a required field.
we're correcting the step 6 in the document.
#please-close
