### ISSUE TITLE
Multiple Domains with different Entra ID Tenants in the same Forest

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/entra-docs#21]
Hi

After looking through the documentation it doesn't appear as if the following scenario is documented:
- Active Directory is a single Forest with 2 child domains
- Each child domain currently has a dedicated AD Connect server pointing to a dedicated Entra ID tenant

If we wish to deploy Password Protection for 1 child domain only this seems simple enough and the current documentation is sufficient. What appears to be missing is what happens if we wish to enable the second child domain into its dedicated tenant. 

We are unsure if this is a supported scenario, mainly due to the documentation highlighting that a lot of the configuration appears to be forest-wide when we would need 2 different configurations at the forest level.

If this is an unsupported scenario it would be useful to have this highlighted, possibly in the FAQ page? If it is supported it would be useful to point this out at the relevant steps to ensure that we are following accurate guidance and not overwriting the first configuration in the forest.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23e000f0-84ce-7ec7-e5ed-4bd9c49f5d49
* Version Independent ID: e636b9d1-be81-0f00-97c4-ff4fa9078be3
* Content: [Deploy on-premises Microsoft Entra Password Protection - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-ban-bad-on-premises-deploy)
* Content Source: [docs/identity/authentication/howto-password-ban-bad-on-premises-deploy.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-password-ban-bad-on-premises-deploy.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RamanathanChinnappan-MSFT** [comment]
@ld0614 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Justinha
Could you Please review this and update as appropriate.

**Comment by Justinha** [comment]
@ld0614 sorry for delay. We only support 1:1 forest\tenant binding. All proxies registered within a forest MUST be registered against the same tenant otherwise the results will be undefined. The issue is documented at https://learn.microsoft.com/en-us/entra/identity/authentication/concept-password-ban-bad-on-premises#forest--tenant-binding-for-microsoft-entra-password-protection

#please-close
