### ISSUE TITLE
Additional information for ForceDelete option

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/entra-docs#210]
Please add a bullet stating that user accounts impacted by the ForceDelete option will be disabled (Azure/Entra Portal and optionally when using the Graph API). This is accurately called out when performing the operation via the Entra Portal, but not in the docs... the two locations should be aligned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67566e6a-ffb4-4adf-73b5-3d6c0c58cd05
* Version Independent ID: 9c9a6f63-ec87-0e45-9d0e-f5030041ab06
* Content: [Add and verify custom domain names - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/domains-manage)
* Content Source: [docs/identity/users/domains-manage.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/domains-manage.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by SaibabaBalapur-MSFT** [comment]
@andypituch 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@andypituch 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
https://github.com/MicrosoftDocs/entra-docs-pr/pull/1271
