### ISSUE TITLE
Set Password white sending a Create user Request via the Provisioning API in ENTRA ID

### ISSUE THREAD

**Issue by ShinraTenseiii** [MicrosoftDocs/entra-docs#213]
Hi Team,

I am trying to set a random password while creating new account in Entra ID for users and send them the credentials via email.

The HTTP call says success and the account gets created but the Password does not work. It says that the username or email is incorrect.  Can you please help me in setting a password via the API-Driven Inbound User Provisioning?

**Comment by SaibabaBalapur-MSFT** [comment]
@ShinraTenseiii 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by SaibabaBalapur-MSFT** [comment]
@ShinraTenseiii 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
