### ISSUE TITLE
SCIM role provisioning: Should you use the role id or use role value instead?

### ISSUE THREAD

**Issue by dbollaer** [MicrosoftDocs/entra-docs#215]
Hello,
I am trying to integrate a new application using SCIM roles.
To do this, I configured my roles attribute, using roles(AppRoleAssignmentsComplex([appRoleAssignments]).
Everything works as documented, but I am having a problem with an inconsistency.
Create contains these attributes
```json
 {
           "primary": false,
           "type": "WindowsAzureActiveDirectoryRole",
           "displayName": "Admin",
           "value": "Admin"
 }
```
But PATCH creates these attributes:
```json

{"id":"06b07648-ecfe-589f-9d2f-6325724a46ee","value":"Admin","displayName":"Admin"}

```

meaning, no Id is provided with create request.

Does this mean, we should not rely on the id, but on the value?
Could you please clarify this in the documentation?

Thank you in advance.

Best regards,
Danny

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b07a9e-5e16-32ed-265e-32a32998ce37
* Version Independent ID: 09008259-4b53-2925-9679-ecad59cefe41
* Content: [Tutorial - Customize Microsoft Entra attribute mappings in Application Provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/customize-application-attributes)
* Content Source: [docs/identity/app-provisioning/customize-application-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/customize-application-attributes.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SaibabaBalapur-MSFT** [comment]
@dbollaer 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @dbollaer 
In the case of SCIM roles, the `id` attribute is not always required, and it is possible to rely on the `value` attribute instead. The `value` attribute contains the name or identifier of the role, and it can be used to uniquely identify the role in some cases.

However, it is important to note that relying solely on the `value` attribute may not be sufficient in all cases, especially if there are multiple roles with the same name or identifier. In these cases, it may be necessary to use the `id` attribute to uniquely identify the role.

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by lorieide** [comment]
Updated the "Provisioning a role to a SCIM app" section to include a note and things to consider:

NOTE: When provisioning roles from enterprise applications, the SCIM standard defines enterprise user role attributes differently. For more information, see https://review.learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups#design-your-user-and-group-schema.

 - When integrating applications using SCIM roles, the `id` attribute is not always required, as for certain cases you can use the `value` attribute instead. For example, if the `value` attribute contains the name or identifier for the role, you can use it to provision the role. However, relying solely on the `value` attribute may not always be sufficient; for example, if there are multiple roles with the same name or identifier. In certain cases, it may be necessary to use the `id` attribute to properly provision the role.
 
#please-close
