### ISSUE TITLE
Helpful tips

### ISSUE THREAD

**Issue by StreichersBC** [MicrosoftDocs/entra-docs#217]
[Enter feedback here]
How about letting us know how to tell which version we are using?

I had a partner set it up for me and would like to check which version before I call them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09eb3bfb-5bcc-3fb1-b36b-6222fe1f4e51
* Version Independent ID: 9772c16b-8364-3ba2-a8b5-2f31a2abef5d
* Content: [Decommissioning Azure AD Connect V1 - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/decommission-connect-sync-v1?WT.mc_id=Portal-Microsoft_AAD_IAM)
* Content Source: [docs/identity/hybrid/decommission-connect-sync-v1.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/decommission-connect-sync-v1.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@StreichersBC 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by billmath** [comment]
The following document tells you how to check your version.
https://learn.microsoft.com/en-us/entra/identity/hybrid/verify-sync-tool-version 

Thanks!

#please-close
