### ISSUE TITLE
How to update associated app gallery documentation?

### ISSUE THREAD

**Issue by Stephanie-kno2** [MicrosoftDocs/entra-docs#218]
Based on this article https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/v2-howto-app-gallery-listing#app-documentation-on-the-microsoft-site 

There is a way to update App Gallery documentation for a company using github. 

What is the process to update documentation that is listed in this repository for setting up a gallery app for SSO?

This is the documentation I'm attempting to update: https://learn.microsoft.com/en-us/entra/identity/saas-apps/kno2fy-tutorial 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 940793a4-349e-a07a-32ab-ed35e56c8ca2
* Version Independent ID: c0c89aaf-b5f8-9773-1db4-5a1d2da0b67a
* Content: [Microsoft Entra SSO integration with Kno2fy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/kno2fy-tutorial)
* Content Source: [docs/identity/saas-apps/kno2fy-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/kno2fy-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by AjayBathini-MSFT** [comment]
@Stephanie-kno2 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-hgampala** [comment]
@Stephanie-kno2, you can update the document by clicking on edit/pencil icon at the top-right corner of article page and please share us the PR once you created for your changes -
<img width="723" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/102347245/6dec2268-c91b-4db2-85af-fc42b4a01a17">

**Comment by v-hgampala** [comment]
@Stephanie-kno2, I think you got the solution for your query, so Iam closing now.
#please-close
