### ISSUE TITLE
Broken Link to PowerShell script

### ISSUE THREAD

**Issue by ColmanPerkins-Stephen** [MicrosoftDocs/entra-docs#219]
The link in the page near the top is broken.
Link text: "You can use this [PowerShell script](https://learn.microsoft.com/en-us/samples/azure-samples/azure-mfa-authentication-method-analysis/azure-mfa-authentication-method-analysis/) to analyze users' MFA configurations and suggest the appropriate MFA authentication method."

Should link to "https://github.com/Azure-Samples/azure-mfa-authentication-method-analysis"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 329ec11e-2b1a-c837-14fa-ce37843cc0af
* Version Independent ID: f3502c0a-f6fe-b004-39fe-c82c5a85f3b3
* Content: [Deployment considerations for Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-getstarted)
* Content Source: [docs/identity/authentication/howto-mfa-getstarted.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-getstarted.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@ColmanPerkins-Stephen 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @ColmanPerkins-Stephen 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

Hi @Justinha 
Can you please check and add broken link for PowerShell script for analyze users' MFA configurations on this doc update request as applicable.

**Comment by Justinha** [comment]
@ColmanPerkins-Stephen thanks so much and sorry for delay! Fixed now. #please-close
