### ISSUE TITLE
Step 7.

### ISSUE THREAD

**Issue by jonbrekhusvt** [MicrosoftDocs/entra-docs#22]
Why do you have the user copy App Federation Metadata Url?  The document never says to paste the App Federation Metadata Url?
7. On the Set up single sign-on with SAML page, In the SAML Signing Certificate section, click copy button to copy App Federation Metadata Url and save it on your computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 957b6f8e-0640-074e-bc70-2934eae5969a
* Version Independent ID: c2d53cc6-f094-c87a-763a-2ce96aa747d2
* Content: [Tutorial: Microsoft Entra SSO integration with hireEZ-SSO - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/hiretual-tutorial)
* Content Source: [docs/identity/saas-apps/hiretual-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/hiretual-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jonbrekhusvt
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@jeevansd 
Can you please check and add your comments on this doc update request as applicable.

@jonbrekhusvt 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by Harshita-130901** [comment]
As we noticed Application side configuration steps are incorrect, we are updating them and the Federation Metadata XML file which is downloaded from the Microsoft Entra admin center is used in the Application side configuration steps.

we're creating a separate PR for the changes in our private repo, you may expect the updated doc within 2-3 working days.
#please-close
