### ISSUE TITLE
Missing or Wrong Info for Microsoft Copilot for M365

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/entra-docs#220]
Hello,
please check the Identifier for Microsoft "Copilot for Microsoft 365"
We have licenses in our tenant and we see SKUID  (GUID)  639dec6b-bb19-468b-871c-c5c441c4b0cb 
and SKU PartNumber (String ID) "Microsoft_365_Copilot"
According to this page it is supposed to be "a809996b-059e-42e2-9866-db24b99a9782" and "M365_Copilot"
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by AjayBathini-MSFT** [comment]
@joergrenn 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Nicholak-MS** [comment]
I have made this update to correct the value. It will publish later today. 

Thanks

#please-close
