### ISSUE TITLE
Column Names vs Graph API

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/entra-docs#221]
Hello,

in the table on this page the columns are named "String ID" and "GUID".
However when fetching licenses via Graph "get-mgsubscribedSku" the properties are called "SkuPartNumber" and "SkuId".
Could this be adapted, so the same terms are used everywhere?

**Comment by AjayBathini-MSFT** [comment]
@joergrenn 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by joergrenn** [comment]
Hello @AjayBathini-MSFT 
the question is what is the "correct" Name for these properties?
On that it depends if the documentation needs to be updated or the graph api response.

You can get the licenses via Powershell using the example listed on this [MS Learn Page.](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/get-mgsubscribedsku?view=graph-powershell-1.0#example-1-get-subscribed-skus)
![pwsh](https://github.com/MicrosoftDocs/entra-docs/assets/62641471/fd1602c9-ec30-4931-ae1e-6059f1093e3a)
![img1](https://github.com/MicrosoftDocs/entra-docs/assets/62641471/3b667aa3-e10f-4586-b668-829ad27f370d)

**Comment by AjayBathini-MSFT** [comment]
@joergrenn 

Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.
