### ISSUE TITLE
typo in note

### ISSUE THREAD

**Issue by pedroneil** [MicrosoftDocs/entra-docs#223]
To step through the multifactor **authnetication** as a user, see [Sign in to your work or school account using your two-step verification method](https://support.microsoft.com/account-billing/sign-in-to-your-work-or-school-account-using-your-two-step-verification-method-c7293464-ef5e-4705-a24b-c4a3ec0d6cf9)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80005683-d3e5-aab5-2642-677a2ef96203
* Version Independent ID: 6abac9a6-5472-62c3-5eae-fa39ecccd12e
* Content: [Enable Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/tutorial-enable-azure-mfa)
* Content Source: [docs/identity/authentication/tutorial-enable-azure-mfa.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/tutorial-enable-azure-mfa.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@pedroneil 
Thanks for your feedback! We will investigate and update as appropriate.
