### ISSUE TITLE
Device Registration Service Service Principal suspicious activity on the AADPasswordProtectionProxy Service Principal

### ISSUE THREAD

**Issue by sopopa2** [MicrosoftDocs/entra-docs#224]
Customers report that the Device Registration Service Service Principal is creating and updating certificates on the AADPasswordProtectionProxy Service Principal. Events show in the audit logs and look suspicious.

We know that this is expected because these are the Password Protection "credentials to communicate with Microsoft Entra ID", which are managed in fact by the Device Registration Service Service Principal.
However, this is not mentioned anywhere in the public documentation. Please consider adding this information into the public doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23e000f0-84ce-7ec7-e5ed-4bd9c49f5d49
* Version Independent ID: e636b9d1-be81-0f00-97c4-ff4fa9078be3
* Content: [Deploy on-premises Microsoft Entra Password Protection - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-ban-bad-on-premises-deploy#install-and-configure-the-proxy-service)
* Content Source: [docs/identity/authentication/howto-password-ban-bad-on-premises-deploy.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-password-ban-bad-on-premises-deploy.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@sopopa2 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@sopopa2 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by Justinha** [comment]
@sopopa2 thanks for the suggestion and sorry for delay. This point has been added to the key considerations section. #please-close
