### ISSUE TITLE
Portal seems to have changed  - no longer accurate-- Navigate to Global Settings > Account Settings and click Define under SSO Authentication. 

### ISSUE THREAD

**Issue by thomasjsweet** [MicrosoftDocs/entra-docs#225]
[Enter feedback here]
This is no longer accurate- specifically  Navigate to Global Settings > Account Settings and click Define under SSO Authentication. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 193ac564-5141-3964-008c-1777ecfdb3e7
* Version Independent ID: 55473104-deb0-bada-525b-b74f69cdf061
* Content: [Tutorial: Microsoft Entra SSO integration with Check Point Infinity Portal - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/checkpoint-infinity-portal-tutorial)
* Content Source: [docs/identity/saas-apps/checkpoint-infinity-portal-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/checkpoint-infinity-portal-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by AjayBathini-MSFT** [comment]
@thomasjsweet 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@thomasjsweet 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd
Can you please check and add your comments on this doc update request as applicable.

**Comment by v-hgampala** [comment]
@thomasjsweet, we're working on the document changes to the latest UI and it will be going to update soon.
#please-close
