### ISSUE TITLE
Managed enivironment section seems to mismatch

### ISSUE THREAD

**Issue by Arun-271** [MicrosoftDocs/entra-docs#226]
This page discusses about the entra join machines which is different from entra join machines for hybrid environment , then why in the manged environment section it is mentioned that the authentication is done with the help of password hash synchronization and 
Microsoft Entra pass-through authentication which is a hybrid environment case. Please clarify. 
thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c65624ff-7545-8514-4374-7dde7885ef43
* Version Independent ID: 2687cf32-1618-a8d9-b249-7f31765f6856
* Content: [Plan your Microsoft Entra join deployment - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/device-join-plan)
* Content Source: [docs/identity/devices/device-join-plan.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/device-join-plan.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@Arun-271 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
You can have Microsoft Entra joined devices even if you are a hybrid customer with resources on-premises. 

Entra joined devices can access resources on-premises still. You don't have to deploy hybrid joined devices to maintain access on-premisies.

**Comment by ManoharLakkoju-MSFT** [comment]
@MicrosoftGuyJFlo 
Thanks for your inputs.

@Arun-271 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by ManoharLakkoju-MSFT** [comment]
@Arun-271 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
