### ISSUE TITLE
Wrong connector for inbound entra connect sync rule in Step 3, Point 3

### ISSUE THREAD

**Issue by pstapf** [MicrosoftDocs/entra-docs#227]
Documentation is wrong, Step 3 Point 3 you need to select the Entra Id Connect not the AD connector as the attribute "cloudMastered" does only exist in Entra Id, not in AD.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1da65039-05e7-474c-ee47-b1e62acb64b7
* Version Independent ID: 1da65039-05e7-474c-ee47-b1e62acb64b7
* Content: [Migrate Microsoft Entra Connect Sync group writeback V2 to Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/migrate-group-writeback)
* Content Source: [docs/identity/hybrid/cloud-sync/migrate-group-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/migrate-group-writeback.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@pstapf 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@pstapf 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
