### ISSUE TITLE
Licensing required

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/entra-docs#228]
Hello everyone!
According to the following docs, Microsoft Entra Connect Health requires Microsoft Entra ID P1 licenses:

- https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-azure-ad-connect
- https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-health-faq

Does this requirement also apply to Microsoft Entra Connect Health **for sync**? (The Health Agent for sync will be installed as part of the Microsoft Entra Connect installation (version 1.0.9125.0 or higher)). This feature is enabled by default after install Microsoft Entra Connect. So if I don't have Microsoft Entra ID P1 licenses, should I disable this feature?

Thanks!
Fernando

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86ed5438-9076-fa6f-d42a-e9bef29beb6e
* Version Independent ID: f6490079-8f4a-f621-623b-d500b52abef8
* Content: [What is Microsoft Entra Connect and Connect Health. - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-azure-ad-connect)
* Content Source: [docs/identity/hybrid/connect/whatis-azure-ad-connect.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/whatis-azure-ad-connect.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@FernandoGualano 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@FernandoGualano 

The requirement for Microsoft Entra ID P1 licenses also applies to Microsoft Entra Connect Health for sync. If you do not have Microsoft Entra ID P1 licenses, you should disable this feature to avoid any licensing compliance issues.
Please go through this below link for your reference.
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-health-agent-install#:~:text=installation%20instructions.-,Install%20the%20agent%20for%20AD%20FS,Entra%20admin%20center.%20For%20more%20information%2C%20see%20the%20requirements.,-Manually%20register%20Microsoft

**Comment by FernandoGualano** [comment]
Hi @Naveenommi-MSFT!
Thanks for your feedback! 
In my case, I do not have Microsoft Entra ID P1/P2 licenses. How do I disable this feature? I didn't find documentation about it.

Thanks!
Fernando

**Comment by Naveenommi-MSFT** [comment]
@FernandoGualano 
To disable Microsoft Entra Connect Health for sync, you can follow these steps:

1. Open the Azure AD Connect configuration wizard.
2. Go to services
3. Select "Microsoft Entra Connect Health"
4. If enable the feature. Click it and change the state as Disable.
5. Complete the configuration wizard to save the changes.
<img width="362" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/113576472/d0141d2e-d0ee-4177-8652-365016d43252">
