### ISSUE TITLE
Outdate instructions?

### ISSUE THREAD

**Issue by alxalm** [MicrosoftDocs/entra-docs#229]
I couldn't match any of the instructions on the page to what I see in the Azure Portal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72f2e675-436d-dcd4-fa27-49408b201158
* Version Independent ID: 4d821732-fc10-f4a6-3c7d-77bce75299d7
* Content: [Add company branding to your organization's sign-in page - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-customize-branding)
* Content Source: [docs/fundamentals/how-to-customize-branding.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-customize-branding.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by AjayBathini-MSFT** [comment]
@alxalm 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by shlipsey3** [comment]
@alxalm Can you describe what you are seeing? It could depend on if you start on the Default sign-in tab vs the Getting started tab. I can make a note about those. But I want to make sure we're talking about the same thing.
Thanks!

**Comment by alxalm** [comment]
@shlipsey3 As I said in my opening comment, I was in the Azure Portal. The instructions in the doc indicate that you should be on Entra admin center and that's where I got confused. I'm still confused with why you'd be making some but not all functions available in the Azure Admin Portal. In any case, the instructions in the doc are correct with respect to the Entra admin center. I just verified. Thanks

**Comment by shlipsey3** [comment]
@alxalm 
The introduction of the new Microsoft Entra admin center makes it complicated to write about features that are available in both the Microsoft Entra admin center and the Azure Portal. We can't provide explicit instructions for both, so we call that out in the documentation.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/66325782/30ce7205-276a-4978-98bc-e3221701dff7)

The company branding is available in the Azure Portal. All of Microsoft Entra ID - formerly Azure AD - is still available in the portal, although the navigation to those features is different. To align with the direction we're heading as a company with the new Microsoft Entra admin center, we're writing for that experience and not the Azure Portal.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/66325782/ecdfe159-7eb7-490e-85a2-997791de9ef1)

**Comment by shlipsey3** [comment]
#please-close
