### ISSUE TITLE
Question about "remember MFA on trusted device" setting

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/entra-docs#230]
The legacy service settings include an option to customize how long a successful MFA is remembered on their trusted devices:
![image](https://github.com/MicrosoftDocs/entra-docs/assets/9206808/611535da-6e90-477a-aa9c-f242e074a5f2)

Is this setting going to still be respected if we complete the migration and/or is there a place to set it in the "Authentication methods policy for Microsoft Entra ID" or must we use "Conditional Access sign-in frequency" for this?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9e50bc-931a-80b2-7363-da6eec0643db
* Version Independent ID: 03575b7a-0bfd-3b6d-cb49-c00d929e68ea
* Content: [How to migrate to the Authentication methods policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-authentication-methods-manage)
* Content Source: [docs/identity/authentication/how-to-authentication-methods-manage.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-authentication-methods-manage.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@sparkitect 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sparkitect** [comment]
Awesome, thank you for those links.
