### ISSUE TITLE
Wrong note description

### ISSUE THREAD

**Issue by reparaturo** [MicrosoftDocs/entra-docs#232]
In the note at the bottom of the page it states

Note
If you're only making a temporary switch to password hash synchronization, then select the Do not convert user accounts check box. Not checking the option will convert each user to federated, and it can take several hours.

There is nowhere a selection checkbox "Do not convert user accounts check box" shown.  Maybe they mean the radio button 'Do not configure'. But this would make no sense as one would need to use one of the propose login methods.
I recommend to either place a correct image or change the note.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b5d859b-57c8-a09b-d21b-2d533542fc65
* Version Independent ID: 09946fbd-cfcd-c30a-1f0d-6e3423813022
* Content: [Microsoft Entra Connect: User sign-in - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/plan-connect-user-signin)
* Content Source: [docs/identity/hybrid/connect/plan-connect-user-signin.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/plan-connect-user-signin.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@reparaturo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@reparaturo 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
