### ISSUE TITLE
Code doesn't work in the Azure Cloud Shell

### ISSUE THREAD

**Issue by dernerl** [MicrosoftDocs/entra-docs#234]
Import-Module Microsoft.Graph.Beta.Applications                                   
Import-Module: **The specified module 'Microsoft.Graph.Beta.Applications' was not loaded because no valid module file was found in any module directory.**

and so the other codes
Get-MgBetaServicePrincipal: The term 'Get-MgBetaServicePrincipal' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 885962c3-89c0-319a-b9fd-84f50d490925
* Version Independent ID: 8fbf93ab-7fdf-13e5-7b64-c0e0e7a8cb7c
* Content: [List Microsoft Entra application proxy connector groups for apps - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/scripts/powershell-get-all-app-proxy-apps-by-connector-group)
* Content Source: [docs/identity/app-proxy/scripts/powershell-get-all-app-proxy-apps-by-connector-group.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/scripts/powershell-get-all-app-proxy-apps-by-connector-group.md)
* Service: **active-directory**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Thank you for the feedback and taking the time to open an issue. I appreciate you. I am removing the cloud shell information until I can figure out the issue.

#please-close
