### ISSUE TITLE
Incorrect steps for POP policy

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#236]
The POP policy (https://learn.microsoft.com/en-us/entra/id-governance/configure-logic-app-lifecycle-workflows#configure-authorization-policy-for-custom-task-extension-with-pop-security-token-type) appears to be a cut-and-paste from the older normal policy. POP policy doesn't appear to need the app id and is creating a single policy, not multiple. This needs to be revisited to be accurate by removing the cut-and-paste content that is not needed for POP.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f86844f-b95c-700a-acd6-8569ada8c6a2
* Version Independent ID: f7a95a72-1516-1da4-9ca2-9c8199bb3ea2
* Content: [Configure a Logic App for Lifecycle Workflow use - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/configure-logic-app-lifecycle-workflows)
* Content Source: [docs/id-governance/configure-logic-app-lifecycle-workflows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/configure-logic-app-lifecycle-workflows.md)
* Service: **active-directory**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by AjayBathini-MSFT** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dloder0 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@OWinfreyATL 
Can you please check and add your comments on this doc update request as applicable.

**Comment by OWinfreyATL** [comment]
Hey @dloder0 

Thanks for bringing this to our attention! I have created a PR and issue with our product team to address this issue and the article should be updated shortly :)

Thanks again!

#please-close
