### ISSUE TITLE
Missing Licensing Info for: Microsoft Entra ID Governance

### ISSUE THREAD

**Issue by MShwed** [MicrosoftDocs/entra-docs#237]
Hi there,

On the page https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference it appears to be missing references for licensing information related to:

- Product Name: `Microsoft Entra ID Governance` 
- SkuID: `cf6b0d46-4093-4546-a0ab-0b1546dcc10e`
- Service Plan ID: `e866a266-3cff-43a3-acca-0c90a7e00c8b`
- Service Plan name: `Entra_Identity_Governance`

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by AjayBathini-MSFT** [comment]
@MShwed 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Nicholak-MS** [comment]
Thank you for the feedback. The missing product ID has been added to both the online table as well as the downloadable CSV. These changes will publish later today.

#please-close
