### ISSUE TITLE
The answer does not match with the question in FAQ

### ISSUE THREAD

**Issue by sscchh2001** [MicrosoftDocs/entra-docs#238]
**In FAQ, the answer does not match with the question.**

> Once SAML/WS-Fed IdP federation is configured with an organization, does each guest need to be sent and redeem an individual invitation?
> 
> Setting up SAML/WS-Fed IdP federation doesn’t change the authentication method for guest users who have already redeemed an invitation from you. You can update a guest user’s authentication method by [resetting their redemption status](https://learn.microsoft.com/en-us/entra/external-id/reset-redemption-status).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1d9428-2dbb-c80b-c2cd-b4841d3d8bd3
* Version Independent ID: 20af5f8d-479c-66ec-aacd-d3f9cb79c814
* Content: [Federation with a SAML/WS-Fed identity provider (IdP) for B2B - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/direct-federation#end-user-experience)
* Content Source: [docs/external-id/direct-federation.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/direct-federation.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@sscchh2001 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.
