### ISSUE TITLE
Staged Rollout Interactive Link leads to partner site with no content relating to Staged Rollout

### ISSUE THREAD

**Issue by holmanjd** [MicrosoftDocs/entra-docs#240]
In the next steps section, the Staged Rollout Interactive Link no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 841f2ad4-1af1-b725-8e21-401a2046653b
* Version Independent ID: 2d82ba73-8dc0-56b7-74a5-59e29d0d19be
* Content: [Microsoft Entra Connect: Cloud authentication via Staged Rollout - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-staged-rollout#prework-for-seamless-sso)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-staged-rollout.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-staged-rollout.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ManoharLakkoju-MSFT** [comment]
@holmanjd 
I'm going to assign this to the document author so they can take a look at it accordingly

@billmath 
Can you please check and add your comments on this doc update request as applicable.

**Comment by billmath** [comment]
I have opened a ticket to investigate this.  In the meantime the link has been removed.  Thank you @holmanjd for catching this.  I am going to close this for now and will update if there is any updates in the future.  Thanks!

#please-close
