### ISSUE TITLE
Select Microsoft Entra ID

### ISSUE THREAD

**Issue by JMo8675309** [MicrosoftDocs/entra-docs#241]
The steps begin at Select Microsoft Entra ID.  But how did you get to that screen?  Is this in portal.azure.com?  Do I go to ADF?  Need a little more navigation instructions here!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1ef3583-67cc-685f-fb2e-09b64f682bf2
* Version Independent ID: 8e441ecd-4771-8620-4423-8c40d8cce192
* Content: [View service principal of a managed identity in the Azure portal - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-view-managed-identity-service-principal-portal)
* Content Source: [docs/identity/managed-identities-azure-resources/how-to-view-managed-identity-service-principal-portal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/how-to-view-managed-identity-service-principal-portal.md)
* Service: **active-directory**
* Sub-service: **msi**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@JMo8675309 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @JMo8675309 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@JMo8675309 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
