### ISSUE TITLE
Page is missing license SKUs

### ISSUE THREAD

**Issue by cdrenshaw** [MicrosoftDocs/entra-docs#242]
I am using the [CSV file](https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv) on the [Licensing Service Plan Reference page](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference) to convert license SKUs to product names and the CSV is missing details for "Microsoft 365 Business Voice (US)", SKU ID: 08d7bce8-6e16-490e-89db-1d508e5e9609.  

Also, are there any plans to add a SKU lookup feature to Graph in the future?  Having to download and parse a CSV in my app to get the product name of a SKU returned from an API seems kind of clunky to me.  Is there a better way?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by AjayBathini-MSFT** [comment]
@cdrenshaw 
Thanks for your feedback! We will investigate and update as appropriate.
