### ISSUE TITLE
What is with the .org is that a typo?

### ISSUE THREAD

**Issue by youngr13uiuedu** [MicrosoftDocs/entra-docs#243]
What is with the .org in here, is that a typo?  Everything is .com or .local but there is one .org that I see currently and it is throwing me through a loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72cdc251-618a-e84e-f40d-960b0ac69f99
* Version Independent ID: 8cbaba3c-e883-2c71-28fb-f88db3fcaf7d
* Content: [Plan your Microsoft Entra hybrid join deployment - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/hybrid-join-plan)
* Content Source: [docs/identity/devices/hybrid-join-plan.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/hybrid-join-plan.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@youngr
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
The example is saying... 
- **.org** is what they built their on-premises directory with. 
- at some point after that they went to the cloud with some of their infrastructure and used **.com** there. 
 
You can have both. Some people used to use **.local** for on-premises AD.

**Comment by Naveenommi-MSFT** [comment]
@youngr13uiuedu 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
