### ISSUE TITLE
Minor correction to section label

### ISSUE THREAD

**Issue by jpjeffery** [MicrosoftDocs/entra-docs#246]
Section title: "Create a new certificate"

Step 6 mentions "...find the SAML Signing Certificate heading...", but that heading name doesn't exist. It should be just "SAML Certificates"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2344f9d-a62b-26f2-aef5-d6828d2890c9
* Version Independent ID: ec5de129-aa5f-eb8b-5f48-3949fec0f356
* Content: [Tutorial: Manage federation certificates - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on)
* Content Source: [docs/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by AjayBathini-MSFT** [comment]
@jpjeffery 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@jpjeffery 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
