### ISSUE TITLE
Found some more unidentifiable skuIDs

### ISSUE THREAD

**Issue by Magnus-A-69** [MicrosoftDocs/entra-docs#247]
Hi.

Noticed that the following ids used in our tenant could not be found, could you please add them?

SkuID         : af739e8e-dd11-4eb5-a986-5908f595c603
SkuPartNumber : DYN365_PROJECT_OPERATIONS_ATTACH

SkuID         : 090b4a96-8114-4c95-9c91-60e81ef53302
SkuPartNumber : DYN365_SCM_ATTACH

SkuID         : 3a349c99-ffec-43d2-a2e8-6b97fcb71103
SkuPartNumber : Viva_Goals_User_led

SkuID         : 19dec69d-d9f3-4792-8a39-d8ecdf51937b
SkuPartNumber : D365_CUSTOMER_SERVICE_PRO_ATTACH

SkuID         : ece037b4-a52b-4cf8-93ea-649e5d83767a
SkuPartNumber : Microsoft_Cloud_for_Sustainability_USL

SkuID         : b84d58c9-0a0d-46cf-8a4b-d9f23c1674d5
SkuPartNumber : Operator_Connect_Mobile

SkuID         : b75074f1-4c54-41bf-970f-c9ac871567f5
SkuPartNumber : Dyn365_Operations_Activity

SkuID         : 52ea0e27-ae73-4983-a08f-13561ebdb823
SkuPartNumber : Teams_Premium_(for_Departments)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference#next-steps)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by Nicholak-MS** [comment]
Thank you for the feedback. The missing product IDs has been added to both the online table as well as the downloadable CSV. These changes will publish later today.

#please-close
