### ISSUE TITLE
Ambiguous question regarding use of MIs

### ISSUE THREAD

**Issue by GoonerW** [MicrosoftDocs/entra-docs#25]
Question states "Which operations can I perform using managed identities?"

The answers in the subsequent paragraph deals with operations that can be performed "ON" the managed identity itself, not what operations that can be performed "USING" the managed identity against other services.

Given the content of the answer, I would suggest the question be updated to the following:
"Which operations can I perform on managed identities?"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72861cc1-7081-cf6e-b7f9-e700a16faa9a
* Version Independent ID: c870872d-0559-6b77-280f-f478e8c84776
* Content: [Managed identities for Azure resources - Microsoft Entra ID](https://learn.microsoft.com/en-gb/entra/identity/managed-identities-azure-resources/overview)
* Content Source: [docs/identity/managed-identities-azure-resources/overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/overview.md)
* Service: **active-directory**
* Sub-service: **msi**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by RamanathanChinnappan-MSFT** [comment]
@GoonerW 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@GoonerW 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
