### ISSUE TITLE
Code snippet with wrong values in Event Grid data connection creation in ADX using SDK

### ISSUE THREAD

**Issue by lucabovo** [MicrosoftDocs/entra-docs#253]
Hi @shsagir, 
I came across this doc and I found a trivial error in a code snippet.

In paragraph "Create an Event Grid data connection"  ( https://learn.microsoft.com/en-us/azure/data-explorer/create-event-grid-connection-sdk?tabs=c-sharp%2Cazure-blob-storage%2Cc-sharp-2#create-an-event-grid-data-connection ) there is a C# snippet, and the 2 vars referring to EventHub and StorageAccount resource Ids have reversed values:
- var eventHubResourceId = new ResourceIdentifier("/subscriptions/<storageAccountSubscriptionId>/resourceGroups/<storageAccountResourceGroupName>/providers/Microsoft.Storage/storageAccounts/<storageAccountName>");
- var storageAccountResourceId = new ResourceIdentifier("/subscriptions/<eventHubSubscriptionId>/resourceGroups/<eventHubResourceGroupName>/providers/Microsoft.EventHub/namespaces/<eventHubNamespaceName>/eventhubs/<eventHubName>");
![image](https://github.com/MicrosoftDocs/entra-docs/assets/77054756/365ecacc-c668-4c33-8fda-c42be3c9f4c1)

Can you please fix the values, just to avoid misunderstanding?

Thanks!
Luca Bovo - Beantech

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5dfd15a9-68d9-b4da-f7e4-351168e911d1
* Version Independent ID: d47d0b65-6a38-f5fc-b179-44a8eee381b3
* Content: [Create an Event Grid data connection for Azure Data Explorer with SDKs](https://learn.microsoft.com/en-us/azure/data-explorer/create-event-grid-connection-sdk)
* Content Source: [data-explorer/create-event-grid-connection-sdk.md
](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/6e10daacfcefd15f904a22b476eff2f34f64f1a7/data-explorer/create-event-grid-connection-sdk.md)
* Service: **data-explorer**
* Sub-service: **data-explorer**
* GitHub Login: @shsagir 
* Microsoft Alias: **shsagir**

**Comment by Naveenommi-MSFT** [comment]
@lucabovo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@lucabovo 
I've delegated this to @shsagir, a content author, to review and share their valuable insights.

**Comment by CelesteDG** [comment]
#please-close
