### ISSUE TITLE
Missing Step in documentation

### ISSUE THREAD

**Issue by jiggyjiyane** [MicrosoftDocs/entra-docs#256]
What happened to step 15 "Define the users and/or groups that you would like to provision to AWS IAM Identity Center by choosing the desired values in Scope in the Settings section."

The option disappeared in the application in Azure, there is no longer a Scope section, what could possibly be the reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a63d94b1-c9fe-53e6-959e-790b57d3c3ce
* Version Independent ID: 3a8cb353-6c8d-10a6-9ffd-2cbabb3e74e3
* Content: [Tutorial: Configure AWS IAM Identity Center(successor to AWS single sign-On) for automatic user provisioning with Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/aws-single-sign-on-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/aws-single-sign-on-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/aws-single-sign-on-provisioning-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @twimmers
* Microsoft Alias: **thwimmer**

**Comment by AjayBathini-MSFT** [comment]
@jiggyjiyane 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by jiggyjiyane** [comment]
The setting has miraculously reappeared

**Comment by Naveenommi-MSFT** [comment]
@jiggyjiyane
Due to miscellaneous reasons, sometimes things happen like that. We expect the issue to be resolved, but if there are any further questions regarding the documentation, please tag me in your reply, and we will be happy to continue the conversation. Thanks!!!
