### ISSUE TITLE
This advice should be exposed directly on the Conditional Access config page itself!

### ISSUE THREAD

**Issue by GeldHades27355** [MicrosoftDocs/entra-docs#257]
The CA config page shows a message to "no longer use required approved client app". When doing that, i.e. switching to the newer "Require app protection policy", we inadvertently blocked access to work for new iOS users. See this setting I mean:
![Screenshot 2024-01-26 125041](https://github.com/MicrosoftDocs/entra-docs/assets/143819181/d8b9f7f3-61b9-40a3-bf5f-652336a34e2d)

Here is what happens:
1. Onboard your new iOS device to Intune MDM using Just in time enrollment.
2. App protection policies do not reliably deploy immediately. In fact, we see instances where it can take hours for that to happen.
3. During that time, apps do not have an app protection policy and CA blocks their access.
4. After a few hours, it seems all devices finally have app protection and access is restored.

This documentation contains a CRUCIAL piece of info to prevent that:
It recommends to deploy BOTH the older "use required client app" AND newer "require app protection policy", while only requiring ONE of the conditions to be met. This does, in fact solve the issue and appears to allow users to access work apps and data on their newly enrolled iOS device immediately.

So in short: please put the (good!) advice from this page right in to the CA config page to avoid folks from switching to instead of including the new policy.

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5b96d45-d3ce-83c2-695c-5b528e32149d
* Version Independent ID: 1315e93b-f3e0-c4aa-d43a-2b9e59378a46
* Content: [Migrate approved client app to application protection policy in Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/migrate-approved-client-app)
* Content Source: [docs/identity/conditional-access/migrate-approved-client-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/migrate-approved-client-app.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@GeldHades27355 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@GeldHades27355 
I'm going to assign this to the document author so they can take a look at it accordingly.

@MicrosoftGuyJFlo 
Please review it.

**Comment by GeldHades27355** [comment]
Folks, the documentation on the Learn site is CORRECT and GOOD. Because it works. 👍
So you got it right. 😁 (the Intune team didn't IMHO)

My comment was rather that Intune's internal UI should reflect what Learn says - because Intune's internal UI is misleading currently. Unless customers actually RTFM (😉), they risk disrupting their endpoint access.

Here are my suggestions (for the Intune team):

  1.  Don't make any recommendations or suggestions in the UI at all. Just mention that the behavior is changing and tell everyone to RTFM (your article) on what exactly to do. Nice and simple.
  2.  If space and the UI permit, make the same suggestions you do on the Learn site - but right within Intune.

Regards,
Dom

________________________________

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for the feedback I will pass it to the PM on my side I work with for this in Identity.

#please-close
