### ISSUE TITLE
Missing & in example code

### ISSUE THREAD

**Issue by autosysops** [MicrosoftDocs/entra-docs#259]
First Case code example is missing a "&" before client_id

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d91ee0b-7926-c0ad-aca2-48958c81acf3
* Version Independent ID: 9fa490aa-49e4-8034-83c2-d6c8517834da
* Content: [Microsoft identity platform and OAuth2.0 On-Behalf-Of flow - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-on-behalf-of-flow)
* Content Source: [docs/identity-platform/v2-oauth2-on-behalf-of-flow.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-oauth2-on-behalf-of-flow.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by AjayBathini-MSFT** [comment]
@autosysops 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @autosysops 
Thank you for bringing this to our attention! You've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
