### ISSUE TITLE
Permisisons to access 

### ISSUE THREAD

**Issue by itishnitsa-msft** [MicrosoftDocs/entra-docs#261]
Hi. Please add which Entra ID roles have access to this data. My customer got this error when accessing Scenario Monitoring tab using Global Reader role "You don't have access to this data. Please contact your global administrator to get access"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bade69c-88bb-3c9d-eaaa-eb004359742d
* Version Independent ID: 7bade69c-88bb-3c9d-eaaa-eb004359742d
* Content: [Learn about Microsoft Entra Health - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-microsoft-entra-health)
* Content Source: [docs/identity/monitoring-health/concept-microsoft-entra-health.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/monitoring-health/concept-microsoft-entra-health.md)
* Service: **active-directory**
* Sub-service: **report-monitor**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by AjayBathini-MSFT** [comment]
@itishnitsa-msft 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by shlipsey3** [comment]
Thanks for the feedback. Global Reader and Security Reader (mentioned in the article) are both roles that provide access to this data. I'm able to view it with the Global Reader role. I'm not sure why your customer got the error with that role. I'll do some testing and confirm with the product group.

**Comment by SaibabaBalapur-MSFT** [comment]
@itishnitsa-msft 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by shlipsey3** [comment]
@itishnitsa-msft Did you have any other details you can provide to help with testing?
