### ISSUE TITLE
GDPR Compliance: Authenticator app GPS location tracking. 

### ISSUE THREAD

**Issue by hakshire** [MicrosoftDocs/entra-docs#263]
https://learn.microsoft.com/en-us/entra/identity/conditional-access/location-condition

1. We have a customer requesting if GPS location based conditional access is GDPR compliant or not. If it is, publish the statement on the document along with the reference link to the GDPR documentation. 
2. The GPS location tracked by authenticator is stored somewhere or not. If not, please mention it on the public documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e67c377-d615-8779-b3f9-420fc4efd81d
* Version Independent ID: 3bcdc8e6-2ab6-5c62-dd5c-cc9a024f3428
* Content: [Using networks and countries/regions in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/location-condition)
* Content Source: [docs/identity/conditional-access/location-condition.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/location-condition.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@hakshire 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@MicrosoftGuyJFlo
Can you please check and add your comments on this doc update request as applicable.

**Comment by MicrosoftGuyJFlo** [comment]
#label:"awaiting-product-team-response"

**Comment by MicrosoftGuyJFlo** [comment]
AB#205448

**Comment by lisaychuang** [comment]
Checking with CELA (Eddie) to verify if there's specific guidance for GDPR compliance related Qs, and Authenticator PM (Zhanna) on GPS location data collection.

**Comment by lisaychuang** [comment]
Confirmed that "CELA doesn't have any particular verbiage that we recommend" and followed-up with CxE, Abizer shared support doc [Common questions about the Microsoft Authenticator app](https://support.microsoft.com/en-us/account-billing/common-questions-about-the-microsoft-authenticator-app-12d283d1-bcef-4875-9ae5-ac360e2945dd) which states that "Authenticator collects your GPS information...but your actual coordinates are never saved or stored on Microsoft servers."

@MicrosoftGuyJFlo please update MS docs to link the this FAQ page. thanks!

**Comment by MicrosoftGuyJFlo** [comment]
Thanks @lisaychuang adding link to the article provided with the additional info about the Microsoft Authenticator app https://support.microsoft.com/account-billing/common-questions-about-the-microsoft-authenticator-app-12d283d1-bcef-4875-9ae5-ac360e2945dd

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"awaiting-product-team-response"
