### ISSUE TITLE
Microsoft 365 Copilot Known Issue

### ISSUE THREAD

**Issue by DJHowellCA** [MicrosoftDocs/entra-docs#266]
The docs for Microsoft 365 Copilot site a known issue with any CA policy targeting SharePoint Online. That is what a Token Protection CA policy currently does.

In my testing M365 Copilot wouldn't light up in desktop apps until exempting a user from the Token Protection policy. Thus, these issues should be cross-referenced. And when fixed (hopefully soon!), updated again. 

Reference: https://learn.microsoft.com/en-gb/microsoft-365-copilot/microsoft-365-copilot-requirements#conditional-access

**Comment by AjayBathini-MSFT** [comment]
@DJHowellCA 
Thanks for your feedback! We will investigate and update as appropriate.
