### ISSUE TITLE
Microsoft Entra admin consent with user assignment required

### ISSUE THREAD

**Issue by TimoWilhelm** [MicrosoftDocs/entra-docs#267]
The section ["I have an application that requires user assignment. A user that I assigned to an application is being asked to request admin consent instead of being able to consent themselves. Why is that?"](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/admin-consent-workflow-faq#i-have-an-application-that-requires-user-assignment-a-user-that-i-assigned-to-an-application-is-being-asked-to-request-admin-consent-instead-of-being-able-to-consent-themselves-why-is-that). Explains that this limitation exists, but it does not explain the "Why is that?" part.

I would like to understand why it is not possible to consent to scopes if the user assignment is required, when it is otherwise possible if user assignment is set to "not required".

Could you please explain the reason for this limitation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b05e9501-9970-560d-a45c-5a705ab120bd
* Version Independent ID: a507819e-a4c0-7772-5e21-fd351bdb6028
* Content: [Frequently asked questions about the admin consent workflow - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/admin-consent-workflow-faq)
* Content Source: [docs/identity/enterprise-apps/admin-consent-workflow-faq.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/admin-consent-workflow-faq.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by AjayBathini-MSFT** [comment]
@TimoWilhelm 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@TimoWilhelm 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@omondiatieno please review it.
