### ISSUE TITLE
Risky users and Risky Sign-ins - Documentation request session policies when its not required and not in the new templates.

### ISSUE THREAD

**Issue by Donovand4** [MicrosoftDocs/entra-docs#269]
Both user and sign-in risk based policy documentation contradict what is recommended in the new templates. The documentation states that a sign-in session should be configured with Every Time when the recommended templates are configures with no session enforcement. Can the session recommendation please be removed from the conditional access policy manual creation steps and have it mirror what is recommended by the templates which is following the best practices for risky users and risky sign-ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 199e51c2-d6f6-ed8f-39a2-4f395155cb50
* Version Independent ID: 66ae328e-38b8-fe84-5ee9-976adbb99135
* Content: [Sign-in risk-based multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-risk)
* Content Source: [docs/identity/conditional-access/howto-conditional-access-policy-risk.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/howto-conditional-access-policy-risk.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@Donovand4 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
The policy can be tweaked to whatever customers want to use. 

As written in the doc it does include the session control because that is an even stricter policy than what the template in the Microsoft Entra admin center configures. I am showing a secure by default policy and the PG is considering that as addition to the template they deploy.

**Comment by MicrosoftGuyJFlo** [comment]
#label:"assigned-to-author"
#remove-label:"cxp"
#reassign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
