### ISSUE TITLE
Tutorial not working as directed with .net 8

### ISSUE THREAD

**Issue by infopro1** [MicrosoftDocs/entra-docs#272]
[Enter feedback here] 
The tutorial “ Implement a protected endpoint to your API - Microsoft identity”
Does not seem to work with .net 8. Instead of the expected 401 message (unauthorized) I get a 404 (not found) for the root / page. Seems like adding all that code to Program.cs does not have the desired effect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc31a3ff-c2cc-be2f-6f56-e21c9e088642
* Version Independent ID: 33df25d7-7fd5-76f9-be4f-2f0c936ee73f
* Content: [Tutorial: Implement a protected endpoint to your API - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/web-api-tutorial-03-protect-endpoint?tabs=visual-studio)
* Content Source: [docs/identity-platform/web-api-tutorial-03-protect-endpoint.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/web-api-tutorial-03-protect-endpoint.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@infopro1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by cilwerner** [comment]
Hi @infopro1, this update to .NET 8.0 is planned for February's sprint. It should still work with .NET 6.0 and .NET 7.0

**Comment by infopro1** [comment]
Thanks
-----------------------
Sure, luck means a lot in football. Not having a good quarterback is bad luck.
--Don Shula
-----------------------

Jeffrey Dreps
***@***.******@***.***>
Cell:  (734) 239-3694

On Jan 31, 2024, at 4:24 AM, Chris Werner ***@***.***> wrote:



Hi @infopro1<https://github.com/infopro1>, this update to .NET 8.0 is planned for February's sprint. It should still work with .NET 6.0 and .NET 7.0

**Comment by AjayBathini-MSFT** [comment]
@infopro1 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
