### ISSUE TITLE
Clarify purpose of inbound security rule AllowSyncWithAzureAD with destination port 443

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/entra-docs#273]
This page displays the following security rule

```json
{
  "name": "AllowSyncWithAzureAD",
  "properties": {
    "access": "Allow",
    "priority": 101,
    "direction": "Inbound",
    "protocol": "Tcp",
    "sourceAddressPrefix": "AzureActiveDirectoryDomainServices",
    "sourcePortRange": "*",
    "destinationAddressPrefix": "*",
    "destinationPortRange": "443"
  }
}
```

But, this page does not explain **Why this security rule is required?**

This inbound rule is not mentioned anywhere in the following guides either
- https://learn.microsoft.com/en-us/entra/identity/domain-services/network-considerations
- https://learn.microsoft.com/en-us/entra/identity/domain-services/alert-nsg

The only rules with port `443` required by the Domain Services, per https://learn.microsoft.com/en-us/entra/identity/domain-services/network-considerations#outbound-connectivity, are the **outbound rules** which are usually applied via the default  `AllowVnetOutbound` and `AllowInternetOutBound`.

Interestingly, the same inbound rule is presented, also without the purpose clarification, in the Terraform examples for the following resources, by @manicminer
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service 
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service_replica_set

There is number of blogs around about setting up managed Domain Services with code 
- https://gmusumeci.medium.com/how-to-deploy-azure-active-directory-ad-domain-services-aadds-with-terraform-4a9551003d38 by @guillermo-musumeci does show the `AllowSyncWithAzureAD` inbound rule as required
- https://schnerring.net/blog/set-up-azure-active-directory-domain-services-aadds-with-terraform-updated/ by @schnerring does not show the inbound rule `AllowSyncWithAzureAD` as required

I suspect, all those places where the rule is presented, could be  'blind' copies of the what is presented in this Resource Manager sample template, hence it would be good to clarify the template, and correct it, if necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 912419aa-f5cd-160d-722a-9e1834fe7ad7
* Version Independent ID: dbc3b6c9-2edd-a73f-2b4a-4d17f68ed2f5
* Content: [Enable Azure DS Domain Services using a template - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/domain-services/template-create-instance)
* Content Source: [docs/identity/domain-services/template-create-instance.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/domain-services/template-create-instance.md)
* Service: **active-directory**
* Sub-service: **domain-services**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@mloskot 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by mloskot** [comment]
@schnerring Thank you for chiming in. I had not found that issue myself. Hopefully our asynchronously collective input will trigger some updates in the Microsoft docs 😊
