### ISSUE TITLE
Assign role to MI - variable names are incorrect

### ISSUE THREAD

**Issue by adiun** [MicrosoftDocs/entra-docs#277]
Step 6 - all 3 variable names are incorrect in the bulleted list since they don't correspond to any of the code on the page. They should be: `oidForMI`, `serverSPOID`, `roleguid`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b01bcd94-4204-af22-46e4-ce45c449358c
* Version Independent ID: 2c0de090-f401-e819-ca19-18e2587f0fe3
* Content: [Assign a managed identity to an application role using Azure CLI - Managed identities for Azure resources](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-cli)
* Content Source: [docs/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-cli.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-cli.md)
* Service: **active-directory**
* Sub-service: **msi**
* GitHub Login: @xstof
* Microsoft Alias: **christoc**

**Comment by AjayBathini-MSFT** [comment]
@adiun 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@adiun 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
