### ISSUE TITLE
Addtional Question on NetSuite AzureSS

### ISSUE THREAD

**Issue by miladeng** [MicrosoftDocs/entra-docs#278]
Hi,

Thanks for the document and Its very clear about the NetSuite SSO setup. I would like to understand more about setting up SSO between NetSuite Planning and Budgeting with Azure. Could you also share a document similarly like this? 

Thanks,
Mila

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6e5ca67-5719-9aa3-e294-6cefa40b2c87
* Version Independent ID: 5241e38f-05f2-a2ba-7483-629418968ab3
* Content: [Tutorial: Microsoft Entra single sign-on (SSO) integration with NetSuite - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/netsuite-tutorial)
* Content Source: [docs/identity/saas-apps/netsuite-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/netsuite-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by AjayBathini-MSFT** [comment]
@miladeng 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by miladeng** [comment]
> @miladeng Thanks for your feedback! We will investigate and update as appropriate.

thanks thanks. 
Please let me know when we could have the updates!

**Comment by AjayBathini-MSFT** [comment]
@miladeng 

I'm glad to hear that you found the NetSuite SSO setup document helpful! Unfortunately, I could not find a specific tutorial or documentation on setting up SSO between NetSuite Planning and Budgeting with Azure. However, I can provide some general guidance on how to approach this.

To set up SSO between NetSuite Planning and Budgeting with Azure, you will need to configure NetSuite to use Azure Active Directory (Azure AD) as the identity provider (IdP). This involves configuring Azure AD as a SAML 2.0-based IdP in NetSuite and configuring NetSuite as a SAML 2.0-based service provider (SP) in Azure AD.

Here are the general steps to set up SSO between NetSuite Planning and Budgeting with Azure:

Configure Azure AD as a SAML 2.0-based IdP in NetSuite. This involves creating a custom SAML 2.0-based IdP in NetSuite and configuring it to use Azure AD as the IdP. You will need to provide the Azure AD metadata URL and the Azure AD issuer URL to NetSuite.

Configure NetSuite as a SAML 2.0-based SP in Azure AD. This involves creating a custom SAML 2.0-based application in Azure AD and configuring it to use NetSuite as the SP. You will need to provide the NetSuite metadata URL and the NetSuite ACS URL to Azure AD.

Configure user provisioning between NetSuite and Azure AD. This involves configuring NetSuite to use Azure AD as the user directory and configuring Azure AD to provision users to NetSuite.

Test the SSO configuration. This involves logging in to NetSuite Planning and Budgeting using Azure AD credentials and verifying that the SSO configuration is working correctly.

Please note that these are general steps and the specific configuration steps may vary depending on your environment and requirements. I recommend consulting the documentation for NetSuite Planning and Budgeting and Azure AD for more detailed guidance on how to set up SSO between these two systems.

I hope this information helps!

**Comment by AjayBathini-MSFT** [comment]
@miladeng 
If you need any further help. I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
