### ISSUE TITLE
Incorrect permisssion listed to run a query

### ISSUE THREAD

**Issue by TomAafloen** [MicrosoftDocs/entra-docs#279]
[Enter feedback here]

Under **Run a query**, it states that you should sign in as at least **Reports Reader**. But to get access to run a query under *Log Analytics* in the Entra portal, no built-in Entra Admin role is enough (not even _Global Reader_).
You actually need at least the **Azure RBAC** role called **Log Analytics Reader** on the Log Analytics Workspace in question to get access to run queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e02bd358-3558-fc11-7653-8730579b74bd
* Version Independent ID: 05bd9f03-0b3d-ffb4-f97d-312e8e301fb9
* Content: [Configure a log analytics workspace in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/tutorial-configure-log-analytics-workspace#run-a-query)
* Content Source: [docs/identity/monitoring-health/tutorial-configure-log-analytics-workspace.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/monitoring-health/tutorial-configure-log-analytics-workspace.md)
* Service: **active-directory**
* Sub-service: **report-monitor**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by shlipsey3** [comment]
@TomAafloen Thanks for this feedback. The Azure and RBAC roles are listed in a different article, but they're not in this tutorial. I'll make a note to include this information in this article as well. Thanks!

**Comment by Naveenommi-MSFT** [comment]
@shlipsey3
Thank you for your inputs. 

@TomAafloen 
If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by shlipsey3** [comment]
#assign:shlipsey3

**Comment by Naveenommi-MSFT** [comment]
@TomAafloen 
I've assigned this issue to the author who will investigate and update as appropriate. Thanks!!!

**Comment by shlipsey3** [comment]
Got those roles added to the tutorial. Continuing to test and confirm roles for everything. Thanks!
#please-close
