### ISSUE TITLE
PowerShell code sample provided on page doesn't work

### ISSUE THREAD

**Issue by vpandey01** [MicrosoftDocs/entra-docs#281]
Following sample command doesn't work as provided on the documentation:
New-MgDomain -Name "child.mydomain.com" -Authentication Federated

Error: New-MgDomain : Creation of federated domain is not allowed.
Status: 400 (BadRequest)
ErrorCode: Request_BadRequest

Corresponding Msol command however works but is not recommended for use since it will be deprecated soon. 
New-MsolDomain -Name "child.mydomain.com" -Authentication Federated

Also it appears that following Graph API converts the domain to managed and section "Change the subdomain authentication type" is not needed.
https://graph.microsoft.com/v1.0/domains/{domain-id}/microsoft.graph.promote

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02c07bd2-01c5-77f4-11e0-6d942c5c0885
* Version Independent ID: f61490c2-0f18-4609-29f1-99ccb4215ad2
* Content: [Change subdomain authentication type using PowerShell and Graph - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/domains-verify-custom-subdomain)
* Content Source: [docs/identity/users/domains-verify-custom-subdomain.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/domains-verify-custom-subdomain.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@vpandey01 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@vpandey01
I've delegated this to @barclayn, a content author, to review and share their valuable insights.

**Comment by Miguel-Wallymundo** [comment]
how do you solve this?
