### ISSUE TITLE
Invalid EMS Trial Link

### ISSUE THREAD

**Issue by PaddyMaddy** [MicrosoftDocs/entra-docs#283]
[Enter feedback here]

The link provided Try out EMS with an accessible [Enterprise Mobility + Security E5 trial subscription](https://signup.microsoft.com/Signup?OfferId=87dd2714-d452-48a0-a809-d2f58c4f68b7&ali=1) is expired or not working anymore. it must be corrected for end users

Thanks,
PaddyMaddy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0e2c4f-bc2a-7107-3e33-897595d29b47
* Version Independent ID: f1b5a7af-0f95-9b3e-7607-e0a28e5f2520
* Content: [Sign up for premium editions - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/get-started-premium?source=docs)
* Content Source: [docs/fundamentals/get-started-premium.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/get-started-premium.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@PaddyMaddy 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by barclayn** [comment]
@PaddyMaddy thank you for your feedback. I have removed the URL as that program is no longer available. #please-close
