### ISSUE TITLE
Provide a worked example for OIDC federated identity "Other issuer" example

### ISSUE THREAD

**Issue by adeturner** [MicrosoftDocs/entra-docs#284]
Using OIDC with federated identities is well documented with Github, but ["Other issuer"](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-create-trust-user-assigned-managed-identity?pivots=identity-wif-mi-methods-azp#other) only gets a passing mention.

It feels possible that this connection method could be used for on-prem VMs to authenticate with user managed identity but is not clear how.

E.g. An example using OIDC authentication in WSL with Entra ID would be great (a different Entra ID if required)

Specifically its unclear what we put in the subject identifier

"Subject identifier: must match the sub claim in the token issued by the external identity provider. In this example using Google Cloud, subject is the Unique ID of the service account you plan to use."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4cebede-5817-4911-564b-32448b9da31e
* Version Independent ID: f65657b6-8647-f3a0-b8a0-59b49baad865
* Content: [Create a trust relationship between a user-assigned managed identity and an external identity provider - Microsoft Entra Workload ID](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-create-trust-user-assigned-managed-identity)
* Content Source: [docs/workload-id/workload-identity-federation-create-trust-user-assigned-managed-identity.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/workload-id/workload-identity-federation-create-trust-user-assigned-managed-identity.md)
* Service: **active-directory**
* Sub-service: **workload-identities**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by AjayBathini-MSFT** [comment]
@adeturner 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@adeturner 
I'm going to assign this to the document author so they can take a look at it accordingly

@rwike77 
Can you please check and add your comments on this doc update request as applicable.

**Comment by rwike77** [comment]
Hi @adeturner .  Apologies for the very slow turn around on this one.  I'll do my best to get this updated in the next couple of weeks, I need to reach out to engineering for some additional information.

We are in the process of transferring to a new unified user feedback system, so I need to close this issue even though it's not resolved.  I've opened an internal work item for the month of June so I won't lose it.

Thanks for your patience.  #please-close
