### ISSUE TITLE
Null and empty values not processed as expected

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/entra-docs#285]
Regarding the mentioned user update issue "Null and empty values not processed as expected"
Can you please describe or reference from where did you get the statement text from Cause:
> "on-premises Active Directory does not support setting empty string values"

Because in on-premise Active Directory, you can normally set the value to empty using "Active Directory Users and Computers" console, or by using Active Directory PowerShell module, with "Set-ADUser -Clear department" as example.

Is this issue "support for sync of null or empty values" a product/provisioning limitation? Can it be documented somewhere? not just mentioned here in troubleshooting docs.

This is critical for Sync/Provision process of HR to IT, due to some cases, when doing HR reorganization, and some Employees/AD Users "loose" the Department value, or some other internal custom AD schema attributes. Another example is with terminationDate or re-hiring the user etc.

Two recommended resolutions do not solve the issue since no null value is written at target / Active Directory
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaac29de-7f44-3c89-6710-a60850950247
* Version Independent ID: b8fc05c3-9734-3813-5e08-d38fa96d7e4a
* Content: [Troubleshoot user update issues with HR provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/hr-user-update-issues#null-and-empty-values-not-processed-as-expected)
* Content Source: [docs/identity/app-provisioning/hr-user-update-issues.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/hr-user-update-issues.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@hkusulja 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by jenniferf-skc** [comment]
Thank you @hkusilja for bringing this to our attention. To clarify, on-premises Active Directory **provisioning connector currently** does not support setting empty string values and hence you see the above error. We will add this to the document for clarification. Also, there is a backlog work item with engineering to resolve this.

**Comment by jenniferf-skc** [comment]
#Please-close

**Comment by hkusulja** [comment]
Can you please reference your statement where it is written "provisioning connector currently does not support setting empty string values" ? we are using product for months in production and did not see such a limitation in product description or elsewhere, just here your statement on this github issue. Can you reference public link with a statement? Any suggested workarounds? Thank you

**Comment by jenniferf-skc** [comment]
Hello @hkusulja Yes, the documentation has been updated with this statement in the **Cause** section under **Null and empty values not processed as expected** - https://learn.microsoft.com/en-us/entra/identity/app-provisioning/hr-user-update-issues#null-and-empty-values-not-processed-as-expected

**Comment by hkusulja** [comment]
Now I see here also:
https://learn.microsoft.com/en-us/entra/identity/app-provisioning/customize-application-attributes
> The Microsoft Entra provisioning service doesn't support provisioning null values.
