### ISSUE TITLE
please check the "connectivity analyzer" link target- it goes to a list of tools, none of which seem to be the right one

### ISSUE THREAD

**Issue by thomasjsweet** [MicrosoftDocs/entra-docs#286]
[Enter feedback here]
please check the "connectivity analyzer" link target- it goes to a list of tools, none of which seem to be the right one for SAML testing.  Possibly the target site was changed by a different group

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c01ec6a-ab66-33b1-8e6f-6437e8f4f660
* Version Independent ID: 2f64f95f-9403-bc88-ac72-5ce56f9d50c3
* Content: [Microsoft Entra Connect: Use a SAML 2.0 Identity Provider for Single Sign On - Azure - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@thomasjsweet 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by billmath** [comment]
@thomasjsweet Thanks for catching this.  We are in the process of updating this article.  But now the recommendation is to use the process outlined here https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/debug-saml-sso-issues#test-saml-based-single-sign-on .  This will allow you to test SSO.  At this time, I am going to go ahead and close the issue.  But an update should be coming in the next week or so.  Thanks!

Bill

#please-close
