### ISSUE TITLE
Unclear that custom app consent policies only apply to custom roles

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#288]
While this doc has a small reference to custom roles in the pre-req section, it is unclear if that is a prereq for **creating** the custom app consent policy or **making use** of it.  Ultimately it is both, as one has to have an appropriate role to create the app consent policy, and another appropriate custom role to make use of the policy.

There should be another section in this doc that talks about linking the new policy to a custom role, or link to that existing doc at https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-consent-permissions.

As it currently stands, after this doc talks about creating the policy, it says that you can now "can allow user[s] [to] consent subject to this policy". This makes one think that this policy is now active for all users, since it hyperlinks to the main user consent policy. In reality, this custom app consent policy still needs to be tied to a custom role before it becomes usable.

We explained this behavior rather well in a blog post at https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/azure-ad-custom-application-consent-policies/ba-p/2115812 but our public docs are lacking that context of how these custom app consent policies should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 819bffaf-da09-9370-762f-fe657a6cc7d0
* Version Independent ID: ec50883b-345f-db49-1127-267456733c00
* Content: [Manage app consent policies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/manage-app-consent-policies?pivots=ms-powershell)
* Content Source: [docs/identity/enterprise-apps/manage-app-consent-policies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/manage-app-consent-policies.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by AjayBathini-MSFT** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@dloder0 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.
