### ISSUE TITLE
[Issue] AADSSHLoginForLinux VM extension not supported on Debian [9/10/11]

### ISSUE THREAD

**Issue by FeoZ** [MicrosoftDocs/entra-docs#29]
### Description 

The VM Extention AADSSHLoginForLinux seems not to be working on Azure Debian Images.
Not exactly sure if it is an issue with the feature or with the documentation itself on the supported versions. 

### Current Behavior:

* Using Azure Portal:
  * The Azure AD (Entra) Login is not supported on Debian images: The documentation indicates to check this box. 

![image](https://github.com/MicrosoftDocs/entra-docs/assets/28101853/3563b1df-265a-4524-b9b6-5e7b6d0d2671)

* using azure-cli:
  * Usage of the following command on a Debian 11 already created machine never succeeds:
  
```
 az vm extension set --publisher Microsoft.Azure.ActiveDirectory --name AADSSHLoginForLinux --resource-group <RGName> --vm-name <MachineName>
```
  * Command stuck with message ( / Running .. )
  * This shows up on Azure portal during the perpetual creation phase:
  
  
![image](https://github.com/MicrosoftDocs/entra-docs/assets/28101853/64590a2f-80fe-4a71-bafa-f85774a76b7b)

### Expected Behavior:

VM Extension should be added to the machine and operate normally.  

### Environment:

* Region: Azure Global (westeurope)
* azure-cli: 2.53.0
* Python (Linux): 3.10.10
* Image VM: Debian 11 gen. 1/2 (x64)

### Anything else:

The same config with Ubuntu 22.04 works normally
Too bad. This feature looks promising. 
Let me know if you need any further information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2ede563-b873-0bc3-959f-69e555f0efcc
* Version Independent ID: 8471d9e4-6c79-0cf1-c5ed-50c58e1b92aa
* Content: [Log in to a Linux virtual machine in Azure by using Microsoft Entra ID and OpenSSH - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-linux?wt.mc_id=searchAPI_azureportal_inproduct_rmskilling&sessionId=7d8f45b96cd04d55aea4bd98659e1057)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-linux.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-linux.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by SaibabaBalapur-MSFT** [comment]
@FeoZ 
I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by SaibabaBalapur-MSFT** [comment]
@FeoZ 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by FeoZ** [comment]
Hello, 

I'm pretty sure there is a bit more to investigate on this issue, I will permit myself to re-open it. 

- Could you reproduce the issue to ensure there was no further adaptation to the documentation in the compatibility list?
- Why exactly do you redirect me to Microsoft Teams community forum? I'm quite sure the issue I raised won't be solved through it. 

> [...].[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows. [Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)


-  Can you please confirm the product is indeed working as stated on Debian before closing this ticket. Or on the contrary, either raise the problem internally OR adapt the documentation accordingly? 

Regards,

**Comment by SaibabaBalapur-MSFT** [comment]
@FeoZ 
I'm going to assign this to the document author so they can take a look at it accordingly.

@MicrosoftGuyJFlo 
Please review it.
