### ISSUE TITLE
Incorrect Sign on URL in Slack SSO tutorial

### ISSUE THREAD

**Issue by stevebingsoo** [MicrosoftDocs/entra-docs#290]
[This](https://github.com/MicrosoftDocs/entra-docs/commit/abbab107aa97a83bd67def8f6a50956d5e04fe84) commit incorrectly changed the Slack Sign On URL from `https://<companyname>.slack.com` to `https://[DOMAIN].slack.com/sso/saml/start`.  That will not work.  It should be `https://[DOMAIN].slack.com` or `https://[DOMAIN].enterprise.slack.com`.

**Comment by stevebingsoo** [comment]
Actually, the /sso/saml/start maybe fine, but Entra seems to generate incorrect SSL public certificates depending on the sign on url you configure even though that url is not part of the certificate.  Here's what I've been able to replicate multiple times to show the problem:

1.  Set a new Slack enterprise app in Entra
2. Configure https://[domain].enterprise.slack.com/sso/saml/start as the sign on url
3. Download the base 64 certificate from Entra and decode using openssl or a website like [this](https://www.sslshopper.com/certificate-decoder.html)
4. Notice that the certificate shows `Common Name: accounts.accesscontrol.windows.net`
5.  If you configure this cert into a new SSO connection in Slack and try to test the connection from Slack, it will fail with a certification validation error
6. In Entra change the sign on url to be https://[domain].enterprise.slack.com
7. Download the base 64 cert again and decode it
8. Notice the certificate now shows `Common Name: Microsoft Azure Federated SSO Certificate`
9. Enter this updated cert in Slack, test SSO from Slack, and notice it works fine

**Comment by AjayBathini-MSFT** [comment]
@stevebingsoo 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by v-hgampala** [comment]
@stevebingsoo, Thanks for the issue!!
we're updating the document with the sign on url, that you mentioned in the issue.
#please-close
