### ISSUE TITLE
Workaround for Conditional Access and Scoped Roles

### ISSUE THREAD

**Issue by dgriffinzero** [MicrosoftDocs/entra-docs#291]
[Enter feedback here]
In the article, it states that CA policies are not enforced for admin unit scoped or custom roles.  A valid workaround that should be mentioned for this situation is to use role-assignable groups to target those roles in the policy.

https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/groups-concept

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91ad3afe-2622-48fe-2290-b2ef42013eb7
* Version Independent ID: 76d2e793-c43f-85de-a613-c009b38a01b2
* Content: [Require multifactor authentication for Microsoft admin portals - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/how-to-policy-mfa-admin-portals)
* Content Source: [docs/identity/conditional-access/how-to-policy-mfa-admin-portals.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/how-to-policy-mfa-admin-portals.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@dgriffinzero 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
@dgriffinzero You are correct, you could use a group in place of the role but you would be at the mercy of the group membership. This policy aligns with the secure score recommendation and is just a template that customers might choose to follow. Customers are free to customize in any way they deem appropriate based on their organization's needs.

**Comment by MicrosoftGuyJFlo** [comment]
#reassign:@MicrosoftGuyJFlo
#remove-label:"cxp"
#label:"assigned-to-author"

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
