### ISSUE TITLE
Inconsistent command arguments

### ISSUE THREAD

**Issue by allison-silverpine** [MicrosoftDocs/entra-docs#292]
Hello, 
Under the section "Assign a managed identity access to another application's app role", for Step 6, the docs list the following command with args:
```
New-MgServicePrincipalAppRoleAssignment `
    -ServicePrincipalId $managedIdentityObjectId `
    -PrincipalId $managedIdentityObjectId `
    -ResourceId $serverServicePrincipalObjectId `
    -AppRoleId $appRoleId
```

Under the "Complete Script" section, the same command has a different argument for ServicePrincipalId:
```
New-MgServicePrincipalAppRoleAssignment `
    -ServicePrincipalId $serverServicePrincipalObjectId `
    -PrincipalId $managedIdentityObjectId `
    -ResourceId $serverServicePrincipalObjectId `
    -AppRoleId $appRoleId
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a32925b4-4773-501a-590e-0ed0d3c017ce
* Version Independent ID: f2b2e4d7-90e1-96c1-cf54-1a1144f6b0ee
* Content: [Assign a managed identity to an application role using PowerShell - Managed identities for Azure resources](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-powershell)
* Content Source: [docs/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-powershell.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-powershell.md)
* Service: **active-directory**
* Sub-service: **msi**
* GitHub Login: @johndowns
* Microsoft Alias: **jodowns**

**Comment by AjayBathini-MSFT** [comment]
@allison-silverpine 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by johndowns** [comment]
Thank you @allison-silverpine. We've fixed the typo.

**Comment by johndowns** [comment]
#please-close
