### ISSUE TITLE
So much detail missing

### ISSUE THREAD

**Issue by CountlessNumber** [MicrosoftDocs/entra-docs#293]
The provisioning process is missing so much detail about different options and scenarios and the the behavior of the app. It makes it very difficult to plan a deployment.

Examples of details that would be good to understand -

- Duplicate Users in Active Directory- What happens when two users have the same name? Does the agent create two users and have the smarts to give the 2nd user a number or something? Does it fail on the 2nd user because that name already exists?
- Out of scope Delete/Disable - "Users out of scope may be disabled or deleted". So which is it? Will they be deleted or will they be disabled? What scenario causes each option? What is the configuration and options for each?
- Scoping filters - Do scoping filters support functions like now()? Can you calculate a date or other similar functions?
- De-provisioning/re-hire users - What happens when users are disabled in SF? Can they be moved out to a disabled OU? Can a re-hire be moved back to an active OU? Does it reset the password?

There just seems to be so much missing detail from actually using this product in a real world scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90fd487d-65b9-917b-4687-650b34dc4d81
* Version Independent ID: 27a18d45-66ab-bc71-d928-93f93fb190dd
* Content: [Tutorial: Configure SuccessFactors inbound provisioning in AD and Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/sap-successfactors-inbound-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/sap-successfactors-inbound-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/sap-successfactors-inbound-provisioning-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @cmmdesai
* Microsoft Alias: **chmutali**

**Comment by AjayBathini-MSFT** [comment]
@CountlessNumber 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
