### ISSUE TITLE
Missing Entra ID role requirements

### ISSUE THREAD

**Issue by skoszewski** [MicrosoftDocs/entra-docs#294]
Prerequisites are missing the **Entra ID** role required to create a Customer tenant. There is only information about Azure role required (Contributor).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95671d5c-a3a3-d621-c6da-a046a4de140d
* Version Independent ID: d381b078-10db-c78e-06cf-f1d68e4be78c
* Content: [Create a customer tenant - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-create-customer-tenant-portal)
* Content Source: [docs/external-id/customers/how-to-create-customer-tenant-portal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-create-customer-tenant-portal.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by RamanathanChinnappan-MSFT** [comment]
@skoszewski 
I've delegated this to @csmulligan, a content author, to review and share their valuable insights.

**Comment by csmulligan** [comment]
Hi @skoszewski thank you so much for pointing this out. We've updated the article and changes should be published shortly. Because we're now tracking this internally, I'll close the issue. Thanks again for helping us improve the documentation!
#please-close
