### ISSUE TITLE
Need clarification on "on-premises identity provider"

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/entra-docs#295]
Does this line mean that SAML SSO will **_not work_** if the application has a relying party trust with an on-premises STS?
> The applications must be able to consume SAML tokens issued by Microsoft Entra ID. This configuration doesn't apply to applications using an on-premises identity provider. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 292363a5-93a9-c1dd-aa53-483ff6dd9969
* Version Independent ID: 10919142-a891-dc93-7154-db83cea262f1
* Content: [SAML single sign-on for on-premises apps with Microsoft Entra application proxy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-configure-single-sign-on-on-premises-apps)
* Content Source: [docs/identity/app-proxy/application-proxy-configure-single-sign-on-on-premises-apps.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/application-proxy-configure-single-sign-on-on-premises-apps.md)
* Service: **active-directory**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@LijuV-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@LijuV-MSFT 

No, this line does not mean that SAML SSO will not work if the application has a relying party trust with an on-premises STS. It means that the applications must be able to consume SAML tokens issued by Microsoft Entra ID, but this configuration does not apply to applications using an on-premises identity provider. In other words, if your application is using an on-premises identity provider, this configuration does not apply to you.

**Comment by LijuV-MSFT** [comment]
> this line does not mean that SAML SSO will not work if the application has a relying party trust with an on-premises STS.

> this configuration does not apply to applications using an on-premises identity provider

@AjayBathini-MSFT , I am finding it difficult to reconcile those two statements.
If the application is integrated with AD FS, does that not imply we are using AD DS as the IdP, and therefore, an on-premises identity provider?

**Comment by AjayBathini-MSFT** [comment]
@LijuV-MSFT 

The documentation you linked (https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-configure-single-sign-on-on-premises-apps) specifically focuses on configuring SAML SSO using Microsoft Entra ID as the cloud-based identity provider.
It states that this configuration isn't directly applicable to applications that exclusively rely on on-premises identity providers like AD FS.

SAML SSO with AD FS:

Direct Trust: If your application is integrated with AD FS, you can still achieve SAML SSO by establishing a direct trust relationship between the application and AD FS, without involving Entra ID. This requires separate configuration on both ends.
Alternative Cloud-Based IdPs: If you prefer a cloud-based solution, explore other identity providers that offer compatible SAML SSO options for your application and AD FS integration.

**Comment by AjayBathini-MSFT** [comment]
@LijuV-MSFT 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
