### ISSUE TITLE
Service Principal Name incorrect 

### ISSUE THREAD

**Issue by micmaher** [MicrosoftDocs/entra-docs#296]
The instructions give a wrong app name. 

>  If you don't see Microsoft Azure Windows Virtual Machine Sign-In as a result, the service principal is missing from the tenant.

It should say ...

>  If you don't see Azure Windows VM Sign-In as a result, the service principal is missing from the tenant.

The wrong app name is also used in the code to check for and create the Service Principal

(https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows#missing-application)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Log in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows#mfa-sign-in-method-required)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#label:"assigned-to-author", "doc-enhancement", "triaged"
#reassign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for catching that. Some names have been changing in the background lately.
