### ISSUE TITLE
Custom claims - restrictions and complexity

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/entra-docs#298]
In the Claims class in the code snippet in section 1.2, is it possible to have a property that is a C# class representing a multi level JSON object. Currently it only has string and List<string>

For eg
```
{
	"claims": {
		"correlationId": "xyz",
		"apiVersion": "1.0.0",
		"dateOfBirth": "01/01/2000",
		"customRoles": [
			"Writer",
			"Editor"
		],
		"components": {
			"a": {
				"actions": [
					"view",
					"edit"
				]
			},
			"b": {
				"actions": [
					"view"
				]
			}
		}
	}
}
```
Could you also indicate whether there is a limit on the number or size of the custom claims?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef99966f-e466-d7fe-3f12-8e725ac0ce85
* Version Independent ID: 827894b5-38c5-7dac-0b90-8f839996c87d
* Content: [Get started with custom claims providers (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-get-started?tabs=entra-admin-center)
* Content Source: [docs/identity-platform/custom-extension-get-started.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-get-started.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@kmathewmk 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@kmathewmk 

Yes, it is possible to have a property that is a C# class representing a multi-level JSON object in the Claims class in the code snippet in section 1.2. You can define a custom class that represents the JSON object and use it as a property in the Claims class. For example, you can define a class called "Components" that has properties "A" and "B", and each of these properties can be another custom class that represents the "actions" property.

Regarding the limit on the number or size of the custom claims, there is no hard limit on the number of custom claims that can be added to a token. However, there is a limit on the size of the token, which includes the size of the claims. The maximum size of a token is 4KB, and this includes the size of the header, payload, and signature. If the size of the claims exceeds this limit, the token cannot be issued. Therefore, it is recommended to keep the size of the claims as small as possible.

**Comment by kmathewmk** [comment]
Thanks for the clarification.

Would it correct to conclude that in
![image](https://github.com/MicrosoftDocs/entra-docs/assets/52198810/0250f2a3-cda9-4254-8a12-92db11b8c3b4)
and in
![image](https://github.com/MicrosoftDocs/entra-docs/assets/52198810/7a757171-3246-48e0-bec2-d63d04702889)
one can specify nested attributes if necessary? For my original example, would it be possible to specify for eg
`components.a` as the attribute that the custom authentication extension must parse from the REST API
and 
`customClaimsProvider.components.a` as the attribute from the custom claims provider, which should be issued into the token as claim.

If the documentation can be improved appropriately, that would be helpful.

**Comment by AjayBathini-MSFT** [comment]
@kmathewmk 
I have already connected with the author and informed them regarding the issue. The document has been updating, and the changes will go live soon.

if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by cilwerner** [comment]
@kmathewmk, according to the software engineers, although such a JSON is technically possible, having a multi-level JSON object is not supported in this implementation. I can specify that multi-layer JSON objects are not supported to avoid further confusion.
