### ISSUE TITLE
Sample projects for .NET 8 Blazor webapps are 4 years old.

### ISSUE THREAD

**Issue by ggrater-touchmark** [MicrosoftDocs/entra-docs#299]
Please update Blazor samples for .NET 8 and Entra Security Single Org ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b90331e5-cca5-b157-eaa1-6f8f90003b32
* Version Independent ID: 4b1b803d-e30d-10b2-90a1-3f0ccd8d7d44
* Content: [Code samples for Microsoft identity platform authentication and authorization - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/sample-v2-code?tabs=apptype)
* Content Source: [docs/identity-platform/sample-v2-code.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/sample-v2-code.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by RamanathanChinnappan-MSFT** [comment]
@ggrater-touchmark 
I've delegated this to @OwenRichards1, a content author, to review and share their valuable insights.
