### ISSUE TITLE
Sample code for "Register the connector using a token created offline" does not work

### ISSUE THREAD

**Issue by BlakeWills** [MicrosoftDocs/entra-docs#30]
The sample code for [Register the connector using a token created offline](https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-register-connector-powershell#register-the-connector-using-a-token-created-offline) does not work.

I've created a .NET 6 console app using the code from the documentation, and instead of obtaining a token we get an error to say the redirect_uri is invalid:

```
Sign in
Sorry, but we’re having trouble with signing you in.

AADSTS50011: The redirect URI 'http://localhost:60108' specified in the request does not match the redirect URIs configured for the application '55747057-9b5d-4bd4-b387-abf52a8bd489'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
Troubleshooting details
If you contact your administrator, send this info to them.

Request Id: 64bee792-97ae-4a5a-a407-abf567545000
Correlation Id: 03dfcf9c-cbe8-43d4-9380-5d308a8173e1
Timestamp: 2023-12-06T13:09:06Z
Message: AADSTS50011: The redirect URI 'http://localhost:60108' specified in the request does not match the redirect URIs configured for the application '55747057-9b5d-4bd4-b387-abf52a8bd489'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
Flag sign-in errors for review: [Enable flagging](https://login.microsoftonline.com/common/debugmode)
If you plan on getting help for this problem, enable flagging and try to reproduce the error within 20 minutes. Flagged events make diagnostics available and are raised to admin attention.
```

This is the same as [85855](https://github.com/MicrosoftDocs/azure-docs/issues/85855), where someone responded saying the redirect needs to be "https://login.microsoftonline.com/common/oauth2/nativeclient", if I update the code to force this url as the redirect url, we get a runtime exception saying the redirect url must be using the loop back address.

```
Microsoft.Identity.Client.MsalClientException: 'Only loopback redirect uri is supported, but https://login.microsoftonline.com/common/oauth2/nativeclient was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. 
```

This is using the lates version of Microsoft.Identity.Client, and I've also tried using v4.7.1 as specified in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62886f64-db39-73f2-a7bf-05336bdbef73
* Version Independent ID: 5325ef4c-c584-d242-b201-1a3466904a5f
* Content: [Silent install Microsoft Entra application proxy connector - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-register-connector-powershell#register-the-connector-with-microsoft-entra-id)
* Content Source: [docs/identity/app-proxy/application-proxy-register-connector-powershell.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/application-proxy-register-connector-powershell.md)
* Service: **active-directory**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**
*

**Comment by RamanathanChinnappan-MSFT** [comment]
@BlakeWills 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@BlakeWills 

Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.

**Comment by BlakeWills** [comment]
Hey @AjayBathini-MSFT, I've used an entirely different method so have a workaround, but isn't the issue here that the docs are wrong? Or are they correct and I was probably doing something daft?

The issue no longer effects me but it would be good if the documentation could be updated to be correct, to help future users?
