### ISSUE TITLE
Branding Contradiction

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/entra-docs#300]
There seems to be a contradiction on this page about what branding to expect:

In the table "[Comparing External Identities feature sets](https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview#comparing-external-identities-feature-sets)," it says this in the Branding row--B2B Collaboration column: "Host/inviting organization's brand is used."

In the section on "[How external collaboration and cross-tenant access settings work together](https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview#how-external-collaboration-and-cross-tenant-access-settings-work-together)," there's text that says "For B2B collaboration end-users who perform cross-tenant sign-ins, their home tenant branding appears, even if there isn't custom branding specified."

This is a contradiction. I believe that the table is correct and it is the host tenant's branding that is used, but please confirm and consider updating the second section on how they work together.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed572d43-0c0e-4b91-7297-9d2158830575
* Version Independent ID: 6920706a-8de6-af57-7457-451171d53522
* Content: [Microsoft Entra External ID overview - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview)
* Content Source: [docs/external-id/external-identities-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/external-identities-overview.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@DontNeedNoGit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@DontNeedNoGit 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@msmimart 
Please review it.
