### ISSUE TITLE
How to get list of the cross-tenant domains which already exist?

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/entra-docs#301]
Hi,
Anybody knows the way to list the current, already setup domains and tenant IDs by the PowerShell?
That might be good topic also to be added into this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fde28984-3cf4-eb30-db25-9b19a02fcde6
* Version Independent ID: c69ecd40-a94e-41b5-28da-0e8fed4d8307
* Content: [Configure cross-tenant synchronization using PowerShell or Microsoft Graph API - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/cross-tenant-synchronization-configure-graph?tabs=ms-powershell)
* Content Source: [docs/identity/multi-tenant-organizations/cross-tenant-synchronization-configure-graph.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/multi-tenant-organizations/cross-tenant-synchronization-configure-graph.md)
* Service: **active-directory**
* Sub-service: **multi-tenant-organizations**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@Petri-X 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Petri-X 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1


Thanks for your contribution. Please add your ideas in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)
