### ISSUE TITLE
Service Principal Names link is broken

### ISSUE THREAD

**Issue by toilDroid** [MicrosoftDocs/entra-docs#303]
"Service Principal Names" link under "Prerequisites" is going to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 975ec66c-8a50-6933-cfe4-0b16697e6450
* Version Independent ID: 975ec66c-8a50-6933-cfe4-0b16697e6450
* Content: [Kerberos-based single sign-on (SSO) in Microsoft Entra ID with Application Proxy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/how-to-configure-sso-with-kcd)
* Content Source: [docs/identity/app-proxy/how-to-configure-sso-with-kcd.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/how-to-configure-sso-with-kcd.md)
* Service: **active-directory**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@toilDroid 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by kenwith** [comment]
Thanks for the catch. Updated link and it should be live shortly. #please-close
