### ISSUE TITLE
include Office 365 Management (Mobile App) app id: 00b41c95-dab0-4487-9791-b9d2c32c80f2

### ISSUE THREAD

**Issue by jku-sr** [MicrosoftDocs/entra-docs#304]
please include Office 365 Management (appid: 00b41c95-dab0-4487-9791-b9d2c32c80f2) it's getting blocked because Conditional Access Policy cannot scope to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c83d2402-0113-e453-e103-a1abc4876531
* Version Independent ID: d638de2c-15f1-546d-05c0-06e3d7e62287
* Content: [Office 365 App in Conditional Access reference - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/reference-office-365-application-contents)
* Content Source: [docs/identity/conditional-access/reference-office-365-application-contents.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/reference-office-365-application-contents.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Blocked in what sense? This article is just a listing of what is included in the app bundle that you can target with Conditional Access.

**Comment by jku-sr** [comment]
> Blocked in what sense? This article is just a listing of what is included in the app bundle that you can target with Conditional Access.

apologies John if this is the wrong place. Conditional Access Policies applied to the "office 365" cloud apps is missing "Office 365 Management (appid: 00b41c95-dab0-4487-9791-b9d2c32c80f2)" to be included in it. Without that, Conditional Access will fail because the Office 365 Management app is not recognized as part of the office 365 app.

Additionally I cannot find that app to exclude in Conditional Access Policies, it doesn't show up in the list. This app is the one that comes from the iOS app Store
https://apps.apple.com/us/app/microsoft-365-admin/id761397963

**Comment by AjayBathini-MSFT** [comment]
@jku-sr 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
Ahh. That is not part of this app group as that is part of the admin side of the apps. I would look at the service dependency that exists when you try to launch the app. I would bet it is actually calling the Windows Azure Service Management API. 

You can find more info in the following troubleshooting article.
https://learn.microsoft.com/entra/identity/conditional-access/troubleshoot-conditional-access#service-dependencies

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"cxp"
#label:"assigned-to-author"

**Comment by jku-sr** [comment]
> Ahh. That is not part of this app group as that is part of the admin side of the apps. I would look at the service dependency that exists when you try to launch the app. I would bet it is actually calling the Windows Azure Service Management API.
> 
> You can find more info in the following troubleshooting article. https://learn.microsoft.com/entra/identity/conditional-access/troubleshoot-conditional-access#service-dependencies

actually it looks like it's calling Microsoft Graph?

![image](https://github.com/MicrosoftDocs/entra-docs/assets/32393560/0866986a-ebff-429b-8c82-e59810319825)

**Comment by MicrosoftGuyJFlo** [comment]
I would suggest trying policies for the [Windows Azure Service Management API or Microsoft Admin Portals](https://learn.microsoft.com/entra/identity/conditional-access/concept-conditional-access-cloud-apps#windows-azure-service-management-api) and see if those allow you access to the app. 

If those don't work the app has the following page on Learn with a support email address [About the Microsoft 365 Admin mobile app](https://learn.microsoft.com/en-us/microsoft-365/admin/admin-overview/admin-mobile-app#what-do-i-do-if-my-question-isnt-answered). They would probably be able to help you further.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"cxp"
#label:"assigned-to-author"
#reassign:@MicrosoftGuyJFlo
