### ISSUE TITLE
Minor adjustment for readability

### ISSUE THREAD

**Issue by jesshaines** [MicrosoftDocs/entra-docs#305]
I stumbled over reading this sentence in the doc a couple times. I believe adding the word "is" will make it more easily readable. 

"The location **[is]** found using the public IP address a client provides to Microsoft Entra ID or GPS coordinates provided by the Microsoft Authenticator app. "

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e67c377-d615-8779-b3f9-420fc4efd81d
* Version Independent ID: 3bcdc8e6-2ab6-5c62-dd5c-cc9a024f3428
* Content: [Using networks and countries/regions in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/location-condition)
* Content Source: [docs/identity/conditional-access/location-condition.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/location-condition.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#label:"assigned-to-author", "doc-enhancement", "triaged"
#reassign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
Thanks @jesshaines for catching that. Fixing in the linked PR in our private repo. Should publish overnight. 

#please-close
