### ISSUE TITLE
Focus on Session management to protect refresh tokens

### ISSUE THREAD

**Issue by cblomart** [MicrosoftDocs/entra-docs#306]
In this article token timeouts are refered. Talking about Sessions it is natural to look at their lifetime.
From recent [blogs](https://techcommunity.microsoft.com/t5/microsoft-entra-blog/addressing-data-exfiltration-token-theft-talk/ba-p/3915337) i think it is also important to emphasize how Tokens can be secured as they can be grabbed from any "public" places they can be found like:
* In transit via MiTM
* On the device by compromising the device

With this in mind i think it is also important to hightlight more device based Conditional Access and protections:
* Conditional access can check for MDM (Compliance) and/or MAM policies
* MAM/MDM can make sure the configuration of the devices highten its protection to MiTM or compromission: Antivirus, root/jailbreak detection, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b38c5bb-b6fd-ed73-e415-837a69a0a8e1
* Version Independent ID: 30bf75b4-a333-2def-a672-b45c83f06348
* Content: [Refresh tokens in the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/refresh-tokens)
* Content Source: [docs/identity-platform/refresh-tokens.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/refresh-tokens.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@cblomart 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@cblomart

**Comment by cilwerner** [comment]
Thanks @cblomart, I'll look through that blog and make updates to that article.
