### ISSUE TITLE
Please document `appproxy=logout` Query String Parameter

### ISSUE THREAD

**Issue by GuyPaddock** [MicrosoftDocs/entra-docs#307]
When Entra ID Application Proxy (which, it seems, is being renamed to "Private Network"?) is added to an application registration, it appears to change the "Front-channel logout URL" of the application to add a `?appproxy=logout` suffix. I assume that this is related to single sign-out functionality (ensuring that all app proxy sessions a user may have started are ended if the user signs out of their Microsoft ID). However, this functionality is not documented.

Please document this. Specifically, we want to know:
1. Is this query string parameter actually respected?
2. Does the query string parameter only have an effect on the root path of the site (e.g., does it work on both `https://example.com/?appproxy=logout` as well as `https://example.com/my/logout/route?appproxy=logout`)?
3. Does the application proxy give the application a chance to process the log out request before ending its own session (e.g., if the URL is `https://example.com/my/logout/route?appproxy=logout`, does the application get a chance to process the `/my/logout/route` route BEFORE the application proxy ends its session)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab65e9bd-17c1-50ce-47e9-1f4eae294c4a
* Version Independent ID: ab65e9bd-17c1-50ce-47e9-1f4eae294c4a
* Content: [Understand single sign-on with an on-premises app using Application Proxy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/how-to-configure-sso)
* Content Source: [docs/identity/app-proxy/how-to-configure-sso.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/how-to-configure-sso.md)
* Service: **active-directory**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@GuyPaddock 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@GuyPaddock 
I'm going to assign this to the document author so they can take a look at it accordingly.

@kenwith 
please review it.
