### ISSUE TITLE
Would be great if Microsoft can explain why I need app registration even for a desktop app

### ISSUE THREAD

**Issue by sijucm** [MicrosoftDocs/entra-docs#309]
I do not get why I need to have app registration even or a desktop app. I wish Microsoft explains that in this page instead of starting off with random paragraphs.

> The account types supported in a desktop application depend on the experience that you want to light up.

experience that I want to "light up" ? Nice. For example? Let's lighten up on uncommon usage of these words. And also please give some example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe0e2091-855e-c07b-c765-bc076ef0099a
* Version Independent ID: 897ef281-a5b5-ccb7-eceb-123c85581df5
* Content: [Register desktop apps that call web APIs - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-desktop-app-registration)
* Content Source: [docs/identity-platform/scenario-desktop-app-registration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-desktop-app-registration.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by AjayBathini-MSFT** [comment]
@sijucm 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sijucm** [comment]
Not pursuing
