### ISSUE TITLE
Wrong Listed Permission

### ISSUE THREAD

**Issue by ElectricalHazards** [MicrosoftDocs/entra-docs#31]
From what I have seen and heard from support you need to be a Privileged Role Administrator or Global admin not Cloud Device Administrator to manage Device administrators
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 823c9751-c496-f972-3b1b-640a1bd81412
* Version Independent ID: 6951f3d5-c766-133c-4785-9cd4192bae19
* Content: [How to manage local administrators on Microsoft Entra joined devices - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/assign-local-admin)
* Content Source: [docs/identity/devices/assign-local-admin.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/assign-local-admin.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@MicrosoftGuyJFlo
Could you please review add comments on this, update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@ElectricalHazards 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
@ElectricalHazards 

You are correct. That item does need at least Privileged Role Administrator. I appreciate the catch. Fixing now.
