### ISSUE TITLE
Needs better Intune deployment Information

### ISSUE THREAD

**Issue by markheydon** [MicrosoftDocs/entra-docs#312]
All well and good saying use Intune to deploy the Windows client, but doesn't give details like the switch for uninstall or even the rule need to detect installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44c5e5d2-9999-6e26-1a24-a675b878e08a
* Version Independent ID: 329a1508-45db-8062-d753-9b9f86629063
* Content: [The Global Secure Access Client for Windows (preview) - Global Secure Access](https://learn.microsoft.com/en-gb/entra/global-secure-access/how-to-install-windows-client)
* Content Source: [docs/global-secure-access/how-to-install-windows-client.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/global-secure-access/how-to-install-windows-client.md)
* Service: **network-access**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by ManoharLakkoju-MSFT** [comment]
@markheydon 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@markheydon 
You can find reference document, 
An Intune administrator can use Uninstall to uninstall (roll back) the latest feature update or the latest quality update for an active or paused update ring. After uninstalling one type, you can then uninstall the other type. Intune doesn't support or manage the ability of users to uninstall updates.

https://learn.microsoft.com/en-in/mem/intune/protect/windows-10-update-rings#uninstall

**Comment by SaibabaBalapur-MSFT** [comment]
@markheydon 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@kenwith
Can you please check and add your comments on this doc update request as applicable.

**Comment by markheydon** [comment]
How was this completed when nothing on the page has changed and the issue still remains?

**Comment by kenwith** [comment]
@markheydon - I am not sure either how it was closed but I think it was an automated process because we are moving to a new article feedback system instead of GitHub. I have copied the issue and created a work item in our internal DevOps system so I can slot this into our backlog. I added a link back with a note so I can provide feedback here once I complete it.
