### ISSUE TITLE
Could you please clarify if Microsoft Entra Connect Health is supported with Microsoft Entra Connect cloud sync?

### ISSUE THREAD

**Issue by grimson73** [MicrosoftDocs/entra-docs#313]
Hi, according to this page Microsoft Entra Connect Sync is 'deprecated' so eventually Microsoft Entra Connect cloud sync will remain the one remaining sync engine:
[Microsoft Entra Connect Sync: Understand and customize synchronization](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sync-whatis)
> 'Microsoft Entra Connect cloud sync is replacing Microsoft Entra Connect Sync, which will be retired after cloud sync has full functional parity with Microsoft Entra Connect Sync.'

This page states that the Microsoft Entra Connect Health is bundled with the Microsoft Entra Connect Sync installer:
[Download and install Microsoft Entra Connect Health Agent](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-roadmap#download-and-install-microsoft-entra-connect-health-agent)
> 'The Health Agent for sync will be installed as part of the Microsoft Entra Connect installation (version 1.0.9125.0 or higher).'
> Therefore almost one bundled product and to the simple eye paired until deprecation?
> 

[Install the Microsoft Entra Connect Health agents | requirements](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-health-agent-install#requirements)
It seems like the product could be and should be installed on a server seperate from Microsoft Entra Connect sync if the roles are supported to monitor. So it looks like there is a possibility to use Microsoft Entra Connect Health with Microsoft Entra Connect cloud sync but again I can't find any support information about this combo (haven't tried either :))

Q:
So what is exactly the status of Microsoft Entra Connect Health regarding Microsoft Entra Connect cloud sync?

Thanks! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 982a752e-1900-0483-d4d2-1a4f5ba314cf
* Version Independent ID: f45f07cc-d53d-07fc-61f9-21915eda76fd
* Content: [Microsoft Entra Connect Health FAQ - Azure - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-health-faq?source=recommendations)
* Content Source: [docs/identity/hybrid/connect/reference-connect-health-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/reference-connect-health-faq.yml)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ManoharLakkoju-MSFT** [comment]
@grimson73 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @grimson73 
According to the details outlined in the Microsoft Entra Connect Health FAQ page, Microsoft Entra Connect Health is compatible with both Microsoft Entra Connect Sync and Microsoft Entra Connect cloud sync. The Health Agent for synchronization is included in the Microsoft Entra Connect installation process. However, it can also be independently installed on a server that fulfills the necessary prerequisites for monitoring the synchronization engine.


<img width="425" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/113576472/df903d5e-7ae3-4975-86ce-3d6340687c09">

Please go through this below link for your reference. It might be useful.
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-health-sync#:~:text=Important,in%20December%202022.

**Comment by grimson73** [comment]
> Hello @grimson73 According to the details outlined in the Microsoft Entra Connect Health FAQ page, Microsoft Entra Connect Health is compatible with both Microsoft Entra Connect Sync and Microsoft Entra Connect cloud sync. The Health Agent for synchronization is included in the Microsoft Entra Connect installation process. However, it can also be independently installed on a server that fulfills the necessary prerequisites for monitoring the synchronization engine.
> 
> <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/113576472/303237462-df903d5e-7ae3-4975-86ce-3d6340687c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODE3OTgsIm5iZiI6MTcwNzM4MTQ5OCwicGF0aCI6Ii8xMTM1NzY0NzIvMzAzMjM3NDYyLWRmOTAzZDVlLTdhZTMtNDk3NS04NmNlLTNkNjM0MDY4N2MwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwODM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGU2ZjJlNzgxN2FjMzY5YjczOGMyOGFmN2EzOGJkMTZkZGEyNDM1YzYwMTQ1OWRiMDkwMzA0YjUxM2Q3ZTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GofqDyv-Z8rcNrxPhZ8Dk9WDHCemu4BztEJHbgUNCnE">
> Please go through this below link for your reference. It might be useful. https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-health-sync#:~:text=Important,in%20December%202022.

Hi thanks for the response. Unfortunately I don't see a reference to Microsoft Entra Connect _cloud_ sync in the FAQ or screenshot you provided? I do see mentioned Microsoft Entra Connect Sync V2 but to my knowledge that is the v2.xx variant of the Microsoft Entra Connect Sync version instead of the v1.xx but still Microsoft Entra Connect Sync.

So, maybe my bad, but I can't see any reference to Microsoft Entra Connect _cloud_ sync within your outlined details?

**Comment by Naveenommi-MSFT** [comment]
@grimson73 
I've delegated this to content author @billmath, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@billmath
Please review it.

**Comment by billmath** [comment]
@grimson73 Thank you for the question.  Currently connect health doesn't work with cloud sync.  Connect health requires connect sync to synchronize data to the portal.  As for supportability in the future, this has yet to be determined.  Even though cloud sync will eventually replace connect sync, we are many years away from this.  I hope this helps.  Thanks!

#please-close

**Comment by grimson73** [comment]
@billmath thanks for this technical detail, makes it all more sense instead of 'but why' :)
> Connect health requires connect sync to synchronize data to the portal.
Thanks!
