### ISSUE TITLE
You're missing what to do about Identifier (Entity ID) ...  what value goes here and where do i find it?

### ISSUE THREAD

**Issue by coffeebeantraining** [MicrosoftDocs/entra-docs#315]
https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/add-application-portal-setup-sso?source=docs

This example is missing what to do about the Identifier (Entity ID).  Exactly what value goes in here and where do i find it?
If I have a Java Web App that is deployed to a Tomcat container as a war file and I want to use SAML only to authenticate against EntraID Enterprise Apps then your Toolkit completely misses the mark.
![image](https://github.com/MicrosoftDocs/entra-docs/assets/59173960/4f1fa5d6-4fbe-4784-abcc-cf3612f7897f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ea1437d-a485-ed34-7706-c5be45ff3d8f
* Version Independent ID: f265f582-1894-bef9-9b81-a6bbd34b4381
* Content: [Enable single sign-on for an enterprise application - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/add-application-portal-setup-sso?source=docs)
* Content Source: [docs/identity/enterprise-apps/add-application-portal-setup-sso.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/add-application-portal-setup-sso.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by ManoharLakkoju-MSFT** [comment]
@coffeebeantraining 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @coffeebeantraining 
you're having trouble finding the Identifier (Entity ID) value for your Java Web App. The Identifier (Entity ID) value is typically the same as the application's metadata entityID value. Azure AD B2C uses this value to look up the application registration in the directory and read the configuration. For this lookup to succeed, identifierUri in the application registration must be populated with a value that matches the Issuer attribute.

To find the entityID value for your Java Web App, you can check the SAML metadata file for your application. This file should contain the entityID value that you need to use for the identifierUri parameter in the application registration manifest.

Regarding your second question, I understand that you want to use SAML only to authenticate against EntraID Enterprise Apps. However, I'm not sure what specific information you're looking for.

I'd recommend working closer with leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
