### ISSUE TITLE
Powershell examples outdated, do not reflect graph beta cmdlets

### ISSUE THREAD

**Issue by snarkDADMin** [MicrosoftDocs/entra-docs#316]
This article seems to be full of outdated / nonworking powershell code. For example, there is no longer a Select-MgProfile cmdlet, and I am running the latest version of the module(s)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aae83fda-27b9-edca-1b59-1140de4cc3f5
* Version Independent ID: c93eb84b-f04b-de03-f3f5-57d4672b0559
* Content: [Prepopulate contact information for self-service password reset - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-sspr-authenticationdata)
* Content Source: [docs/identity/authentication/howto-sspr-authenticationdata.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-sspr-authenticationdata.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by ManoharLakkoju-MSFT** [comment]
@snarkDADMin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@snarkDADMin
I've delegated this to @Justinha, a content author, to review and share their valuable insights.
