### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by saylee-dharne-msft** [MicrosoftDocs/entra-docs#318]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

The word blocked is misspelled on line 164.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bd8b41a-26fd-936b-5773-3eb158de253a
* Version Independent ID: eac9538f-02c5-efec-77ed-1059777c294d
* Content: [Govern access for external users in entitlement management - Microsoft Entra ID Governance](https://review.learn.microsoft.com/en-us/entra/id-governance/entitlement-management-external-users?branch=main)
* Content Source: [docs/id-governance/entitlement-management-external-users.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/entitlement-management-external-users.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by ManoharLakkoju-MSFT** [comment]
@saylee-dharne-msft 
Thanks for pointing this out. Required changes have been made, once approve by author it will reflect in the document itself.
