### ISSUE TITLE
[Article needs to be updated ]

### ISSUE THREAD

**Issue by AnthonyDelagarde** [MicrosoftDocs/entra-docs#320]
[The article graphics do not align with what is in the Entra portal or the Entra ID blade in the portal. Also the workflow is not the same and user experience as within the portal with what your article displays.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cccbfac-fe61-ed55-efff-6030b72de3cb
* Version Independent ID: ac5c4382-332b-f772-f01e-1d9c88227a92
* Content: [Microsoft Entra on-premises app provisioning to SCIM-enabled apps - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/on-premises-scim-provisioning#install-and-configure-the-microsoft-entra-connect-provisioning-agent)
* Content Source: [docs/identity/app-provisioning/on-premises-scim-provisioning.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/on-premises-scim-provisioning.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@AnthonyDelagarde 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by billmath** [comment]
@AnthonyDelagarde Thanks for catching this.  We are in the process of updating our graphics since the rebranding.  So you should see an update soon.  Thank you!

#please-close

**Comment by AnthonyDelagarde** [comment]
Hello, please see the latest update I sent. Not sure you saw it. The graphics and flow are accurate. I made a mistake. Sorru for the inconvenience. I did an update on GitHub



Anthony de Lagarde


Principal FastTrack Engineer
Azure CXP IX
Desk +1 410.564.2714
Mobile: +1 301.787.5887
https://time.is/Washington,_D.C.
***@***.***
***@***.******@***.***>
***@***.***<https://www.linkedin.com/in/anthonydelagarde/>
This email message may contain confidential and proprietary information.  Any unauthorized use is prohibited.  If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.
FYI: If you want me to act on something please put me on the TO: line. If you just want to just inform me place me on the CC: line.  Thank you
