### ISSUE TITLE
Break glass for workload identities recommended?  

### ISSUE THREAD

**Issue by JBines** [MicrosoftDocs/entra-docs#322]
Hello Team,

Currently it is impossible to apply a user based break glass account to Conditional Access polices applied to workload identities. 

Is a break glass Service Princpal required for CA polices applied only to workload identities? not sure if his makes sense to me. If you agree maybe this needs updating.

"at least one emergency access account needs to be excluded from *all* Conditional Access policies"

Br.
Joshua

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fff5de5d-9a97-73ff-4694-79027720b5c3
* Version Independent ID: 566a8387-bbdd-8e35-13cc-f2d891bd5608
* Content: [Manage emergency access admin accounts - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-emergency-access)
* Content Source: [docs/identity/role-based-access-control/security-emergency-access.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/security-emergency-access.md)
* Service: **active-directory**
* Sub-service: **roles**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **rolyon**

**Comment by RamanathanChinnappan-MSFT** [comment]
@JBines 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@JBines 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by JBines** [comment]
Stale -eq closed... Insert sad face here
