### ISSUE TITLE
Expression Builder - Missing option to search for a user when testing expressions

### ISSUE THREAD

**Issue by vek473** [MicrosoftDocs/entra-docs#323]
Hello,

Previously we had the option to select a user and then test the expression using user info. But now this option is not visible and we need to provide the details for every function we add, Documentation says "Test the expression **by searching for a user** or providing values and selecting Test expression."
![image](https://github.com/MicrosoftDocs/entra-docs/assets/103120270/179dfbc6-371f-4682-9c9c-b46618e54b2a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3ff9f49-1560-d727-6b82-4e1bde9b59b5
* Version Independent ID: 3241fa8b-8b7f-d1a5-6f73-8077f1632cc2
* Content: [Understand how expression builder works with Application Provisioning in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/expression-builder)
* Content Source: [docs/identity/app-provisioning/expression-builder.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/expression-builder.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by RamanathanChinnappan-MSFT** [comment]
@vek473
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@vek473 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@kenwith 
Can you please check and add your comments on this doc update request as applicable.

**Comment by lorieide** [comment]
Updated the topic to match test instructions found in the how-to-expression-builder#test-an-expression "Expression Builder" topic. I've updated the instructions to say: 

Test the expression by providing values and selecting Test expression. For example, from the dropdown list, select the mail attribute. Fill in the value with the email domain that starts with the @ sign; for example, `@fabrikam.com`. Then select Test expression and the output of the expression test appears in the View expression output box.

#please-close
