### ISSUE TITLE
No SSO Information for ENTRA side

### ISSUE THREAD

**Issue by gatewood502** [MicrosoftDocs/entra-docs#324]
It appears this app is no longer in the gallery, and the Entity ID/Reply URL information for the Entra app is NOT showing in the configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd35b3e-5e84-8be5-f87b-b4b666a9f7cd
* Version Independent ID: c768f626-4ea1-4ede-492d-3a9d9e2178f3
* Content: [Tutorial: Microsoft Entra integration with Amazon Web Services to connect multiple accounts - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/aws-multi-accounts-tutorial)
* Content Source: [docs/identity/saas-apps/aws-multi-accounts-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/aws-multi-accounts-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by ManoharLakkoju-MSFT** [comment]
@gatewood502 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@gatewood502 
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd 
please review it.

**Comment by v-hgampala** [comment]
Thanks for raising the issue!!
we are updating the information accordingly.
#please-close
