### ISSUE TITLE
Which of these risk detections are NOT available in Azure Gov? 

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/entra-docs#325]
Can you please be specific about which of these risk protections are currently not available in Azure Gov? I am particularly interested in understanding if Suspicious API traffic should be available within Azure Gov. Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a1385f-b90a-e7b4-8cbd-f25aeb8b3c49
* Version Independent ID: d468eb75-88a9-b1aa-7fb3-19ebb4faa179
* Content: [What are risks in Microsoft Entra ID Protection - Microsoft Entra ID Protection](https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks)
* Content Source: [docs/id-protection/concept-identity-protection-risks.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/concept-identity-protection-risks.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#label:"awaiting-product-team-response"
#label:"assigned-to-author", "product-question", "triaged"
#reassign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
@J227668 Thanks for your question... 

Reaching out to the PM who owns the detection.

**Comment by MicrosoftGuyJFlo** [comment]
@J227668 

Suspicious API Traffic will be available across all clouds. If it isn't already, it will be soon.

#please-close
