### ISSUE TITLE
`App Password` not available in Custom Authentication Strength

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/entra-docs#327]
Hi,

Though `App Password` is available as an option in `My Sign-Ins`:
![image](https://github.com/MicrosoftDocs/entra-docs/assets/298208/d384dca8-e282-404c-891e-2242c2beefc3)

It doesn't seem to be available as an authentication strength.

Any plans to have it included?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15fceb88-05e3-df67-6a00-3f72d50d391b
* Version Independent ID: 15fceb88-05e3-df67-6a00-3f72d50d391b
* Content: [Overview of custom authentication strengths and advanced options for FIDO2 security keys and certificate-based authentication in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-strength-advanced-options)
* Content Source: [docs/identity/authentication/concept-authentication-strength-advanced-options.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-strength-advanced-options.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @InbarckMS
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@haneef95 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@haneef95 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.
