### ISSUE TITLE
caballerodondinero

### ISSUE THREAD

**Issue by Tadahugo7** [MicrosoftDocs/entra-docs#33]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b288484-6709-7381-7ec9-31553f473842
* Version Independent ID: c15b9c6c-6211-1504-89c9-303b43f77d1d
* Content: [Scopes and permissions in the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scopes-oidc#admin-restricted-permissions)
* Content Source: [docs/identity-platform/scopes-oidc.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scopes-oidc.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
 #```
[harh7 Users.csv](https://github.com/MicrosoftDocs/entra-docs/files/13592888/harh7.Users.csv)
[Procfile.txt](https://github.com/MicrosoftDocs/entra-docs/files/13592891/Procfile.txt)
[README.md](https://github.com/MicrosoftDocs/entra-docs/files/13592894/README.md)

**Comment by RamanathanChinnappan-MSFT** [comment]
@Tadahugo7 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Tadahugo7 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
