### ISSUE TITLE
New update for Sign-in Frequency every time - additional support scenario - 

### ISSUE THREAD

**Issue by ShiChen872** [MicrosoftDocs/entra-docs#330]
[Enter feedback here]
Internal documents show that the feature is now supported additional scenarios below.  Could you please update because our customer asks the public evident support. 

AVD,
sensitive app
VPN

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9561a367-20d8-62e9-57e5-694bab4c0878
* Version Independent ID: a7c757e0-052b-fc42-70c5-030081baa573
* Content: [Configure authentication session management - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-session-lifetime)
* Content Source: [docs/identity/conditional-access/howto-conditional-access-session-lifetime.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/howto-conditional-access-session-lifetime.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by RamanathanChinnappan-MSFT** [comment]
@ShiChen872 
I've delegated this to @MicrosoftGuyJFlo, a content author, to review and share their valuable insights.

**Comment by MicrosoftGuyJFlo** [comment]
Resolved in https://github.com/MicrosoftDocs/entra-docs-pr/pull/1134

Following up offline internally.

#please-close
