### ISSUE TITLE
Run dsregcmd /status as local user not admin

### ISSUE THREAD

**Issue by prasanjitdas111** [MicrosoftDocs/entra-docs#331]
Hi Team,

Can you check and verify this information. 

CMD should be opened as normal user to run dsregcmd /status not as admin. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9f81d74-8dcb-e644-9647-0d1d0817f975
* Version Independent ID: e249cc9d-2120-8868-dbca-bc3b85f38b4b
* Content: [Troubleshoot Microsoft Entra hybrid joined devices - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/troubleshoot-hybrid-join-windows-current)
* Content Source: [docs/identity/devices/troubleshoot-hybrid-join-windows-current.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/troubleshoot-hybrid-join-windows-current.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@prasanjitdas111 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@prasanjitdas111
Exactly. While a normal user can execute `dsregcmd/status` in the command prompt, accessing certain additional features or requiring elevated privileges may necessitate opening the command prompt as an administrator.

**Comment by RamanathanChinnappan-MSFT** [comment]
@prasanjitdas111
We are going to close this thread. if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
