### ISSUE TITLE
Single sign-out section should mention the sid query parameter

### ISSUE THREAD

**Issue by AriPaaWun** [MicrosoftDocs/entra-docs#333]
Currently, Single sign-out section doesn't tell what parameter the `HTTP GET request to the registered LogoutUrl` will have.

I had to test it to find out it is `sid`. The documentation should also elaborate on which request this `sid` is acquired.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d3746e5-5147-d996-ba4f-350fd1d086ef
* Version Independent ID: afff03f1-16c3-9866-39b0-bdddd0e55d7d
* Content: [OpenID Connect (OIDC) on the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc#single-sign-out)
* Content Source: [docs/identity-platform/v2-protocols-oidc.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-protocols-oidc.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by ManoharLakkoju-MSFT** [comment]
@AriPaaWun 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@AriPaaWun 
Thank you for bringing this to our attention.
I've delegated this to content author @OwenRichards1, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@OwenRichards1 
Could you please review add comments on this, update as appropriate.
