### ISSUE TITLE
Missing Role

### ISSUE THREAD

**Issue by DeanGross144** [MicrosoftDocs/entra-docs#334]
The Authentication Extensibility Administrator role is available in the Entra portal but not described on the documentation page. Please add the description for this role and for any other roles that may be missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0767aac4-fcd9-eaac-2c30-8f17d8eadd92
* Version Independent ID: a380a828-03f9-e037-3a62-e4165fda7cb6
* Content: [Microsoft Entra built-in roles - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference)
* Content Source: [docs/identity/role-based-access-control/permissions-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/permissions-reference.md)
* Service: **active-directory**
* Sub-service: **roles**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by ManoharLakkoju-MSFT** [comment]
@DeanGross144 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by DeanGross144** [comment]
This is the page that is missing the information about that role https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference

**Comment by DeanGross144** [comment]
Here's an image of what is shown in the portal 
![image](https://github.com/MicrosoftDocs/entra-docs/assets/85760922/896eab85-a81d-48fb-bcbc-20e490ea465c)

**Comment by ManoharLakkoju-MSFT** [comment]
@DeanGross144 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@DeanGross144 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@rolyon 
Can you please check and add your comments on this doc update request as applicable.

**Comment by rolyon** [comment]
Hi @DeanGross144 
Thanks for your feedback. We've added this role to the docs.
https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#authentication-extensibility-administrator
thanks

**Comment by rolyon** [comment]
#please-close
