### ISSUE TITLE
Limits for Attributes  and Sets

### ISSUE THREAD

**Issue by sudeip** [MicrosoftDocs/entra-docs#335]
If we have 500 attribute sets defined, are we allowed to have just one attribute per set?

On the tenant when i am adding new Attribute set, it says "Maximum number of attributes for the attribute set. Maximum number is 500". This does not state the limit is on tenant level. Could someone confirm correct limits on tenant and sets? 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2896aa11-53c5-722b-aabf-e59dda55cf38
* Version Independent ID: 7291a3a0-24d6-0e88-9105-29001f7e3ed1
* Content: [What are custom security attributes in Microsoft Entra ID? - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/custom-security-attributes-overview#limits-and-constraints)
* Content Source: [docs/fundamentals/custom-security-attributes-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/custom-security-attributes-overview.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@sudeip 
The limit of 500 custom security attributes per tenant applies to the total number of active attributes across all attribute sets in the tenant. This means that if you have 500 attribute sets defined, you can have one attribute per set, or you can have multiple attributes per set as long as the total number of active attributes across all sets does not exceed 500.

When creating a new attribute set, the maximum number of attributes for the set is also 500. This means that you can define up to 500 custom security attributes within a single attribute set.

I hope this clarifies the limits and constraints for custom security attributes in Azure AD. Let me know if you have any other questions.

**Comment by AjayBathini-MSFT** [comment]
@sudeip 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
