### ISSUE TITLE
Chrome extension Windows 10 Accounts not needed anymore?

### ISSUE THREAD

**Issue by velden** [MicrosoftDocs/entra-docs#338]
I think the Chrome extension  "Windows 10 Accounts" isn't needed anymore because Chrome natively supports CloudAP.

https://chromeenterprise.google/policies/?policy=CloudAPAuthEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3bcf99-60c3-876c-c421-3351e507a81b
* Version Independent ID: c906978e-acf2-462c-d7ff-20221872a793
* Content: [Primary Refresh Token (PRT) and Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/concept-primary-refresh-token#detailed-flows)
* Content Source: [docs/identity/devices/concept-primary-refresh-token.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/concept-primary-refresh-token.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"cxp"
#label:"assigned-to-author"
#reassign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
