### ISSUE TITLE
[ Disregard the request for this page to updated ]

### ISSUE THREAD

**Issue by AnthonyDelagarde** [MicrosoftDocs/entra-docs#339]
[Hello, I made an earlier request to update the pictures and workflow on this document. My request was in error. I was looking at the screen and made a mistake when matching up the steps. Sorry for the inconvenience and error on my part.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cccbfac-fe61-ed55-efff-6030b72de3cb
* Version Independent ID: ac5c4382-332b-f772-f01e-1d9c88227a92
* Content: [Microsoft Entra on-premises app provisioning to SCIM-enabled apps - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/on-premises-scim-provisioning)
* Content Source: [docs/identity/app-provisioning/on-premises-scim-provisioning.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/on-premises-scim-provisioning.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ManoharLakkoju-MSFT** [comment]
@AnthonyDelagarde 
Glad to know you have self-resolved the issue.
