### ISSUE TITLE
Error on step 4 ps command

### ISSUE THREAD

**Issue by BigStan82** [MicrosoftDocs/entra-docs#34]
At Enable sensitivity label support in PowerShell section, when run powershell command on step 4, it returns an error: 

**PS Command:**
$params = @{
     Values = @(
 	    @{
 		    Name = "EnableMIPLabels"
 		    Value = "True"
 	    }
     )
}

Update-MgBetaDirectorySetting -DirectorySettingId $grpUnifiedSetting.Id -BodyParameter $params

**Error:**

Update-MgBetaDirectorySetting: Cannot process argument transformation on parameter 'DirectorySettingId'. Cannot convert value to type System.String.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef84a3e0-879e-4312-a89d-7a3bb0cd9a51
* Version Independent ID: 43851f8a-b71f-0a0a-8b1f-629e3528972f
* Content: [Assign sensitivity labels to groups - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-assign-sensitivity-labels)
* Content Source: [docs/identity/users/groups-assign-sensitivity-labels.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-assign-sensitivity-labels.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by RamanathanChinnappan-MSFT** [comment]
@BigStan82
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@BigStan82 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation

**Comment by BigStan82** [comment]
Thanks for quick response. When I use .ToString() it returns this error:
Update-MgBetaDirectorySetting_Update: The format of the specified identifier is invalid.

Status: 400 (BadRequest)
ErrorCode: Request_BadRequest
Date: 2023-12-11T09:29:44

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : f6db2ec8-b575-4fc5-b949-69c761173888
client-request-id             : f38d2060-5138-43a5-abee-38bb1f27c58a
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Switzerland North","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"ZRH2EPF000000ED"}}
x-ms-resource-unit            : 1
Date                          : Mon, 11 Dec 2023 09:29:43 GM

**Comment by ManoharLakkoju-MSFT** [comment]
@BigStan82 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
Thank you for your time and patience throughout this issue.

**Comment by johntroupmagnixaero** [comment]
> Thanks for quick response. When I use .ToString() it returns this error: Update-MgBetaDirectorySetting_Update: The format of the specified identifier is invalid.
> 
> Status: 400 (BadRequest) ErrorCode: Request_BadRequest Date: 2023-12-11T09:29:44
> 
> Headers: Cache-Control : no-cache Transfer-Encoding : chunked Vary : Accept-Encoding Strict-Transport-Security : max-age=31536000 request-id : f6db2ec8-b575-4fc5-b949-69c761173888 client-request-id : f38d2060-5138-43a5-abee-38bb1f27c58a x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"Switzerland North","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"ZRH2EPF000000ED"}} x-ms-resource-unit : 1 Date : Mon, 11 Dec 2023 09:29:43 GM

Seeing the same errors as well.

**Comment by BigStan82** [comment]
> 
> Seeing the same errors as well.

I have fixed mine, by just continuing reading the next paragraph.

_"1. Issue a **Get-MgBetaDirectorySetting | FL** cmdlet and check the ID. If several ID values are present, use the one where you see the EnableMIPLabels property on the Values settings.
2. Issue the **Update-MgBetaDirectorySetting** cmdlet, using the **ID** that you retrieved."_

And instead of $grpUnifiedSetting.Id I used the ID value.

Hope this helps!

**Comment by johntroupmagnixaero** [comment]
I ended up doing something similar. I saw that it was returning an array instead of just one record so I changed it to retrieving the second 3 item e.g. $grpUnifiedSetting = $grpUnifiedSetting[2]. It looks like their search scope wasn't filtering properly and returned all items.

John

**Comment by InfiniteSpektrum** [comment]
It's strange that the default code from Microsoft from the documentation does not work as expected.

I fixed my code like this:

$grpUnifiedSetting = Get-MgBetaDirectorySetting -Search DisplayName:"Group.Unified"
foreach ($grp in $grpUnifiedSetting) {
    if ($grp.Displayname -eq "Group.Unified") {
        $id = $grp.Id
    }
}
$params = @{
     Values = @(
 	    @{
 		    Name = "EnableMIPLabels"
 		    Value = "True"
 	    }
     )
}
Update-MgBetaDirectorySetting -DirectorySettingId $id -BodyParameter $params
