### ISSUE TITLE
"dispalyName"

### ISSUE THREAD

**Issue by JesperJohag** [MicrosoftDocs/entra-docs#341]
Under section "Schema for Entra ID to AD configurations"  displayName is misspelled as **dispalyName**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba290a8-7b6e-a859-4f4d-70ea2d035424
* Version Independent ID: 1ba290a8-7b6e-a859-4f4d-70ea2d035424
* Content: [Provision groups to Active Directory using Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Naveenommi-MSFT** [comment]
@JesperJohag 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@JesperJohag 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
