### ISSUE TITLE
Poorly written and extremely confusing

### ISSUE THREAD

**Issue by ltjones12** [MicrosoftDocs/entra-docs#344]
What a poorly written article. The workflow diagram is blurry and zooming in makes it worse. The section under User sign-in frequency and device identities makes absolutely no sense whatsover and is extremely confusing. After reading it over 3x I still can't make sense of it. It could not have been written any worse. Are these tech articles written by the lowest bidder? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9561a367-20d8-62e9-57e5-694bab4c0878
* Version Independent ID: a7c757e0-052b-fc42-70c5-030081baa573
* Content: [Configure authentication session management - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-session-lifetime)
* Content Source: [docs/identity/conditional-access/howto-conditional-access-session-lifetime.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/howto-conditional-access-session-lifetime.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@ltjones12 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@MicrosoftGuyJFlo 
Can you please check and add your comments on this doc update request as applicable.
