### ISSUE TITLE
Unexpected wording 

### ISSUE THREAD

**Issue by gb5757870** [MicrosoftDocs/entra-docs#347]
Shortly after the title "On-premises integration" it says "![Validating password writeback is enabled and working][Writeback]"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18640c6c-b52c-84e3-59d8-90f2a663cc6b
* Version Independent ID: 77b249dc-4440-0334-31d7-b05d30f52657
* Content: [Self-service password reset deep dive - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-howitworks)
* Content Source: [docs/identity/authentication/concept-sspr-howitworks.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-sspr-howitworks.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by ManoharLakkoju-MSFT** [comment]
@gb5757870 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@gb5757870 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
