### ISSUE TITLE
feedback 

### ISSUE THREAD

**Issue by marche97** [MicrosoftDocs/entra-docs#348]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb61215-dbe7-bd17-91c1-c1af722b65cc
* Version Independent ID: 40da65bb-b522-4b6f-8954-bb2b8ad17706
* Content: [Quickstart - Access & create new tenant - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/create-new-tenant)
* Content Source: [docs/fundamentals/create-new-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/create-new-tenant.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by ManoharLakkoju-MSFT** [comment]
@marche97 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ManoharLakkoju-MSFT** [comment]
@marche97 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
