### ISSUE TITLE
Logout does not work when using Microsoft Authentication Library (MSAL)

### ISSUE THREAD

**Issue by raghu1488** [MicrosoftDocs/entra-docs#351]
The trouble is that when I try to logout the user it does not work as expected.

If the user logs out and immediately after kills the app, the next time the app is started the login screen is presented as expected.

But if the user does NOT kill the app, but instead presses my login button   the sign in screen is presented but still says signed in for the user that is signed out. on selecting that user a valid token is immediately returned and the app is able to use this token for service calls, i.e. it is a valid token.

I have referred to below app also please help 
https://github.com/Azure-Samples/ms-identity-ciam-dotnet-tutorial/tree/main/1-Authentication/2-sign-in-maui

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78b80b9e-b853-a829-9199-358fe8c05cc1
* Version Independent ID: 4de26915-1ece-a5ac-b24c-107e1fecde15
* Content: [Tutorial: Create a .NET MAUI shell app, add MSAL SDK, and include an image resource - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-desktop-app-maui-sign-in-prepare-app#add-msal-sdk-support-using-msal-helper-classes)
* Content Source: [docs/external-id/customers/tutorial-desktop-app-maui-sign-in-prepare-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-desktop-app-maui-sign-in-prepare-app.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by Naveenommi-MSFT** [comment]
@raghu1488 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@raghu1488 
I'm going to assign this to the document author so they can take a look at it accordingly

@henrymbuguakiarie
Can you please check and add your comments on this doc update request as applicable.

**Comment by raghu1488** [comment]
Any updates on this so far??
