### ISSUE TITLE
Group or group for Attributes and Claims

### ISSUE THREAD

**Issue by ifoam** [MicrosoftDocs/entra-docs#352]
Step 7 claims names are sensitive. The screen show in step 6 shows "Group" while the table on step 7 shows "group". It's not clear what is correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 675b6583-259f-1135-6443-b9aa40258163
* Version Independent ID: 28e01c75-b130-260c-4aa6-75a1cba20558
* Content: [Tutorial: Microsoft Entra SSO integration with FortiGate SSL VPN - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/fortigate-ssl-vpn-tutorial#configure-azure-ad-sso)
* Content Source: [docs/identity/saas-apps/fortigate-ssl-vpn-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/fortigate-ssl-vpn-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@ifoam 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@ifoam 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

**Comment by v-hgampala** [comment]
@ifoam, thanks for raising the issue!!
we're updating the document with proper attribute values to avoid confusion and the correct attribute value is 'group'.
#please-close
