### ISSUE TITLE
Create a Temporary Access Pass Section Incorrect

### ISSUE THREAD

**Issue by JasonRBeer** [MicrosoftDocs/entra-docs#353]
Unless I'm missing something, it appears the instructions under the "Create a Temporary Access Pass" section are wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5eeab12d-7578-3f86-4461-10603274408b
* Version Independent ID: f4911928-14be-ecf6-0b02-cc80871ae365
* Content: [Configure a Temporary Access Pass in Microsoft Entra ID to register passwordless authentication methods - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-temporary-access-pass)
* Content Source: [docs/identity/authentication/howto-authentication-temporary-access-pass.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-temporary-access-pass.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @tilarso
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@JasonRBeer 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by tilarso** [comment]
pushed change to main doc, PR is in progress of merging to main.

**Comment by JasonRBeer** [comment]
It also appears to state that you need the global administrator or
authentication policy administrator role to create a temporary access pass.
I think it should be global administrator or authentication administrator.

**Comment by Naveenommi-MSFT** [comment]
@tilarso 
Could you please check following comments from @JasonRBeer, Add your insights on this.
