### ISSUE TITLE
Implications of Direct Connect Default Settings

### ISSUE THREAD

**Issue by DontNeedNoGit** [MicrosoftDocs/entra-docs#354]
This page is very clear that B2B Direct Connect requires both organizations to enable the connection, usually in the form of directly adding the tenant ID in both tenants. However, there are no examples or information about the implications of the default settings. What if I make the default outbound B2B Direct Connect setting to be allowed for all organizations? Does this mean that my users can be added to shared channels in any organization that has inbound settings that allowed my tenant, or if they allowed inbound B2B Direct Connect for all organizations? If all authentication happens in my own tenant, then are there security implications for allowing unrestricted outbound access for B2B Direct Connect to facilitate maximum collaboration without having to switch tenants in Teams? I'm struggling to think why the default would be to block this. And same or similar questions about inbound access. If I allow inbound Direct Connect for everyone, then what is the security difference between allowing my users to invite any user in another unknown Microsoft tenant to be in a Shared Channel vs them adding a Guest into other types of channels (since you can't add Guests to shared channels...boooooo!!!). 

It would be good to add more information about the impacts of the default settings--both inbound and outbound--and touch on the security/resource access concerns. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a16a239-3c26-c839-6b40-a12afe1d5fba
* Version Independent ID: b86ecce0-b57d-8d53-f3ae-cbd0f0fcbbba
* Content: [B2B direct connect Microsoft Entra overview - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/b2b-direct-connect-overview)
* Content Source: [docs/external-id/b2b-direct-connect-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/b2b-direct-connect-overview.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by Naveenommi-MSFT** [comment]
@DontNeedNoGit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@csmulligan
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@DontNeedNoGit 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by csmulligan** [comment]
Hi @DontNeedNoGit thank you so much for your suggestions. I’ve added this to an internal work item for a documentation update. Since we’re tracking it there, I’ll go ahead and close this issue. Feel free to reopen if you have anything to add. Thanks again!
#please-close

**Comment by DontNeedNoGit** [comment]
I understand that you're tracking it in your other "documentation updates needed" tracker, but then I do not get any notification when this information is added. Can you leave this open until the change is made to explain the default settings so that I will know when an answer is provided?
