### ISSUE TITLE
fideback

### ISSUE THREAD

**Issue by yudhakr** [MicrosoftDocs/entra-docs#355]
[Enter feedback here]

sanagt bagus
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 500e494e-9d83-0395-cffc-66a97e516849
* Version Independent ID: 38de4d4c-d4ed-8c96-d9d2-e6dc50cf97c0
* Content: [Introduction to identity - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/identity-fundamental-concepts?source=recommendations)
* Content Source: [docs/fundamentals/identity-fundamental-concepts.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/identity-fundamental-concepts.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by Naveenommi-MSFT** [comment]
@yudhakr 
It would be great if you could elaborate your query? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@yudhakr 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
