### ISSUE TITLE
Document how to send a blocking response in case of error when adding claims

### ISSUE THREAD

**Issue by AlbertoPa** [MicrosoftDocs/entra-docs#356]
The current documentation shows how to send a response to enrich the token with custom claims. However, there is no mention of what  the response needs to be when an error occurs in the custom claim provider.

It would be useful to document what response causes Entra to show an error message to the user (is it any status code different from 200?)

Thank you :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe819e4f-33cb-8ab0-a5f1-f197e9fbe499
* Version Independent ID: f1818b00-ab24-133a-2ca0-6a268c842614
* Content: [Custom claims provider reference - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-claims-provider-reference)
* Content Source: [docs/identity-platform/custom-claims-provider-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-claims-provider-reference.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by Naveenommi-MSFT** [comment]
@AlbertoPa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@cilwerner
Can you please check and add your comments on this doc update request as applicable.

**Comment by cilwerner** [comment]
@AlbertoPa, have you checked out the following [troubleshooting doc](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-troubleshoot#error-behavior), and the section on error behaviour? Is this what you're looking for or is some further clarification needed?

**Comment by AlbertoPa** [comment]
Hello @cilwerner 

Thank you for the link. It explains what error codes from Entra to the application in case of errors.
What I wanted to know is what is the expected return response **from the custom authorization extension API to Entra ID** in case of error, specifically in the custom claim provider (````tokenIssuanceStart``` event).

If the request is successful, the API endpoint of the custom claim provider must return an HTTP 200 response, with the JSON content shown here https://learn.microsoft.com/en-us/entra/identity-platform/custom-claims-provider-reference#rest-api-schema 

So the questions I was trying to answer with the documentation are:

- What HTTP response is expected by Entra in case of error in the custom claim provider? Any standard HTTP error status code, or is there a specific response to be sent?

- Does the ```tokenIssuanceStart``` event have the equivalent of the "blocking response" available for attribute collection events, which allows a customized error message to be sent to the app as shown in https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-onattributecollectionstart-reference#response-from-the-external-rest-api?

Thanks!

**Comment by cilwerner** [comment]
In [Configure a custom claim provider token issuance event: Step 5](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-get-started?tabs=entra-admin-center#step-5-protect-your-azure-function), you set the App Service authentication settings to `HTTP 401` for an **unauthenticated response**. This is recommended for APIs. 

That response is also expected for the [attribute collection events Step 5](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-attribute-collection?tabs=start-continue%2Csubmit-continue#step-5-protect-your-azure-function).

From what I can see here for both of these, `302`, `401`, `403` and `404` can all be used here, but as per the instructions there, it's best to go with `401`. Does that answer both your questions?

**Comment by AlbertoPa** [comment]
Thanks @cilwerner  

I think ```401``` and Step 5 deal with the case when the custom authentication extension receives an unauthenticated request. My question was about valid, authenticated requests that fail internally, but this still answers my questions :-)

If I get it correctly, the API should respond as a regular API in case of error (for example ```500```), Entra will throw an error code, and based on such an error code, the application should show an appropriate message to the user.

**Comment by cilwerner** [comment]
@AlbertoPa, sounds good! You could also try going through that how-to guide and simulate an error and see what you get? I recommend using a workforce tenant, I'm working on fixing a couple of bugs in that doc, but totally up to you.

When you get to Step 5, enter the following issuer URL, `https://login.microsoftonline.com/{tenantId}/v2.0/`, where `{tenantId}` is the tenant ID of your workforce tenant.

I'll close this issue as I've answered your question, and will liaise with the product managers if further clarification is needed.

**Comment by cilwerner** [comment]
#please-close
