### ISSUE TITLE
The from address for managed certificate expiry notifications is wrong - they're coming from "mssecurity-noreply@microsoft.com"

### ISSUE THREAD

**Issue by UKAdmin2024** [MicrosoftDocs/entra-docs#360]
The from address for managed certificate expiry notifications is wrong - they're coming from "mssecurity-noreply@microsoft.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2344f9d-a62b-26f2-aef5-d6828d2890c9
* Version Independent ID: ec5de129-aa5f-eb8b-5f48-3949fec0f356
* Content: [Tutorial: Manage federation certificates - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on#add-email-notification-addresses-for-certificate-expiration)
* Content Source: [docs/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/tutorial-manage-certificates-for-federated-single-sign-on.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by Naveenommi-MSFT** [comment]
@UKAdmin2024 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@UKAdmin2024 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
