### ISSUE TITLE
Total scope of Microsoft Entra Password Protection on all on-premises users (synced an non synced)

### ISSUE THREAD

**Issue by grimson73** [MicrosoftDocs/entra-docs#364]
Hello,

Could you please clarify in the docs the following 2 items?

I'm seeking specific information about how Microsoft Entra Password Protection applies to all on-premises users, regardless of whether they are synchronized with Microsoft Entra ID or not.

### **Question 1: Microsoft Entra Password Protection for all on-premises users?**
Unfortunately I cannot find explicit information if the Microsoft Entra Password Protection is enabled for _all on-premises users_ and cannot be changed if set-up. I do think this is the case but the only thing I could find was regarding Online Entra ID (synced) tenant accounts:

https://learn.microsoft.com/en-us/entra/identity/authentication/concept-password-ban-bad#global-banned-password-list
> The global banned password list is automatically applied to all users in a Microsoft Entra tenant. There's nothing to enable or configure, and can't be disabled. This global banned password list is applied to users when they change or reset their own password through Microsoft Entra ID.

So, please clarify if installing the Microsoft Entra Password Protection on-premises indeed apply for all on-premises users (per domain) without any exception possible (of course the custom banned list).

### **Question 2: Please expand license requirements for non-synced on-premises users.**
https://learn.microsoft.com/en-us/entra/identity/authentication/concept-password-ban-bad#license-requirements
> _**Note**_
> On-premises AD DS users that aren't synchronized to Microsoft Entra ID also benefit from Microsoft Entra Password Protection based on existing licensing for synchronized users.

If question one establishes that the on-premises Microsoft Entra Password Protection applies to all on-premises users, regardless of whether they are synchronized with Microsoft Entra ID or not, how about specific licensing?
In what regard is the 'benefit' of having, for example, _ONE_ P1 license, but 100 on-premises users without any online presence? Is this the 'requirement' the article states and are you therefore compliant?
I understand that all on-premises synced must be licensed but what about the 100 on-premises users or specific license scenario for non-licensed on-premises users?

So please expand on this on-premises license topic.

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53684ada-fb90-0497-30d2-8c8c5d3a39ec
* Version Independent ID: f6b5da43-1f40-3bdf-58cd-037632680668
* Content: [Microsoft Entra Password Protection - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-password-ban-bad-on-premises)
* Content Source: [docs/identity/authentication/concept-password-ban-bad-on-premises.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-password-ban-bad-on-premises.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@grimson73 
Question 1: Microsoft Entra Password Protection for all on-premises users?
Microsoft Entra Password Protection can be enabled for on-premises users, regardless of whether they are synchronized with Microsoft Entra ID or not. However, the implementation of Microsoft Entra Password Protection for on-premises users may require additional configuration and setup. The article you referenced regarding the global banned password list applies to all users in a Microsoft Entra tenant, including on-premises users. This means that the global banned password list is automatically applied to all on-premises users in a Microsoft Entra tenant and cannot be disabled.

Question 2: Please expand license requirements for non-synced on-premises users.
Regarding your question about licensing requirements for non-synced on-premises users with Microsoft Entra Password Protection, it is important to note that licensing requirements may vary depending on the specific scenario and licensing agreement.

According to article you referenced states that on-premises AD DS users that are not synchronized to Microsoft Entra ID can also benefit from Microsoft Entra Password Protection based on existing licensing for synchronized users. This means that if you have licensed synchronized users with Microsoft Entra Password Protection, the same license can be used to enable Microsoft Entra Password Protection for non-synced on-premises users.

However, it is important to review the specific licensing agreement and requirements for your organization to ensure compliance. If you have 100 on-premises users without any online presence, you may need to review your licensing agreement to determine if they are covered under your existing license or if additional licensing is required.

I suggest reviewing the Microsoft Entra licensing documentation or contacting Microsoft support for further clarification on licensing requirements for non-synced on-premises users with Microsoft Entra Password Protection.
Please log a case here: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request. Thank you.

**Comment by grimson73** [comment]
Hi @Naveenommi-MSFT 
So the answer for question 1 is that it's all or nothing when enabling Microsoft Entra Password Protection for on-premises users.
When enabled, all on-premises users are subjected to Microsoft Entra Password Protection without any configurable exception.

The issue I have (please be kind :)) is that the article says that non online present users can also benefit from Microsoft Entra Password Protection so in my (technical) opinion its because of the non configurable option (all or nothing) when enabling Microsoft Entra Password Protection for on-premises users. Therefore I guess the article states that all on-premises users benefit from Microsoft Entra Password Protection regardless their online presence or not.

Also because you cannot choose which on-premises users can utilize Microsoft Entra Password Protection again I think its why the article states that all users benefit, even the non licensed ones.

So therefore I think there isn't anything to license but just like the article says; just a license for the cloud enabled users and all other non cloud on-premises users benefit because of this all or nothing setting. Wouldnt you agree?

**Comment by Naveenommi-MSFT** [comment]
@grimson73 
It appears that when Microsoft Entra Password Protection is enabled for on-premises users, it is an all-or-nothing approach. This means that all on-premises users are subjected to Microsoft Entra Password Protection without any configurable exception.

Regarding licensing, it seems that only cloud-enabled users require a license for Microsoft Entra Password Protection. However, all on-premises users benefit from Microsoft Entra Password Protection due to the all-or-nothing approach. This means that even non-licensed on-premises users benefit from the policy.

If you're still having trouble understanding my point, we encourage you to utilize our beloved Microsoft Q&A platform for any technical queries or clarifications. Please feel free to raise your query on the [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html).

**Comment by grimson73** [comment]
> @grimson73 It appears that when Microsoft Entra Password Protection is enabled for on-premises users, it is an all-or-nothing approach. This means that all on-premises users are subjected to Microsoft Entra Password Protection without any configurable exception.
> 
> Regarding licensing, it seems that only cloud-enabled users require a license for Microsoft Entra Password Protection. However, all on-premises users benefit from Microsoft Entra Password Protection due to the all-or-nothing approach. This means that even non-licensed on-premises users benefit from the policy.
> 
> If you're still having trouble understanding my point, we encourage you to utilize our beloved Microsoft Q&A platform for any technical queries or clarifications. Please feel free to raise your query on the [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html).

Thank you, again sorry for nagging about this issue, but it's now clear what the benefit is. No license requirement is needed. Also established that it's an all or nothing approach. Therefore the first question was needed to answer the second question.
