### ISSUE TITLE
Cannot login with username

### ISSUE THREAD

**Issue by rbrayb** [MicrosoftDocs/entra-docs#365]
"Authentication - Username and password"

This is not correct. 

You can create a username/password, but the user flow only allows an email login, so it throws an error saying, "Enter valid email address" if you try a username.

You can log in with the username UPN, which is an email address.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b05f311f-f88c-e54c-7b40-ecd7a1056656
* Version Independent ID: f5a5a217-9681-8732-2212-e740dfc02092
* Content: [Supported features in customer tenants - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/concept-supported-features-customers#openid-connect-and-oauth2-flows)
* Content Source: [docs/external-id/customers/concept-supported-features-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/concept-supported-features-customers.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by Naveenommi-MSFT** [comment]
@rbrayb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msmimart** [comment]
Hi @rbrayb thank you for pointing this out, we'll clarify this in the doc.

**Comment by AjayBathini-MSFT** [comment]
@rbrayb 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by alaanasser00** [comment]
Hi, I would like to know if this feature will be available in the future.

Thank you
