### ISSUE TITLE
Product does not match the page

### ISSUE THREAD

**Issue by W00tFoo** [MicrosoftDocs/entra-docs#368]
Hi,

When I follow this step:

> 2. Browse to Identity governance > Privileged Identity Management > Azure Resources.
> 
> If this is your first time using Privileged Identity Management for Azure resources, you'll see a Discover resources page.

I've never seen a Discover resources page; What I do see is:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/127457543/eee5b141-3123-48be-87a6-e3d5ce1c04cf)

Several times I've walked through the process in what I do see, drilled down to a resource, and selected Manage resource. It then takes me to the resource, with no indication that anything happened. I don't think anything has happened.

I'm being careful as I learn PIM, and have not yet activated PIM on our subscription. If PIM was in fact not activated for the resource after I followed the steps (I'm guessing because I'm not sure how to verify this), could it be because PIM has not yet been activated for the subscription? 

Either way, I'm not sure what has or has not happened, and also confused about why what I see in the product does not match the documentation.

I'm hoping you can update this quickly, as I need to get PIM deployed soon. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bef8c4d4-c8f5-aaf2-c1e8-4da44f9fdee0
* Version Independent ID: 4850f3f9-10ce-78c3-9f6d-8e037e5f3de1
* Content: [Discover Azure resources to manage in PIM - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-resource-roles-discover-resources)
* Content Source: [docs/id-governance/privileged-identity-management/pim-resource-roles-discover-resources.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/pim-resource-roles-discover-resources.md)
* Service: **entra-id-governance**
* Sub-service: **privileged-identity-management**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@W00tFoo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@W00tFoo 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.
