### ISSUE TITLE
Requesting more troubleshooting guidance for empty drop-down menu.

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/entra-docs#37]
This note:

    Note

    If your AD domain is not visible in the Active Directory Domain dropdown list, reload the provisioning app in the browser. Click on View on-premises agents for your domain to ensure that your agent status is healthy.

seems aimed at people who's AD domain is not visible in the drop-down list. However the troubleshooting advice in the second sentence is not helpful, since that "view on-premises agents" doesn't exist[0], if the domain isn't visible.

Furthermore, I have registered a server and I cannot get the domain to appear. Refreshing the page doesn't help. Additional troubleshooting tips, such as checking the event logs[1], or other areas would be helpful, as the current suggestion is confusing and inadequate.
[0]
![Screenshot 2023-12-07 144418](https://github.com/MicrosoftDocs/entra-docs/assets/6467813/e9d07db6-c30b-456d-b92c-eb96a292fd38)

[1]
![Screenshot 2023-12-07 121215](https://github.com/MicrosoftDocs/entra-docs/assets/6467813/d23de65c-c66b-48ab-b7b4-d8d5985d5545)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e947f34f-6e1f-199d-df18-061e4aed6980
* Version Independent ID: 80ecf3b7-3470-ed5c-c769-779a24fe3305
* Content: [Configure API-driven inbound provisioning app - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/inbound-provisioning-api-configure-app#configure-api-driven-inbound-provisioning-to-on-premises-ad)
* Content Source: [docs/identity/app-provisioning/inbound-provisioning-api-configure-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/inbound-provisioning-api-configure-app.md)
* Service: **active-directory**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Mike-Crowley 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@kenwith
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@Mike-Crowley 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by kenwith** [comment]
Sorry for the long delay. I am checking with the product team and will update documentation based on their feedback. Thank you for the thorough information and screenshots. It is very helpful.

**Comment by kenwith** [comment]
Quick update that I am still following up with the product team. To get the issue resolved asap it would be best to open a service ticket so that it gets in the queue. I am going to keep following up and will update the doc on what I find out though too.
