### ISSUE TITLE
"scope" appears to be required

### ISSUE THREAD

**Issue by thedanhoffman** [MicrosoftDocs/entra-docs#370]
Received this response: `The request body must contain the following parameter: 'scope'`, but `scope` is only listed as "Recommended" and not "Required"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3eac288-4ddd-1099-1c86-885aa42a566f
* Version Independent ID: 190585ca-8337-0644-2182-75b77f53c175
* Content: [Microsoft identity platform and OAuth 2.0 Resource Owner Password Credentials - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth-ropc)
* Content Source: [docs/identity-platform/v2-oauth-ropc.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-oauth-ropc.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by Naveenommi-MSFT** [comment]
@thedanhoffman 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@thedanhoffman 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
