### ISSUE TITLE
@ManoharLakkoju-MSFT  The issue still exists.

### ISSUE THREAD

**Issue by raghu1488** [MicrosoftDocs/entra-docs#372]
@ManoharLakkoju-MSFT  The issue still exists.

Hi the issue is still there 
I am using MAUI Hybrid blazor application 
the issue is coming with popup window only

I have check with cache account everything is cleared but still the popup window says signed in unless I close and reopen the application again.

the issues isn't resolved yet

_Originally posted by @raghu1488 in https://github.com/MicrosoftDocs/entra-docs/issues/351#issuecomment-1940905322_

**Comment by Naveenommi-MSFT** [comment]
@raghu1488 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@raghu1488 
I will reopen the case and assign it to the content author. You can follow the updates on that thread.
Thank you
