### ISSUE TITLE
Global Secure Access and Microsoft Defender

### ISSUE THREAD

**Issue by peterjoinobits** [MicrosoftDocs/entra-docs#374]
Hi 

Are there any plans to incorporate this into https://security.microsoft.com? It would be really useful to have at least the reporting components of this technology stack on the Defender Portal. 

Also there was no mention of iOS/Mac in the document. I'm assuming there will be support for it at some point. 

I will be testing this technology shortly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a38ffcf6-31e4-abc7-d13f-1535236e6401
* Version Independent ID: 4dc4d4fa-b377-be53-fe99-f23c3dfdebba
* Content: [Get started with Global Secure Access (preview) - Global Secure Access](https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-get-started-with-global-secure-access)
* Content Source: [docs/global-secure-access/how-to-get-started-with-global-secure-access.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/global-secure-access/how-to-get-started-with-global-secure-access.md)
* Service: **global-secure-access**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by Naveenommi-MSFT** [comment]
@peterjoinobits 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@peterjoinobits 
Microsoft is constantly working to improve its security offerings and may consider incorporating Microsoft Entra Global Secure Access into the portal in the future. The document you referenced does not mention particular support for iOS/Mac. However, Microsoft Entra Global Secure Access supports a wide range of platforms and devices, including Windows, macOS, iOS, and Android. 
For any technical queries or clarifications,  I'd recommend working closer with our team, we encourage to utilise Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)

**Comment by Naveenommi-MSFT** [comment]
@peterjoinobits 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
