### ISSUE TITLE
Yaml File Broken

### ISSUE THREAD

**Issue by andyorszula** [MicrosoftDocs/entra-docs#379]
Uploading the yaml file even as is creates an error on the attribute mapping policy page in Rackspace. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1497cdb6-3e0c-de54-9526-bb60d539c673
* Version Independent ID: 2b8bf8ef-a4af-9b0a-a7b2-cff4875012e0
* Content: [Tutorial: Microsoft Entra SSO integration with Rackspace SSO - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/rackspacesso-tutorial)
* Content Source: [docs/identity/saas-apps/rackspacesso-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/rackspacesso-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@andyorszula 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by andyorszula** [comment]
I was able to make the file acceptable in the below format. However, the mapping is not working by using the groupid. I have a ticket open with Rackspace to look into the issue and I will report back here the resolution. The groupID I used for this example was randomly generated.

`---
mapping:
  rules:
    - local:
        user:
          domain: "{D}"
          email: "{D}"
          expire: "{D}"
          groups: "{D}"
          name: "{D}"
      remote:
        - multiValue: true
          path: |
              (
              if (mapping:get-attributes('http://schemas.microsoft.com/ws/2008/06/identity/claims/groups')='39accd1b-b267-4919-8749-d90b3dd7f258') then ('admin','billing:admin') else()
              )
  version: RAX-1`

**Comment by Harshita-130901** [comment]
@andyorszula
Thanks for notifying the issue, we have contacted the Rackspace Team and will get this fixed once we receive any update from the team.
#please-close
