### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by cathyethoca** [MicrosoftDocs/entra-docs#38]
Under "Back up your Microsoft Entra Connect configuration" it should be "rollback" not "role-back"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fab65962-15ad-f425-ed08-ffe652bea4da
* Version Independent ID: c8292ca0-1831-e004-3741-b2a535dbe520
* Content: [Migrate Microsoft Entra Connect to Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/migrate-azure-ad-connect-to-cloud-sync)
* Content Source: [docs/identity/hybrid/cloud-sync/migrate-azure-ad-connect-to-cloud-sync.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/migrate-azure-ad-connect-to-cloud-sync.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Naveenommi-MSFT** [comment]
@cathyethoca 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
