### ISSUE TITLE
Block/unblock users name and description are ambiguous

### ISSUE THREAD

**Issue by Moodjbow** [MicrosoftDocs/entra-docs#380]
The "Block/unblock users" section name and description are ambiguous. These imply blocking or unblocking user sign-in attempts in general. In reality, they only disable MFA per blocked user.
Proposed improvements are:
Step 1: Change the **description** from "A blocked user will not receive multifactor authentication requests. Authentication attempts for that user will be automatically denied. A user will remain blocked for 90 days from the time they are blocked." to "A blocked user will not receive multifactor authentication requests. **The user will not be challenged with multifactor authentication for 90 days from the time they are blocked**."
Step 2: Change the **section name** from "Block/unblock users" to "**Disable/enable MFA for users**". Change the description from "A blocked user will not receive multifactor authentication requests. The user will not be challenged with multifactor authentication for 90 days from the time they are blocked." to "**An MFA disabled user will not receive multifactor authentication requests for 90 days**."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84b26750-880c-8f14-1628-436293de915e
* Version Independent ID: 518b727f-79e8-b5c2-bcb3-ff4de3444c6f
* Content: [Configure Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-mfasettings#block-and-unblock-users)
* Content Source: [docs/identity/authentication/howto-mfa-mfasettings.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-mfasettings.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@Moodjbow 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@Moodjbow 
Thank you for bringing this to our attention.
I've delegated this to content author @Justinha, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@Justinha 
Could you please review add comments on this, update as appropriate.
