### ISSUE TITLE
"Microsoft Azure Windows Virtual Machine Sign-in" vs "Azure Windows VM Sign-in"

### ISSUE THREAD

**Issue by cheezewhizze** [MicrosoftDocs/entra-docs#381]
This was driving me crazy--in my  tenant, at least, the display name of  the "Azure Windows VM Sign-in" app is "Microsoft Azure Windows Virtual Machine Sign-in".  The search described above (for "VM") to find the app in enterprise applications (or in conditional access) does not work. If I click on the app in enterprise application, it THEN shows it's name as "Azure Windows VM Sign-in", but the search does not find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Log in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows#enforce-conditional-access-policies)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#label:"assigned-to-author", "product-question", "triaged"
#reassign:@MicrosoftGuyJFlo
