### ISSUE TITLE
Incorrect third-party email address

### ISSUE THREAD

**Issue by jpjeffery** [MicrosoftDocs/entra-docs#386]
Hi

This section: https://learn.microsoft.com/en-us/entra/identity/saas-apps/condeco-tutorial#configure-condeco-sso:~:text=the%20Assign%20button.-,Configure%20Condeco%20SSO,-To%20configure%20single

...includes a link to a Condeco support email address [supportna@condecosoftware.com], but that email appears to be incorrect as I immediately received an NDR after sending a message to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8780ba69-7748-5447-53e3-03e6670f0bcb
* Version Independent ID: b306bd38-6fc1-bb6c-65db-b7a99249aea0
* Content: [Tutorial: Microsoft Entra integration with Condeco - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/condeco-tutorial)
* Content Source: [docs/identity/saas-apps/condeco-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/condeco-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@jpjeffery 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Harshita-130901** [comment]
@jpjeffery 
Can you please share the accurate support team group email address or website to replace in the tutorial?

**Comment by Harshita-130901** [comment]
@jpjeffery 
Thanks for reaching out, we will contact the Condeco team for accurate support group email and get this updated.
#please-close
