### ISSUE TITLE
Lack of Instructions

### ISSUE THREAD

**Issue by iLoveInstructions** [MicrosoftDocs/entra-docs#387]
**Open the CSV file and add a line for each group member you want to import into the group. Required values are either Member object ID or User principal name. Then save the file.**
 
Does not tell you how to ascertain this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d9b26a1-e401-4d6d-f37e-cceed1c04549
* Version Independent ID: 3db7c764-4815-ee19-a229-8bad3da4a381
* Content: [Bulk upload to add or create members of a group - Microsoft Entra ID](https://learn.microsoft.com/en-gb/entra/identity/users/groups-bulk-import-members)
* Content Source: [docs/identity/users/groups-bulk-import-members.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-bulk-import-members.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@iLoveInstructions 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@iLoveInstructions 
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@barclayn 
Please review it.

**Comment by barclayn** [comment]
@iLoveInstructions thank you for your feedback. #please-close
