### ISSUE TITLE
Bug Create Microsoft Entra ID is disabled

### ISSUE THREAD

**Issue by damienbod** [MicrosoftDocs/entra-docs#389]
I try to create a new tenant and a new subscription (pay as you go) and after I enter all the details, when I open the portal, I end up in a tenant and cannot create the new tenant. What should I do? This doc does not work?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb61215-dbe7-bd17-91c1-c1af722b65cc
* Version Independent ID: 40da65bb-b522-4b6f-8954-bb2b8ad17706
* Content: [Quickstart - Access & create new tenant - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/create-new-tenant)
* Content Source: [docs/fundamentals/create-new-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/create-new-tenant.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@damienbod 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@damienbod 

To troubleshoot this issue, I recommend checking the following:

- Check if the new tenant and subscription are listed in the Azure portal. If they are not listed, then the creation process may have failed and you may need to try creating them again.
 - Make sure that you are signed in to the correct tenant in the Azure portal. If you are signed in to the wrong tenant, you may not be able to see the new tenant and subscription.
 - Check if you have the necessary permissions to create a new tenant and subscription. You may need to be a global administrator or have the appropriate permissions assigned to your account.

If you are still having trouble creating a new tenant and subscription, I recommend reaching out to [Microsoft support](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Thanks!

**Comment by damienbod** [comment]
Thanks for your answer. I was able to solve this issue, but the docs are incorrect or incomplete. The docs should mention that a new Entra ID tenant cannot be created using an existing Entra ID account unless you have the global administrator permission.

To create a new tenant using this manual you need to create a new email account which is not connected to an existing tenant. Then add the credit cards details and you can then invite the original account into the tenant.

**Comment by Naveenommi-MSFT** [comment]
@damienbod 
 We will discuss with your query to the content owner, who will review it and offer their insightful opinions. I will also follow up to ensure it gets sorted. We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
 
 #Please-close
