### ISSUE TITLE
how to remove external guest account when its not listed in org tab

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/entra-docs#39]
https://learn.microsoft.com/en-us/entra/external-id/leave-the-organization#why-cant-i-leave-an-organization
This section does not contain how to leave the external organization if its not listed ?
https://techcommunity.microsoft.com/t5/microsoft-teams/wish-to-remove-guest-account-from-ms-teams-desktop-app/m-p/862133

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b448cfd0-b673-7d04-047b-71aa62bebc27
* Version Independent ID: 75118bff-94de-c9f9-7666-d2a6f4253b11
* Content: [Leave an organization as a guest user - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/leave-the-organization#why-cant-i-leave-an-organization)
* Content Source: [docs/external-id/leave-the-organization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/leave-the-organization.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by RamanathanChinnappan-MSFT** [comment]
@robinpoulose1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @robinpoulose1 
The document you provided explains how to leave an external organization in Azure Active Directory. If the organization is not listed, it means that you are not a member of that organization and therefore do not need to leave it. If you are having trouble removing a guest account from Microsoft Teams, you can try the following steps:

1. Open Microsoft Teams and go to the Teams tab.
2. Find the team that the guest account is a member of and click on it.
3. Click on the three dots next to the guest account's name and select "Remove from team".
4. Confirm that you want to remove the guest account from the team.

If you are still having trouble, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). 

Thank you for your time and patience throughout this issue.

**Comment by ManoharLakkoju-MSFT** [comment]
@robinpoulose1 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
