### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by wdomon** [MicrosoftDocs/entra-docs#392]
Has not been updated in over 3 months, must be outdated as some of these seem fixed now

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18796183-0c8c-be38-8321-d6f0c9f467e3
* Version Independent ID: 9add98e0-9608-5452-beaf-7edb3e79a1f8
* Content: [Known issues for multitenant organizations (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/multi-tenant-organization-known-issues)
* Content Source: [docs/identity/multi-tenant-organizations/multi-tenant-organization-known-issues.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/multi-tenant-organizations/multi-tenant-organization-known-issues.md)
* Service: **entra-id**
* Sub-service: **multitenant-organizations**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@wdomon 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by rolyon** [comment]
Hi @wdomon 
Thanks for your feedback. We will be working to update this doc.
thanks

**Comment by rolyon** [comment]
Hi @wdomon 
The team made some updates to this doc. Let us know if you have any additional feedback.
https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/multi-tenant-organization-known-issues
thanks

**Comment by rolyon** [comment]
#please-close
