### ISSUE TITLE
Please check the title of the page, it seems to be missing 'Graph' in the end

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/entra-docs#394]
Hello,

please check the title of this page: "How to analyze activity logs with **Microsoft**"

It seems to be missing 'Graph' in the end. It should probably read "How to analyze activity logs with **Microsoft Graph**"

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 492a93a1-ed2f-bb28-0704-adbcc29caedd
* Version Independent ID: 492a93a1-ed2f-bb28-0704-adbcc29caedd
* Content: [How to analyze activity logs with Microsoft Graph - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/howto-analyze-activity-logs-with-microsoft-graph)
* Content Source: [docs/identity/monitoring-health/howto-analyze-activity-logs-with-microsoft-graph.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/monitoring-health/howto-analyze-activity-logs-with-microsoft-graph.md)
* Service: **entra-id**
* Sub-service: **monitoring-health**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by AjayBathini-MSFT** [comment]
@QueryCoordinator 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@QueryCoordinator 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
