### ISSUE TITLE
Outdated Instructions

### ISSUE THREAD

**Issue by Metroidude** [MicrosoftDocs/entra-docs#396]
Hi there. This page is outdated. It's still fairly easy to navigate, but the information is no longer accurate for less tech-savvy users after the "New Experience" was rolled out on the referred sites (entra.microsoft.com).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14ab965b-dc45-f450-1302-5ffe491ca129
* Version Independent ID: 0d96d50d-a349-3408-3b93-d8b084e1cbd1
* Content: [Quickstart: Create a Microsoft Entra tenant - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-create-new-tenant)
* Content Source: [docs/identity-platform/quickstart-create-new-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/quickstart-create-new-tenant.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **ryanwi**

**Comment by Naveenommi-MSFT** [comment]
@Metroidude 
Thank you for bringing this to our attention.
I've delegated this to content author @OwenRichards1, who will review it and offer their insightful opinions.
