### ISSUE TITLE
Sync My settings seems to be gone in window11 and is now backup

### ISSUE THREAD

**Issue by ewhiteway** [MicrosoftDocs/entra-docs#397]
more of what this documents talks about seems to be outdated with the current version of windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af15f989-31c5-1730-869d-66531023658b
* Version Independent ID: 72248318-2edd-8b80-5d42-45f35daba812
* Content: [Troubleshoot Enterprise State Roaming in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/enterprise-state-roaming-troubleshooting)
* Content Source: [docs/identity/devices/enterprise-state-roaming-troubleshooting.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/enterprise-state-roaming-troubleshooting.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@ewhiteway 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@ewhiteway 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
Depending on the installed build the naming might change but the feature still exists. Will look at updating in the future. Thanks!

#please-close
