### ISSUE TITLE
"Notes" section need clarification

### ISSUE THREAD

**Issue by sw-sw-sw-sw** [MicrosoftDocs/entra-docs#398]
In the section that says "How can I control these capabilities?" there is a purple note block that says "Note: Office 365 for Education users, are currently the only ones who are added to existing managed tenants even when this toggle is enabled."

It is unclear what "this toggle" refers to. 

The preceding paragraph indicates: AllowEmailVerifiedUsers, and AllowAdHocSubscriptions. So, an assumption can be made that "this toggle" refers to one or both of these controls. 

However, it is also unclear why "even when this toggle is enabled" would enable a feature that has the toggle name "allow...". 

Was it the author's intent to say "Note: Office 365 for Education users, are currently the only ones who are added to existing managed tenants even when this toggle is **DISABLED**"?

Please clarify. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06c24fd7-43ce-1445-b734-ffd28410911f
* Version Independent ID: b835d64a-a78a-95d9-11a7-8b93a23944c8
* Content: [Self-service sign up for email-verified users - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/directory-self-service-signup)
* Content Source: [docs/identity/users/directory-self-service-signup.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/directory-self-service-signup.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@sw-sw-sw-sw 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@sw-sw-sw-sw 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@barclayn 
Could you please review add comments on this, update as appropriate.
