### ISSUE TITLE
AADSTS1100001: Non-retryable error has occurred when testing an API with this tutorial

### ISSUE THREAD

**Issue by AlbertoPa** [MicrosoftDocs/entra-docs#399]
I set up a protected API with Entra ID for Customers following the documentation. The API works correctly with authenticated users, however when I try to use app permissions and test with the documented procedure in this page I receive the error:

AADSTS1100001: Non-retryable error has occurred. 

Could you please provide any insight?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b75d93ff-09bb-3582-e952-010634e796b5
* Version Independent ID: 97c83698-e80d-11e3-d2d7-53287453d29b
* Content: [Test a protected web API - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-protect-web-api-dotnet-core-test-api)
* Content Source: [docs/external-id/customers/tutorial-protect-web-api-dotnet-core-test-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-protect-web-api-dotnet-core-test-api.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @SHERMANOUKO
* Microsoft Alias: **shermanouko**

**Comment by Naveenommi-MSFT** [comment]
@AlbertoPa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@AlbertoPa 

The error message "AADSTS1100001: Non-retryable error has occurred" typically indicates that there was an issue with the authentication process. This error can occur for a variety of reasons, but it is typically related to an issue with the app registration or permissions in Azure AD.

To troubleshoot this issue, I would recommend checking the following:

Ensure that you have correctly configured the app registration and permissions in Azure AD. You can check this by verifying that the app registration has been created with the appropriate permissions and that the permissions have been granted by an administrator.

Ensure that you are using the correct app ID and secret when authenticating with the app. You can check this by verifying that the app ID and secret are correct and that they have been added to the app's configuration.

Ensure that you are using the correct endpoint when authenticating with the app. You can check this by verifying that the endpoint is correct and that it is accessible from your testing environment.

Check the Azure AD logs for more information about the error. You can access the Azure AD logs from the Azure portal by navigating to your Azure AD tenant, selecting "Logs" from the left-hand menu, and then selecting "Sign-ins" or "Audit logs".

If you have checked all of the above and are still facing issues, I would recommend reaching out to Microsoft support for further assistance. They should be able to help you troubleshoot the issue and provide guidance on any additional configurations that may be required.  https://azure.microsoft.com/en-us/support/community/. 

I hope this helps! Let me know if you have any other questions or if there is anything else I can help you with.

**Comment by AlbertoPa** [comment]
Thank you @AjayBathini-MSFT 

Does this mean you confirm the instructions in the page are working?

I am asking because I initially thought the problem was specific to my tenant, because it uses a custom claim provider. However, I can reproduce the issue also with a clean registration without custom claim provider and using the recommended settings.

**Comment by AjayBathini-MSFT** [comment]
@AlbertoPa 

Yes. So, I would recommend reaching out to Microsoft support for further assistance. They should be able to help you troubleshoot the issue and provide guidance on any additional configurations that may be required. https://azure.microsoft.com/en-us/support/community/.

**Comment by mdddev** [comment]
I recently had some trouble, too. In my case, there was a sub-code in the error, which I could look-up [here](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-troubleshoot#error-codes-reference) which helped narrowing down the root cause. I hope this is helpful.

**Comment by AlbertoPa** [comment]
Thank you @mdddev 

This pointed me in the right direction!

The issue was related to a custom claim provider, which I did not expect to be invoked when making calls to authenticate on behalf of the app. Entra calls it without distinction, based on the user flow, even if an app is authenticating as itself rather than on behalf of a user. Consequently, the custom claim provider must deal with the special case itself. 

A note in the documentation would save days of troubleshooting (this is not a product issue, really, but a documentation issue IMHO) 😄 .

**Comment by SHERMANOUKO** [comment]
Thank you for your feedback @AlbertoPa.

The test your API article is to help guide you on testing the API and whether it works that's why it doesn't go deeper into different cases and scenarios. That's why it is short and direct. It isnt meant tp teach what to consider when creating a client app that calls an API. However, there are already plans to create articles that show what top consider when creating an app that calls an API. This will include scenarios where an app is authenticating itself to call an API and the things to consider.

**Comment by AlbertoPa** [comment]
@SHERMANOUKO we have a different perspective. It is incomplete. Put a custom claim provider in the picture, and it will fail :-) This being a security product, the documentation leaves way too much to be guessed (comment not limited to this report but to the overall documentation and samples spread over several repositories).

In any case, I am closing this because I found a solution. It would be nice to improve the page with a comment that the daemon MUST configure the custom claim provider if the API is using one, otherwise, the testing daemon app will not work.
