### ISSUE TITLE
Spell check 

### ISSUE THREAD

**Issue by johnathansagarcsuci** [MicrosoftDocs/entra-docs#40]
The word "verify" in heading of the section at the anchor linked below is misspelled. 

https://learn.microsoft.com/en-us/entra/identity/hybrid/verify-sync-tool-version#verfiy-connect-sync

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfbbfe1a-7192-ae14-764e-1ccbd130545b
* Version Independent ID: 5cba21f3-9f28-ed39-3480-47a676655c6b
* Content: [Verify your version of cloud sync or connect sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/verify-sync-tool-version)
* Content Source: [docs/identity/hybrid/verify-sync-tool-version.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/verify-sync-tool-version.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by RamanathanChinnappan-MSFT** [comment]
@johnathansagarcsuci 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@johnathansagarcsuci 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

https://github.com/MicrosoftDocs/entra-docs-pr/pull/745
