### ISSUE TITLE
The description of the Prerequisites is unclear.

### ISSUE THREAD

**Issue by keijutan** [MicrosoftDocs/entra-docs#402]
[Enter feedback here]
The requirements for Prerequisites are vague and difficult to understand. 
The following is written in Prerequisites: It is unclear whether Entra ID Premium Licenses are required for environments that only use cloud users.

**For later tutorials in this series, you'll need a Microsoft Entra ID P1 or trial license for on-premises password writeback.**

On the actual setup screen, the following description is given.
**Assign a Microsoft Entra ID Premium license to anyone in the created group**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cacc043b-aeec-5deb-e60f-b11e6381b0ba
* Version Independent ID: aa2be87c-296f-b3ff-9549-4407c46746d4
* Content: [Enable Microsoft Entra self-service password reset - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/tutorial-enable-sspr)
* Content Source: [docs/identity/authentication/tutorial-enable-sspr.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/tutorial-enable-sspr.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@keijutan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@keijutan 
I'm going to assign this to the document author so they can take a look at it accordingly.

@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@keijutan thanks for raising this and sorry for delay. I revised the prerequisites and added a link for more details about SSPR licensing requirements at https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-licensing. #please-close
