### ISSUE TITLE
Please clarify group writeback support when using multiple forest scenarios

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/entra-docs#404]
The Cloud Sync Features allows environments with multiple forests as described here: https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/plan-cloud-sync-topologies#multi-forest-single-microsoft-entra-tenant

Please clarify if the new cloud sync group writeback will also work for these setups? Will you support to write back groups in multiple forests?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 793df638-faa2-8d6b-1b94-f6ac79b84368
* Version Independent ID: 40a3d7d6-8aa5-d2db-9409-c7f5fb11724d
* Content: [Microsoft Entra Cloud Sync supported topologies and scenarios - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/plan-cloud-sync-topologies#multi-forest-single-microsoft-entra-tenant)
* Content Source: [docs/identity/hybrid/cloud-sync/plan-cloud-sync-topologies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/plan-cloud-sync-topologies.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Naveenommi-MSFT** [comment]
@J-a-k-o-b 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@J-a-k-o-b 
 I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.

**Comment by J-a-k-o-b** [comment]
Hi @ManoharLakkoju-MSFT,
in the group writeback v2 docs, which are a kind of previous version of cloud sync group provisioning, is also a note about this functionality. I would expect the same here.

See: https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-group-writeback-v2#understand-limitations-of-public-preview
> Group Writeback only supports writing back groups to a single Organization Unit (OU).

**Comment by ManoharLakkoju-MSFT** [comment]
@J-a-k-o-b 
Thank you for bringing this to our attention.
I've delegated this to content author @billmath, who will review it and offer their insightful opinions.
