### ISSUE TITLE
"Entra to Workday" not "Active Directory to Workday"

### ISSUE THREAD

**Issue by treestryder** [MicrosoftDocs/entra-docs#406]
For the article about Workday to Entra, shouldn't the section "Writeback flow – from on-premises Active Directory to Workday" be about "Entra to Workday", not "Active Directory to Workday"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51ada37b-33e9-6eaf-7676-53e4f1904d82
* Version Independent ID: dd720ef1-5c71-e843-1546-1c68c9411ee6
* Content: [Tutorial: Configure Workday inbound provisioning in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/workday-inbound-cloud-only-tutorial)
* Content Source: [docs/identity/saas-apps/workday-inbound-cloud-only-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/workday-inbound-cloud-only-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @cmmdesai
* Microsoft Alias: **chmutali**

**Comment by AjayBathini-MSFT** [comment]
@treestryder 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@treestryder 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

**Comment by treestryder** [comment]
Which pull request? There are none attached to this issue. I do not see one with a name matching this issue. Looking at what is in production, and the two feature branches with changes to the document, they all still have the heading "Writeback flow – from on-premises Active Directory to Workday" with information about syncing from Active Directory to Workday. 🤷‍♂️
