### ISSUE TITLE
Incorrect issuer provided as guidance

### ISSUE THREAD

**Issue by mdddev** [MicrosoftDocs/entra-docs#408]
In your [guidance to use the OpenID provider](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-get-started?tabs=entra-admin-center#51-using-openid-connect-identity-provider:~:text=Under%20the%20Metadata%20entry%2C%20enter%20the%20following%20URL%20to%20the%20Document%20URL.%20Replace%20the%20%7BtenantId%7D%20with%20your%20Microsoft%20Entra%20tenant%20ID.) in case the function app is in another tenant (which, I guess would be then norm?), it's stated to just replace the tenant id from the template string `https://login.microsoftonline.com/{tenantId}/v2.0/.well-known/openid-configuration`

This led to my EasyAuth configuration on my function app to reject any requests. 

```text
JWT validation failed: Issuer validation failure - Expected: https://login.microsoftonline.com/TENANT_ID/v2.0; Token: https://TENANT_ID.ciamlogin.com/TENANT_ID/v2.0
```
Instead, for the metadata url I had to use `https://TENANT_NAME.ciamlogin.com/TENANT_ID/v2.0/.well-known/openid-configuration` to make it work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef99966f-e466-d7fe-3f12-8e725ac0ce85
* Version Independent ID: 827894b5-38c5-7dac-0b90-8f839996c87d
* Content: [Get started with custom claims providers (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-get-started?tabs=entra-admin-center#51-using-openid-connect-identity-provider)
* Content Source: [docs/identity-platform/custom-extension-get-started.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-get-started.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@mdddev 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@mdddev 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
