### ISSUE TITLE
"You don't current qualify for a Microsoft 365 Developer Program sandbox subscription."

### ISSUE THREAD

**Issue by etrah-etrah** [MicrosoftDocs/entra-docs#409]
I have attempted to set up a developer account on both my work and personal outlook email accounts but in both instances I receive the error "You don't current qualify for a Microsoft 365 Developer Program sandbox subscription.". With no further explanation as to why i dont qualify.

Can you please assist?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58a9537e-1377-6b90-667e-becc6d1399a0
* Version Independent ID: 96e4ee73-6da2-e2bd-2a8c-a33a01e6fbe1
* Content: [Create a free Microsoft Entra developer tenant - Microsoft Entra Verified ID](https://learn.microsoft.com/en-us/entra/verified-id/how-to-create-a-free-developer-account)
* Content Source: [docs/verified-id/how-to-create-a-free-developer-account.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/verified-id/how-to-create-a-free-developer-account.md)
* Service: **entra-verified-id**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@etrah-etrah 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@etrah-etrah 
I'm sorry to hear that you're having trouble setting up a developer account. The error message you received indicates that you may not meet the eligibility requirements for the Microsoft 365 Developer Program sandbox subscription.

To be eligible for the program, you must be a professional developer or a student who is actively enrolled in a STEM program. Additionally, you must have a Microsoft account (such as Outlook, Hotmail, or Live) that is not associated with a Microsoft 365 subscription or Azure Active Directory account.

If you meet these requirements and are still unable to sign up, you may want to try clearing your browser cache and cookies, or using a different browser or device to sign up. If the issue persists, you can contact Microsoft support for further assistance.

I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). 
I hope this helps! Let me know if you have any other questions.
