### ISSUE TITLE
Is 'disabled' duplicated on purpose?

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/entra-docs#411]
Hello,

please check if '**disabled**' is duplicated on purpose in this string: "Don’t set up single sign-on. Leave the single sign-on **disabled** option **disabled**."

Is the option really labeled as **single sign-on disabled**?

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa42942-653d-70c6-427b-c6b541652ee0
* Version Independent ID: c2156850-bc1d-c3f1-9e3b-5e3ba2e30cdc
* Content: [Microsoft Entra application proxy and Qlik Sense - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-qlik)
* Content Source: [docs/identity/app-proxy/application-proxy-qlik.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/application-proxy-qlik.md)
* Service: **entra-id**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
Thank you for catch! Updated and should be live today. #please-close
