### ISSUE TITLE
Conditional Access: Admin Portals Needed for 'Install Apps' Functionality

### ISSUE THREAD

**Issue by BikerAdmin** [MicrosoftDocs/entra-docs#412]
Greetings,

I work in education, and it is often necessary to block our student accounts from various resources.  They are frequently compromised, and are sometimes created with fraudulent applications.  To that end, we recently blocked student access to 'Microsoft Admin Portals.'  Sadly, our legitimate students are now unable to install 365 apps on their devices, and we have no idea which admin portal is needed for this functionality.  Not only that, but the 'Microsoft Admin Portals' "app" is all inclusive, so there's no way we can grant access to just the one, we have to now grant access to all.  It would be wonderful if the 'Install Apps' feature wasn't part of an admin portal.  It would also be nice to be able to block access to these portals individually, instead of the current all-or-nothing approach.

With Gratitude!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6d2ea9-04c9-d4e5-36b5-2ce7e17192e1
* Version Independent ID: eff8d31c-d3ce-f72c-22ab-53b415b221b0
* Content: [Cloud apps, actions, and authentication context in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-cloud-apps)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-cloud-apps.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-cloud-apps.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@BikerAdmin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @BikerAdmin 
Thanks for your contribution. Please add your ideas in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)
