### ISSUE TITLE
This article doesnt seem to describe how to add multiple filters to group claims

### ISSUE THREAD

**Issue by craftzneko** [MicrosoftDocs/entra-docs#414]
![image](https://github.com/MicrosoftDocs/entra-docs/assets/662108/44a3b1e1-48cf-47de-966a-6d25932fa368)
Specifically can we add multiple filters so groups that match either this OR this

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6626e5-bcb0-9abe-557b-a9cdb33cb3a6
* Version Independent ID: 147a86d5-1eec-123b-b757-efb29dbe5681
* Content: [Configure group claims for applications by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-group-claims)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-fed-group-claims.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-fed-group-claims.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@craftzneko 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@billmath 
Can you please check and add your comments on this doc update request as applicable.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
