### ISSUE TITLE
duplicate content

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/entra-docs#415]
The section: Migration between policies

is mostly already covered in the dedicated topic. I suggest it be linked to:

- https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-authentication-methods-manage
- https://aka.ms/authmethodsmigrationdoc

instead of repeating portions of it here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7212e5d4-c9ba-0ea3-0ffd-44dfbf9559f4
* Version Independent ID: 0993e970-9eee-9681-98f1-c76f7bd7dd0a
* Content: [Manage authentication methods - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-methods-manage)
* Content Source: [docs/identity/authentication/concept-authentication-methods-manage.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-methods-manage.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@Mike-Crowley 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Mike-Crowley 
Thanks for your contribution. Please add your ideas in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)

**Comment by Mike-Crowley** [comment]
No thanks.

- Mike Crowley
________________________________
