### ISSUE TITLE
How do you resolve an issue with the user not existing in the current directory?

### ISSUE THREAD

**Issue by Nick-ShortalMASC** [MicrosoftDocs/entra-docs#417]
[Enter feedback here]

My issue is the user is shown in Users in Azure.  As best I can tell the format of the CSV upload is accurate and has the appropriate headers.
Yet with each attempt it's suggesting the "User does not exist in the current directory".

Would like to know how in a hybrid local AD that is synchronizing to Azure, if there is any type of Ad attribute that could be responsible for this user somehow being seen as an Azure user but not one that can be seen by OATH, to have a token issued.
This has worked for three other users in our environment before without issue.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3580bf07-789b-a9c0-26c2-68d21eb66b70
* Version Independent ID: f61c354b-cac2-c3e2-881a-2f0540bdd8e1
* Content: [OATH tokens authentication method - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-oath-tokens#oath-hardware-tokens-preview)
* Content Source: [docs/identity/authentication/concept-authentication-oath-tokens.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-oath-tokens.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@Nick-ShortalMASC 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @Nick-ShortalMASC 
It's possible that the user is not being properly synchronized from your on-premises Active Directory to Azure AD. One possible reason for this could be that the user object in your on-premises Active Directory is missing some required attributes that are needed for synchronization to Azure AD. 

To troubleshoot this issue, you can check the Azure AD Connect sync logs to see if there are any errors or warnings related to this user object. You can also check the user object in your on-premises Active Directory to ensure that it has all the required attributes for synchronization to Azure AD. 

Regarding your question about the AD attribute that could be responsible for this issue, there are several attributes that are required for synchronization to Azure AD, such as the userPrincipalName, mail, and proxyAddresses attributes. You can check if these attributes are present and properly configured for the user object in your on-premises Active Directory. 

If you're still having issues after checking these things, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
