### ISSUE TITLE
Entra External Id self-service registration results in "AADSTS131010"

### ISSUE THREAD

**Issue by behrad-techtiq** [MicrosoftDocs/entra-docs#419]
Having Entra External Identity for customers, fails when creating a new user "self-service registration" with following error : 
Entra External Id self-service registration results in "AADSTS131010: User not allowed by policy conditions." 

Although the user has been created inside the directory and able to login in another seasson but when user creates account and as a result of successful signup, redirects back to the application (tested in python, .NET and NextJS) resulting on above error.

Currently there are few open issues that other users have same problem : 

https://learn.microsoft.com/en-us/answers/questions/1527355/entra-external-id-self-service-registration-result?page=0&orderby=Helpful#answers

https://stackoverflow.com/questions/77863677/user-not-allowed-by-policy-conditions-entra-external-id-for-customers

the solution suggested on above link is irreverent as that page only for Entra ID for workforce and not external ID for customers, such page doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c05d9cd-275d-4585-f25f-fa5b88f1ec10
* Version Independent ID: a3d263e6-20a6-9cea-f60c-a9f772a7f444
* Content: [Add a self-service sign-up user flow - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/self-service-sign-up-user-flow)
* Content Source: [docs/external-id/self-service-sign-up-user-flow.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/self-service-sign-up-user-flow.md)
* Service: **entra-external-id**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@behrad-techtiq 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by KasperiP** [comment]
@msmimart any updates? This issue appears to be plaguing many individuals, and there seems to be no answer available anywhere as of yet.

https://stackoverflow.com/questions/77863677/user-not-allowed-by-policy-conditions-entra-external-id-for-customers

https://learn.microsoft.com/en-us/answers/questions/1527355/entra-external-id-self-service-registration-result

https://techcommunity.microsoft.com/t5/microsoft-entra/entra-customers-msalserviceexception-aadsts131010-user-not/m-p/3987421

https://github.com/Azure-Samples/ms-identity-ciam-javascript-tutorial/issues/64

**Comment by msmimart** [comment]
@KasperiP thank you for pointing this out. You're right that the doc referenced above is for a workforce/B2B collaboration scenario. The customer sign-up user flow content can be found in the [external/customer scenario docs](https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam) here: https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-user-flow-sign-up-sign-in-customers. We can start there, and meanwhile we'll look into the issue further.

**Comment by behrad-techtiq** [comment]
Hi @

**Comment by msmimart** [comment]
Hi @behrad-techtiq, agreed; I'm checking into this further and will let you know what I find out.

**Comment by KasperiP** [comment]
Still not directly related to documentation, but I thought sharing this might be helpful:

An error occurs during the authentication flow. When your user creates an account on `/oauth2/v2.0/authorize`, the accounts are created. Then the user is redirected to the callback URL with the `?code` parameter. However, if you try to exchange the code for an access token via `/oauth2/v2.0/token`, it won't work, and you will encounter the mentioned error (AADSTS131010). However, if you authorize again with all the same parameters, the code will work.

So, it seems to me that there is indeed a bug in the system. The first code after login should be exchangeable for an access token via `/oauth2/v2.0/token`. 🤔

**Comment by mcle0463** [comment]
also seeing this problem as an early adopter of the External ID solution. Doesnt exactly instill confidence seeing this in a standard susi flow.

**Comment by mcle0463** [comment]
Does ms have any documentation (code or otherwise) that can tell us under what conditions the error 'AADSTS131010: User not allowed by policy conditions.' can happen. If its a simple configuration issue we could probably figure it out ourselves but thats pretty difficult without some context to the error.

**Comment by KasperiP** [comment]
I have opened an Azure support ticket regarding this issue, and it's currently under internal investigation. So hopefully, it will either be fixed soon or more information will be provided about the current behavior. I will update the findings here anyway when I receive any new information 🕵️

**Comment by KasperiP** [comment]
Got response:
> Upon receiving the response from our internal team, we have been indicated that this is a known issue which is being worked on by our PG Team. 
 
The fix for this issue is already underway with an ETA for April 19th.

**Comment by behrad-techtiq** [comment]
Fantastic 
Finally some updates 😊

**Comment by msmimart** [comment]
@KasperiP thanks so much for updating this thread with your findings! I'm hearing the same 👍

**Comment by msmimart** [comment]
#please-close
