### ISSUE TITLE
Need to add the PowerShell way to get the data 

### ISSUE THREAD

**Issue by Visinghr** [MicrosoftDocs/entra-docs#420]
Customer who are request this data are mostly from the Admin team and familar with the PowerShell. 
It will be better if we had the information about PowerShell Command also to fetch the information, that will be great deflection of support case.

**Comment by Naveenommi-MSFT** [comment]
@Visinghr 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!
