### ISSUE TITLE
Please clarify: Passwordless using any of the supported Microsoft Entra credentials (recommended)

### ISSUE THREAD

**Issue by bkgh** [MicrosoftDocs/entra-docs#422]
What does this mean, please: Passwordless using any of the supported Microsoft Entra credentials (recommended)
Does this mean only passwordless auth methods, or all Entra auth methods?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Log in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@bkgh 
Thanks for your feedback! We will investigate and update as appropriate.
