### ISSUE TITLE
User Permissions not available in custom roles yet

### ISSUE THREAD

**Issue by danielmarker** [MicrosoftDocs/entra-docs#423]
Please can a header / banner be added to these pages as the option to add user permission roles via a Custom Role in Entra ID is NOT supported currently - and an error is raised when Cx tries to implement this.

New-MgRoleManagementDirectoryRoleDefinition_CreateExpanded: Action 'microsoft.directory/policies/standard/read' is not supported for Custom Role creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9661198d-b7ad-f939-637b-5a879b50e5a2
* Version Independent ID: 8a286ca6-982f-cfd7-77ce-ad2cb1fa325d
* Content: [User management permissions for Microsoft Entra custom roles - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-user-permissions)
* Content Source: [docs/identity/role-based-access-control/custom-user-permissions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/custom-user-permissions.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment]
@danielmarker 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@rolyon
Could you Please review this and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@danielmarker 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by rolyon** [comment]
Hi @danielmarker
Thanks for your feedback. I'll contact you separately to review your feedback.
thanks

**Comment by rolyon** [comment]
#please-close
