### ISSUE TITLE
How to remove "Additional resources" from the view.

### ISSUE THREAD

**Issue by LioDiera** [MicrosoftDocs/entra-docs#424]
I do not like how compact the reading material is while on a laptop, if we could just get rid of the additional resources section/pane it would make the reading experience improve on Surface Pro 9 or other smaller windows OS devices. 

![2024-02-22 07_15_19-](https://github.com/MicrosoftDocs/entra-docs/assets/40646041/08a628b9-c28f-4166-bb89-04d2946b4c54)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b5b4ad9-f729-c381-3a69-8aa0daf0b89f
* Version Independent ID: ef468de3-24e5-52be-1984-b5ab4361b331
* Content: [What are Microsoft Entra registered devices? - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/concept-device-registration)
* Content Source: [docs/identity/devices/concept-device-registration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/concept-device-registration.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@LioDiera 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by merill** [comment]
@LioDiera until there is an out of the box solution, I created a chrome extension to help with those of us on small screens. https://microsoftedge.microsoft.com/addons/detail/refined-microsoft-learn/ohjiccikicdhcdlophelgjppakkdlfmg

**Comment by LioDiera** [comment]
Thank you will give this a shot!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Naveenommi-MSFT** [comment]
@LioDiera 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
