### ISSUE TITLE
Authentication policies information

### ISSUE THREAD

**Issue by chi3f10** [MicrosoftDocs/entra-docs#425]
Hi Team,

The current version of the https://learn.microsoft.com/en-us/entra/identity/saas-apps/atlassian-cloud-tutorial doesn't seem to include any information about Authentication Policies. Documentation: 
- https://support.atlassian.com/security-and-access-policies/docs/understand-authentication-policies/
- https://support.atlassian.com/security-and-access-policies/docs/edit-authentication-settings-and-members/

Back in 2021, this information was added to the documentation: https://github.com/MicrosoftDocs/azure-docs/issues/76744#issuecomment-858717827, but it seems maybe due to recent changes to the documentation site - the information regarding authentication policies was left out on the current version of the mentioned page.

For SAML logins to work with Atlassian accounts, the end user's Atlassian account must be a member of an Authentication Policy where "Enforced SSO" is enabled. Otherwise, the end user won't be able to log in via SAML and IdP-init. auth. would result in the user being blocked from being able to log in to their Atlassian account.

If possible, please also include a banner stating the following(or similar):
> We **strongly** recommend that you test single sign-on with a few non-org. admin test members first to make sure the SAML configuration is working and to avoid locking out the org. admin(s). Documentation: https://support.atlassian.com/security-and-access-policies/docs/understand-authentication-policies/#Testing-your-authentication-settings

Mentioning this in case it is helpful, regarding: https://learn.microsoft.com/en-us/entra/identity/saas-apps/atlassian-cloud-tutorial#create-atlassian-cloud-test-user - it is not actually necessary to create a Cloud site account for testing a SAML login. Mentioning this because not all Atlassian customers will have a Jira Cloud site to test with - they may have other products such as Trello and Bitbucket. In most cases, it's possible for a test user to navigate to https://id.atlassian.com and test the SAML login flow from there.

Thanks,
Derrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb39c8bf-2709-c59d-94f8-6db76d21bcfb
* Version Independent ID: f7122c2c-ef68-95b6-2273-edbc4bb89464
* Content: [Tutorial: Microsoft Entra SSO integration with Atlassian Cloud - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/atlassian-cloud-tutorial#configure-azure-ad-sso)
* Content Source: [docs/identity/saas-apps/atlassian-cloud-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/atlassian-cloud-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@chi3f10 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@jeevansd
Can you please check and add your comments on this doc update request as applicable.

**Comment by v-hgampala** [comment]
Updating the document with Authentication policies info, you can expect the updated article within 2-3 business days.
#please-close
