### ISSUE TITLE
Multi-Tenant Licensing information for M365 apps missing, like SharePoint, Teams,...

### ISSUE THREAD

**Issue by andikrueger** [MicrosoftDocs/entra-docs#426]
the current documentation lacks information about the licensing model for B2B Guest users of type "Member". ASFAIK, there is no need for additional licensing in the M365 areas like SharePoint, Teams for users of type "Guest". How does this change in terms of multi tenant orgs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df552597-54a7-50e4-55b3-4cd0f0a91977
* Version Independent ID: a7b0a42e-c1a8-58f4-28c0-8a9e2b7e2a99
* Content: [Multitenant organization scenario and Microsoft Entra capabilities - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/overview?toc=%2Fentra%2Fexternal-id%2Ftoc.json&bc=%2Fentra%2Fexternal-id%2Fbreadcrumb%2Ftoc.json)
* Content Source: [docs/identity/multi-tenant-organizations/overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/multi-tenant-organizations/overview.md)
* Service: **entra-id**
* Sub-service: **multitenant-organizations**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@andikrueger 
Here is the licensing information, we currently have for MTO
https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/multi-tenant-organization-overview#license-requirements

if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by andikrueger** [comment]
@AjayBathini-MSFT thank you for the link. This is already  helpful in our discussions. 
Furthermore we need information about the licensing of B2B users as UserType=‘member’ in SharePoint Online, Teams and other services. This is the major point of our uncertainty. Do they need to be fully licensed?

**Comment by AjayBathini-MSFT** [comment]
@andikrueger 
I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by rolyon** [comment]
Hi @andikrueger
Thanks for your feedback. We provided your feedback to the Microsoft 365 team since they are better equipped to respond to your question.
thanks

**Comment by andikrueger** [comment]
@rolyon Do you have an update on this ask?

**Comment by rolyon** [comment]
Hi @andikrueger 
Thanks for your patience. I dont have an update at this time. I sent a reminder to the team about your feedback.
thanks

**Comment by rolyon** [comment]
Hi @andikrueger 
Thanks for your patience. The Microsoft 365 team has updated license information here:
https://learn.microsoft.com/en-us/microsoft-365/enterprise/plan-multi-tenant-org-overview#license-requirements
Let us know you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
