### ISSUE TITLE
Can I use an Azure B2C-associated Entra ID Tenant to verify and issue VCs?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/entra-docs#427]
When you create an Azure AD B2C resource, it comes with an Entra ID instance. You can see this when from the Home page you search for Entra ID (be sure your selected directory remains the Azure B2C directory). In This Entra ID instance, I can add a custom domain. Then I can go to Security => Verified ID and setup Verified ID with the Quick setup. It is not looking any different (so far) from using a regular Entra ID tenant. Is it then correct to say that we can use this B2C-associated Entra ID as a VC issuer and Verifier?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f84b158e-eebc-7d96-0992-8864316ddf5c
* Version Independent ID: 8909ba9b-bf26-fb5c-29f0-76244984e75a
* Content: [Tutorial - Advanced Microsoft Entra Verified ID setup - Microsoft Entra Verified ID](https://learn.microsoft.com/en-us/entra/verified-id/verifiable-credentials-configure-tenant)
* Content Source: [docs/verified-id/verifiable-credentials-configure-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/verified-id/verifiable-credentials-configure-tenant.md)
* Service: **entra-verified-id**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@SB-o-matic 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SB-o-matic** [comment]
Any answers?

**Comment by ManoharLakkoju-MSFT** [comment]
@SB-o-matic 
Yes, that is correct. When you create an Azure AD B2C resource, it comes with an Entra ID instance. You can use this Entra ID instance as a VC issuer and verifier. You can add a custom domain to this Entra ID instance and set up Verified ID with the Quick setup. Once you have set up Verified ID, you can use it to issue and verify verifiable credentials.

**Comment by SB-o-matic** [comment]
Wonderful!! Thank you very much!
