### ISSUE TITLE
Fix minor spelling issue

### ISSUE THREAD

**Issue by FurenaOCGUS** [MicrosoftDocs/entra-docs#428]
Minor spelling: Prerequisites section, 5th bullet point reads:

**Mircorosft** Entra Connect with build version...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba290a8-7b6e-a859-4f4d-70ea2d035424
* Version Independent ID: 1ba290a8-7b6e-a859-4f4d-70ea2d035424
* Content: [Provision groups to Active Directory using Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@FurenaOCGUS 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@FurenaOCGUS 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
