### ISSUE TITLE
Lockout Threshold for Failed Attempts

### ISSUE THREAD

**Issue by git-msy** [MicrosoftDocs/entra-docs#429]
According to the "Manage Microsoft Entra smart lockout values", bullet 3, it states that the lockout against the source IP occurs after 10 failed attempts on "AN" (emphasis mine) account (or 3 for Azure US Govt). Doc: https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-smart-lockout

Does this indicate 10 failures against ONE account?

The reason I'm asking is because in the SANS SEC504 on-demand course by Joshua Wright, both the course notes and instructor in the video say that it's 10 failures in TOTAL across 1 or multiple accounts to thwart password spray attacks. However, on the same course slide, it does say "Account lockout following multiple login failures for ONE account" (emphasis mine).

Wanted to confirm and clarify the Microsoft documentation on whether the lockout is triggered for 10 failures against ONE account, or 10 collective fails across any collection of usernames?

In my own testing against a live environment whose settings are the defaults (Threshold: 10, Duration: 60, Custom Password Ban: No, Enable AD protection: Yes, Mode: Audit), I found the following:
1. Ten failures across 1 account: lockout activated
2. 20 failures across 7 accounts: my IP never got locked

The test confirms that the lock occurs for 10 attempts on ONE account and not what the SANS instructor (in the video and book notes) says. The course SLIDE does say "failures for one account".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7b90ca-a2b1-9cd8-9769-cd48c27f10ea
* Version Independent ID: b8c29389-c435-b2f0-4186-1e9c47ab4f3e
* Content: [Prevent attacks using smart lockout - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-smart-lockout)
* Content Source: [docs/identity/authentication/howto-password-smart-lockout.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-password-smart-lockout.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@git-msy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by git-msy** [comment]
Got feedback from the instructor and he clarified that he meant:

"- Account lockout: Blocks account following multiple login failures for one account" (this addresses Password Guessing)
"- Smart lockout: Blocks IP address source following 10 unsuccessful login attempts [across one or multiple accounts] (3 for Azure US .gov)" (this addresses Password Spraying)

In Microsoft's documentation, it needs more clarification as it currently states under "Manage Microsoft Entra smart lockout values", bullet #3: "Set the Lockout threshold, based on how many failed sign-ins are allowed on AN account" (emphasis mine). It says "AN" and seemingly indicates failures against just 1 account (same as "Account Lockout" above and not what "Smart Lockout" seems to want to address)

**Comment by SaibabaBalapur-MSFT** [comment]
@git-msy 
I'm going to assign this to the document author so they can take a look at it accordingly.

@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@git-msy @SaibabaBalapur-MSFT Sorry for delay. A SME here says "No, the current documentation is accurate. I'm not sure which course instructor claim smart lockout block IP address with 10 unsuccessful sign-in. Smart lockout is account level lockout, not IP address level."
