### ISSUE TITLE
Dynamic User Group to include users with a Microsoft 365 E3 License.

### ISSUE THREAD

**Issue by michaelfromslc** [MicrosoftDocs/entra-docs#432]
I am having trouble finding the resources needed to learn how to create a Syntax Rule for a Dynamic user group that will only include users who have been give the Microsoft 365 E3 License. I have located the GUID for the License but that is about all I can do. Even Copilot is not use full as it only produces rule that have a invalid object error. 

Can we get a Syntax example added that I can use to create a Rule that applies to Specific Microsoft 365 Licenses?

The Broken rule that Copilot keeps spitting out is: (user.assignedLicenses -any (assignedLicense: assignedLicense.skuId -eq "05e9a617-0261-4cee-bb44-138d3ef5d965"))

Any help is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7a4070-1be8-5f1f-0092-68fb6b9e2305
* Version Independent ID: cd34312f-b507-affe-555e-1e0c63e7d494
* Content: [Rules for dynamically populated groups membership - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-membership#rules-with-complex-expressions)
* Content Source: [docs/identity/users/groups-dynamic-membership.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-dynamic-membership.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@michaelfromslc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@michaelfromslc 
Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
