### ISSUE TITLE
Phone login is not supported

### ISSUE THREAD

**Issue by rbrayb** [MicrosoftDocs/entra-docs#433]
This article is about "Microsoft Entra ID for customers tenant".

This sentence below is incorrect:

"For example, you can configure a user flow that requires users to sign-in or sign-up with a phone number or email address."

You cannot sign-in or sign-up with a phone number in a customer tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e84fb9a-837d-46fb-cb96-6231c9bb7552
* Version Independent ID: 04010d26-967a-f3c0-011f-21c7dd3d6254
* Content: [Tutorial: Prepare your customer tenant to authenticate users in a .NET browserless app - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-browserless-app-dotnet-sign-in-prepare-tenant)
* Content Source: [docs/external-id/customers/tutorial-browserless-app-dotnet-sign-in-prepare-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-browserless-app-dotnet-sign-in-prepare-tenant.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @SHERMANOUKO
* Microsoft Alias: **shermanouko**

**Comment by ManoharLakkoju-MSFT** [comment]
@rbrayb 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
