### ISSUE TITLE
How can we build a scoping filter based on date?

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/entra-docs#438]
Is there a possibility to build a scoping filter and relate it to current or future dates?
In my case, I would like to delete users from AD after 14 days from their lastTerminationDate from SuccessFactors

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a77e752-0785-c3bd-9b33-f37bb7af6acd
* Version Independent ID: d865098d-299a-ddeb-6eed-9a1db3175de3
* Content: [Scoping users or groups to be provisioned with scoping filters in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/define-conditional-rules-for-provisioning-user-accounts?pivots=app-provisioning)
* Content Source: [docs/identity/app-provisioning/define-conditional-rules-for-provisioning-user-accounts.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/define-conditional-rules-for-provisioning-user-accounts.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by RamanathanChinnappan-MSFT** [comment]
@Michal-Ziemba 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Michal-Ziemba 
Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
