### ISSUE TITLE
Confirm if Typo in Troubleshooting instructions

### ISSUE THREAD

**Issue by nilesh-ava** [MicrosoftDocs/entra-docs#440]
[Article:Microsoft Entra device management FAQ](https://learn.microsoft.com/en-us/entra/identity/devices/faq#i-disabled-or-deleted-my-device--but-the-local-state-on-the-device-says-it-s-still-registered--what-should-i-do) 
The section for "_I disabled or deleted my device, but the local state on the device says it's still registered. What should I do?_" seems to have a typo where the first part suggests "_To re-register Microsoft **Entra joined** Windows 10/11 and Windows Server 2016/2019 devices, take the following steps:_" 
Where as I believe it should be for a **Hybrid Device** instead. Please confirm and rectify. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa632bd8-9300-c9fa-11fc-0c4be6862c6e
* Version Independent ID: d0d3cf71-5945-c202-d466-12c3da3fb473
* Content: [Microsoft Entra device management FAQ - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/faq#i-disabled-or-deleted-my-device--but-the-local-state-on-the-device-says-it-s-still-registered--what-should-i-do)
* Content Source: [docs/identity/devices/faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/faq.yml)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by RamanathanChinnappan-MSFT** [comment]
@nilesh-ava 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@nilesh-ava 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@MicrosoftGuyJFlo
Can you please check and add your comments on this doc update request as applicable.

**Comment by MicrosoftGuyJFlo** [comment]
Resolving in a PR I am working on in the private repo. Should publish later today. Thanks!
