### ISSUE TITLE
License SKUs missing from documentation

### ISSUE THREAD

**Issue by JLambEJG** [MicrosoftDocs/entra-docs#442]
These SKUs are missing. Please add them:

OFFICEBASIC
Microsoft_Teams_Calling_Plan_pay_as_you_go_(country_zone_1_US)
MCOPSTN_6 
Dynamics_365_Guides_vTrial
Microsoft_Defender_for_Endpoint_F2

When added to this page, will this CSV also receive an update?
https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv

We rely on it for automations

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by RamanathanChinnappan-MSFT** [comment]
@JLambEJG 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@JLambEJG 
Thank you for bringing this to our attention.
I've delegated this to content author @Nicholak-MS, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@Nicholak-MS 
Could you please review add comments on this, update as appropriate.

**Comment by Nicholak-MS** [comment]
Hi @JLambEJG I have inserted the above 5 SKUs into the online table and the downloadable SV. The changes will publish later today and be available in the online table and the downloadable CSV. thank you for bringing this to our attention. 

Thanks
Nick

#please-close
