### ISSUE TITLE
Cannot find type [Microsoft.Open.MSGraph.Model.InvitedUserMessageInfo]

### ISSUE THREAD

**Issue by soloplanWK** [MicrosoftDocs/entra-docs#443]
Hello  everyone,
I try to follow the tutorial 
[Tutorial: Use PowerShell to bulk invite Microsoft Entra B2B collaboration users](https://learn.microsoft.com/en-us/entra/external-id/bulk-invite-powershell)

- I'm using Powershell 7 on Windows 10
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

- The module `Microsoft.Graph` was installed like described
```powershell
Get-InstalledModule Microsoft.Graph

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.15.0               Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module
```

- I was also able to connect to the tennant `Connect-MgGraph -TenantId "aaa-bbb-ccc-ddd-eee` (my real id is a different one, of course)

When I try to create a new Object 
```powershell
$messageInfo = New-Object Microsoft.Open.MSGraph.Model.InvitedUserMessageInfo
```
I get the error
```
New-Object: Cannot find type [Microsoft.Open.MSGraph.Model.InvitedUserMessageInfo]: verify that the assembly containing this type is loaded.
```

I already found [InvitedUserMessageInfo - cannot find type #59466 ](https://github.com/MicrosoftDocs/azure-docs/issues/59466), but it was closed without any solution.

Can you help? Thank you.

**Comment by RamanathanChinnappan-MSFT** [comment]
@soloplanWK 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @soloplanWK 
After installing the PowerShell and MSGraph modules, you'll need to sign in to your tenant using PowerShell. Then, to send invitations, execute the following PowerShell script, replacing "c:\bulkinvite\invitations.csv" with the path to your CSV file containing the invitations.

Please refer it below once.
https://learn.microsoft.com/en-us/entra/external-id/bulk-invite-powershell#:~:text=a%20new%20line.-,Sign%20in%20to%20your%20tenant,You%20should%20see%20output%20similar%20to%20the%20following%20for%20each%20user%3A,-Verify%20users%20exist

**Comment by soloplanWK** [comment]
Hi @Naveenommi-MSFT, 
thanks for your reply.

> After installing the PowerShell and MSGraph modules, you'll need to sign in to your tenant using PowerShell. 

What do you mean? 
Is this call
`Connect-MgGraph -TenantId "aaa-bbb-ccc-ddd-eee"`
not signing in?

If not, how exactly do I have do sigh in?

Thank you.

**Comment by Naveenommi-MSFT** [comment]
@soloplanWK 
I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows. [Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by soloplanWK** [comment]
@Naveenommi-MSFT 
In my opinion the documentation is not complete. I just tried to replay exactly the steps from your tutorial and it doesn't work.
Anyway, I'll try to find help somewhere else.
