### ISSUE TITLE
Typo in Time-bassed

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#445]
In this section https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-session-lifetime#require-reauthentication-every-time

it says "we recommend using [time-bassed user sign-in frequency](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-session-lifetime#user-sign-in-frequency)"

It should be "time-based"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae35742-79e9-237a-e77e-8d52e9ea17c8
* Version Independent ID: 4ae35742-79e9-237a-e77e-8d52e9ea17c8
* Content: [Conditional Access adaptive session lifetime policies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-session-lifetime#require-reauthentication-every-time)
* Content Source: [docs/identity/conditional-access/concept-session-lifetime.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-session-lifetime.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by RamanathanChinnappan-MSFT** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@dloder0 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
