### ISSUE TITLE
 "AttributeCollectionStart " and "AttributeCollectionSubmit", not supported in Entra Workforce Tenants

### ISSUE THREAD

**Issue by jasonfritts** [MicrosoftDocs/entra-docs#447]
I suggest updating pre-requisites section of this article to indicate that a Entra External ID for Customers tenant is required, and call out that an Entra Workforce tenant is not supported.

This article assumes you realize that an Entra External ID for Customers tenant type exists, and that you already have one. 

Making things more confusing is that the Menu blade referenced in "Step 2: Create and register a custom authentication extension" does exist in a Entra Workforce tenant, it just doesnt have the options described in this article "AttributeCollectionStart " or "AttributeCollectionSubmit".  Only the "TokenIssuanceStart" event type.

To prevent future confusion, I'd suggest updating article to make it very clear that these options are only available in Entra External ID for Customer tenants.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00b5cb48-d4b9-4baa-3aa2-0c9d096db9fb
* Version Independent ID: 00b5cb48-d4b9-4baa-3aa2-0c9d096db9fb
* Content: [Create attribute collection events (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-attribute-collection?tabs=start-set-prefill-values%2Csubmit-continue#step-2-create-and-register-a-custom-authentication-extension)
* Content Source: [docs/identity-platform/custom-extension-attribute-collection.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-attribute-collection.md)
* Service: **identity-platform**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jasonfritts 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msmimart** [comment]
Hi @jasonfritts, thanks so much for this feedback. We're currently revising this article and related custom auth extension docs to clarify the prerequisites. Right now we include the "Applies to: Microsoft Entra External ID customer configurations" statement, but we're looking at ways to make this more prominent throughout. @cilwerner, fyi

**Comment by Naveenommi-MSFT** [comment]
@jasonfritts 
Thank you for bringing this to our attention.
I've delegated this to content author @msmimart, who will review it and offer their insightful opinions.

**Comment by msmimart** [comment]
Updates noted in earlier comments are in progress. Thanks again for the feedback! #please-close
