### ISSUE TITLE
Fix issues in tutorial Vanilla Javascript SPA

### ISSUE THREAD

**Issue by igor-h** [MicrosoftDocs/entra-docs#449]
[Enter feedback here]

Raised Pull Request in official documentation:
https://github.com/MicrosoftDocs/entra-docs/pull/448
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14b15ab4-e5da-3566-e36e-5c7c1f0e7a73
* Version Independent ID: 18543aad-fbb7-78ea-b49a-3a08b75d75cc
* Content: [Tutorial - Handle authentication flows in a Vanilla JavaScript single-page app - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-vanillajs-configure-authentication)
* Content Source: [docs/external-id/customers/tutorial-single-page-app-vanillajs-configure-authentication.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-single-page-app-vanillajs-configure-authentication.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by igor-h** [comment]
@OwenRichards1

**Comment by RamanathanChinnappan-MSFT** [comment]
@igor-h 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by igor-h** [comment]
@RamanathanChinnappan-MSFT 
No need to investigate much, I create a fix in this Pull request 👍🏽 
Have a look here:
https://github.com/MicrosoftDocs/entra-docs/pull/448

**Comment by ManoharLakkoju-MSFT** [comment]
@igor-h 
Thank you for pointing this out! and creating a PR for this issue, currently waiting for the author to review and sign off.
I will now close out this issue. Please allow some time for the author to review and the changes to reflect.
