### ISSUE TITLE
This documentation needs improvement.  

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/entra-docs#451]
Because the user interface for Administrative Units is so limited, this documentation needs to be improved.  My questions (which should be answered in this document) are:

1. How do I easily tell which roles under administrative unit/Roles and Administrators are aligned with my admin unit?  I see a list with a bunch of numerical indicators of how many assignments each one has.  Am I supposed to understand from that what role/group is tied to my administrative unit?
2. Why, when there's a UI, is the documentation for PowerShell/graphAPI better than the docs for the UI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee59fc3-8f8f-cecc-47c3-3e1c12248942
* Version Independent ID: 45f956e0-d4ea-42cd-6e1c-0fd8dab34834
* Content: [Assign or list Microsoft Entra roles with administrative unit scope - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/admin-units-assign-roles)
* Content Source: [docs/identity/role-based-access-control/admin-units-assign-roles.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/admin-units-assign-roles.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by ManoharLakkoju-MSFT** [comment]
@CJRicard 
Thanks for your feedback! We will investigate and update as appropriate.
