### ISSUE TITLE
The guide is a bit confusing, could you please clarify?

### ISSUE THREAD

**Issue by oistein-git** [MicrosoftDocs/entra-docs#452]
Step 1 - Copy adminDescription to msDS-ExternalDirectoryObjectID
Is this something you have to do on all existing group writeback V2 groups?
The guide doesn't specify which groups you do it on.

Step 3 - Create a custom group inbound rule
"Connected System: Choose the AD connector that you're writing the custom sync rule for"
But the image show contososocorp.onmicrosoft.com - isn't that the Entra/AAD connector?

Step 4 - Create a custom group outbound rule
"Connected System: Choose the Microsoft Entra connector that you're writing the custom sync rule for"
But the image show contoso.com - isn't that the AD connector?
I assume that is the local AD domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1da65039-05e7-474c-ee47-b1e62acb64b7
* Version Independent ID: 1da65039-05e7-474c-ee47-b1e62acb64b7
* Content: [Migrate Microsoft Entra Connect Sync group writeback V2 to Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/migrate-group-writeback)
* Content Source: [docs/identity/hybrid/cloud-sync/migrate-group-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/migrate-group-writeback.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@oistein-git 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@oistein-git 
I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by oistein-git** [comment]
Thank you for your suggestions, that would probably help me out. However, I am hoping the article itself can be improved so that others can be helped as well.

**Comment by SaibabaBalapur-MSFT** [comment]
@oistein-git 
We'll be concluding this thread for now. However, if you have any more questions about the documentation, feel free to mention me in your response, and I'll be glad to assist you further.
