### ISSUE TITLE
Feedback about "Proxy configuration example" section of Global Secure Access Client for Windows (preview) KB having missing information

### ISSUE THREAD

**Issue by rboshmaf** [MicrosoftDocs/entra-docs#454]
The reason for me to reach out is due to the fact that I work as CSE a a customer did reach out and opened a case proving feedback that the document seems to be missing information and is due to this things are vague for him and not clear.

This is related to "Proxy configuration example" section of Global Secure Access Client for Windows (preview) article. 

---
We mention the following:
 
<img width="850" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/112098981/cff0d2c8-50c6-4680-8be8-c6b2db1eb844">

In the paragraph  "Organizations must then create a system variable named grpc_proxy with a value like http://10.1.0.10:8080/ that matches your proxy server's configuration on end-user machines to allow the Global Secure Access Client services to use the proxy **by configuring the following.**" so it say **by configuring the following** but we don't list the example and mention anything after **following** as if there should be an example showing how to setup this but it is missing, hence you don't have clarity of what needs to be done.
 
I assume the following is what needs to be done and is missing for the document, is this correct?

<img width="575" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/112098981/6aac4b77-77e7-449d-93d9-ae6ce9c7e50f">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44c5e5d2-9999-6e26-1a24-a675b878e08a
* Version Independent ID: 329a1508-45db-8062-d753-9b9f86629063
* Content: [The Global Secure Access Client for Windows (preview) - Global Secure Access](https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-install-windows-client#proxy-configuration-example)
* Content Source: [docs/global-secure-access/how-to-install-windows-client.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/global-secure-access/how-to-install-windows-client.md)
* Service: **global-secure-access**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SaibabaBalapur-MSFT** [comment]
@rboshmaf 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by kenwith** [comment]
Discussing in email with product team. I will make updates based on that discussion. #please-close
