### ISSUE TITLE
Not able to connect with cmd "Connect-MgGraph -Environment China" in Azure China

### ISSUE THREAD

**Issue by alexchen2016** [MicrosoftDocs/entra-docs#457]
Hi team,

Our customers found they are not able to connect to a tenant with command "Connect-MgGraph -TenantId "<YOUR_TENANT_ID>" -Environment China" in section "Sign in to your tenant" in this article.  Can you help to confirm whether "Connect-MgGraph -Environment China" can be used in Azure China or not?  

If yes, do Azure China users need some other steps before using "Connect-MgGraph", such as creating certificates? Please provide detailed information in the article.

If it's not available, can you add some words in the article to suggest Azure China users still using "Connect-AzureAD" and providing detailed steps?  The same issue happened in https://learn.microsoft.com/en-us/entra/external-id/bulk-invite-powershell and some other articles. Thanks.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/13617729/0eb97777-e1d1-42c6-a5c9-6f2f068c3431)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/13617729/9d828d14-b2cc-4372-8fe3-3afa9fb42acb)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7ea676e-0678-9e2d-e009-fb44587f93dd
* Version Independent ID: 40b581da-26ea-2890-4a78-54b29f5dc610
* Content: [Quickstart: Add a guest user with PowerShell - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/b2b-quickstart-invite-powershell)
* Content Source: [docs/external-id/b2b-quickstart-invite-powershell.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/b2b-quickstart-invite-powershell.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by RamanathanChinnappan-MSFT** [comment]
@alexchen2016 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@alexchen2016 
Thank you for bringing this to our attention.
I've delegated this to content author @csmulligan, who will review it and offer their insightful opinions.

**Comment by alexchen2016** [comment]
@csmulligan, Any update?

**Comment by alexchen2016** [comment]
@ManoharLakkoju-MSFT, @csmulligan , Any reply?

**Comment by alexchen2016** [comment]
@csmulligan, Any update?

**Comment by SteveMutungi254** [comment]
@timayabi2020, kindly assist.

cc: @csmulligan.

**Comment by alexchen2016** [comment]
@timayabi2020, Can you help with this?

**Comment by alexchen2016** [comment]
Hi @timayabi2020, Any reply? Thanks

**Comment by alexchen2016** [comment]
@SteveMutungi254, @timayabi2020, Any update?

**Comment by timayabi2020** [comment]
@alexchen2016 you will need to configure tenant Id, client Id and client secret or certificate. Also ensure that the application registration is done in the Microsoft Entra admin center that corresponds to China national cloud. For more information, please refer to the prerequisites section in this [article](https://learn.microsoft.com/en-us/graph/sdks/national-clouds?tabs=powershell) before connecting to national cloud using any Microsoft Graph SDKs

**Comment by alexchen2016** [comment]
@timayabi2020 , Thanks for your help.

**Comment by csmulligan** [comment]
Thank you @timayabi2020 and @alexchen2016. I've added this to an internal work item for a future update. Since we're tracking it there, I'll go ahead and close this issue. Feel free to reopen in you have anything to add. Thanks again!
#please-close
