### ISSUE TITLE
Whitelisting application access for guest users

### ISSUE THREAD

**Issue by staible-keyon** [MicrosoftDocs/entra-docs#458]
The conditional access example in section 'Block external users from resources' is unusable as it also blocks guest users from accessing the following essential applications which they require to complete the invitation process or enroll MFA. Both of which are Microsoft first-party applications that cannot be added to the exclude section:
- Microsoft Invitation Acceptance Portal
- My Signins

There is currently no way to whitelist application access for guest users (if they are supposed to use the Registration Acceptance portal or need to enroll MFA). The only way that works is to black list applications they should not access which is frankly unmanageable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 808c5ef4-b3fb-eb0f-1d72-05137b9939b3
* Version Independent ID: d555df00-bd80-cc58-b1f6-2521ff0a2fb1
* Content: [Manage external access to resources with Conditional Access - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/7-secure-access-conditional-access)
* Content Source: [docs/architecture/7-secure-access-conditional-access.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/7-secure-access-conditional-access.md)
* Service: **entra**
* Sub-service: **architecture**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by RamanathanChinnappan-MSFT** [comment]
@staible-keyon
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by janicericketts** [comment]
Thank you for raising this issue. I've removed the example in a PR that will be live later today.
