### ISSUE TITLE
Wrong endpoint in the docs for SCIM schema discovery

### ISSUE THREAD

**Issue by busch** [MicrosoftDocs/entra-docs#460]
Hey Microsoft,

small error in the docs regarding the SCIM endpoint for schema discovery:

`Discover schema - If your end point supports **/Schema**, this option lets the tool discover the supported attributes. We recommend this option as it reduces the overhead of updating your app as you build it out.`

Should be:

`Discover schema - If your end point supports **/Schemas**, this option lets the tool discover the supported attributes. We recommend this option as it reduces the overhead of updating your app as you build it out.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37753d44-c812-b775-134c-e1081f8a2cd9
* Version Independent ID: 05b3ccf1-e811-0498-c0c4-e91cd2034606
* Content: [Tutorial - Test your SCIM endpoint for compatibility with the Microsoft Entra provisioning service. - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/scim-validator-tutorial)
* Content Source: [docs/identity/app-provisioning/scim-validator-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/scim-validator-tutorial.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@busch 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@busch 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
