### ISSUE TITLE
Azure MFA, O365 legacy, Security Defaults etc. breaks Seamless SSO for certain Windows applications

### ISSUE THREAD

**Issue by StureA** [MicrosoftDocs/entra-docs#462]
Greetings. Can you update the documentation for Seamless SSO so it clearly states that having any kind of MFA enabled breaks Seamless SSO for certain Windows applications.  In particular; Teams, OneDrive, Outlook etc. All are at latest enterprise versions.
For example, a consequence is that Teams and OneDrive asks for password instead of doing Seamless SSO.

If there are any registry settings to circumvent this, please include those.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f01328-ebfa-31af-4e67-6de92c8f924e
* Version Independent ID: a990551f-e6c9-dede-308a-b5578fb7ee1e
* Content: [Microsoft Entra Connect - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sso-faq)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sso-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sso-faq.yml)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@StureA 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@StureA 
Thank you for bringing this to our attention.
I've delegated this to content author @billmath, who will review it and offer their insightful opinions.

**Comment by StureA** [comment]
Thank you very much! :)
