### ISSUE TITLE
Too many options; it doesn’t work as expected

### ISSUE THREAD

**Issue by dcal-start** [MicrosoftDocs/entra-docs#464]
Enabling the integration between an on premise Remote Desktop deployment (with a Remote Desktop Gateway) and MFA provided by MS Entra it’s really too icy an hassle. 
There are agents (entra connect and cloud sync), it’s unclear when and is the former must be replaced by the latter, you must use Powershell scripts which install and configure a scary lot of options and when you have finished to follow all of the instructions , it doesn’t work. Logging is (by definition) a mess. It’s unclear where is the problem: maybe a licensing one? Maybe something else?
I’m beginning to think about a complete switch to a third party solutions: Microsoft makes things too complicated. There are people who don’t want to rely all of their digital life and business to “the cloud” 

note: 95% of grammar and syntax errors have been caused by iPhone error correction. I’m sorry. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a61a7e9a-44bf-7bdc-f810-87e2fd6792e1
* Version Independent ID: 71d11105-b83e-952e-d107-1ff9a7c8d107
* Content: [Use Microsoft Entra multifactor authentication with NPS - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension)
* Content Source: [docs/identity/authentication/howto-mfa-nps-extension.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-nps-extension.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaibabaBalapur-MSFT** [comment]
@dcal-start 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dcal-start 
For an issue like this, I'd recommend you create a [support ticket](https://azure.microsoft.com/support/create-ticket/) since the support team will be able to respond much more quickly and have a conversation with you to figure out what could be going on.
