### ISSUE TITLE
image in dark theme

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftDocs/entra-docs#465]
The image in the beginning of the article doesn't look correct in the dark theme.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a8936f3-3cd7-a365-81f2-33b9ee505a7b
* Version Independent ID: 6488ea50-f1d7-8240-3669-41591c56d862
* Content: [Hybrid Identity required ports and protocols - Azure - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/reference-connect-ports)
* Content Source: [docs/identity/hybrid/connect/reference-connect-ports.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/reference-connect-ports.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@MaratMussabekov 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@MaratMussabekov 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

@billmath
Can you please check and add your comments on this doc update request as applicable.

**Comment by billmath** [comment]
@MaratMussabekov thanks for catching this. This will be updated as we re-brand to Microsoft Entra.   This may be a few months out depending on where this doc is scheduled.  Thanks!

#please-close
