### ISSUE TITLE
App password delete 

### ISSUE THREAD

**Issue by BoNiuMM** [MicrosoftDocs/entra-docs#466]
It will need Global Admin to delete existing app password. Authentication admin cannot do this.
https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/delegate-by-task

Please update the doc

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51eadd8e-b820-be21-9cb3-b52f334fb94d
* Version Independent ID: fe358aa5-5bb6-b8f0-8ab7-ef181dc8af42
* Content: [Manage authentication methods for Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-userdevicesettings)
* Content Source: [docs/identity/authentication/howto-mfa-userdevicesettings.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-userdevicesettings.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaibabaBalapur-MSFT** [comment]
@BoNiuMM 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@BoNiuMM 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
