### ISSUE TITLE
Role requirements are incorrect

### ISSUE THREAD

**Issue by MGKocho** [MicrosoftDocs/entra-docs#467]
The role permissions under the following section is incorrect:
https://learn.microsoft.com/en-us/entra/external-id/external-collaboration-settings-configure#configure-settings-in-the-portal

It states at least “External Identity Provider administrator” is required, as per the RBAC pages, its actually the “Global Administrator” role which is required:
https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/delegate-by-task#external-identitiesb2c

Preferably it would be good if the delegated permissions were actually “External Identity Provider administrator”, please can this be updated accordingly, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa45818-3e2a-f952-2a60-86fe930d416c
* Version Independent ID: 02f84110-9385-e158-b847-303cd31d888f
* Content: [Enable B2B external collaboration settings - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/external-collaboration-settings-configure#configure-settings-in-the-portal)
* Content Source: [docs/external-id/external-collaboration-settings-configure.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/external-collaboration-settings-configure.md)
* Service: **entra-external-id**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by SaibabaBalapur-MSFT** [comment]
@MGKocho 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@MGKocho 
Thank you for bringing this to our attention.
I've delegated this to content author @msmimart, who will review it and offer their insightful opinions.

**Comment by msmimart** [comment]
Hi @MGKocho, apologies for the delay. Thanks so much for pointing this out. I've created an internal work item for this issue, which we'll track and resolve internally. I'll go ahead and close this issue. Thanks again for your feedback. #please-close
