### ISSUE TITLE
"Reply URL" list missing servers

### ISSUE THREAD

**Issue by jweber14580** [MicrosoftDocs/entra-docs#468]
The "Reply URL" list of the "Configure Microsoft Entra SSO" section (Step 5b) is missing TWO servers.

Please add:
https://www-p01.intacct.com/ia/acct/sso_response.phtml
https://www-p06.intacct.com/ia/acct/sso_response.phtml

... to the appropriate spots on the list. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2809f192-e944-902e-db51-149939878611
* Version Independent ID: 2d788b57-9c1a-3124-690f-4469bc552cee
* Content: [Tutorial: Microsoft Entra SSO integration with Sage Intacct - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/intacct-tutorial#configure-and-test-microsoft-entra-sso-for-sage-intacct)
* Content Source: [docs/identity/saas-apps/intacct-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/intacct-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by SaibabaBalapur-MSFT** [comment]
@jweber14580 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@jweber14580 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

**Comment by jweber14580** [comment]
How do I contact the author?  Or at least determine if the author works for the vendor?

No update has been made to the page yet...  Thank you!

**Comment by SaibabaBalapur-MSFT** [comment]
@jweber14580 Thanks for the follow-up. Our internal Microsoft authors need to review my pull request (PR). Once the author reviews the changes, they will be merged, and the updates should go live shortly.
