### ISSUE TITLE
Ask for clarification

### ISSUE THREAD

**Issue by jean-luc-chatton** [MicrosoftDocs/entra-docs#47]
Hello,

Thank you for this information.

Cameroon is an opt-in country and our organization has users there. Our head office is located in Switzerland where we do not require opt-in.

Could you please clarify and give us answers to the following questions:
1.	Is it riskier to call a user in Cameroon than a user in Switzerland? 
2.	If the answer to 1 is yes, explain why.
3.	If the answer to 1 is yes, explain the risk?
4.	If one of the risks is financial, confirm that it is an unexpected/high phone bill.
5.	If the answer to 4 is yes, who will receive the unexpected/high phone bill? Microsoft or our organisation?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6b8272b-ad70-460b-3dff-f1a263cfedcb
* Version Independent ID: d965389e-1889-ea6c-5339-2a94d8b2ff2a
* Content: [Understanding telephony fraud risk for Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-telephony-fraud)
* Content Source: [docs/identity/authentication/concept-mfa-telephony-fraud.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-mfa-telephony-fraud.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @aloom3
* Microsoft Alias: **justinha**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jean-luc-chatton 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by aloom3** [comment]
This is a customer ask- I can take it from here.
________________________________

**Comment by SaibabaBalapur-MSFT** [comment]
@jean-luc-chatton 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by jean-luc-chatton** [comment]
Thank you

**Comment by aloom3** [comment]
We can close this out.

**Comment by jean-luc-chatton** [comment]
Is this a question or a statement?

**Comment by aloom3** [comment]
Resolved

**Comment by SaibabaBalapur-MSFT** [comment]
#please-close
