### ISSUE TITLE
Information about ERROR AADSTS120002

### ISSUE THREAD

**Issue by zjorz** [MicrosoftDocs/entra-docs#472]
Through the URL https://login.microsoftonline.com/error?code=AADSTS120002

it provides the following information
AADSTS120002: New password doesn't meet complexity requirements. Passwords can't contain user ID, and need to be **8-16 characters long**, with at least 3 of the following: uppercase letters, lowercase letters, numbers, and symbols.

The part "**8-16 characters long**" is obviously not correct as Entra ID support longer passwords with max length of 256 characters

see: https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-policy

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a826ee6f-f457-7109-9f77-67c57977d4e7
* Version Independent ID: 11766f27-492e-a579-dced-8a42528cbb47
* Content: [Microsoft Entra authentication & authorization error codes - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes)
* Content Source: [docs/identity-platform/reference-error-codes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-error-codes.md)
* Service: **identity-platform**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by SaibabaBalapur-MSFT** [comment]
@zjorz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@zjorz 
Thank you for your suggestion. It would be helpful to provide your ideas in the below link so our product team will work on it.
https://feedback.azure.com/d365community
