### ISSUE TITLE
Ambiguous definition for 18 year old users

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/entra-docs#475]
Under the description of parental controls, it's not clear where 18 year old users belong.  They're included in both the "Adult" definition and the "Not adult" definition.  I believe "Not adult" should say 13-17 years old.

**_Parental controls: For organizations like K-12 school districts, the user's age group may need to be provided. Minors are 12 and under, Not adult are 13-18 years old, and Adults are 18 and over._** 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5417b9b2-1390-5d11-d899-bf7fcf99c41d
* Version Independent ID: 07ac10b0-c108-0e95-da1a-5a7a08527616
* Content: [How to manage user profile information in the Microsoft Entra admin center - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-manage-user-profile-info)
* Content Source: [docs/fundamentals/how-to-manage-user-profile-info.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-manage-user-profile-info.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by SaibabaBalapur-MSFT** [comment]
@gregmilligan 
Thanks for your feedback! We will investigate and update as appropriate.
