### ISSUE TITLE
Use PowerShell to soft-delete the cloud account?

### ISSUE THREAD

**Issue by a7259w** [MicrosoftDocs/entra-docs#477]
[Enter feedback here]
The document has a line "2. Use PowerShell to soft-delete the cloud account:"
Nowhere is it explained, or linked to an explanation, of what soft-delete is and how to do it in Powershell.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1cbaa50-6ef1-b698-43a2-82ffdc72dfbd
* Version Independent ID: aceadd9f-d050-ba0a-7b41-3a08eea20a60
* Content: [Microsoft Entra Connect: Troubleshoot errors during synchronization - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/tshoot-connect-sync-errors)
* Content Source: [docs/identity/hybrid/connect/tshoot-connect-sync-errors.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/tshoot-connect-sync-errors.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@a7259w 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@a7259w 
Soft-delete is a feature in Azure that allows you to recover deleted resources within a certain period of time. When you delete a resource, it is moved to a soft-deleted state and is not immediately deleted. Instead, it is retained for a specified period of time (usually 14 days) before it is permanently deleted.

To soft-delete an Azure resource using PowerShell, you can use the `Remove-AzResource` cmdlet with the `-Force` and `-AsJob` parameters. The `-Force` parameter specifies that the resource should be deleted without prompting for confirmation, and the `-AsJob` parameter specifies that the deletion should be performed as a background job.

Here is an example of how to soft-delete an Azure resource using PowerShell:

```
# Connect to your Azure account
Connect-AzAccount

# Set the name of the resource you want to delete
$resourceName = "myResource"

# Set the resource group name
$resourceGroupName = "myResourceGroup"

# Get the resource ID
$resourceId = (Get-AzResource -Name $resourceName -ResourceGroupName $resourceGroupName).ResourceId

# Soft-delete the resource
Remove-AzResource -ResourceId $resourceId -Force -AsJob
```

I hope this helps clarify what soft-delete is and how to use PowerShell to perform a soft-delete. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@a7259w 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
