### ISSUE TITLE
Intune Dependencies

### ISSUE THREAD

**Issue by dgriffinzero** [MicrosoftDocs/entra-docs#479]
It would be extremely beneficial if the service/app dependency requirements for Intune were mentioned in this article as Intune basically underpins everything from a device-based policy standpoint.  As near as I can tell, the following are required for Intune to function correctly for device management:

Microsoft Intune Enrollment | d4ebce55-015a-49b5-a083-c84d1797ae8c
Microsoft Activity Feed Service | d32c68ad-72d2-4acb-a0c7-46bb2cf93873
Microsoft Device Directory Service | 8f41dc7c-542c-4bdd-8eb3-e60543f607ca
Microsoft Command Service | 19686ca6-5324-4571-a231-77e026b0e06f

If devices are being co-managed, the ConfigMgr Server and Client apps will be required as well. I did not include the appIDs for those as they are "per tenant" app registrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7834fc25-6e4d-1a00-e9d3-949928ccb94b
* Version Independent ID: 23e71a83-28ea-da6f-0e3e-cda56a320358
* Content: [Conditional Access service dependencies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/service-dependencies)
* Content Source: [docs/identity/conditional-access/service-dependencies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/service-dependencies.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@dgriffinzero 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dgriffinzero 
I'm going to assign this to the document author so they can take a look at it accordingly.

@MicrosoftGuyJFlo 
Can you please check and add your comments on this doc update request as applicable.

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for the feedback I will check with the PG and see how they want to handle this. Because of the number of apps that could and do have service dependencies we have used this as a representation of some specific examples and as mentioned in the article **This list isn't exhaustive**. 

I do understand why Intune would be a valuable addition so I will bring it up with the PG. 

#please-close
