### ISSUE TITLE
Doesn't work. Try it.

### ISSUE THREAD

**Issue by bit-doctor-x** [MicrosoftDocs/entra-docs#48]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1279b6d-8210-1751-8e37-cf544cd3695d
* Version Independent ID: 6dc2d359-8d50-1df3-7983-29fb06bfdbb6
* Content: [Tutorial - Create a Blazor Server app that uses the Microsoft identity platform for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-blazor-server)
* Content Source: [docs/identity-platform/tutorial-blazor-server.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-blazor-server.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by SaibabaBalapur-MSFT** [comment]
@bit-doctor-x 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by bit-doctor-x** [comment]
None of the samples you guys show for sso work out if the box. Start an up follow those instructions they absolutely don’t work at all. Anything identity related is outdated and doesn’t work.i ended up cobbling together an easy auth solution but it won’t work for my custom domain xenodyne.com it only works for xenodyne.azure websites.net.if i try to go to xenodyne.com it tries to redirect and fails saying i don’t have a valid redirect. where am i supposed to add additional redirects for easy auth. it doesn’t say anywhere…you guys need a step by step real world example that takes you from the dev environment to a custom domain.extremely frustrating. i could have implemented my own oidc / fido2 code from scratch in the time i’ve spent fiddling with this.- DavidOn Dec 10, 2023, at 11:11 PM, Saibaba Balapur Hireka ***@***.***> wrote:﻿
@bit-doctor-x
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ManoharLakkoju-MSFT** [comment]
@bit-doctor-x 
I apologize for the inconvenience you have faced. It can be frustrating when things don't work as expected. Based on your message, it seems like you're trying to set up SSO for a custom domain and you're having trouble with the redirect.

Regarding your Easy Auth solution, it sounds like you need to add your custom domain to the redirect URIs in the Azure portal. To do this, go to the Authentication / Authorization section of your App Service in the Azure portal and add the redirect URI for your custom domain (e.g. https://xenodyne.com/signin-oidc). This should allow Easy Auth to redirect to your custom domain.

I understand that this process can be complex and frustrating, especially when dealing with custom domains. Microsoft is constantly updating their documentation, so it's important to make sure you're following the most recent version. If you're still having trouble, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
Thank you for your time and patience throughout this issue.

**Comment by bit-doctor-x** [comment]
Yes it’s frustrating.The solution of redirecting to signin-oidc  incorrect.For easyauth the redirect is to https://xenodyne.com/.auth/login/aad/callbackWhich I figured out through trial and error.I believe the issue I’m having now is that no one else can log into the domain because I haven’t been verified.Do you know what the logout should be?- DavidOn Dec 14, 2023, at 12:24 AM, ManoharLakkoju-MSFT ***@***.***> wrote:﻿
@bit-doctor-x
I apologize for the inconvenience you have faced. It can be frustrating when things don't work as expected. Based on your message, it seems like you're trying to set up SSO for a custom domain and you're having trouble with the redirect.
Regarding your Easy Auth solution, it sounds like you need to add your custom domain to the redirect URIs in the Azure portal. To do this, go to the Authentication / Authorization section of your App Service in the Azure portal and add the redirect URI for your custom domain (e.g. https://xenodyne.com/signin-oidc). This should allow Easy Auth to redirect to your custom domain.
I understand that this process can be complex and frustrating, especially when dealing with custom domains. Microsoft is constantly updating their documentation, so it's important to make sure you're following the most recent version. If you're still having trouble, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
Thank you for your time and patience throughout this issue.

**Comment by ManoharLakkoju-MSFT** [comment]
@bit-doctor-x 
I'm going to assign this to the document author so they can take a look at it accordingly

@henrymbuguakiarie
Can you please check and add your comments on this doc update request as applicable.

**Comment by bit-doctor-x** [comment]
I’ve already moved past this and just used easyauth.easyauth lets me authenticate but not anyone else. i think this is most likely because the new business identity hasn’t been “verified” yet.the easyauth documentation needs a lot of work too though as it doesn’t explain that it creates entra ids and that you have to add return urls etc. it would be very helpful if the steps to complete auth setup were summarized at the beginning. you probably need 5 sentences to describe the entire process from start to finish.Also easyauth could be a LOT easier. what if you clicked a button and supplied your custom domain and then it goes and does the rest for you with no fiddling.i don’t think devs have this kind of time to spend on sso.- DavidOn Dec 14, 2023, at 5:18 AM, ManoharLakkoju-MSFT ***@***.***> wrote:﻿
@bit-doctor-x
I'm going to assign this to the document author so they can take a look at it accordingly
@henrymbuguakiarie
Can you please check and add your comments on this doc update request as applicable.

**Comment by henrymbuguakiarie** [comment]
> I’ve already moved past this and just used easyauth.easyauth lets me authenticate but not anyone else. i think this is most likely because the new business identity hasn’t been “verified” yet.the easyauth documentation needs a lot of work too though as it doesn’t explain that it creates entra ids and that you have to add return urls etc. it would be very helpful if the steps to complete auth setup were summarized at the beginning. you probably need 5 sentences to describe the entire process from start to finish.Also easyauth could be a LOT easier. what if you clicked a button and supplied your custom domain and then it goes and does the rest for you with no fiddling.i don’t think devs have this kind of time to spend on sso.- DavidOn Dec 14, 2023, at 5:18 AM, ManoharLakkoju-MSFT ***@***.***> wrote:﻿ @bit-doctor-x I'm going to assign this to the document author so they can take a look at it accordingly @henrymbuguakiarie Can you please check and add your comments on this doc update request as applicable. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Thank you for providing valuable feedback on how we can enhance our documentation. Regarding this article, the primary goal wasn't to teach how to implement single sign-on (SSO), and I agree that confusing content can make the task even more challenging.

I will clean up the article, remove any mention of SSO, and close this GitHub issue.
