### ISSUE TITLE
Activating a roles does not require the Privileged role administrator

### ISSUE THREAD

**Issue by ChuckSnow-DSG** [MicrosoftDocs/entra-docs#480]
[Enter feedback here]

Using link https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-how-to-activate-role#activate-a-role

This is incorrect "Sign in to the Microsoft Entra admin center as **at least a Privileged role administrator**"

You do not have to be a Privileged Role Administrator to use PIM to activate your roles.  That is only required to assign roles. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43125fc1-f1fb-fa8c-69a6-7866a1b3a1fe
* Version Independent ID: 174dbe2c-7469-a63a-ffd6-757272ce5c50
* Content: [Activate Microsoft Entra roles in PIM - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-how-to-activate-role)
* Content Source: [docs/id-governance/privileged-identity-management/pim-how-to-activate-role.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/pim-how-to-activate-role.md)
* Service: **entra-id-governance**
* Sub-service: **privileged-identity-management**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@ChuckSnow-DSG 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@ChuckSnow-DSG 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.
