### ISSUE TITLE
Find and record the https value applicationURI within launchSettings.json

### ISSUE THREAD

**Issue by jasperjiasc** [MicrosoftDocs/entra-docs#481]
[Enter feedback here]
Should be applicationUrl in this sentence "Find and record the https value applicationURI within launchSettings.json"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69195a1b-0f0d-5b82-7302-f6984b3316dc
* Version Independent ID: 69195a1b-0f0d-5b82-7302-f6984b3316dc
* Content: [Tutorial: Prepare a web application for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-app-dotnet-prepare-app?tabs=visual-studio)
* Content Source: [docs/identity-platform/tutorial-web-app-dotnet-prepare-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-web-app-dotnet-prepare-app.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@jasperjiasc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@jasperjiasc 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
