### ISSUE TITLE
Feedback on user not found error

### ISSUE THREAD

**Issue by Nick-ShortalMASC** [MicrosoftDocs/entra-docs#482]
[Enter feedback here]

It might be useful to others to mention that if sys admins are using Excel to compose thier CSV upload to ensure that the row headers and unique details for the upn, serial number, secret key, time interval, manufacturer and model should not be separated with inputted commas.

Or provide a sample CSV upload template that could be used.  In my circumstances the user not found issue I had I assume occured as Entra was looking to match a user that was assuming that all the data was part of the username.

EG: user@domain.com,

In the end Micrsofot Support put me on the right track.  Encouraging me to input the rows without an comma separators and then the unique user data below, save as a .CSV then upload and all went well.

Just hoping this might assist another user who is tearing thier hair out assuming there is an issue with the user not being found when the issue is more to do with the format of the data within the CSV.  

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/N9B6B~1.SHO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/N9B6B~1.SHO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

counter@mountalexander.vic.gov.au
--

</body>

</html>

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/N9B6B~1.SHO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/N9B6B~1.SHO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

counter@mountalexander.vic.gov.au,MT0100055173,Crystal
--

</body>

</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3580bf07-789b-a9c0-26c2-68d21eb66b70
* Version Independent ID: f61c354b-cac2-c3e2-881a-2f0540bdd8e1
* Content: [OATH tokens authentication method - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-oath-tokens)
* Content Source: [docs/identity/authentication/concept-authentication-oath-tokens.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-oath-tokens.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaibabaBalapur-MSFT** [comment]
@Nick-ShortalMASC 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Nick-ShortalMASC** [comment]
My suggestion:

"If you are authoring your OAUTH upload in Excel, ensure that the headers and unique information is listed without comma separators, before saving as a CSV UTF-8 (Comma delimited) (*.csv) file type.  

Otherwise, the inclusion of commas in the cells of Excel will be misinterpreted as being part of the username to be matched. 

Resulting in a failure report from Entra suggesting, no match to the user.  

No commas in data of the Excel sheet, when then saved as a CSV, will result in OATH token associating with the user as intended."

**Comment by luc-msft** [comment]
@Nick-ShortalMASC Could you clarify to me why you would enter comma separators in the Excel file?

**Comment by Nick-ShortalMASC** [comment]
> @Nick-ShortalMASC Could you clarify to me why you would enter comma separators in the Excel file?

For my specific circumstance, the reference .CSV sample I was provided was provided from a colleague that was originally composed in NotePad++, when opened in Excel at the end of each unique entry a comma separator was present.

If there was included within the Reference documentation a sample template, or a screenshot displaying a sample of the correct layout of the sample CSV import.  This might help avoid the confusion of "User does not exist in the current directory." when this is a result of the username data being passed as for example "counter@mountalexander.vic.gov.au, MT0100055173, Crystal" which will never resolve, due to the incorrect interpretation of the username including the additional data as a suffix to the username.

I understand now, why this occurred, perhaps my circumstance is too specific.  But I anticipate as MFA become more of a requirement for organisations, there may be others attempting to enable MFA tokens that might also have issues with the formatting of their CSV files, that might appreciate this being pointed out, and avoid seeking support from Microsoft.

**Comment by Nick-ShortalMASC** [comment]
> @Nick-ShortalMASC Could you clarify to me why you would enter comma separators in the Excel file?

For my specific circumstance, the reference .CSV sample I was provided was provided from a colleague that was originally composed in NotePad++, when opened in Excel at the end of each unique entry a comma separator was present.

If there was included within the Reference documentation a sample template, or a screenshot displaying a sample of the correct layout of the sample CSV import.  This might help avoid the confusion of "User does not exist in the current directory." when this is a result of the username data being passed as for example "counter@mountalexander.vic.gov.au, MT0100055173, Crystal" which will never resolve, due to the incorrect interpretation of the username including the additional data as a suffix to the username.

I understand now, why this occurred, perhaps my circumstance is too specific.  But I anticipate as MFA become more of a requirement for many organisations, there may be others attempting to enable MFA tokens that might also have issues with the formatting of their CSV files.  Some examples, might be useful to others to avoid this mistake.
