### ISSUE TITLE
TypeScript Version

### ISSUE THREAD

**Issue by mirojs** [MicrosoftDocs/entra-docs#484]
[Enter feedback here]

Hello,

For this tutorial code, could there possibly be a TypeScript version?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1b7eaa-c458-fce5-5fc2-b8c8c16b25b8
* Version Independent ID: a2566e4c-fcc6-a820-44cc-22455a8c9fba
* Content: [Tutorial: Create a React SPA for authentication in a customer tenant - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-react-sign-in-prepare-app)
* Content Source: [docs/external-id/customers/tutorial-single-page-app-react-sign-in-prepare-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-single-page-app-react-sign-in-prepare-app.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @garrodonnell
* Microsoft Alias: **godonnell**

**Comment by mirojs** [comment]
@SaibabaBalapur-MSFT Appreciate that, thanks!

**Comment by SaibabaBalapur-MSFT** [comment]
@garrodonnell
Please review it.

**Comment by SaibabaBalapur-MSFT** [comment]
@mirojs 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by mirojs** [comment]
@SaibabaBalapur-MSFT Thanks for taking care of it.
