### ISSUE TITLE
Missing word to complete statement

### ISSUE THREAD

**Issue by Joyos7** [MicrosoftDocs/entra-docs#485]
In the Note (pruple box) section, where it states:

" Note

Microsoft will not allow a domain name to be verified with more than Microsoft Entra tenant. Once you delete a domain name from your tenant, you will not be able to re-add/re-verify it with your Microsoft Entra tenant if it is subsequently added and verified with another Microsoft Entra tenant."

I believe you are missing the word "one" in the first sentence, so it should read: "Microsoft will not allow a domain name to be verified with more than _one_ Microsoft Entra tenant."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67566e6a-ffb4-4adf-73b5-3d6c0c58cd05
* Version Independent ID: 9c9a6f63-ec87-0e45-9d0e-f5030041ab06
* Content: [Add and verify custom domain names - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/domains-manage)
* Content Source: [docs/identity/users/domains-manage.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/domains-manage.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by SaibabaBalapur-MSFT** [comment]
@Joyos7 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Joyos7 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
