### ISSUE TITLE
HOW 

### ISSUE THREAD

**Issue by MitinPham** [MicrosoftDocs/entra-docs#486]
[Nhập phản hồi vào đây]

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho learn.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 09eb3bfb-5bcc-3fb1-b36b-6222fe1f4e51
* Version Independent ID: 9772c16b-8364-3ba2-a8b5-2f31a2abef5d
* Content: [Decommissioning Azure AD Connect V1 - Microsoft Entra ID](https://learn.microsoft.com/vi-vn/entra/identity/hybrid/decommission-connect-sync-v1?WT.mc_id=Portal-Microsoft_AAD_IAM)
* Content Source: [docs/identity/hybrid/decommission-connect-sync-v1.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/decommission-connect-sync-v1.md)
* Service: **entra-id**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@MitinPham 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by SaibabaBalapur-MSFT** [comment]
@MitinPham 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

#please-close
