### ISSUE TITLE
SAML EntraID = Failed: Digest mismatch

### ISSUE THREAD

**Issue by sicog** [MicrosoftDocs/entra-docs#487]
Following the document, and revalidating, when I test the SAML within github it failed with Digest mismatch.

Not much info on this, but found this: https://joshudofia.com/2023/01/04/digest-mismatch-github-enterprise-sso-azure-ad/

That should be pretty much straight forward but SAML does not work between Entra ID/Github!

**Comment by SaibabaBalapur-MSFT** [comment]
@sicog 
It would be great if you could add a link to the Microsoft documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by sicog** [comment]
https://learn.microsoft.com/fr-ca/entra/identity/saas-apps/github-enterprise-cloud-enterprise-account-tutorial

**Comment by SaibabaBalapur-MSFT** [comment]
@sicog 
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd 
please review it.

**Comment by sicog** [comment]
Got to work around the issue with Github support...  Here's how I got it working...

Are you configuring SAML sso at the Enterprise account level or organization level? 
 
but when I try the config, I keep getting Digest Mismatch.

 

A Digest mismatch error generally indicates that either your Identity Provider (IdP) is using a different SAML Signing certificate than the one you have uploaded to your GitHub.com, or that the Signature Method or Digest Method configured on GitHub.com differ from what your IdP is using.
 
I would ensure that the certificate is properly formatted and that it matches what your IdP is using to sign your SAML Responses. You can copy and paste the string into a tool like this to format it properly with the headers:
 
https://www.samltool.com/format_x509cert.php

Copy the Entra ID certificat in the X509 cert, and used the x509 cert with header in GitHub and it work...

**Comment by v-hgampala** [comment]
There is no requirement to change in the document about the certificate.
#please-close
