### ISSUE TITLE
Document Revision or Product Bgug

### ISSUE THREAD

**Issue by RDukes425** [MicrosoftDocs/entra-docs#488]
On Step 4 of applying the MIP Sensitivity Labels to M365 Groups, it mentions to update the Params for MIPLabels to True and then update settings. 

Per document: 
$params = @{
     Values = @(
 	    @{
 		    Name = "EnableMIPLabels"
 		    Value = "True"
 	    }
     )
}

Update-MgBetaDirectorySetting -DirectorySettingId $grpUnifiedSetting.Id -BodyParameter $params

The above commands will return HttpStatusCode 400 (Bad Request)

The params field requires all the labels for the Group to be included before Update-MgBetaDirectorySetting will work. 
In my Repro, the params field had to look like the following: 
$params = @{
     Values = @(
 	    @{
 		    Name = "EnableMIPLabels"
 		    Value = "True"
 	    }
		@{
 		    Name = "CustomBlockedWordsList"
 		    Value = ""
 	    }
		@{
 		    Name = "EnableMSStandardBlockedWords"
 		    Value = "True"
 	    }
		@{
 		    Name = "PrefixSuffixNamingRequirement"
 		    Value = ""
 	    }
		@{
 		    Name = "AllowGuestsToBeGroupOwner"
 		    Value = "True"
 	    }
		@{
 		    Name = "AllowGuestsToAccessGroups"
 		    Value = "True"
 	    }
		@{
 		    Name = "AllowToAddGuests"
 		    Value = "True"
 	    }
		@{
 		    Name = "GuestUsageGuidelinesUrl"
 		    Value = ""
 	    }
		@{
 		    Name = "UsageGuidelinesUrl"
 		    Value = ""
 	    }
		@{
 		    Name = "ClassificationDescriptions"
 		    Value = ""
 	    }
		@{
 		    Name = "DefaultClassification"
 		    Value = ""
 	    }
		@{
 		    Name = "ClassificationList"
 		    Value = ""
 	    }
		@{
 		    Name = "GroupCreationAllowedGroupId"
 		    Value = ""
 	    }
		@{
 		    Name = "EnableGroupCreation"
 		    Value = "True"
 	    }
     )
}

Ask: 
- Please consider updating the messaging for the steps that all parameters will be needed or if this is not expected, please review the behavior of the cmdlet to update the MIPLabels parameter only without having to add each value from the Group. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef84a3e0-879e-4312-a89d-7a3bb0cd9a51
* Version Independent ID: 43851f8a-b71f-0a0a-8b1f-629e3528972f
* Content: [Assign sensitivity labels to groups - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-assign-sensitivity-labels)
* Content Source: [docs/identity/users/groups-assign-sensitivity-labels.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-assign-sensitivity-labels.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by SaibabaBalapur-MSFT** [comment]
@RDukes425 
I'm going to assign this to the document author so they can take a look at it accordingly.
