### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ThePoShWolf** [MicrosoftDocs/entra-docs#489]
On step 7 under 'Configure automatic user account provisioning to GitHub in Microsoft Entra ID', the link no longer works. I believe the correct link is: https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61e856ff-405a-62ab-20d6-b91a336c674f
* Version Independent ID: a54166e0-1a4a-b9ef-1c41-9a9f61dc6af9
* Content: [Tutorial: User provisioning for GitHub - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/github-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/github-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/github-provisioning-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @twimmers
* Microsoft Alias: **thwimmer**

**Comment by SaibabaBalapur-MSFT** [comment]
@ThePoShWolf 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@ThePoShWolf 
Thank you for bringing this to our attention.
I've delegated this to content author @twimmers, who will review it and offer their insightful opinions.
