### ISSUE TITLE
Please update the page to indicate that the Windows VPN client doesn't support TOTP

### ISSUE THREAD

**Issue by swalker-aup** [MicrosoftDocs/entra-docs#49]
We've been trying to implement MFA on our VPN (currently using RRAS and the integrated Windows VPN client).  Using the registry key to disable TOTP and force out-of-band MFA (**Approve/Deny** via MS Authenticator push notification, or **phone call** for those without MS Authenticator) works fine, but Microsoft's own documentation indicates that TOTP is more secure, and we wanted the flexibility of using being able to use TOTP codes and SMS auth, so we set up authentication via PAP to allow for TOTP.

This article gives detailed instructions on setting up NPS/MFA with an RRAS VPN server and Windows client, but doesn't seem to have been updated to reflect the fact that the NPS/MFA combination now supports TOTP when using PAP authentication... **but the Windows VPN client doesn't**.

Given that the page specifically discusses setting up RRAS to use NPS and Entra ID MFA, and how to configure the Windows 10 VPN client with it, can Microsoft please add _something_ on this page to simply indicate that their own VPN client doesn't support the TOTP feature?

My ticket with Azure (the only way to get this actual answer) pointed me towards using OpenVPN, because apparently an open-source product can get updated to support Microsoft's RADIUS-based TOTP MFA implementation, but Microsoft makes it almost impossible to know that their own Windows VPN client does not support it.

It's OK to not support something, I suppose, but this one _really_ should be mentioned explicitly by Microsoft, as one would expect their products to be at least a bit intercompatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf322e2b-b09c-2a09-2b0d-27de43075953
* Version Independent ID: c82153d8-7449-09e7-bd8f-328eb9fd8d74
* Content: [VPN with Microsoft Entra multifactor authentication using the NPS extension - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension-vpn)
* Content Source: [docs/identity/authentication/howto-mfa-nps-extension-vpn.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-nps-extension-vpn.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaibabaBalapur-MSFT** [comment]
@swalker-aup 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@swalker-aup 
Thank you for bringing this to our attention.
I've delegated this to content author @Justinha, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@Justinha 
Could you please review add comments on this, update as appropriate.

**Comment by Justinha** [comment]
@swalker-aup @Naveenommi-MSFT sorry for delay folks. I added a note to the introduction to say Windows VPN client doesn't support TOTP. #please-close
