### ISSUE TITLE
microsoft app

### ISSUE THREAD

**Issue by Mdashad071192** [MicrosoftDocs/entra-docs#490]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd4f98b7-3d87-6a84-8247-20a8893f7e98
* Version Independent ID: 01482485-7e2b-5621-897b-850618ef3f1e
* Content: [Supported account types - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-supported-account-types)
* Content Source: [docs/identity-platform/v2-supported-account-types.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-supported-account-types.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by SaibabaBalapur-MSFT** [comment]
@Mdashad071192 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by SaibabaBalapur-MSFT** [comment]
@Mdashad071192 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
