### ISSUE TITLE
Missing docs on "Prevents removal of the last active Global Administrator and Privileged Role Administrator role assignments"

### ISSUE THREAD

**Issue by Expecho** [MicrosoftDocs/entra-docs#491]
One of the mentioned benefits of PIM is 

> Prevents removal of the last active Global Administrator and Privileged Role Administrator role assignments

However, I can't find any documentation regarding this specific point.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7338196-8434-f76e-ec0d-15bc85d51434
* Version Independent ID: c7003b7a-91f8-3727-0f3e-93f52f5809fa
* Content: [What is Privileged Identity Management? - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-configure)
* Content Source: [docs/id-governance/privileged-identity-management/pim-configure.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/pim-configure.md)
* Service: **entra-id-governance**
* Sub-service: **privileged-identity-management**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by SaibabaBalapur-MSFT** [comment]
@Expecho 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by barclayn** [comment]
@Expecho there is no additional documentation that expands on that line. Do you have any specific questions? #please-close

**Comment by Expecho** [comment]
Yes well, if the docs mention that PIM prevents removing the last global administrator I expect the docs to show me/explain how that is done.
