### ISSUE TITLE
Isu tech

### ISSUE THREAD

**Issue by Azorisho** [MicrosoftDocs/entra-docs#492]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5cea15b5-0fca-d8ae-9423-4f4c91d7a9de
* Version Independent ID: 6f6159f1-8a56-7aa2-81ab-bf9e6c339a7d
* Content: [B2B collaboration API and customization - Microsoft Entra External ID](https://learn.microsoft.com/en-gb/entra/external-id/customize-invitation-api#powershell)
* Content Source: [docs/external-id/customize-invitation-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customize-invitation-api.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by ManoharLakkoju-MSFT** [comment]
@Azorisho 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ManoharLakkoju-MSFT** [comment]
@Azorisho 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
