### ISSUE TITLE
Request to update the list of administrator centers included in 'Microsoft Admin Portals'

### ISSUE THREAD

**Issue by NatsukiNK** [MicrosoftDocs/entra-docs#493]
Please add the following two administrator centers to this page, the list of 'Microsoft Admin Portals'
https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-cloud-apps#microsoft-admin-portals

- SharePoint admin center
https://go.microsoft.com/fwlink/?linkid=2185219
- Microsoft Teams Admin Center
https://admin.teams.microsoft.com/dashboard

I don't see those on this 'Microsoft Admin Portals' description in Microsoft Learn today, but I checked in my demo environment and I think SharePoint admin center and Microsoft Teams Admin Center are also included in Microsoft Admin Portals.
Since customers access SharePoint admin center and Microsoft Teams Admin Center frequently, but several of my customers read this description and make a mistake and stop using this Microsoft Admin Portals, such as the Microsoft managed conditional access policy.
 I would like to see those 2 admin centers listed in this Microsoft Learn information so that there is no misunderstanding.

- **Currently**
Azure portal
Exchange admin center
Microsoft 365 admin center
Microsoft 365 Defender portal
Microsoft Entra admin center
Microsoft Intune admin center
Microsoft Purview compliance portal

- **I would like you to do this**
Azure portal
Exchange admin center
Microsoft 365 admin center
Microsoft 365 Defender portal
Microsoft Entra admin center
Microsoft Intune admin center
Microsoft Purview compliance portal
**SharePoint admin center
Microsoft Teams Admin Center**

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6d2ea9-04c9-d4e5-36b5-2ce7e17192e1
* Version Independent ID: eff8d31c-d3ce-f72c-22ab-53b415b221b0
* Content: [Cloud apps, actions, and authentication context in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-cloud-apps#microsoft-admin-portals)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-cloud-apps.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-cloud-apps.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by ManoharLakkoju-MSFT** [comment]
@NatsukiNK 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
Pending feedback from the PM #label:"awaiting-product-team-response"

**Comment by MicrosoftGuyJFlo** [comment]
Teams is being added in the linked PR to publish later today. The SharePoint admin center is not really an admin center just a different page inside of SharePoint. The product team is looking into how that can be covered by this grouping. You can see if a policy is applied by checking the sign-in logs.
