### ISSUE TITLE
Handling endpoint authentication

### ISSUE THREAD

**Issue by wrbobby** [MicrosoftDocs/entra-docs#496]
You mention two options for Handling endpoint authentication:

1. A long-lived bearer token
2. Microsoft Entra bearer token

Regarding no. 2 you write "The token generated by the Microsoft Entra ID should only be used for testing".

Is that right? Meaning we should only consider no. 1 in production anyway?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 271dc426-fb47-7441-d627-ec11f8c7a6ea
* Version Independent ID: 4cb8bfc8-4748-e501-425a-e4c2da0f5f5a
* Content: [Tutorial - Develop a SCIM endpoint for user provisioning to apps from Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups)
* Content Source: [docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by SaibabaBalapur-MSFT** [comment]
@wrbobby I believe there might be a misunderstanding. The document you provided is specific to Microsoft Entra Verified ID and the use of SCIM to provision users and groups. In that context, the document mentions two options for handling endpoint authentication:
1.Long-lived bearer token
2.Microsoft Entra bearer token
Regarding option 2, the document states that the token generated by the Microsoft Entra Verified ID platform should only be used for testing purposes. This means that in a production environment, you should use option 1, which is the long-lived bearer token.

However, it's important to note that this information is specific to the use of SCIM to provision users and groups with Microsoft Entra Verified ID. In other contexts, such as API authentication and authorization, there might be different options available.

I'd recommend working closer with our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. [Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.)[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by wrbobby** [comment]
@SaibabaBalapur-MSFT "Verified" is not mentioned at all on the page. Is there any difference in this regard between "Microsoft Entra Verified ID" and "Microsoft Entra ID"?

Also if there is only one viable option for a production setup, then I suggest you don't mention two options, and instead describe the one option for production, and with a different headline the additional option for testing purposes.

**Comment by SaibabaBalapur-MSFT** [comment]
@wrbobby Thanks for your valuable feedback. 
I'm going to assign this to the document author so they can take a look at it accordingly. 

@kenwith
Can you please check and add your comments on this doc update request as applicable.
