### ISSUE TITLE
Application enforced restrictions links

### ISSUE THREAD

**Issue by jd1984** [MicrosoftDocs/entra-docs#499]
Hello,

The 'Application enforced restrictions' section was changed on commit https://github.com/MicrosoftDocs/entra-docs/commit/d599c6e946ecb48a3927266f9d69995a25b6ab76 to remove references to SharePoint and Exchange Online.

The link now says:

> For a list of supported applications and how to configure policies, see the article [Idle session timeout for Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/idle-session-timeout-web-apps#details-about-idle-session-timeout)

Instead of the previously more relevant:

> For more information on the use and configuration of app-enforced restrictions, see the following articles:
> - [Enabling limited access with SharePoint Online](/sharepoint/control-access-from-unmanaged-devices)
> - [Enabling limited access with Exchange Online](/microsoft-365/security/office-365-security/secure-email-recommended-policies?view=o365-worldwide&preserve-view=true#limit-access-to-exchange-online-from-outlook-on-the-web)

Is there a reason these were taken out?

Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 609a0eda-f113-8b77-67ee-c5e8bd94cbac
* Version Independent ID: 7468d74e-9a7e-2a11-ba35-da46103a1b80
* Content: [Session controls in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-gb/entra/identity/conditional-access/concept-conditional-access-session#application-enforced-restrictions)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-session.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-session.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by SaibabaBalapur-MSFT** [comment]
@MicrosoftGuyJFlo
please review it.

**Comment by SaibabaBalapur-MSFT** [comment]
@jd1984 
I'm going to assign this to the document author so they can take a look at it accordingly.
