### ISSUE TITLE
Reference REST API for MS Identity Platform

### ISSUE THREAD

**Issue by odi76** [MicrosoftDocs/entra-docs#50]
[Enter feedback here]
I need a reference documentation for the REST API of MS Identity Platform. I could not fin exact specification about the details (request/response parameters, error codes). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc5f32d-7f05-cb8e-fc96-f1a2da4c605f
* Version Independent ID: 79665705-66cc-995f-6b89-7239bbdee2aa
* Content: [Acquire and cache tokens with Microsoft Authentication Library (MSAL) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/msal-acquire-cache-tokens)
* Content Source: [docs/identity-platform/msal-acquire-cache-tokens.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/msal-acquire-cache-tokens.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by SaibabaBalapur-MSFT** [comment]
@odi76 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@odi76 
Here is the correct link to the REST API documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols. This documentation provides detailed information about the request and response parameters, error codes, and other details related to the REST API. If you have any specific questions or need further assistance, please let me know.

**Comment by SaibabaBalapur-MSFT** [comment]
@odi76 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
