### ISSUE TITLE
Section inacurate - cannot search and launch apps from search bar

### ISSUE THREAD

**Issue by ivandretvic** [MicrosoftDocs/entra-docs#500]
This section is not accurate: https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/myapps-overview#my-apps-secure-sign-in-extension
There are likely other areas that reference the search bar. Currently you type in the search, and it loads a page with the search query, and results. It used to be all in-line within the app making it actually useful.
Verify my statement with the comments/feedback here: https://microsoftedge.microsoft.com/addons/detail/my-apps-secure-signin-ex/gaaceiggkkiffbfdpmfapegoiohkiipl?hl=en-US

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99b4887c-ba4c-a47e-ff49-4423941926b4
* Version Independent ID: 39ce9137-e3b6-998b-0492-794592f59785
* Content: [My Apps portal overview - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/myapps-overview)
* Content Source: [docs/identity/enterprise-apps/myapps-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/myapps-overview.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by ManoharLakkoju-MSFT** [comment]
@ivandretvic 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@ivandretvic 
Thank you for bringing this to our attention.
I've delegated this to content author @omondiatieno, who will review it and offer their insightful opinions.

**Comment by omondiatieno** [comment]
This issue has been resolved by PR: https://github.com/MicrosoftDocs/entra-docs/issues/500.

#please-close
