### ISSUE TITLE
Incomprehensible sentence

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/entra-docs#501]
Hello,

please rewrite this sentence: "For complex, large-scale Microsoft Windows Server Active Directory to Azure AD Sync needs such as synchronizing groups over 50,000 and device sync, customers can use Microsoft Entra Connect Sync to meet their needs."

It is not clear as such.

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53a27a13-93e8-55cf-f382-cafd97b60700
* Version Independent ID: 26c98c27-8363-c663-a271-09c3ac138d33
* Content: [Solutions to automate identity provisioning to applications - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/automate-provisioning-to-applications-solutions)
* Content Source: [docs/architecture/automate-provisioning-to-applications-solutions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/automate-provisioning-to-applications-solutions.md)
* Service: **entra**
* Sub-service: **architecture**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by ManoharLakkoju-MSFT** [comment]
@QueryCoordinator 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by janicericketts** [comment]
Edited for clarity in https://github.com/MicrosoftDocs/entra-docs-pr/pull/2441

**Comment by QueryCoordinator** [comment]
Hi @janicericketts, when will the update be live and seen on the page?
