### ISSUE TITLE
Misisng row in the Data Security Table

### ISSUE THREAD

**Issue by noendscripting** [MicrosoftDocs/entra-docs#504]
[Microsoft Entra Id Data Protection Considerations](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/data-protection-considerations.md) document has a paragraph in the in the [Data Security Section](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/data-protection-considerations.md#data-security) that states:

> For more information about Secret encryption at rest, see the following table.

However the table below does not have "Secret encryption at rest" row. The older document had following data in that row:
> In addition to disk level encryption, 
when at rest, secrets stored in the 
directory are encrypted using the 
Distributed Key Manager(DKM).
The encryption keys are stored in Azure 
AD core store and in turn are encrypted 
with a scale unit key. The key is stored 
in a container that is protected with 
directory ACLs, for highest privileged 
users and specific services. 
The symmetric key is typically rotated 
every six months.
Access to the environment is further 
protected with operational controls and 
physical security. See sections Operator 
Security and Physical Security for more 
details.
The higher-level services that consume 
the secret store call the encrypt/decrypt 
operations through a dedicated 
interface, locked down to these specific 
services. The key material used for these 
operations does not leave the Azure AD 
Core Store. The encryption operations 
must also define a scope that can be the 
tenant, user, or service principal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f78f2c4c-4164-85f3-e87d-e602d0f9a341
* Version Independent ID: c486ecae-205b-0c63-fcd7-68c078ea6b04
* Content: [Data protection considerations - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/data-protection-considerations)
* Content Source: [docs/fundamentals/data-protection-considerations.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/data-protection-considerations.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by ManoharLakkoju-MSFT** [comment]
@noendscripting 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@noendscripting 
I'm going to assign this to the document author so they can take a look at it accordingly.

@janicericketts 
Can you please check and add your comments on this doc update request as applicable.

**Comment by janicericketts** [comment]
This reference is not present in article history, going back to when the article was posted in January 2023. This article does list encryption details for secret encryption at rest at various points in the table. No additional information is available at this time. #please-close

**Comment by noendscripting** [comment]
I was referring the original pdf document which is a copy of this article except for the omitted entry I opened  
[
[Azure-AD-Data-Security-Considerations.pdf](https://github.com/MicrosoftDocs/entra-docs/files/15191229/Azure-AD-Data-Security-Considerations.pdf)
](url)
