### ISSUE TITLE
What logo is used for the MS authenticator app? 

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/entra-docs#505]
please advise which logo is used for the MS authenticator app. 

see question here: https://stackoverflow.com/q/50832480/1747983
also similar content here: https://learn.microsoft.com/en-us/entra/fundamentals/how-to-customize-branding

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c092d2aa-a71a-443c-9635-ea66b05fed3f
* Version Independent ID: 39a22444-d600-57a5-5ffa-a91c052da320
* Content: [Customize your branding for your customers - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-customize-branding-customers)
* Content Source: [docs/external-id/customers/how-to-customize-branding-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-customize-branding-customers.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by ManoharLakkoju-MSFT** [comment]
@TiloGit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @TiloGit 
The Microsoft Authenticator app uses the Microsoft logo as its branding logo. You can download the official Microsoft logo in PNG or SVG format from the [Sign in with Microsoft branding guidelines](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps) page. The logo can be used in your app to convey that Microsoft manages the work or school accounts.

**Comment by ManoharLakkoju-MSFT** [comment]
@TiloGit 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
