### ISSUE TITLE
sing in error troubleshooting

### ISSUE THREAD

**Issue by swy** [MicrosoftDocs/entra-docs#506]
Type error in section https://learn.microsoft.com/en-us/entra/identity/monitoring-health/howto-customize-filter-logs?tabs=audit-logs#next-steps

"sing-in" vs "sign-in"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c446d7d8-9d96-e51f-d5cc-b6d11293ac53
* Version Independent ID: a81f7696-1fa9-1c7a-759a-825cc1047ac6
* Content: [Customize and filter activity logs in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/howto-customize-filter-logs?tabs=audit-logs)
* Content Source: [docs/identity/monitoring-health/howto-customize-filter-logs.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/monitoring-health/howto-customize-filter-logs.md)
* Service: **entra-id**
* Sub-service: **monitoring-health**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by ManoharLakkoju-MSFT** [comment]
@swy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@swy
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
