### ISSUE TITLE
Potentially dangerous link in this article

### ISSUE THREAD

**Issue by PottsSG** [MicrosoftDocs/entra-docs#507]
There is a link to http://calebb.net in this article.  That is a potentially dangerous link because:

- No SSL certificate matching the domain name
- Link is HTTP by default
- The site purpose is to decode security tokens which means it encourages people to send tokens to it via a browser
- The site does not identify who owns it
- There is no posted privacy policy or data policy

In my opinion as a security software developer, Microsoft should not link to (endorse) a possibly 3rd party site for this purpose, especially one where it's not clear what happens to the tokens submitted to it.  At the very least it teaches bad security practices.  Red flags all over the place on this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Log in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by ManoharLakkoju-MSFT** [comment]
@PottsSG 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @PottsSG 
Thanks for your contribution. Please add your feedback in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)

**Comment by MicrosoftGuyJFlo** [comment]
@PottsSG 

Author here... I am taking ownership of this and escalating this to the Product Team for their feedback directly. No need to fill out an idea. 

#remove-label:"cxp"
#label:"assigned-to-author"
#reassign:@MicrosoftGuyJFlo

#label:"awaiting-product-team-response"

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label: "product-question"
#label: "doc-enhancement"

**Comment by MicrosoftGuyJFlo** [comment]
Replacing with another tool that uses HTTPS
