### ISSUE TITLE
General Motors requested additional guidance on Android Shared Device Mode

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/entra-docs#513]
Hello, 

GM has provided strong feedback that they want to see additional guidance on how to leverage Android Shared Device Mode.

There is documentation for iPad https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-shared-ipad, but nothing to be found with more details specifically on how to configure and use it with Intune for Android.

The only other piece of documentation found is a blog post by the Intune team.

https://techcommunity.microsoft.com/t5/intune-customer-success/endpoint-manager-supports-sign-out-for-apps-not-optimized-with/ba-p/3034398
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1b1eff-e5dd-8455-9408-898dd724f48e
* Version Independent ID: 576f2d3b-ac0c-0d72-8080-4e3737886a96
* Content: [Shared device mode overview - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/msal-shared-devices)
* Content Source: [docs/identity-platform/msal-shared-devices.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/msal-shared-devices.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by ManoharLakkoju-MSFT** [comment]
@cadasi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @cadasi the document below refers to enrolling in Intune for Android. This might be helpful for reference.
https://learn.microsoft.com/en-us/mem/intune/enrollment/android-fully-managed-enroll

if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by cadasi** [comment]
@SaibabaBalapur-MSFT thank you for the response and research! I was aware about the article that you mentioned as General Motors is, but that article solely talks about enrolling devices for single user mode and does not go into details about the specifics of Shared Device Mode for Android, where their pain lives is that while this article from Entra mentions Shared Devices (https://learn.microsoft.com/en-us/entra/identity-platform/msal-shared-devices#supporting-multiple-users-on-devices-designed-for-one-user) and there are documents from the Intune team for iPads https://learn.microsoft.com/en-us/mem/intune/enrollment/device-enrollment-shared-ipad, there is nothing on Android. 
Not sure if this is something we need to get input from the Intune team, but probably the request here would be to have an article detailing the specifics of Android Shared Mode, the same that already exists for iPad.

**Comment by SaibabaBalapur-MSFT** [comment]
@cadasi 
I'm going to assign this to the document author so they can take a look at it accordingly.

@henrymbuguakiarie 
Can you please check and add your comments on this doc update request as applicable.

**Comment by henrymbuguakiarie** [comment]
Hello @cadasi,

I contacted the PM who owns that area, and the PM is working on an initiative to improve and share more guides on how to configure Shared Device Mode and use it with Intune for Android.

The timeline isn't a hard deadline but might be completed before the end of FY24.

Cc: @SaibabaBalapur-MSFT

**Comment by henrymbuguakiarie** [comment]
Hello @cadasi,

We are tracking this work internally, I'll go ahead an close the GitHub issue.

Thank you for your feedback.

#please-close
