### ISSUE TITLE
Does Azure SAML support the Enhanced Client or Proxy (ECP) Profile?

### ISSUE THREAD

**Issue by 3BK** [MicrosoftDocs/entra-docs#514]
[Enter feedback here]
Does Azure SAML support the Enhanced Client or Proxy (ECP) Profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c01ec6a-ab66-33b1-8e6f-6437e8f4f660
* Version Independent ID: 2f64f95f-9403-bc88-ac72-5ce56f9d50c3
* Content: [Microsoft Entra Connect: Use a SAML 2.0 Identity Provider for Single Sign On - Azure - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-saml-idp)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-fed-saml-idp.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by 3BK** [comment]
References
https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf section 4.2
https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf section 3.3.3.

**Comment by ManoharLakkoju-MSFT** [comment]
@3BK 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@3BK 
I recommend working closer with our support team for precise details via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
