### ISSUE TITLE
Reference to a diagram that does not exist

### ISSUE THREAD

**Issue by MagrPain** [MicrosoftDocs/entra-docs#515]
In the following section: https://learn.microsoft.com/en-us/entra/architecture/secure-multiple-tenants#isolation-common-usage there is reference to a diagram but then no corresponding diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca77e3f-dd92-78a5-e5c9-cd34e56383c9
* Version Independent ID: fadbbd04-975d-b1b5-5935-65f29602e8d6
* Content: [Resource isolation with multiple tenants to secure with Microsoft Entra ID - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/secure-multiple-tenants)
* Content Source: [docs/architecture/secure-multiple-tenants.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/secure-multiple-tenants.md)
* Service: **entra**
* Sub-service: **architecture**
* GitHub Login: @Gargi-Sinha
* Microsoft Alias: **gasinh**

**Comment by ManoharLakkoju-MSFT** [comment]
@MagrPain 
Thanks for your feedback! We will investigate and update as appropriate.
