### ISSUE TITLE
Steps don't match

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/entra-docs#517]
[Enter feedback here]
https://learn.microsoft.com/en-us/entra/fundamentals/how-to-customize-branding#how-to-navigate-the-company-branding-process

First step does not match. No clue how to find Company Branding since User Experiences is not found under Identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72f2e675-436d-dcd4-fa27-49408b201158
* Version Independent ID: 4d821732-fc10-f4a6-3c7d-77bce75299d7
* Content: [Add company branding to your organization's sign-in page - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-customize-branding)
* Content Source: [docs/fundamentals/how-to-customize-branding.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-customize-branding.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by ManoharLakkoju-MSFT** [comment]
@ahmadpirani 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @ahmadpirani 
Here is Company Branding under User Experiences. Please review it and let me know if any adjustments are needed.

<img width="585" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/113576472/8e074a3e-4137-4fce-b345-3bc314478095">

**Comment by Naveenommi-MSFT** [comment]
@ahmadpirani 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
