### ISSUE TITLE
No steps specified

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/entra-docs#518]
[Enter feedback here]

There are no steps specified to go to Layouts.

https://learn.microsoft.com/en-us/entra/fundamentals/how-to-customize-branding#layout

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72f2e675-436d-dcd4-fa27-49408b201158
* Version Independent ID: 4d821732-fc10-f4a6-3c7d-77bce75299d7
* Content: [Add company branding to your organization's sign-in page - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-customize-branding)
* Content Source: [docs/fundamentals/how-to-customize-branding.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/how-to-customize-branding.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by ManoharLakkoju-MSFT** [comment]
@ahmadpirani 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@shlipsey3
Can you please check and add your comments on this doc update request as applicable.

**Comment by shlipsey3** [comment]
It's one of the tabs in the customize branding process. The navigation is described just above that section and illustrated in the image. The tabs are pretty standard in the UI so we don't always call it out. I can look into revising it, but at this time I can't prioritize this work. 

![image](https://github.com/MicrosoftDocs/entra-docs/assets/66325782/7ad0f92e-43a8-4553-8311-40cbd7721b74)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/66325782/27e0a294-f4e2-4ea0-b6dc-f015012297e8)

**Comment by ahmadpirani** [comment]
The point is that the documentation is wrong. There exists nothing called as Layout Header and Footer when on the Customize Branding page. Whether you go from portal.azure.com or entra,microsoft.com

It seems that those customization are no longer available and hence documentation needs to be updated in consultation with the team developing/maintaining this feature.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/11561396/a9dae011-c1dd-4d32-9f78-4bd6826884cd)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/11561396/cfc5919e-9e00-48f8-8554-2ba4c7b914c8)

**Comment by shlipsey3** [comment]
We now have two threads on the same topic. Let's close this one and focus on the other one. The documentation's not wrong but you are seeing something different.
