### ISSUE TITLE
ClientID in MSAL Config

### ISSUE THREAD

**Issue by ajhaddaddio** [MicrosoftDocs/entra-docs#520]
Where do I find my clientid for the config of MSAL?  The document does not describe where to find it.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6e5855-ef79-2759-6773-f3a44886cb14
* Version Independent ID: 73154754-ea03-f123-3506-9173f7472322
* Content: [Configure single-page app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-app-configuration?tabs=javascript2)
* Content Source: [docs/identity-platform/scenario-spa-app-configuration.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-spa-app-configuration.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by ManoharLakkoju-MSFT** [comment]
@ajhaddaddio 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @ajhaddaddio 
To find the `clientId` for the configuration of MSAL, you can follow these steps:

1. Sign in to the [Azure portal](https://portal.azure.com/).

2. Navigate to the Azure AD B2C tenant that you want to use for your application.

3. In the left-hand menu, select **App registrations**.

4. Select the application that you want to configure with MSAL.

5. In the **Overview** page for the application, you should see the `Application (client) ID`. This is the `clientId` that you need to use in your MSAL configuration.

I hope this helps. Let me know if you have any further questions.

**Comment by ManoharLakkoju-MSFT** [comment]
@ajhaddaddio 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
