### ISSUE TITLE
Azure Active Directory still mentioned in RSS feed link

### ISSUE THREAD

**Issue by gerbermarco** [MicrosoftDocs/entra-docs#523]
There's still Azure Active Directory mentioned in the RSS feed link: 

`https://learn.microsoft.com/api/search/rss?search=%22Release+notes+-+Azure+Active+Directory%22&locale=en-us
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a89edb7f-c01c-00d7-0c2e-2e07921b89ee
* Version Independent ID: 0325cc56-f493-07e5-3792-249c684fca85
* Content: [What's new? Release notes - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/whats-new?utm_source=substack&utm_medium=email)
* Content Source: [docs/fundamentals/whats-new.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/whats-new.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by ManoharLakkoju-MSFT** [comment]
@gerbermarco 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@gerbermarco 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by OWinfreyATL** [comment]
Hey @gerbermarco

Thanks for bringing this to our attention! I have created an internal work item, and this should be updated soon.


Thanks again!

#please-close
