### ISSUE TITLE
[Feedback] Tutorial: Microsoft Entra SSO integration with Zendesk

### ISSUE THREAD

**Issue by littlefitzie14** [MicrosoftDocs/entra-docs#524]
Under [Configure Microsoft Entra SSO](https://learn.microsoft.com/en-us/entra/identity/saas-apps/zendesk-tutorial#configure-microsoft-entra-sso) step **5b**, for _configuring Identifier (Entity ID)_, the user will want to enter the URL **without** `https://` or else they'll get an error. Source: I'm a TSSE for Zendesk

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16ae6014-a5f6-03f3-4ad4-4425cfe5b6ca
* Version Independent ID: 1d3d0543-89f7-180a-e52a-b5668a314e6a
* Content: [Tutorial: Microsoft Entra SSO integration with Zendesk - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/zendesk-tutorial)
* Content Source: [docs/identity/saas-apps/zendesk-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/zendesk-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@littlefitzie14 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-hgampala** [comment]
@littlefitzie14, thanks for raising the issue!!
we created a PR for the identifier value changes in the document and the changes will live within 2-3 working days.
#please-close

**Comment by richard-northumbria** [comment]
Value still incorrect and I hit the same issue
