### ISSUE TITLE
Guidance for "Ensure separate user accounts and mail forwarding for Global Administrator accounts" is insufficient

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#527]
For the section "Ensure separate user accounts and mail forwarding for Global Administrator accounts" there is a bullet item "Be sure those accounts have their email forwarded to a working mailbox."

But there are no details for how to accomplish this. It's not obvious what needs to be done, as the obvious action of setting the same email address on the admin account results in a duplicate email error.  I have not been able to find any other MS docs that provide the necessary detail.

So please add here guidance around using Other Emails or ExO Plus Addressing to accomplish this goal or a link to an appropriate doc that already contains this level of detail.  I've found 3rd party instructions, but nothing official in our docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 826a3309-03a5-60b4-aa4c-63f385150455
* Version Independent ID: 1d2e2f1c-2805-5cda-a4ad-76fedbc3f525
* Content: [Secure access practices for administrators in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/security-planning)
* Content Source: [docs/identity/role-based-access-control/security-planning.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/security-planning.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment]
@dloder0 
Thank you for bringing this to our attention.
I've delegated this to content author @rolyon, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@rolyon 
Could you please review add comments on this, update as appropriate.
