### ISSUE TITLE
Need content describing admin accounts without mailbox

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#528]
Part of our security guidance is for admin accounts to not have a mailbox. With that stance, many of these notifications do not occur. There needs to be a section that talks about using alternate/other email or ExO plus addressing to continue to receive notifications while maintaining the security stance of not having a mailbox for those accounts.  Also should have a section that talks about the limitation for PIM-eligible accounts like global admins to not receive notifications targeted to global admins while not active within PIM. And making use of break-glass accounts that are always active with a DL for their email to continue to receive those notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5a932ce-6046-f6a9-9b85-188c8530174c
* Version Independent ID: 196cb921-fbf8-6819-e0e2-8cd03fda4505
* Content: [Email notifications in Privileged Identity Management (PIM) - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-email-notifications)
* Content Source: [docs/id-governance/privileged-identity-management/pim-email-notifications.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/pim-email-notifications.md)
* Service: **entra-id-governance**
* Sub-service: **privileged-identity-management**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by barclayn** [comment]
@dloder0 thank you for your feedback. I have created an internal work item for us to keep track of this suggestion. #please-close
