### ISSUE TITLE
No Pager information?

### ISSUE THREAD

**Issue by Phenix51** [MicrosoftDocs/entra-docs#529]
Is there no Pager property that can used for Dynamic groups? My organization uses the Pager field in AD to list our main line/number for our each office location. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7a4070-1be8-5f1f-0092-68fb6b9e2305
* Version Independent ID: cd34312f-b507-affe-555e-1e0c63e7d494
* Content: [Rules for dynamically populated groups membership - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-membership)
* Content Source: [docs/identity/users/groups-dynamic-membership.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-dynamic-membership.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by ManoharLakkoju-MSFT** [comment]
@Phenix51 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Phenix51 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.
