### ISSUE TITLE
Incorrect limitations mentioned

### ISSUE THREAD

**Issue by the-sentinental-guy** [MicrosoftDocs/entra-docs#530]
The limitations section currently states that only 5 tenants can be linked using MTO while we do see an option of connecting up to 50 tenants in the portal itself.
Kindly correct this.

https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/multi-tenant-organization-overview#limits
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94ff49b6-b5fe-df1a-c359-c81006998929
* Version Independent ID: 7e765471-f9ba-61e7-e30a-bad2f16c66f6
* Content: [What is a multitenant organization in Microsoft Entra ID? (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/multi-tenant-organizations/multi-tenant-organization-overview#multitenant-organization-example)
* Content Source: [docs/identity/multi-tenant-organizations/multi-tenant-organization-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/multi-tenant-organizations/multi-tenant-organization-overview.md)
* Service: **entra-id**
* Sub-service: **multitenant-organizations**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment]
@the-sentinental-guy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by the-sentinental-guy** [comment]
@Naveenommi-MSFT Please check and confirm soon. Need a confirmation that the limit (of 50) in the MTO portal is not conflicting with the limit (of 5) mentioned here.

**Comment by SaibabaBalapur-MSFT** [comment]
@the-sentinental-guy Thank you for the follow-up. We are awaiting confirmation from the PG team to update this document.

**Comment by SaibabaBalapur-MSFT** [comment]
@the-sentinental-guy 
We will close this thread for now. Once I receive confirmation from the PG team, I'll update the status here. If you have any further questions regarding the documentation, please tag me in your reply, and I'll be happy to continue the conversation.
