### ISSUE TITLE
Update docs for AzureADHybridAuthenticationManagement with MgGraph (Graph API)

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/entra-docs#531]
Please update the docs on how to use "AzureADHybridAuthenticationManagement" with the Module "Microsoft.Graph" instead of "AzureAD"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b27a01-622e-d980-83f2-1ed27060613b
* Version Independent ID: e6472e15-10d7-bd4a-da02-558f2774dbaf
* Content: [Passwordless security key sign-in to on-premises resources - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises#install-the-azureadhybridauthenticationmanagement-module)
* Content Source: [docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@weyCC81 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@weyCC81 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by Justinha** [comment]
@weyCC81 thanks for raising this. The engineering team has a work item to track the need to replace this option. There's dependencies to be worked out, and we don't have an ETA at this time. #please-close
