### ISSUE TITLE
Missing Custom Claims information

### ISSUE THREAD

**Issue by DevopsMercenary** [MicrosoftDocs/entra-docs#534]
in https://learn.microsoft.com/en-us/entra/identity/saas-apps/aws-single-sign-on-tutorial#configure-microsoft-entra-sso

"Configure Microsoft Entra SSO"

Step 8. Prodvides the default details but states "AWS IAM Identity Center application expects the SAML assertions in a **specific format,** which requires you to add custom attribute mappings to your SAML token attributes configuration. The following screenshot shows the list of default attributes."

There is no information on what the specific format is or needs to be or how to configure it

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8e131bf-99d7-a850-a597-ac02b9f6c3a9
* Version Independent ID: a27625d3-cf35-ffaf-5734-d1a2bbcdd60c
* Content: [Tutorial: Microsoft Entra SSO integration with AWS IAM Identity Center (successor to AWS Single Sign-On) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/aws-single-sign-on-tutorial)
* Content Source: [docs/identity/saas-apps/aws-single-sign-on-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/aws-single-sign-on-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by ManoharLakkoju-MSFT** [comment]
@DevopsMercenary 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@DevopsMercenary 
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd 
Can you please check and add your comments on this doc update request as applicable.

**Comment by v-hgampala** [comment]
@DevopsMercenary, the text 'Special format' refers to the fixed format of attributes to mentioned at Entra side as provided in the screenshot, there no any particular context or configuration about it -
<img width="406" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/102347245/245b2039-671d-48a5-aee0-06725ab687bb">
