### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/entra-docs#535]
In the license overview and the csv file the Product:
"Microsoft Teams EEA" with SKU "7e74bd05-2c47-404e-829a-ba95c66fe8e5" is missing.
Please add it.

How is this going to work when this github is closed? In the past the missing licenses were added very quickly. With the new feedback system, will this also be guaranteed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by Nicholak-MS** [comment]
Hi @joergrenn I have added the Teams EEA SKU to the online table and the downloadable CSV. The changes will publish later today. 

Can you share additional details on the github closing question you posed? I am not aware of changes here.

**Comment by joergrenn** [comment]
Hello @Nicholak-MS ,

thanks for adding the SKU.

> Can you share additional details on the github closing question you posed? I am not aware of changes here.

I mean this announcement from MS, that github issues will be replaced by a new feeedback system.
The "new feeback" system will be a step back in terms of beeing able to get responses on issues and being involved.
<img width="925" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/62641471/67357d7d-3e91-4a2e-860a-a353fc76e0cb">

**Comment by Nicholak-MS** [comment]
Thanks @joergrenn appreciate the context. I took a look at the article you linked to and it looks like submitted feedback will go to the content writers (me) so I would have visibility into any feedback that is submitted for this particular article. So I can action any missing SKU's from that mechanism. 

Thanks
Nick

**Comment by Naveenommi-MSFT** [comment]
@Nicholak-MS 
Thank for your response.

**Comment by Nicholak-MS** [comment]
#Please-Close
