### ISSUE TITLE
Outdated Link

### ISSUE THREAD

**Issue by ines-lehmann** [MicrosoftDocs/entra-docs#536]
The link for the referenced knowledge base article 3047486 (https://launchpad.support.sap.com/#/notes/3047486) is not available anymore. It would be great if you could update the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56401d85-b771-94ed-5505-c0ba929ba27b
* Version Independent ID: d7a38614-2897-1c94-5d24-120431cb018a
* Content: [Microsoft Entra ID and SAP SuccessFactors integration reference - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/sap-successfactors-integration-reference)
* Content Source: [docs/identity/app-provisioning/sap-successfactors-integration-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/sap-successfactors-integration-reference.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Naveenommi-MSFT** [comment]
@ines-lehmann 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@ines-lehmann 
Thank you for bringing this to our attention.
I've delegated this to content author @kenwith, who will review it and offer their insightful opinions.

**Comment by kenwith** [comment]
Thank you for the catch and taking the time to open an issue. I have contacted the product team to get an updated link and am removing the dead link in the meantime. 

#please-close
