### ISSUE TITLE
poor wording

### ISSUE THREAD

**Issue by Curtmcgirt** [MicrosoftDocs/entra-docs#54]
i think the sentence "Global Administrator and Global Reader can see all access reviews." should read "Global Administrator and Global Reader can see history reports for all access reviews."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 706805d0-10bf-a3aa-5c86-b3099dd8af3b
* Version Independent ID: 54485263-aebd-fed6-820c-3f4824742a6a
* Content: [Create and manage downloadable access review history report - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/access-reviews-downloadable-review-history)
* Content Source: [docs/id-governance/access-reviews-downloadable-review-history.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/access-reviews-downloadable-review-history.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by SaibabaBalapur-MSFT** [comment]
@Curtmcgirt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Curtmcgirt 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
https://github.com/MicrosoftDocs/entra-docs-pr/pull/823

**Comment by Curtmcgirt** [comment]
The page still says "Global Administrator and Global Reader can see all access reviews." should this issue be closed when the change wasn't made?

On Dec 12, 2023 11:54 PM, AjayBathini-MSFT ***@***.***> wrote:

Closed #54<https://github.com/MicrosoftDocs/entra-docs/issues/54> as completed.
