### ISSUE TITLE
Suggestion: Custom security attributes documentation - Add brief hint on SAML custom claim

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/entra-docs#540]
Might be good to add in the FAQ if these attributes can be used for Enterprise Applications / attribute claims?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43c892af-3e7a-7475-bea4-e49d33afc7a6
* Version Independent ID: 88355bde-bac2-943e-08f8-fd5f2ecf707b
* Content: [Assign, update, list, or remove custom security attributes for a user - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/users-custom-security-attributes?toc=%2Fentra%2Ffundamentals%2Ftoc.json&bc=%2Fentra%2Ffundamentals%2Fbreadcrumb%2Ftoc.json&tabs=ms-powershell)
* Content Source: [docs/identity/users/users-custom-security-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/users-custom-security-attributes.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment]
@jbostoen 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@jbostoen 
Thanks for your contribution. Please add your suggestions in below link, so our production team can review it and update the same.
[feedback · Community (azure.com)](https://feedback.azure.com/d365community)
