### ISSUE TITLE
What does the "Office" check box actually do?

### ISSUE THREAD

**Issue by bku-bezell** [MicrosoftDocs/entra-docs#541]
Missing information on what the "Office" check box actually does.

Navigate to MS Entra portal > Protection > Authentication methods > Voice call > Configure

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd8e9708-dae9-55bb-4bcf-b2bad768b695
* Version Independent ID: e78950ad-e28a-a3be-b526-c77bfba7e82c
* Content: [Phone authentication methods - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-phone-options#mobile-phone-verification)
* Content Source: [docs/identity/authentication/concept-authentication-phone-options.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-phone-options.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@bku-bezell 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@bku-bezell 
Thank you for bringing this to our attention.
I've delegated this to content author @Justinha, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@Justinha 
Could you please review add comments on this, update as appropriate.

**Comment by Justinha** [comment]
@bku-bezell thanks for asking about this and sorry for delay. The legacy MFA policy has different options for mobile phone, which can do text or voice, and office phone is, which voice call only. The topic explains more in this section: https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-phone-options#office-phone-verification

And more info about migration to the newer Authentication methods policy at https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-authentication-methods-manage#sms-and-voice-calls 

If you want to add anything more specific, could you kindly submit a pull request? SMEs will review your submission for accuracy.

#please-close
