### ISSUE TITLE
Additional URL to add to the "Allow access to URLs" section

### ISSUE THREAD

**Issue by darylnz** [MicrosoftDocs/entra-docs#543]
Hi there,

We have found that an additional URL is necessary to add an additional URL to the list of "Allow access to URLs" if you have a conditional access policy that requires accepting a configured "Terms of Use Policy"

tokenprovider.termsofuse.identitygovernance.azure.com 

Regards,
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 861ceb04-ecea-4eb3-62b5-14163d12e3f2
* Version Independent ID: edac4607-e5d1-4d17-0af5-9ea432bfc5c6
* Content: [Add an on-premises application for remote access through application proxy in Microsoft Entra ID. - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-add-on-premises-application)
* Content Source: [docs/identity/app-proxy/application-proxy-add-on-premises-application.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/application-proxy-add-on-premises-application.md)
* Service: **entra-id**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AjayBathini-MSFT** [comment]
@darylnz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@darylnz 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
