### ISSUE TITLE
Test SSO needs more details

### ISSUE THREAD

**Issue by mcm-ham** [MicrosoftDocs/entra-docs#545]
The `Test SSO` section could do with more details.

* It's not clear what SP and IDP are, I suggest displaying as `Service Provider (SP)` and `Identity Provider (IdP)` the first time it's used in the article, had to google what these were.
* How can "Test this application" test both SP and IdP flows? It doesn't mention where to find the button, discovered it under Single sign-on" page. At end of section it mentions "if configured in SP mode" where do we configure this mode?
* It says you can also test the app in your MyApps, however even though I'm added to the app and in app properties "Visible to users?" I cannot see the app under MyApps. Eventually I discovered you have to install the "My Apps Secure Sign-in Extension" and access the MyApps page from that extension now it works.
* What is the "AWS Single-Account Access Sign-on URL" is this the same as the https://docs.aws.amazon.com/signin/latest/userguide/console-sign-in-tutorials.html?
* Where do you find the signin URL to give to users? If I go to the app registration and try "Home page URL" it doesn't work. Eventually discovered "User access URL" under app properties works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8fa5814d-91e2-2f75-77e7-62a8597f340c
* Version Independent ID: 458e93d7-a180-4c2f-5077-9b9d124d726a
* Content: [Tutorial: Microsoft Entra SSO integration with AWS Single-Account Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/amazon-web-service-tutorial)
* Content Source: [docs/identity/saas-apps/amazon-web-service-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/amazon-web-service-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@mcm-ham 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by jeevansd** [comment]
@mcm-ham AWS only support IDP initiated SSO and Service Provider flow is not supported. If you add the application AWS Single account access from the App gallery you dont need to populate the Sign on URL and keep that blank. When you use the Test Single sign on button then it will perform the flow by taking the user to the MyApps Page and invoking the app link from that. So it will perform the IDP initiated SSO flow in this case. When you populate the Sign on URL for the app in the URL configuration then only Entra ID will perform the SP initiated flow. Please do let me know if you still have questions.

**Comment by ManoharLakkoju-MSFT** [comment]
@jeevansd 
Thanks for your inputs.

@mcm-ham 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by ManoharLakkoju-MSFT** [comment]
@mcm-ham 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
