### ISSUE TITLE
Verbiage around synced users and tenants is confusing

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#546]
There are multiple ways to interpret the ambiguous Synced User Conversion section.

The document needs to be more explicit when discussing synced users and tenants.  Does synced mean, synced directly into this tenant and B2B converted, so this new process now reverses that initial B2B conversion? Or is it synced as a cross-tenant sync scenario? So then does "tenant" refer to the home tenant where the user is a normal member, or the converting tenant, where the B2B user object was created by cross tenant sync?  This section is confusing as "synced" can be interpreted as either synced from on-prem to some tenant and then B2B invited, or synced as in cross-tenant sync creating the B2B user via automated invitation.  You might not have visibility to know if that B2B user authenticates in their home tenant via cloud auth, PHS or federation, as they possibly originate in a tenant you don't have rights to.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87999564-0514-26cf-1b85-86f4a59d4c69
* Version Independent ID: 87999564-0514-26cf-1b85-86f4a59d4c69
* Content: [Convert external users to internal users (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/convert-external-users-internal)
* Content Source: [docs/identity/users/convert-external-users-internal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/convert-external-users-internal.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by Naveenommi-MSFT** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dloder0 
I'm going to assign this to the document author so they can take a look at it accordingly.

@barclayn 
please review it.
