### ISSUE TITLE
If there's a catastrophic outage, what is MS's data backup plan, and what is the RTO, RPO.

### ISSUE THREAD

**Issue by laurenzha** [MicrosoftDocs/entra-docs#547]
How MS decide which of the datacenters in Australia to use if I choose the region as Australia. (For example, Australia East DC is the default DC and MS will auto mirror the data to Australia South?) 

Can we understand the data transformation between DCs is real-time and 0 loss? If not, what is RTO, RPO?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8360f11-7706-ab3c-8c1e-a6298d610bb8
* Version Independent ID: 4373debc-5b1b-af86-9231-387b7e7506a5
* Content: [Microsoft Entra ID and data residency - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/data-residency)
* Content Source: [docs/fundamentals/data-residency.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/data-residency.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by Naveenommi-MSFT** [comment]
@laurenzha 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@laurenzha Based on Microsoft recommends using geo-redundant storage to protect against regional outages. With geo-redundant storage, three additional copies of your Azure Storage blobs and tables are stored in a different region. In the event of a complete regional outage or a disaster in which the primary region is not recoverable, Azure remaps all of the DNS entries to the geo-replicated region. 

For detailed information on Microsoft’s data residency in Australia, including how data is handled and specific commitments, you can refer to the official Microsoft documentation. It’s also recommended to review the service-level agreements (SLAs) for the specific Microsoft services you are using to understand the guaranteed RTO and RPO levels.

When you choose the region as Australia, Microsoft will automatically select the default datacenter for that region, which is Australia East. However, customers can also choose to use the Australia Southeast datacenter instead. 

Regarding data transformation between datacenters, Microsoft provides several options for replicating data, including locally redundant storage (LRS), zone-redundant storage (ZRS), and geo-redundant storage (GRS). LRS maintains three copies of your data within a single facility in a single region, while ZRS maintains three copies of your data across two to three facilities to provide higher durability than LRS. GRS maintains six copies of your data, with three copies in the primary region and three copies in a secondary region hundreds of miles away from the primary region. In the event of a failure at the primary region, Azure Storage fails over to the secondary region. While Microsoft does not specify that data transformation between datacenters is real-time and 0 loss, these replication options are designed to provide high durability and availability for customer data.

**Comment by SaibabaBalapur-MSFT** [comment]
@laurenzha 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
