### ISSUE TITLE
Contradiction in the document

### ISSUE THREAD

**Issue by mlibenocg** [MicrosoftDocs/entra-docs#548]
Document says this at the beginning:
Required permissions
Both admin and non-admin users can download user lists.

Yet in the very next section, it states, "Sign in to the Microsoft Entra admin center as at least a Global Administrator."

A global administrator is certainly an admin user. Further, there should be another administrative role with required permissions that is not global administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7800fcb4-d251-f271-bc12-9377cd0407fa
* Version Independent ID: 319b62fc-cea7-1add-559b-bb2a35b3a0ad
* Content: [Download a list of users in the Azure portal - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/users-bulk-download?source=docs)
* Content Source: [docs/identity/users/users-bulk-download.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/users-bulk-download.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by ManoharLakkoju-MSFT** [comment]
@mlibenocg 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.
