### ISSUE TITLE
Add supporting text

### ISSUE THREAD

**Issue by danwdavey** [MicrosoftDocs/entra-docs#55]
The 'Enable with Conditional Access policy' section could use some additional wording given recent changes around sign in frequency. Previously the conditions were 'Grant, Require MFA' we have now added sign in frequency as a session control recommendation with no context as to why.

This page has some additional useful wording to explain why which could be re-used; https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-session-lifetime#require-reauthentication-every-time

This line in particular would be good to highlight the consequences of selecting 'every time';
"When administrators select Every time, it will require full reauthentication when the session is evaluated."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75919910-c2c4-b678-44c0-62ed63fe8a1a
* Version Independent ID: c82be269-3182-f9f5-2d88-c95b258f969e
* Content: [Risk policies - Microsoft Entra ID Protection](https://learn.microsoft.com/en-us/entra/id-protection/howto-identity-protection-configure-risk-policies#sign-in-risk-policy-in-conditional-access)
* Content Source: [docs/id-protection/howto-identity-protection-configure-risk-policies.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/howto-identity-protection-configure-risk-policies.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@danwdavey 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@danwdavey 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@MicrosoftGuyJFlo 
please review it.

**Comment by danwdavey** [comment]
[like]  Dan Davey reacted to your message:
________________________________

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for the feedback. Addressing with a PR in our private repo. Should publish later today.
