### ISSUE TITLE
Exchange Requirements

### ISSUE THREAD

**Issue by ronbuie** [MicrosoftDocs/entra-docs#551]
Hi,

Trying to get some confirmation on this:  For cloud sync, is an Actual running Exchange Server required or just that the latest Exchange schema has been updated in the environment?

And - if the Exchange Schema has been updated and the Exchange Server turned off and all management is being done using PowerShell at this time, with hybrid functions removed, is this viewed as hybrid for cloud sync purposes?

**Comment by Naveenommi-MSFT** [comment]
@ronbuie 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@ronbuie 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
