### ISSUE TITLE
Confirm-MgDomain has no -ForceTakeover option

### ISSUE THREAD

**Issue by jasonfritts** [MicrosoftDocs/entra-docs#552]
Per this doc Confirm-MgDomain should have a -ForceTakeover parameter.  It does not have this parameter however.  To perform a forceful takeover you have to revert back to old MSOL module and the Confirm-MsolDomain -ForceTakeover Force instructions found in this [old github commit](https://github.com/MicrosoftDocs/entra-docs/blob/2ff8573fc33eb8d5a67ca61500ed46a7f059501c/docs/identity/users/domains-admin-takeover.md#powershell-example) of this same article

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd934d58-08f8-a3ca-2686-0006b0b8f74a
* Version Independent ID: 84d9cab3-09b7-95ba-83ea-435ca0ccbb47
* Content: [Admin takeover of an unmanaged directory - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/domains-admin-takeover)
* Content Source: [docs/identity/users/domains-admin-takeover.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/domains-admin-takeover.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@jasonfritts 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
