### ISSUE TITLE
Does the "UserAgentApplication" method exist in MSAL.js 2.30.0?

### ISSUE THREAD

**Issue by osamum** [MicrosoftDocs/entra-docs#555]
[Enter feedback here]
An error occurs on the first line of the sample code below.

https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-javascript-spa#use-the-msal-to-sign-in-the-user

I checked the contents of msal-browser.js on the CDN below that is referenced by the sample application, but the method "UserAgentApplication" was not found.

https://https://alcdn.msauth.net/browser/2.30.0/js/msal-browser.js

Shouldn't we be calling "PublicClientApplication" here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c6d2219-cb28-5527-1079-6e3195cad282
* Version Independent ID: 70c2aad0-6883-51a9-fed7-01be62302483
* Content: [Tutorial: Create a JavaScript single-page application that uses the Microsoft identity platform for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-javascript-spa#use-the-msal-to-sign-in-the-user)
* Content Source: [docs/identity-platform/tutorial-v2-javascript-spa.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-v2-javascript-spa.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by OwenRichards1** [comment]
Thanks for the feedback @osamum - it looks like you're using an outdated article, which is currently in the process of being deprecated.

Alternatively, you can use our following quickstart to use a newer sample:

[Quickstart: Sign in users in a single-page app (SPA) and call the Microsoft Graph API using JavaScript](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-single-page-app-javascript-sign-in)

The full range of JavaScript samples available for identity can be found [here](https://github.com/OwenRichards1/microsoft-authentication-library-for-js/tree/dev/samples). 

I will close this issue for now, but feel free to let us know if you require further assistance.

Thanks!

**Comment by OwenRichards1** [comment]
#pleaseclose

**Comment by AjayBathini-MSFT** [comment]
Answered by Author
