### ISSUE TITLE
Azure AD B2C being part of Microsoft Entra External ID or not

### ISSUE THREAD

**Issue by smtl** [MicrosoftDocs/entra-docs#556]
This page, https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview, shows and describes Azure AD B2C under "Microsoft Entra External Identities"

This FAQ, https://learn.microsoft.com/en-us/entra/external-id/customers/faq-customers, has a question and answer as follows:

Why is Azure AD B2C not part of Microsoft Entra External ID?
Microsoft Entra External ID and Azure AD B2C are two separate platforms powered by ESTS and IEF respectively. Microsoft Entra External ID is our new converged platform which is future proof and developer friendly to meet all your identity needs – B2E, B2B and B2C. At the same time, we will still continue to support Azure AD B2C as a separate product offering with no change in SLA, and we’ll continue investments in the product to ensure security, availability, and reliability.

Even though Microsoft Entra External ID (for customers) is in preview, the messaging is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed572d43-0c0e-4b91-7297-9d2158830575
* Version Independent ID: 6920706a-8de6-af57-7457-451171d53522
* Content: [Microsoft Entra External ID overview - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview)
* Content Source: [docs/external-id/external-identities-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/external-identities-overview.md)
* Service: **entra-external-id**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@smtl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msmimart** [comment]
Hi @smtl, you're right, this messaging is being clarified and the Microsoft Entra External ID overview is undergoing updates. Thanks so much for your feedback!

**Comment by AjayBathini-MSFT** [comment]
@smtl 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
