### ISSUE TITLE
Debian 12 erroneously listed as supported distro

### ISSUE THREAD

**Issue by LeonarddeR** [MicrosoftDocs/entra-docs#557]
> While Debian 12 is now listed as supported, i'm not seeing the aadsshlogin package in the Microsoft package repository. So honestly I'm not convinced that this will actually work. Has anyone confirmed this?

_Originally posted by @LeonarddeR in https://github.com/MicrosoftDocs/azure-docs/issues/115244#issuecomment-1970550707_
            
> @MicrosoftGuyJFlo I have just tried this and even though listed, aadsshlogin is still not supported for Debian 12. Therefore the documentation is now showing incorrect information.

_Originally posted by @LeonarddeR in https://github.com/MicrosoftDocs/azure-docs/issues/115244#issuecomment-1981177426_
            
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2ede563-b873-0bc3-959f-69e555f0efcc
* Version Independent ID: 8471d9e4-6c79-0cf1-c5ed-50c58e1b92aa
* Content: [Log in to a Linux virtual machine in Azure by using Microsoft Entra ID and OpenSSH - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-linux)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-linux.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-linux.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@LeonarddeR 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by MicrosoftGuyJFlo** [comment]
#label:"awaiting-product-team-response"
@SanDeo-MSFT Please take a look at this issue.

**Comment by LeonarddeR** [comment]
This was indeed fixed, the extension is now available for Debian 12.
