### ISSUE TITLE
Using Password based single sign-on with a proxy

### ISSUE THREAD

**Issue by jesshaines** [MicrosoftDocs/entra-docs#560]
There is no mention on this page about how to work with proxies and sign-in pages. 
After working with a customer attempting to use this feature, we found that when using an Entra ID proxy, the **external** URL must be used as the sign-on URL or the Sign-on page will not be detected and Metadata cannot be saved. We both felt that this little Note would have saved a lot of time for this support case. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e973cbe2-df0f-d310-b439-17e14a0af060
* Version Independent ID: b4649ad0-6baa-a2e4-dd13-20593f10c09a
* Content: [Add password-based single sign-on to an application - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/configure-password-single-sign-on-non-gallery-applications)
* Content Source: [docs/identity/enterprise-apps/configure-password-single-sign-on-non-gallery-applications.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/configure-password-single-sign-on-non-gallery-applications.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by AjayBathini-MSFT** [comment]
@jesshaines 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@jesshaines 
Thank you for bringing this to our attention.
I've delegated this to content author @omondiatieno, who will review it and offer their insightful opinions.

**Comment by kenwith** [comment]
I am not sure this is referring to the application proxy functionality or generally just a proxy on a network. Here is an article on application proxy that might be helpful. If this is helpful we can add it to this article. https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-add-on-premises-application#add-an-on-premises-app-to-microsoft-entra-id

**Comment by omondiatieno** [comment]
As we wait for the author of this issue to response to the previous message, we'll proceed to close this issue and track it internally in our ADO.

#please-close
