### ISSUE TITLE
Creating with portal no longer an option yet doc references this

### ISSUE THREAD

**Issue by tcharetteacerta** [MicrosoftDocs/entra-docs#561]
FYI - Doc mentions using the functions tab in the overview to create a function in the UI, yet this no longer appears to be an option.

Only VS Code Desktop and Other Editors or CLI

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb5253a-691d-7805-ca24-e7f47b7cd641
* Version Independent ID: 8eb5253a-691d-7805-ca24-e7f47b7cd641
* Content: [Create a REST API with a token issuance start event for Azure Functions (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-tokenissuancestart-setup)
* Content Source: [docs/identity-platform/custom-extension-tokenissuancestart-setup.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-tokenissuancestart-setup.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by PesalaPavan** [comment]
@tcharetteacerta ,
Thanks for your feedback! We will investigate and update as appropriate.
