### ISSUE TITLE
Outdated Jedox support contact information

### ISSUE THREAD

**Issue by Xetrill** [MicrosoftDocs/entra-docs#562]
The way to contact Jedox support has changed and sadly they don't bounce messages to the invalid `support@jedox.com` address.
The new way is through https://my.jedox.com according to their documentation ([#1](https://knowledgebase.jedox.com/jedox/security/saml.htm), [#2](https://knowledgebase.jedox.com/jedox/customer-portal.htm)).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdbc1c13-fdc1-48f0-7042-fb53972aa8d8
* Version Independent ID: ff9517a7-2151-bd14-0761-ceece38a2235
* Content: [Tutorial: Microsoft Entra single sign-on (SSO) integration with Jedox - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/jedox-tutorial)
* Content Source: [docs/identity/saas-apps/jedox-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/jedox-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by AjayBathini-MSFT** [comment]
@Xetrill 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-hgampala** [comment]
@Xetrill, thanks for the information, we're updating the document with the proper support contact.
#please-close
