### ISSUE TITLE
Common questions - Risk Levels

### ISSUE THREAD

**Issue by amasse3** [MicrosoftDocs/entra-docs#563]
I think we can add a [!NOTE] that risk detections are continuously improving. Risk level calculations and detection frequency for a particular risk may fluctuate based on these changes. We recommend using risk to inform access decisions, not make decisions. Prefer tight grant and session controls vs 'block' for a risk level to avoid user disruption due to false positives.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a1385f-b90a-e7b4-8cbd-f25aeb8b3c49
* Version Independent ID: d468eb75-88a9-b1aa-7fb3-19ebb4faa179
* Content: [What are risks in Microsoft Entra ID Protection - Microsoft Entra ID Protection](https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks)
* Content Source: [docs/id-protection/concept-identity-protection-risks.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/concept-identity-protection-risks.md)
* Service: **entra-id-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@amasse3 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@amasse3 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
@amasse3 thanks! We are working on multiple docs updates for ID Protection. Passed the feedback to the PG so they can review and we can add it in.

#please-close
