### ISSUE TITLE
New SAP Concur Provisioning?

### ISSUE THREAD

**Issue by JordanMastel** [MicrosoftDocs/entra-docs#564]
Hello, is there a new version of SAP Concur Provisioning available so that way we can keep our users in sync with Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e98995c-09f1-2c1d-fd55-27f978e8262c
* Version Independent ID: 40a8b6e7-dae3-172a-5373-896372b30174
* Content: [Tutorial: Configure Concur for automatic user provisioning with Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/concur-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/concur-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/concur-provisioning-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by AjayBathini-MSFT** [comment]
@JordanMastel 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@JordanMastel 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by JordanMastel** [comment]
Thanks, it would be nice if there was a new option.

Jordan Mastel
System Administrator II| Information Technology Services
Grand Canyon Education
3300 W. Camelback Rd. | Phoenix, AZ | 85017
602-639-7700 Office | 602-639-8319 Direct
***@***.******@***.***> | gce.com<https://www.gce.com/>

**Comment by v-hgampala** [comment]
@twimmers, Can you please check and add your comments on this request as applicable.

**Comment by CelesteDG** [comment]
@jeevansd @twimmers @v-hgampala We are migrating all GitHub issues to ADO as we switch our feedback mechanism to UUF. Please either address the issue, or close and track it in ADO no later than June 10, 2024. Thank you.

**Comment by v-hgampala** [comment]
we are working on the issue, will reflect the changes into the main article soon.
#please-close
