### ISSUE TITLE
Using ccrecipients with New-MgInvitation

### ISSUE THREAD

**Issue by s-fordham** [MicrosoftDocs/entra-docs#565]
How can I use ccrecipients with New-MgInvititation?

I need to be able to add a CC address for guest invite by bulk, but I cannot work out the parameter to use to include a CC address..

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7ea676e-0678-9e2d-e009-fb44587f93dd
* Version Independent ID: 40b581da-26ea-2890-4a78-54b29f5dc610
* Content: [Quickstart: Add a guest user with PowerShell - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/b2b-quickstart-invite-powershell)
* Content Source: [docs/external-id/b2b-quickstart-invite-powershell.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/b2b-quickstart-invite-powershell.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by AjayBathini-MSFT** [comment]
@s-fordham 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by s-fordham** [comment]
> @s-fordham Thanks for your feedback! We will investigate and update as appropriate.


Finally cracked it, having found "torecipients" in the code snippets for New-MgUserMessage i got the hash table correct for cc recipients. I recommend adding an example so nobody else struggles like i have for two days!!.



```
$InvitedUserMessageInfo = @{
	CustomizedMessageBody = "Welcome!"
	ccRecipients = @(
		@{
			emailAddress = @{
				address = "user@ccaddress.com"
			}
		}
	)
}

New-MgInvitation -InvitedUserDisplayName "User" -InvitedUserEmailAddress "user@logonaddress.com" -InviteRedirectUrl "https://myapplications.microsoft.com" -InvitedUserMessageInfo $InvitedUserMessageInfo -SendInvitationMessage -Debug
```

**Comment by SaibabaBalapur-MSFT** [comment]
@s-fordham 
Thanks for your contribution. Please add your feedback in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)
