### ISSUE TITLE
Something wrong with the parentheses

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/entra-docs#566]
Hello,

please review this string: "Example : user is performing certificate-based authentication (CBA) and no certificate is sent **(or Proxy removes) the users certificate in the sign-in request**."

I think it should be "Example : user is performing certificate-based authentication (CBA) and no certificate is sent **(or Proxy removes the user's certificate in the sign-in request)**." Also 'users certificate' should be 'user's certificate'

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a826ee6f-f457-7109-9f77-67c57977d4e7
* Version Independent ID: 11766f27-492e-a579-dced-8a42528cbb47
* Content: [Microsoft Entra authentication & authorization error codes - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes)
* Content Source: [docs/identity-platform/reference-error-codes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-error-codes.md)
* Service: **identity-platform**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by AjayBathini-MSFT** [comment]
@QueryCoordinator 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@QueryCoordinator 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
