### ISSUE TITLE
Article Update for Postman collection link

### ISSUE THREAD

**Issue by ALMSLabs** [MicrosoftDocs/entra-docs#567]
[Update at step 12 in section "Create an inventory of current Okta applications" needed; New link: https://app.getpostman.com/run-collection/febec0ced153d9cd3db1]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07e1a021-a944-1814-5e91-d1c53e1bf27c
* Version Independent ID: ef33c18c-d416-cf30-464b-f323c86ef5a9
* Content: [Tutorial to migrate your applications from Okta to Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/migrate-applications-from-okta)
* Content Source: [docs/identity/enterprise-apps/migrate-applications-from-okta.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/migrate-applications-from-okta.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @Gargi-Sinha
* Microsoft Alias: **gasinh**

**Comment by SaibabaBalapur-MSFT** [comment]
@ALMSLabs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@ALMSLabs 
I'm glad to update that there are no issues with the [URL](https://app.getpostman.com/run-collection/377eaf77fdbeaedced17) available in this document.

<img width="571" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/111563669/85b089dd-ae9f-40d6-b739-aaffa9af61df">

Still if any concern. Please add your feedback in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)
