### ISSUE TITLE
custom gMSA not functioning as expected, it assigns more permissions on Root Domain Level while running wizard leveraging custom gMSA account | Bug? 

### ISSUE THREAD

**Issue by vamdevmishra** [MicrosoftDocs/entra-docs#568]
While configuring Microsoft Entra Provisioning Agent with [custom gMSA](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-prerequisites?tabs=public-cloud#custom-gmsa-account) Account, I have observed that it doesn’t honor custom gMSA account permissions, rather it stamps additional permissions on Domain Root Level.

As part of testing and pilot we assigned below permissions to one TestOU and found after installation it added new ACEs on Domain Root.

 
![image](https://github.com/MicrosoftDocs/entra-docs/assets/66116147/59df772d-3cb7-4b84-adbc-8bd5f06e87b5)

ACE added by gMSA account on Domain Root Level
 
![image](https://github.com/MicrosoftDocs/entra-docs/assets/66116147/a9a74c14-21a5-4db9-8f5d-152c18fc9001)

It also says in Configuration GUI that ‘Creating group managed service account’, although it doesn’t create new gMSA, validated whencreated AD attribute of this gMSA account.

 
![image](https://github.com/MicrosoftDocs/entra-docs/assets/66116147/4b8f3422-60ba-4764-89a6-f32d87d34f98)

Wondering Are these known issues, bugs or expected results ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 88fc98f5-0c60-1f46-2f02-3dad22b6632a
* Version Independent ID: 4d2ce2cc-94dd-6073-f145-5a0694e9b542
* Content: [Prerequisites for Microsoft Entra Cloud Sync in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-prerequisites?tabs=public-cloud)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-prerequisites.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-prerequisites.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@vamdevmishra 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@vamdevmishra 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
