### ISSUE TITLE
Broken link on page

### ISSUE THREAD

**Issue by jpdicicco** [MicrosoftDocs/entra-docs#569]
Link in the "License requirements" section is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1414bc2-4151-b667-65f5-b44f2bf582a1
* Version Independent ID: b93aee66-1769-8d98-fea5-ebca3a12d5fc
* Content: [Use Microsoft Entra groups to manage role assignments - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/groups-concept)
* Content Source: [docs/identity/role-based-access-control/groups-concept.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/groups-concept.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by SaibabaBalapur-MSFT** [comment]
@jpdicicco 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @jpdicicco 
I am able to access the link provided under the License Requirements section. For your reference, please find the screenshot below.
![image](https://github.com/MicrosoftDocs/entra-docs/assets/110587558/70cd5b8e-3653-4ecb-95e8-d13a8617b880)

**Comment by ManoharLakkoju-MSFT** [comment]
@jpdicicco 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
