### ISSUE TITLE
What is CBA with federation?

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/entra-docs#57]
It would be hugely beneficial to explain what CBA with federation is, how it differs from native CBA and what the authentication flow looks like. This article is raising a lot of confusion, because federation here can mean a lot of things:

- Federated auth where password is validated in AD FS
- certificate auth in AD FS
- federation with any other IdPs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f50b3f0-0af5-89f3-f29a-f73bf5bba678
* Version Independent ID: a4f5dae2-373d-38bb-dd1e-9fbbd7bb3703
* Content: [Certificate-based authentication with federation - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/certificate-based-authentication-federation-get-started)
* Content Source: [docs/identity/authentication/certificate-based-authentication-federation-get-started.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/certificate-based-authentication-federation-get-started.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@LijuV-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@LijuV-MSFT Certificate-based authentication (CBA) with federation is a method of authentication that allows users to authenticate with Azure Active Directory (Azure AD) using a client certificate on a Windows, Android, or iOS device when connecting to Microsoft mobile applications such as Microsoft Outlook and Microsoft Word, as well as Exchange ActiveSync (EAS) clients. 

Federation in this context refers to the use of a federated identity provider (IdP) such as Active Directory Federation Services (AD FS) to authenticate users. With CBA and federation, the client certificate is validated by the federated IdP, which then issues a security token that is sent to Azure AD for validation. 

In contrast, native CBA allows users to authenticate directly with X.509 certificates against their Azure AD for applications and browser sign-in, without the need for a federated IdP. 

The authentication flow for CBA with federation involves the following steps:
1. The user presents their client certificate to the federated IdP for validation.
2. The federated IdP issues a security token that includes the user's identity and other claims.
3. The security token is sent to Azure AD for validation.
4. Azure AD validates the security token and issues an access token that can be used to access the requested resource.

I hope this helps clarify things for you! Let me know if you have any further questions.

**Comment by SaibabaBalapur-MSFT** [comment]
@LijuV-MSFT I will check internally with the document author. As of now, we are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
