### ISSUE TITLE
Why is Microsoft Message Analyzer still mentioned.

### ISSUE THREAD

**Issue by teusrenes** [MicrosoftDocs/entra-docs#572]
Why is microsoft message analyzer still linked?
It is deprecated since 2019...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61df48bb-a963-b1f0-8f64-b55d0bd6904c
* Version Independent ID: 677de59f-a222-8905-11c0-a3ac619d8b56
* Content: [Integrate RDG with Microsoft Entra multifactor authentication NPS extension - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension-rdg)
* Content Source: [docs/identity/authentication/howto-mfa-nps-extension-rdg.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-nps-extension-rdg.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@teusrenes 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@just
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@teusrenes thanks for the heads up. I removed it. #please-close
