### ISSUE TITLE
Wrong link to 'Enable passwordless security key sign-in to Windows 10 devices.'

### ISSUE THREAD

**Issue by YoniGit** [MicrosoftDocs/entra-docs#573]
It seems that the link to:
 [Enable passwordless security key sign-in to Windows 10 devices](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key).

Should rather go to: https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b27a01-622e-d980-83f2-1ed27060613b
* Version Independent ID: e6472e15-10d7-bd4a-da02-558f2774dbaf
* Content: [Passwordless security key sign-in to on-premises resources - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises)
* Content Source: [docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@YoniGit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@YoniGit 
Thank you for bringing this to our attention.
I've delegated this to content author @Justinha, who will review it and offer their insightful opinions.

**Comment by Justinha** [comment]
@YoniGit thanks for raising this and sorry for delay. The link is right but the link text is outdated. It's been corrected and will appear no later than tomorrow. #please-close
