### ISSUE TITLE
Application missing

### ISSUE THREAD

**Issue by b-peixoto** [MicrosoftDocs/entra-docs#574]
The application "**Microsoft Power Query for Excel**" is missing in detailed list of services and applications that are included in the Conditional Access Office 365 App.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c83d2402-0113-e453-e103-a1abc4876531
* Version Independent ID: d638de2c-15f1-546d-05c0-06e3d7e62287
* Content: [Office 365 App in Conditional Access reference - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/reference-office-365-application-contents)
* Content Source: [docs/identity/conditional-access/reference-office-365-application-contents.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/reference-office-365-application-contents.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@b-peixoto 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
@b-peixoto do you have the GUID for the app because it is not called that inside the actual grouping.

**Comment by b-peixoto** [comment]
Application : Microsoft Power Query for Excel
Application ID : a672d62c-fc7b-4e81-a576-e60dc46e951d


________________________________
De : John Flores ***@***.***>
Envoyé : jeudi 28 mars 2024 21:50
À : MicrosoftDocs/entra-docs ***@***.***>
Cc : b-peixoto ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/entra-docs] Application missing (Issue #574)


@b-peixoto<https://github.com/b-peixoto> do you have the GUID for the app because it is not called that inside the actual grouping.

**Comment by MicrosoftGuyJFlo** [comment]
@b-peixoto I just checked and that GUID is not part of the Office 365 bundle of apps. A service dependency might be what is triggering your policy. 

I suggest checking the sign-in using the info provided in https://learn.microsoft.com/entra/identity/conditional-access/troubleshoot-conditional-access#service-dependencies. If you are still having an issue I would open a support case for further troubleshooting. 

#please-close
