### ISSUE TITLE
DEPRECATED!

### ISSUE THREAD

**Issue by cslammy** [MicrosoftDocs/entra-docs#575]
Admin.microsoft.com pages no longer look like your examples any longer.  Functionality has changed.
PLEASE PLEASE microsoft. You guys have money. You have lots of employees You guys are smart.  TAKE DOWN YOUR DEPRECATED CONTENT. it does admins like me a huge disservice to keep out of date instructional content online.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3c7993-0036-507f-f3eb-40845fa312c8
* Version Independent ID: 59f8fd79-2104-fed4-0b47-250a61b0138b
* Content: [Quickstart: Add a guest user and send an invitation - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/b2b-quickstart-add-guest-users-portal)
* Content Source: [docs/external-id/b2b-quickstart-add-guest-users-portal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/b2b-quickstart-add-guest-users-portal.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by AjayBathini-MSFT** [comment]
@cslammy 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by csmulligan** [comment]
Hi @cslammy thank you so much for your feedback. We’ve updated the article, and the changes should be published shortly.  Since the changes will publish shortly, I'll go ahead and close this issue.

In the description, you mentioned admin.microsoft.com. If you need any assistance with the Microsoft 365 admin center, you can visit [this link](https://learn.microsoft.com/en-us/microsoft-365/admin/?view=o365-worldwide).

Thanks again!

**Comment by csmulligan** [comment]
#please-close

**Comment by cslammy** [comment]
thank you. There are tons of deprecated web content from MS out there, and
it's not just confusing admins, it is poisoning answers from AI, who don't
know what is current.  I know MS is big into making $$ off of AI so you
guys should fix this.

I had no idea if I commented it was deprecated anyone would do anything.
