### ISSUE TITLE
Instructions do not match webpage

### ISSUE THREAD

**Issue by glittle** [MicrosoftDocs/entra-docs#577]
Instructions say:
1. Sign in to the [Microsoft Entra admin center](https://entra.microsoft.com/) as at least a [Domain Name Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#domain-name-administrator).

2. Browse to Identity > Settings > Domain names > Add custom domain.

However, I am a Global Admin and do not see Identity > Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 455c7ecb-4214-5ad1-dc68-88ff558e98c7
* Version Independent ID: 381e1b03-06cd-64ac-c811-9e15fa0c4457
* Content: [Add your custom domain - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/add-custom-domain#add-your-custom-domain-name)
* Content Source: [docs/fundamentals/add-custom-domain.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/add-custom-domain.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by AjayBathini-MSFT** [comment]
@glittle 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@glittle 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.

**Comment by barclayn** [comment]
@glittle I just tested this. Thank you for contacting us. I just checked this. It is under identity\settings\domain names. You may need to expand the side menu so all options are visible.  If you can't see it and you are logged on as global admin, please reach out to support for assistance.  #please-close
