### ISSUE TITLE
Add additional context for the "More information required" / "Is this info up to date" prompt.

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/entra-docs#58]
Some users may already be registered, however still receive prompts such as

!["is this info up to date](https://github.com/MicrosoftDocs/entra-docs/assets/6467813/5eac1cee-bc73-464c-970e-1264ceb13e1e)

Trying to understand the causes for this screen continued to lead me to this registration campaign article, however I think its not directly related, as the Authentication Context in the Entra ID logs state: 

`User authentication was blocked because they need to provide password reset information. Their next interactive sign in will ask them for this, which the app should trigger next.`

Can you please describe this parallel feature in a note or link to the relevant documentation at the bottom of the article? If you decide to describe it here, please also explain how frequently these prompts are expected to happen. I have users who have already registered their Authenticator App, and continue to see this screen a few times a year.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c8810aa-a874-83bd-1ce6-42617b75557e
* Version Independent ID: c5c460d5-e255-40a5-a8bf-2d930d39c392
* Content: [How to run a registration campaign to set up Microsoft Authenticator - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-mfa-registration-campaign)
* Content Source: [docs/identity/authentication/how-to-mfa-registration-campaign.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-mfa-registration-campaign.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @mjsantani
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@Mike-Crowley 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @Mike-Crowley 
The prompt you are describing may be related to the self-service password reset feature in Azure AD. When this feature is enabled, users are prompted to provide password reset information such as a phone number or email address. This information is used to verify the user's identity and allow them to reset their password if they forget it.

If a user has not provided this information or if the information they provided is out of date, they may be prompted to update it. This can happen periodically to ensure that the user's information is up to date and accurate.

The frequency of these prompts can vary depending on the settings configured by the administrator. By default, users are prompted to update their password reset information every 180 days. However, this can be changed by the administrator to a shorter or longer interval.

I hope this helps clarify the prompt you are seeing.

**Comment by ManoharLakkoju-MSFT** [comment]
@Mike-Crowley 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation

**Comment by Mike-Crowley** [comment]
Thanks. I was hoping it could be incorporated into the Docs, but I appreciate your comment. For others, it's here:

https://entra.microsoft.com/#view/Microsoft_AAD_IAM/PasswordResetMenuBlade/~/Registration/fromNav/Identity
