### ISSUE TITLE
More information required regarding troubleshooting

### ISSUE THREAD

**Issue by bballpaul4work** [MicrosoftDocs/entra-docs#581]
There should be more information regarding troubleshooting SSO to on-prem resources. Specifically when several devices/users are unable to access SQL/file shares, but others can.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d912434-0693-e158-f371-51b010f8a533
* Version Independent ID: 51892e2c-8bd5-df84-28a1-548bbf0d8d96
* Content: [How SSO to on-premises resources works on Microsoft Entra joined devices - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/device-sso-to-on-premises-resources?view=o365-worldwide)
* Content Source: [docs/identity/devices/device-sso-to-on-premises-resources.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/device-sso-to-on-premises-resources.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by AjayBathini-MSFT** [comment]
@bballpaul4work 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@bballpaul4work 
I'd recommend posting your question in https://azure.microsoft.com/en-us/support/community/. We'll follow up there. We will now proceed to close this thread. If there are further questions regarding this matter.
