### ISSUE TITLE
go

### ISSUE THREAD

**Issue by Rishoooz** [MicrosoftDocs/entra-docs#582]
victory

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c1e4aed-6ad2-33fa-52a6-a2ce8412bea1
* Version Independent ID: 5a20dd96-2fb0-5178-454b-ffa08619fae5
* Content: [New name for Azure Active Directory - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/new-name#glossary-of-updated-terminology)
* Content Source: [docs/fundamentals/new-name.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/new-name.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by AjayBathini-MSFT** [comment]
@Rishoooz 
Could you please elaborate the query for better understanding. So, we can assist you further.
