### ISSUE TITLE
privilege

### ISSUE THREAD

**Issue by Rishoooz** [MicrosoftDocs/entra-docs#583]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f9558c0-abb6-24f8-81c8-9000b80539e8
* Version Independent ID: a4739135-863b-27bb-1f2e-cf297f21b4cc
* Content: [Least privileged roles by task - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/delegate-by-task)
* Content Source: [docs/identity/role-based-access-control/delegate-by-task.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/delegate-by-task.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@Rishoooz 
Could you please elaborate the query for better understanding. So, we can assist you further.
