### ISSUE TITLE
Change password discrepancy

### ISSUE THREAD

**Issue by aleksbor** [MicrosoftDocs/entra-docs#584]
Hello. The required permissions are listed as such:
Reset password
Change password
Write permissions on lockoutTime
Write permissions on pwdLastSet
Extended rights for "Unexpire Password" on the root object of each domain in that forest, if not already set.

However, "change password" is missing later in the detailed steps. 
Do we need to set "Change password" or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115ae83a-95dd-5643-bc88-f5447ebb2b99
* Version Independent ID: 7462ce84-0a9f-4bfd-7eba-c00928d77865
* Content: [Enable Microsoft Entra password writeback - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/tutorial-enable-sspr-writeback)
* Content Source: [docs/identity/authentication/tutorial-enable-sspr-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/tutorial-enable-sspr-writeback.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@aleksbor 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @aleksbor 
You are correct that the **Change password** permission is not mentioned in the detailed steps. However, it is required for password writeback to work correctly. So, in addition to the permissions listed in the document, you also need to assign the "Change password" permission to the account specified in Azure AD Connect. 

Please go through this below link for your reference.
[ Note
](https://learn.microsoft.com/en-us/entra/identity/authentication/tutorial-enable-sspr-writeback#:~:text=Note,AD%20DS%20environment.)
