### ISSUE TITLE
Documentation regarding 2012R2 needs to be updated/removed.

### ISSUE THREAD

**Issue by William-zzZ** [MicrosoftDocs/entra-docs#585]
Windows Server 2012 R2 is no longer supported, documentation needs to be updated.

**Comment by SaibabaBalapur-MSFT** [comment]
@William-zzZ 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

#please-close
