### ISSUE TITLE
What about users who require syncing to AD?

### ISSUE THREAD

**Issue by fei0x** [MicrosoftDocs/entra-docs#587]
Does this feature work if the external user needs an account that's synced from AD as well? If so how?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87999564-0514-26cf-1b85-86f4a59d4c69
* Version Independent ID: 87999564-0514-26cf-1b85-86f4a59d4c69
* Content: [Convert external users to internal users (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/convert-external-users-internal)
* Content Source: [docs/identity/users/convert-external-users-internal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/convert-external-users-internal.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@fei0x 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@fei0x 
If you want to provide external users with access to your resources and they need an account that's synced from AD, you can use Azure AD B2B collaboration. With B2B collaboration, you can invite external users to access your resources, and they can use their own credentials to sign in. You can also use Azure AD Connect to sync identities from your on-premises AD to Azure AD, which allows you to manage external users in the same way as internal users.

Regarding users who require syncing to AD, you can use Azure AD Connect to sync identities from your on-premises AD to Azure AD. This allows you to manage external users in the same way as internal users. However, keep in mind that external users are not part of your organization, so you need to manage their access to your resources carefully.
