### ISSUE TITLE
Nested Hybrid Group - PIM permission applicability clarification

### ISSUE THREAD

**Issue by rdill-83** [MicrosoftDocs/entra-docs#589]
If I were to nest a AD/EntraID Hybrid security group w/in an EntraID role assignable group.
The EntraID group would then be linked to EntraID Role PIM permissions.

Would the members of the Hybrid group then be eligible for PIM escalation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1414bc2-4151-b667-65f5-b44f2bf582a1
* Version Independent ID: b93aee66-1769-8d98-fea5-ebca3a12d5fc
* Content: [Use Microsoft Entra groups to manage role assignments - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/groups-concept)
* Content Source: [docs/identity/role-based-access-control/groups-concept.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/groups-concept.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@rdill-83 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@rdill-83 
Yes, if you nest an AD/EntraID Hybrid security group within an EntraID role-assignable group, the members of the Hybrid group would be eligible for PIM escalation. However, please note that every user who is eligible for membership in or ownership of a PIM for Groups must have an Azure AD Premium P2 license. Also, please keep in mind that the group must be enabled in PIM for Groups and the Azure AD role must be assigned to the group and users must be assigned to be eligible for group membership.

**Comment by rdill-83** [comment]
For clarification, the final sentence "please keep in mind that the group must be enabled in PIM for Groups and the Azure AD role must be assigned to the group".

Which group are you referring to ?

- the root entraID native group
- the nested AD / entraID hybrid group

it's my understanding that onPrem and hybrid groups are unable to have PIM roles directly assigned, as those group types lack the `isAssignableToRole` attribute that is made only available/modifiable on creation of EntraID native groups

**Comment by ManoharLakkoju-MSFT** [comment]
@rdill-83 
I apologize for the confusion. To clarify, the group that needs to be enabled in PIM for Groups and assigned to the Azure AD role is the EntraID role-assignable group that contains the nested AD/EntraID Hybrid security group. 

You are correct that on-premises and hybrid groups are unable to have PIM roles directly assigned, as those group types lack the isAssignableToRole attribute that is only available/modifiable on creation of EntraID native groups. Therefore, you would need to create an EntraID native group that is role-assignable and assign the Azure AD role to that group. Then, you can nest the AD/EntraID Hybrid security group within the EntraID native group to make the members of the Hybrid group eligible for PIM escalation.

**Comment by rdill-83** [comment]
Clarification is much appreciated @ManoharLakkoju-MSFT
