### ISSUE TITLE
URL's are wrong

### ISSUE THREAD

**Issue by rbrayb** [MicrosoftDocs/entra-docs#590]
The doc. refers to e.g.:

{tenant_subdomain}.onmicrosoft.com/oauth2/v2.0/initiate

This will not work.

The URL needs to be:

{tenant_subdomain}.ciamlogin.com/{tenant_subdomain}.onmicrosoft.com/oauth2/v2.0/initiate

and similarly for the other endpoints.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 415432bb-47e0-392f-6d0c-4effa9eb57f7
* Version Independent ID: 415432bb-47e0-392f-6d0c-4effa9eb57f7
* Content: [Native authentication with email and password API reference - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-native-authentication-email-password?bc=%2Fentra%2Fexternal-id%2Fcustomers%2Fbreadcrumb%2Ftoc.json&toc=%2Fentra%2Fexternal-id%2Fcustomers%2Ftoc.json)
* Content Source: [docs/identity-platform/reference-native-authentication-email-password.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-native-authentication-email-password.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @kengaderdus
* Microsoft Alias: **kengaderdus**

**Comment by AjayBathini-MSFT** [comment]
@rbrayb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@rbrayb 
Thank you for bringing this to our attention.
I've delegated this to content author @kengaderdus, who will review it and offer their insightful opinions.
