### ISSUE TITLE
Bullets Squashed under 'Configure DocuSign SSO', Point 8

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/entra-docs#592]
Hi,

Under point 8 of the 'Configure DocuSign SSO' heading, the bullets (a..b..c..d) should probably be split across multiple lines - right now they're all squashed into a kind of paragraph.

Perhaps on a related note, this doc itself is out of date with the DocuSign admin portal changes - we were able to figure it out, but it's changed by a bit,.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40756c7c-63eb-10f8-c8c4-17b57877bb7f
* Version Independent ID: 9de82050-9230-0236-c246-b2fd273888ce
* Content: [Tutorial: Microsoft Entra SSO integration with DocuSign - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/docusign-tutorial)
* Content Source: [docs/identity/saas-apps/docusign-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/docusign-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by PesalaPavan** [comment]
@HiltonGiesenow 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@HiltonGiesenow 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd 
Can you please check and add your comments on this doc update request as applicable.

**Comment by jeevansd** [comment]
@v-hgampala and @v-pugoe Can you please review this doc again for accuracy and get it updated?

**Comment by v-hgampala** [comment]
@HiltonGiesenow, thanks for notifying this!!
we're updating the document accordingly.
#please-close
