### ISSUE TITLE
Add a section at the top for JWT claims using admin center

### ISSUE THREAD

**Issue by ruaden94** [MicrosoftDocs/entra-docs#595]
Recommend adding a note at the top of this document to let customers know they can set up optional claims (JWT) in the enterprise application. https://learn.microsoft.com/en-us/entra/identity-platform/jwt-claims-customization

Having a customer modifying a manifest of an app registration should not be practice. Plus any synced directory extensions will never show up here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4a177db-c714-599f-9091-b1e97506cd49
* Version Independent ID: 2bbfd6ca-1032-6afb-49bd-9dba40aa2513
* Content: [Configure optional claims - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims)
* Content Source: [docs/identity-platform/optional-claims.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/optional-claims.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by PesalaPavan** [comment]
@ruaden94 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@ruaden94 
Thank you for bringing this to our attention.
I've delegated this to content author @cilwerner, who will review it and offer their insightful opinions.

**Comment by cilwerner** [comment]
We are in the process of transferring to a new unified user feedback system. This issue is being triaged and added to the backlog where it will be addressed in an upcoming sprint.
