### ISSUE TITLE
Syntax is incorrect - nltest /dsgetdc:<dc name> /keylist /kdc

### ISSUE THREAD

**Issue by mbiasMSFT** [MicrosoftDocs/entra-docs#598]
The syntax of the NLTEST command is incorrect.  It should be nltest /dsgetdc:<domain name> /keylist /kdc instead of nltest /dsgetdc:<dc name> /keylist /kdc.

**Comment by PesalaPavan** [comment]
@mbiasMSFT 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by SaibabaBalapur-MSFT** [comment]
@mbiasMSFT 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

#please-close
