### ISSUE TITLE
Missing products

### ISSUE THREAD

**Issue by bkeski** [MicrosoftDocs/entra-docs#599]
[Enter feedback here]

Cannot find products that my customer have:
SkuId                                                                  SkuPartNumber        
-----                                -------------        
8ecbd3c1-b108-437c-a859-e3c125e3f83f       PBI_PREMIUM_EM2_ADDON
c9d442fc-21fb-4bd7-89e0-a710d74987f6       VIVA_LEARNING        
bc757c42-5622-4583-a483-a9e537fcb71c      PBI_PREMIUM_EM1_ADDON

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by PesalaPavan** [comment]
@bkeski 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Nicholak-MS
Can you please check and add your comments on this doc update request as applicable.

**Comment by Nicholak-MS** [comment]
Hi @bkeski thanks for bringing this to our attention. The noted products have now been added to the online table and the downloadable CSV. 

Thanks
Nick

#please-close
