### ISSUE TITLE
Cloud Sync Group Writeback with Devices Support

### ISSUE THREAD

**Issue by jmeyerrdo** [MicrosoftDocs/entra-docs#6]
We are currently using Entra Connect Sync and would like to write back Entra ID groups that include Entra Joined Devices to AD as security groups using Group Writeback V2. The documentation stated at one time that this group writeback functionality was going to be removed from Connect Sync after public preview and built into Cloud Sync. The document still suggests using Cloud Sync for Group Writeback V2, but I don't see anything stating that Cloud Sync supports device writeback.

"The security group writeback functionality has been replaced by Microsoft Entra Cloud Sync. Going forward, you should use Microsoft Entra Cloud Sync for this functionality."

Reading further into the document it states that device writeback needs to be enabled:

"Devices that are members of writeback-enabled groups in Microsoft Entra ID will be written back as members of Active Directory. Microsoft Entra registered and Microsoft Entra joined devices require device writeback to be enabled for group membership to be written back."

So, in order to writeback groups of devices, will Cloud Sync support device writeback in the future? Or will Group Writeback V2 still be supported with Connect Sync?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e833c88-90fa-360c-5b80-980e3e7f1cd8
* Version Independent ID: 2957d2c0-2626-68f1-1f05-da6f29186ae1
* Content: [Microsoft Entra Connect: Group writeback - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-group-writeback-v2)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-group-writeback-v2.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-group-writeback-v2.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AjayBathini-MSFT** [comment]
@jmeyerrdo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@jmeyerrdo 
Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
