### ISSUE TITLE
To Add Routing

### ISSUE THREAD

**Issue by mirojs** [MicrosoftDocs/entra-docs#607]
[Enter feedback here]
Hello,

Is there any suggest/example on how to add the routing within the <MsalProvide></MsalProvider> tags?

 const App = ({ instance }) => {
     return (
         <MsalProvider instance={instance}>
             <PageLayout>
                 <MainContent />
             </PageLayout>
         </MsalProvider>
     );
 };

Should it be in parallel with the <MainContent /> like https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/typescript-sample/src/App.tsx? 
 const App = ({ instance }) => {
     return (
         <MsalProvider instance={instance}>
             <PageLayout>
                 <MainContent />
                 <Grid container justifyContent="center">
                    <Pages />
                </Grid>
             </PageLayout>
         </MsalProvider>
     );
 };

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bcf5209-d3df-11ea-64b7-0521f33a2348
* Version Independent ID: 9ca03d8c-2eaa-5cdd-e63a-dbbe0ad04430
* Content: [Tutorial: Add sign-in and sign-out to a React SPA for a customer tenant - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-react-sign-in-sign-out)
* Content Source: [docs/external-id/customers/tutorial-single-page-app-react-sign-in-sign-out.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-single-page-app-react-sign-in-sign-out.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @godonnell
* Microsoft Alias: **godonnell**

**Comment by mirojs** [comment]
The above code not shown. Here are they.

Is there any suggest/example on how to add the routing within the tags?

        <MsalProvider instance={instance}> 
             <PageLayout>
                 <MainContent />
             </PageLayout>
         </MsalProvider>

Should it be in parallel with the like https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/typescript-sample/src/App.tsx?
  
      
        <MsalProvider instance={instance}>
             <PageLayout>
                 <MainContent />
                 <Grid container justifyContent="center">
                    <Pages />
                 </Grid>
             </PageLayout>
         </MsalProvider>
Thanks!

**Comment by PesalaPavan** [comment]
@mirojs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@mirojs 
I'm going to assign this to the document author so they can take a look at it accordingly.

@csmulligan 
please review it.

**Comment by csmulligan** [comment]
I re-assign this issue to the author @garrodonnell.

**Comment by csmulligan** [comment]
#assign: @garrodonnell

**Comment by garrodonnell** [comment]
We've added this issue to our documentation backlog work item for internal tracking and prioritization. We'll update this issue as documentation updates are published. Thanks again for your feedback. #please-close
