### ISSUE TITLE
Step 1 is inaccurate

### ISSUE THREAD

**Issue by StuBeck32** [MicrosoftDocs/entra-docs#608]
The section starting with "Start Microsoft Entra Connect, and then select Configure." is inaccurate for users of Azure AD Connect. The specific next step is "Configure device options", there is no specific "Configure" option. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c959c98-c6ce-7a6e-d4d6-2a2118d63138
* Version Independent ID: ad40c382-f00b-dd28-b2b5-d889ac265ba5
* Content: [Configure Microsoft Entra hybrid join - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/how-to-hybrid-join)
* Content Source: [docs/identity/devices/how-to-hybrid-join.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/how-to-hybrid-join.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@StuBeck32 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"cxp"
#label:"assigned-to-author"
#reassign:@MicrosoftGuyJFlo
#please-close
