### ISSUE TITLE
Branding Update Needed

### ISSUE THREAD

**Issue by RobGANA** [MicrosoftDocs/entra-docs#609]
The automatic update a little over a week ago rebranded these services, but this article still contains multiple references to Azure AD which are no longer correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c53448ff-443b-9d3e-9300-344636c30d5d
* Version Independent ID: eae8e4cc-a4f3-d6ce-85cd-9c5f588c3174
* Content: [Install the Microsoft Entra Connect Health agents in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-health-agent-install#install-the-agent-for-ad-domain-services)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-health-agent-install.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-health-agent-install.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
@RobGANA thanks for raising this issue.  We are in the process of updating.  This is being done by a separate team.  It should get updated shortly.  Thanks!

#please-close
