### ISSUE TITLE
Target framework

### ISSUE THREAD

**Issue by zingaroo** [MicrosoftDocs/entra-docs#611]
In this document it says to create a function with .NET 6.0 (Long Term Support) as the target framework. However, MS recommends using .NET 8.0 Isolated, especially since the support for .NET 6 will end.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb5253a-691d-7805-ca24-e7f47b7cd641
* Version Independent ID: 8eb5253a-691d-7805-ca24-e7f47b7cd641
* Content: [Create a REST API with a token issuance start event for Azure Functions (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-tokenissuancestart-setup?pivots=visual-studio)
* Content Source: [docs/identity-platform/custom-extension-tokenissuancestart-setup.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-tokenissuancestart-setup.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by PesalaPavan** [comment]
@zingaroo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by cilwerner** [comment]
Hi @zingeroo, as I understand it, the .NET 8 Isolated version using the NuGet package is still undergoing testing and fine tuning. I hope to get clarification from the dev team soon about this and update the article accordingly.

**Comment by cilwerner** [comment]
#please-close
