### ISSUE TITLE
update to use microsoft graph instead of auzre ad powershell for graft.

### ISSUE THREAD

**Issue by cstirland** [MicrosoftDocs/entra-docs#612]
update to use microsoft graph instead of auzre ad powershell for graft. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f01328-ebfa-31af-4e67-6de92c8f924e
* Version Independent ID: a990551f-e6c9-dede-308a-b5578fb7ee1e
* Content: [Microsoft Entra Connect - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sso-faq#how-can-i-roll-over-the-kerberos-decryption-key-of-the--azureadsso--computer-account-)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sso-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sso-faq.yml)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@cstirland 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@cstirland 
I'm going to assign this to the document author so they can take a look at it accordingly.

@billmath 
please review it.

**Comment by billmath** [comment]
@cstirland Thank you for submitting this. This process is on-going currently.  Although I don't have a timeline for this doc, it is in the rotation, and you should see an update in the future.  In the meantime, if you are looking specifically for how to do it, you can try the cmdlet map here:  https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0 

Thanks!

#please-close
