### ISSUE TITLE
Issue with sample code for Option 3

### ISSUE THREAD

**Issue by FIMTooler** [MicrosoftDocs/entra-docs#613]
The sample code for Option 3 seems to be incorrect and non-functional.  httpClient.DefaultRequestHeaders is only a Get accessor.  You must create and assign a new AuthenticationHeaderValue object.  Due to the way the AuthenticationHeaderValue constructor works, the authorizationHeader string also needs "Bearer " to be removed.

authorizationHeader = (await authorizationHeaderProvider.GetAuthorizationHeaderForUserAsync(scopes)).Replace("Bearer ","");
_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", authorizationHeader);

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b124de3b-0981-7064-5ff6-43fd67eeb36d
* Version Independent ID: 0c36165d-80b7-56ba-8208-3e13b9f754e6
* Content: [Web API that calls web APIs - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-api-call-api-call-api?tabs=aspnetcore)
* Content Source: [docs/identity-platform/scenario-web-api-call-api-call-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-web-api-call-api-call-api.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by PesalaPavan** [comment]
@FIMTooler 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@FIMTooler 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
