### ISSUE TITLE
Tutorial: Microsoft Entra integration with Everbridge

### ISSUE THREAD

**Issue by Spiker985** [MicrosoftDocs/entra-docs#616]
Hello, just happened to notice that the article's name in the navigation pane is incorrectly cased, as is the Gallery App inside Entra.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/7829451/8db40f24-8966-458b-8e61-8ea4a4e69d49)
![image](https://github.com/MicrosoftDocs/entra-docs/assets/7829451/537d7ddd-ad27-40b2-9652-a32a49036ceb)

Otherwise, I found no other issues with this article

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2d66e3-fdd2-3567-b759-54c8a2d2ed5a
* Version Independent ID: a2321350-e67f-e1b2-a2a1-fb55f5c3dd51
* Content: [Tutorial: Microsoft Entra integration with Everbridge - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/everbridge-tutorial)
* Content Source: [docs/identity/saas-apps/everbridge-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/everbridge-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by PesalaPavan** [comment]
@Spiker985 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Spiker985** [comment]
Something else that I noticed, is that you can actually configure the Enterprise Application Single Sign On settings, so that your Manager Portal and Member Portal can both be supported by a single Entra Service Principal.

Is there any security reason why this shouldn't be performed? Or perhaps against best practice?

Or would it be worthwhile to add a new section with information about how to combine the existing configurations into a single Service Principal?

**Comment by v-hgampala** [comment]
@Spiker985, no, we can't combine the two configurations. If you want to configure both at a time, then you need two different tenants for two configurations.

we're updating the app name as per your request.

**Comment by Spiker985** [comment]
> @Spiker985, no, we can't combine the two configurations. If you want to configure both at a time, then you need two different tenants for two configurations. The configuration is different for two portals.
> 
> we're updating the app name as per your request.

With all due respect, this is false. I have a single configuration supporting authentication for both the Manager Portal and Member Portal for a single Everbridge Account.

**Comment by CelesteDG** [comment]
@jeevansd @v-hgampala We are migrating all GitHub issues to ADO as we switch our feedback mechanism to UUF. Please either address the issue, or close and track it in ADO no later than June 10, 2024. Thank you.

**Comment by v-hgampala** [comment]
we are working on the issue, will reflect the changes into the main article soon.
#please-close
