### ISSUE TITLE
Missing Business Voice licensing entries licensing-service-plan-reference.md

### ISSUE THREAD

**Issue by sycorr-mpool** [MicrosoftDocs/entra-docs#617]
It appears the licensing-service-plan-reference.md documentation is missing the following voice add-ons:

| Product name | String ID | GUID | 
| --- | --- | --- |
| Microsoft Business Voice | BUSINESS_VOICE_MED2 | a6051f20-9cbc-47d2-930d-419183bf6cf1 | 
| Microsoft Business Voice | BUSINESS_VOICE |e5a17adf-8f0d-4b57-bc14-d331235f9307  | 
| Microsoft Business Voice Without Calling Plan | BUSINESS_VOICE_DIRECTROUTING | d52db95a-5ecb-46b6-beb0-190ab5cda4a8 | 
| Microsoft Business Voice Without Calling Plan | BUSINESS_VOICE_DIRECTROUTING_MED | 8330dae3-d349-44f7-9cad-1b23c64baabe |

I apologize for not submitting a PR, but I don't know the associated service plans!

//cc @Nicholak-MS 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by PesalaPavan** [comment]
@sycorr-mpool 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by sycorr-mpool** [comment]
@PesalaPavan - 

No worries, no problems.  

First off, we identified this gap when we started getting a license SKU off of MS Graph that we didn't recognize (a6051f20-9cbc-47d2-930d-419183bf6cf1).  

A quick search lead me to a few pages like this:
[https://support.simplevoip.com/hc/en-us/articles/5845763438231-Microsoft-Licensing-for-the-PBX-and-SIP-Trunk-Connector](https://support.simplevoip.com/hc/en-us/articles/5845763438231-Microsoft-Licensing-for-the-PBX-and-SIP-Trunk-Connector)

I then cross-referenced the SKUs in a few of these pages with what is in the md documentation; what I submitted was the missing differences.  

So again, I defer to your team, but **_for certain_** SKU a6051f20-9cbc-47d2-930d-419183bf6cf1 is coming off of MS Graph and is not properly documented.

Any help is appreciated!

**Comment by Naveenommi-MSFT** [comment]
Hi @sycorr-mpool 
Thank you for bringing this to our attention.
I've delegated this to content author @Nicholak-MS, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@Nicholak-MS
Could you please review add comments on this, update as appropriate.

**Comment by Nicholak-MS** [comment]
I will have someone from my team take a look and get the products added.

**Comment by sycorr-mpool** [comment]
Saw the latest update on 5/2 and it looks like those were added - thanks!

Just a heads up that new lines s223 and 225 BUSSINESS _VOICE_DIRECTROUTING is duplicated, but that is a minor detail.

Thanks again! I consider this issue resolved.

**Comment by Nicholak-MS** [comment]
Thanks @sycorr-mpool for both the feedback and for calling out the dupe... We will get it removed. 

Thanks
Nick

#please-close
