### ISSUE TITLE
Tutorial, again, fails and is likely out-dated

### ISSUE THREAD

**Issue by MikeyCSharpDude** [MicrosoftDocs/entra-docs#619]
As usual, many, if not most, of these tutorials fail; likely, due to being outdated. I followed these tutorials exactly as illustrated, and, yet they still fail.

I am getting a 'stubbed_public_client_application_called' error when running the App: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/errors.md#stubbed_public_client_application_called

The preceding means the files aren't structured correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91f81499-5314-8295-b6fb-f597dc8d7f97
* Version Independent ID: 00301f3d-8ec1-619f-2c7d-408592acd3d7
* Content: [Tutorial: Call an API from a React single-page app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-single-page-app-react-call-api)
* Content Source: [docs/identity-platform/tutorial-single-page-app-react-call-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-single-page-app-react-call-api.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by TPavanBalaji** [comment]
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MikeyCSharpDude** [comment]
Hi,

This is related to this tutorial:
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-single-page-app-react-call-api

I performed all of the steps, to a T, and the app loads without any issues,
but the following browser (Chrome 123.0.6312.106 (Official Build) (64-bit))
console error appears when clicking on the 'Sign in using Popup' button:











*BrowserConfigurationAuthError: stubbed_public_client_application_called:
Stub instance of Public Client Application was called. If using msal-react,
please ensure context is not used without a provider. For more visit:
aka.ms/msaljs/browser-errors <http://aka.ms/msaljs/browser-errors>    at
createBrowserConfigurationAuthError (chunk-IUUUWHG4.js?v=d94a6890:162:10)
  at Object.loginPopup (chunk-V26QY2UY.js?v=d94a6890:1292:27)    at
handleLogin (SignInButton.jsx:17:22)    at onClick
(SignInButton.jsx:33:55)    at Object.current
(chunk-AFCKHMCG.js?v=d94a6890:2185:32)    at
chunk-DJS4V3AL.js?v=d94a6890:996:31    at HTMLUnknownElement.callCallback2
(chunk-XBHG3ID7.js?v=d94a6890:3674:22)    at
Object.invokeGuardedCallbackDev (chunk-XBHG3ID7.js?v=d94a6890:3699:24)
at invokeGuardedCallback (chunk-XBHG3ID7.js?v=d94a6890:3733:39)    at
invokeGuardedCallbackAndCatchFirstError
(chunk-XBHG3ID7.js?v=d94a6890:3736:33)*

The calls to the *useMsal* function do seem to be included within the
context of *MsalProvider*:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/errors.md#stubbed_public_client_application_called


Regards,

Mike

**Comment by MikeyCSharpDude** [comment]
Also There is no "sample" associated with this tutorial: it's created and
completed from scratch. Since you're referring to a "sample" that works for
you, can you please share that sample with me?


Regards,

Michael Gonzalez

**Comment by OwenRichards1** [comment]
Thanks @MikeyCSharpDude - you have raised some clear issues with this tutorial, which i'll address in a PR this week.

In the meantime, please check out the repo that this tutorial is built on:

https://github.com/Azure-Samples/ms-identity-docs-code-javascript/tree/main/react-spa

I'll keep this issue open, and advise when updates have been made.

Thanks,
Owen.

**Comment by MikeyCSharpDude** [comment]
Great; thanks; much appreciated!


Regards,

Mike

**Comment by AjayBathini-MSFT** [comment]
@MikeyCSharpDude 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by MikeyCSharpDude** [comment]
So, the repo you provided "that this tutorial is built on" is not the same:
the tutorial I followed uses Visual Studio:
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-single-page-app-react-prepare-spa?tabs=visual-studio


Do you have the VS-based code?

If not, that's fine. I will use VS Code; although, it would've been nice to
get the VS solution/tutorial working.

Regards,

Mike

**Comment by MikeyCSharpDude** [comment]
The git repo version of this tutorial worked for me. However, the VS Code
version of the tutorial (on MS Learn) did not work:
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-single-page-app-react-prepare-spa?tabs=visual-studio-code

I am moving on. Thanks.


Regards,

Mike
