### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by rbrayb** [MicrosoftDocs/entra-docs#620]
The text is:

"The OTP code that the customer user received in their email. Replace {otp_code} with the OTP code that the customer user received in their email. To resend an OTP code, the app needs to make a request to the /signup/v1.0/challenge endpoint again. **The OTP code**"

The last sentence is incomplete - "The OTP code" ....?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 415432bb-47e0-392f-6d0c-4effa9eb57f7
* Version Independent ID: 415432bb-47e0-392f-6d0c-4effa9eb57f7
* Content: [Native authentication with email and password API reference - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-native-authentication-email-password?bc=%2Fentra%2Fexternal-id%2Fcustomers%2Fbreadcrumb%2Ftoc.json&toc=%2Fentra%2Fexternal-id%2Fcustomers%2Ftoc.json)
* Content Source: [docs/identity-platform/reference-native-authentication-email-password.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-native-authentication-email-password.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @kengaderdus
* Microsoft Alias: **kengaderdus**

**Comment by TPavanBalaji** [comment]
@rbrayb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @rbrayb 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
