### ISSUE TITLE
IOException: IDX20807: Unable to retrieve document from exception when implementing MS Learn tutorial

### ISSUE THREAD

**Issue by MikeyCSharpDude** [MicrosoftDocs/entra-docs#621]
This tutorial also doesn't work as-is, on startup: https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-app-dotnet-call-api?tabs=visual-studio%2Cdotnet6

I followed all of the steps, exactly as outlined in the related tutorial's pages. All of my efforts to find a solution online have been futile.

It throws the following exception when the app is launched:

> InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/ac0ea384-5318-4e55-9d72-ef0d5f076f0/v2.0/.well-known/openid-configuration'. Will retry at '4/8/2024 1:59:41 PM +00:00'. Exception: 'System.IO.IOException: IDX20807: Unable to retrieve document from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. HttpResponseMessage: '[PII of type 'System.Net.Http.HttpResponseMessage' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]', HttpResponseMessage.Content: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'. at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel) at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel) at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.

I am using Visual Studio 2022 Enterprise.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d460a936-67c4-7d18-7003-38dcc133d43d
* Version Independent ID: d460a936-67c4-7d18-7003-38dcc133d43d
* Content: [Tutorial: Call an API and display the results - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-app-dotnet-call-api?tabs=visual-studio%2Cdotnet6)
* Content Source: [docs/identity-platform/tutorial-web-app-dotnet-call-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-web-app-dotnet-call-api.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by TPavanBalaji** [comment]
@MikeyCSharpDude 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@MikeyCSharpDude 
I'm going to assign this to the document author so they can take a look at it accordingly.

@cilwerner 
Can you please check and add your comments on this doc update request as applicable.

**Comment by cilwerner** [comment]
We are in the process of transferring to a new unified user feedback system. This issue is being triaged and added to the backlog where it will be addressed in an upcoming sprint.

#please-close
