### ISSUE TITLE
Trim()

### ISSUE THREAD

**Issue by alicain** [MicrosoftDocs/entra-docs#625]
[Enter feedback here]

There is an option of Trim() within the "Manage Transformation" page.

However, Trim is not listed on this documentation page and the Trim transform appears to not work.

For product feedback - the Replace Regex transform page allows the transform to be tested, that would be useful for other transforms where that is currently not available.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c350829-8476-71a7-f53b-6cf788917037
* Version Independent ID: fbab99b8-0e94-1075-cb38-11a972feba87
* Content: [Customize SAML token claims - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/saml-claims-customization)
* Content Source: [docs/identity-platform/saml-claims-customization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/saml-claims-customization.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by Naveenommi-MSFT** [comment]
@alicain 
Thank you for bringing this to our attention.
I've delegated this to content author @cilwerner, who will review it and offer their insightful opinions.

**Comment by cilwerner** [comment]
We are in the process of transferring to a new unified user feedback system. This issue is being triaged and added to the backlog where it will be addressed in an upcoming sprint.

#please-close
