### ISSUE TITLE
AzureADHybridAuthenticationManagement module - lack of support?

### ISSUE THREAD

**Issue by mwilsonthbc** [MicrosoftDocs/entra-docs#626]
The AzureADHybridAuthenticationManagement module hasn't been updated in two years and appears to lack proper support. Issues with the module is preventing me from using these instructions and reporting the issues gets no response. Any plans to change to a more supported module?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b27a01-622e-d980-83f2-1ed27060613b
* Version Independent ID: e6472e15-10d7-bd4a-da02-558f2774dbaf
* Content: [Passwordless security key sign-in to on-premises resources - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises#install-the-azureadhybridauthenticationmanagement-module)
* Content Source: [docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@mwilsonthbc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@mwilsonthbc thanks for raising this. The engineering team has a work item to track the need to replace this option. There's dependencies to be worked out, and we don't have an ETA at this time.

if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
