### ISSUE TITLE
Issue with what doc states, needs to be edited. 

### ISSUE THREAD

**Issue by kingsleyokonkwo19** [MicrosoftDocs/entra-docs#628]
Where it says, "The Tenant Schema Extension App is a system-only application that can't be deleted, and attribute extension definitions can't be removed." It would be better if it said should not be deleted. Had issue with cx in which this was confusing since they were able to delete which led to major issues in their environment as they did not know when doing mass deletion of applications that this was part of the apps, they deleted ad confused on how it got deleted based off what document states.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc5c0d2-f57a-d462-01f0-f185362681bc
* Version Independent ID: 0d99a6af-1382-963c-d163-04492eb596b3
* Content: [Microsoft Entra Connect Sync: Directory extensions - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sync-feature-directory-extensions#configuration-changes-in-microsoft-entra-id-made-by-the-wizard)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sync-feature-directory-extensions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sync-feature-directory-extensions.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@kingsleyokonkwo19 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@billmath
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@kingsleyokonkwo19 
I've delegated this to content author @, who will review it and offer their insightful opinions.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
