### ISSUE TITLE
"Add an OpenID Connect-based single sign-on application" documentation shouldn't rely on app-specific integrations.

### ISSUE THREAD

**Issue by ag-TJNII** [MicrosoftDocs/entra-docs#629]
This page doesn't document how to set up a generic OIDC app, it documents how to add SmartSheet.  That's not the same.

I don't have access to Entra, as I'm not a SSO admin.  My support team is telling me Entra doesn't support OIDC for Enterprise apps, only SAML and SWA.  Based on this this they're not wrong, Entra apparently does not generally support OIDC on Enterprise Apps because this documentation shows only preconfigured, integrated apps.  If that's not true then hopefully the point of this report is clear.

Please bear in mind when writing these docs the person reading them likely will not have access to the console due to corporate access policies, and even if they do what is available might be masked by incorrect ACLs.  So please do not assume anything is discoverable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92406442-8660-21d8-c0ce-a29e91351739
* Version Independent ID: 70ce205a-9019-2a4a-087e-6b0239e77a21
* Content: [Add an OpenID Connect-based single sign-on application - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/add-application-portal-setup-oidc-sso)
* Content Source: [docs/identity/enterprise-apps/add-application-portal-setup-oidc-sso.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/add-application-portal-setup-oidc-sso.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by TPavanBalaji** [comment]
@ag-TJNII 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@ag-TJNII 
I'm going to assign this to the document author so they can take a look at it accordingly.

@omondiatieno 
Can you please check and add your comments on this doc update request as applicable.

**Comment by omondiatieno** [comment]
@ag-TJNII, thanks for your feedback concerning the OIDC article. We're currently reviewing your feedback internally and if we find that we need to update the article to improve clarity based on your feedback, we'll raise a PR to do so. I'll proceed to close this issue for now. Feel free to reach out in case of anything.

#please-close
