### ISSUE TITLE
Wrong link for Microsoft 365 App  (pointing to Mac Store instead of Google Play)

### ISSUE THREAD

**Issue by ctillier-vmware** [MicrosoftDocs/entra-docs#630]
Since this is the Android Shared Device Mode the Microsoft 365 App link should point to the Google store. (not the Mac store) https://play.google.com/store/apps/details?id=com.microsoft.office.officehubrow&hl=en_US&gl=US

**Comment by ManoharLakkoju-MSFT** [comment]
@ctillier-vmware 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
