### ISSUE TITLE
Admin consent via token grant flow

### ISSUE THREAD

**Issue by krzysztof-plutoflume** [MicrosoftDocs/entra-docs#631]
The documentation for granting admin consent (in our case, to grant application permissions) instructs us to redirect the user to the admin consent endpoint (`/adminconsent`).

It seems that it's also possible to prompt for admin consent as part of an OAuth 2 token grant flow, e.g. the [auth code flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow), skipping the admin consent endpoint altogether. The token grant flow is useful because it could allow us to take care of admin consent and obtain ID/access tokens in a single step, resulting in simpler UX.

Could you confirm that using the `/authorize` endpoint to complete admin consent for granting application permissions is a valid approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5837e27-7af3-12ad-3fd7-10995017581e
* Version Independent ID: 6ccb62ba-b31c-0cd5-c169-06c3ca899a4b
* Content: [Microsoft identity platform admin consent protocols - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-admin-consent)
* Content Source: [docs/identity-platform/v2-admin-consent.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-admin-consent.md)
* Service: **identity-platform**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by TPavanBalaji** [comment]
@krzysztof-plutoflume 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@krzysztof-plutoflume 
For an issue like this, I'd recommend you create a [support ticket](https://azure.microsoft.com/support/create-ticket/) since the support team will be able to respond much more quickly and have a conversation with you to figure out what could be going on.

**Comment by SaibabaBalapur-MSFT** [comment]
@krzysztof-plutoflume 
I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by krzysztof-plutoflume** [comment]
Thank you, I've posted on the Q&A board instead.
