### ISSUE TITLE
Fslogix

### ISSUE THREAD

**Issue by sundelit-se** [MicrosoftDocs/entra-docs#632]
Does this also apply if Fslogix is used for profile management?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8f55d4-539c-7835-010b-34026860f699
* Version Independent ID: 4f8db376-bed9-6fd2-2e65-ac11c0952540
* Content: [Device identity and desktop virtualization - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-device-identity-virtual-desktop-infrastructure#non-persistent-vdi)
* Content Source: [docs/identity/devices/howto-device-identity-virtual-desktop-infrastructure.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-device-identity-virtual-desktop-infrastructure.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@sundelit-se 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@sundelit-se 
Yes, the document you provided explains how to use Azure AD to manage device identity in a non-persistent VDI environment. It also mentions that FSLogix is the recommended user profile solution for Azure Virtual Desktop, which is a remote computing environment. FSLogix is designed to roam profiles in remote computing environments, such as Azure Virtual Desktop. At sign-in, this container is dynamically attached to the computing environment using a natively supported Virtual Hard Disk (VHD) and a Hyper-V Virtual Hard Disk (VHDX). The user profile is immediately available and appears in the system exactly like a native user profile.

**Comment by ManoharLakkoju-MSFT** [comment]
@sundelit-se 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
