### ISSUE TITLE
You should see an HTTP Error 403 – Forbidden response.You should see an HTTP Error 403 – Forbidden response.

### ISSUE THREAD

**Issue by anothervictim** [MicrosoftDocs/entra-docs#633]
Number 18: "You should see an HTTP Error 403 – Forbidden response." There is no documentation to support this. I think this may have been confused with the Intune Connector. Please remove or provide additional context.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f49a9221-b949-95db-f53b-ba6bd4337000
* Version Independent ID: c170ba58-5d57-90e4-10ff-e9f4c0546d0f
* Content: [Use Microsoft Entra application proxy with a Network Device Enrollment Service (NDES) server - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/app-proxy-protect-ndes)
* Content Source: [docs/identity/app-proxy/app-proxy-protect-ndes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/app-proxy-protect-ndes.md)
* Service: **entra-id**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by Naveenommi-MSFT** [comment]
@anothervictim 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @anothervictim This document might prove to be helpful.
https://learn.microsoft.com/en-us/troubleshoot/azure/api-mgmt/availability/request-throttling-http-403 

Thanks for your contribution. Please add your feedback in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)

**Comment by SaibabaBalapur-MSFT** [comment]
@anothervictim 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by anothervictim** [comment]
I understand what 403 means, generally speaking. It is a well documented response. However, depending on the working scenario it has other implications. In the scenario presented in this support article the indication is that a 403 is expected (step 18). In the case of a standard NDES deployment, 403 is not an expected response. In this case, the mscep.dll url would resolve as a response of 200. So, we should not expect a 403 unless it is behaving similarly to the Intune connector and expecting a [well-formed SCEP certificate request](https://learn.microsoft.com/en-us/mem/intune/protect/certificates-scep-configure#support-for-ndes-on-the-internet). Since the article related to this issue indicates that a 403 is desired (Step 18), like it is desired for that of the Intune Connector, then where is the supporting documentation for this (the Entra ID App Proxy Connector)? This is the reason for my original concern.

I don't believe to misunderstand the process. I believe it is either incorrect (Step 18). Or, perhaps the Entra Private Network Connector doesn't work correctly. I also saw the same behavior, or lack thereof, with the older Azure connector.

**Comment by SaibabaBalapur-MSFT** [comment]
@anothervictim I apologize for confusion caused, I'm going to assign this to the document author so they can take a look at it accordingly.

@kenwith
Please review it.

**Comment by kenwith** [comment]
@anothervictim - thanks for taking the time to open the issue. I appreciate it. I agree that it doesn't make sense to get a 403 there. I am in the process of moving the app proxy connector content over to Global Secure Access area ( https://learn.microsoft.com/entra/global-secure-access/ ) and will be stepping through all of the articles as I am doing that. I will get to the bottom of this step and make sure the doc is clear. The reason for moving the content is that the same connector is now used for Microsoft Entra Private Access and also application proxy.

**Comment by anothervictim** [comment]
Very much appreciate you both @kenwith and @SaibabaBalapur-MSFT

**Comment by kenwith** [comment]
Moving feedback to content backlog as an open work item and closing in the GitHub Issue list.

#please-close
