### ISSUE TITLE
Deprecated Information

### ISSUE THREAD

**Issue by Yogi8BooBoo** [MicrosoftDocs/entra-docs#634]
I am currently following the guide, but the Admin/Azure portal do not have the same fields/blades.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60d23869-94f5-22cc-425e-4bf675d84ce0
* Version Independent ID: 5105047f-04bf-87ef-ee8e-3e9bf9b5ac3a
* Content: [Microsoft Entra Conditional Access for workload identities - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/workload-identity)
* Content Source: [docs/identity/conditional-access/workload-identity.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/workload-identity.md)
* Service: **entra-workload-id**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
@Yogi8BooBoo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Yogi8BooBoo 
Could you clarify on below so we can be able to assist you.
What fields? What blades? Do they have a license? Are they signed in with the right role?

**Comment by AjayBathini-MSFT** [comment]
@Yogi8BooBoo 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
