### ISSUE TITLE
Incorrect/missing info on Azure 'AWS Single-account Access' setup

### ISSUE THREAD

**Issue by barnabyibis** [MicrosoftDocs/entra-docs#637]
The username and password returned when enabling console access is not what is needed for the clientsecret and secret token values.
Instead, I created a 3rd party access key, which worked for this step

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8fa5814d-91e2-2f75-77e7-62a8597f340c
* Version Independent ID: 458e93d7-a180-4c2f-5077-9b9d124d726a
* Content: [Tutorial: Microsoft Entra SSO integration with AWS Single-Account Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/amazon-web-service-tutorial#how-to-configure-role-provisioning-in-aws-single-account-access)
* Content Source: [docs/identity/saas-apps/amazon-web-service-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/amazon-web-service-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by Naveenommi-MSFT** [comment]
@barnabyibis 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@barnabyibis 
I'm going to assign this to the document author so they can take a look at it accordingly.

@jeevansd 
Can you please check and add your comments on this doc update request as applicable.

**Comment by v-hgampala** [comment]
@jeevansd, will you please add your comments on this issue.

**Comment by CelesteDG** [comment]
@jeevansd @v-hgampala We are migrating all GitHub issues to ADO as we switch our feedback mechanism to UUF. Please either address the issue, or close and track it in ADO no later than June 10, 2024. Thank you.

**Comment by v-hgampala** [comment]
we are working on the issue, will reflect the changes into the main article soon.
#please-close
