### ISSUE TITLE
Group provisioning to Zoom app  is unsupported at this time by Microsoft

### ISSUE THREAD

**Issue by calazlo** [MicrosoftDocs/entra-docs#638]
Please mention in a note that Group Provisioning to Zoom is unsupported at this time by Microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37280d15-75ea-7486-48d6-08e82fd4c1a4
* Version Independent ID: 037a01c2-1908-6ca4-f868-a9cd488e85d5
* Content: [Tutorial: Configure Zoom for automatic user provisioning with Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/zoom-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/zoom-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/zoom-provisioning-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @twimmers
* Microsoft Alias: **thwimmer**

**Comment by Naveenommi-MSFT** [comment]
@calazlo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Harshita-130901** [comment]
@calazlo,  we're creating a separate PR for this in our private repo for better content review, the changes will merge within 2-3 working days.
#please-close
