### ISSUE TITLE
Installation of Entra Cloud Connect fails due to incorrect encryption type on gMSA

### ISSUE THREAD

**Issue by Ross-Y** [MicrosoftDocs/entra-docs#639]
During the installation of Entra Cloud Connect agent, gMSA is generated by default. During circumstances below the installation will stop with the error:

> 'Error while creating group managed service account (gMSA). Error: Unable to install service account pGMSA_2345ad35$ after 6 retries.'

As it happens, gMSA is generated with default setting for the encryption type, RC4, AES128 and AES256. If the server, where an agent is installed has turned off support for RC4, this results in the error caused by mismatch of encryption types.

>Install-ADServiceAccount : Cannot Install service account. Error Message:  'The provided context did not match the target' 
 https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/the-rc4-removal-files-part-1-what-s-in-an-error-message/ba-p/1029309)

Fix - Setup should query registry path below to check which encryption types are supported. Then same encryption types have to be specified while creating new gMSA.
`HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters\`
key: `SupportedEncryptionTypes`
Values: 
0x7ffffff8 represents AES128, AES256
0x1c represents RC4, AES128, AES256

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4692b48-2a40-3a4f-bd2c-5ccc8efc2f62
* Version Independent ID: e869ea03-68be-9de8-4219-18a4e5e7005e
* Content: [Install the Microsoft Entra provisioning agent - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-install)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-install.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-install.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Naveenommi-MSFT** [comment]
@Ross-Y 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by Ross-Y** [comment]
Sorry, didn't know that the page link is not saved anywhere. Here are the instructions I was following:
https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-install

**Comment by ManoharLakkoju-MSFT** [comment]
@Ross-Y 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Ross-Y 
For an issue like this, I'd recommend you create a [support ticket](https://azure.microsoft.com/support/create-ticket/) since the support team will be able to respond much more quickly and have a conversation with you to figure out what could be going on.

**Comment by SaibabaBalapur-MSFT** [comment]
@Ross-Y 
I'm going to assign this to the document author so they can take a look at it accordingly.

@billmath 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Ross-Y** [comment]
This is a product bug, nothing to do with the documentation. More specifically - part of installation process doesn't work as it should. It is a minor bug, will only cause some frustration to some 10-20% of your customers who are migrating to Entra Cloud Sync. And yes, there is the known workaround to create a gMSA manually. But it is just so easy to fix - just one check, one parameter change and that's all.

Steps to reproduce:
1. Create a GPO and assign to the test server
2. Configure "Network security: Configure encryption types allowed for Kerberos" to support only AES128 and AES256 encryption
3. Start installation of Entra Cloud Sync agent on this server.
4. Actual result: installation will fail on creating gMSA account, just as described above.

**Comment by billmath** [comment]
Thank you for your issue submission. Unfortunately, this appears to be a support issue. Issues in this repo are for documentation issues. If it is a bug, a support engineer can assist in getting it to engineering.  You can also try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
