### ISSUE TITLE
Prove Cloud Kerberos Migration

### ISSUE THREAD

**Issue by jamiewdickson** [MicrosoftDocs/entra-docs#640]
Is there any way to prove a computer is using Cloud Kerberos Trust to know users have migrated? I ask because we want to decommission a certificate authority, and Windows Hello is using that right now for our key trust. I need to know when all my users have migrated to Cloud Kerberos Trust before decommissioning it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b27a01-622e-d980-83f2-1ed27060613b
* Version Independent ID: e6472e15-10d7-bd4a-da02-558f2774dbaf
* Content: [Passwordless security key sign-in to on-premises resources - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises)
* Content Source: [docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@jamiewdickson 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @jamiewdickson 
There are a few ways to verify that a computer is using Cloud Kerberos Trust for authentication.

One way is to check the Kerberos ticket cache on the computer. When a user logs in using Cloud Kerberos Trust, a Kerberos ticket is issued and stored in the ticket cache on the computer. You can use the klist command to view the contents of the ticket cache and verify that the ticket was issued by the Cloud Kerberos Trust.

Another way to verify that a computer is using Cloud Kerberos Trust is to check the event logs on the computer. When a user logs in using Cloud Kerberos Trust, an event is logged in the Windows Security event log with event ID 4769. You can search for this event in the event log to verify that the user logged in using Cloud Kerberos Trust.

Finally, you can also check the Azure AD sign-in logs to verify that the user logged in using Cloud Kerberos Trust. The sign-in logs will show the authentication method used for each sign-in, including whether Cloud Kerberos Trust was used.

I hope this helps! If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@jamiewdickson 
I've delegated this to content author @Justinha, who will review it and offer their insightful opinions.

**Comment by jamiewdickson** [comment]
@Justinha Is it possible to get an update on this reporting in Azure?

**Comment by Justinha** [comment]
@jamiewdickson sorry I don't have any more to add here. #please-close
