### ISSUE TITLE
Issue with 'Name' attribute: API-driven inbound user provisioning to on-premises Active Directory

### ISSUE THREAD

**Issue by dankitch** [MicrosoftDocs/entra-docs#641]
## Issue description

Unable to update the on-premises `Name` attribute when using API-driven inbound user provisioning into on-premises Active Directory.  

When a user is provisioned into on-premises Active Directory, the `Name` attribute automatically takes the value of the `displayName` proprty which is defined in SCIM request:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/140333496/223827ea-bed7-4fc2-8b25-d88bdca9f940)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/140333496/afc8442a-778b-4588-8e99-371aac6bd360)

Assuming, no changes have been made to the default Attribute Mapping on the Enterprise Application, the `Name` attribute isn't in scope, by default. 

If we add the `Name` attribute to the mappings (like below) and try define a constant value, for example, displayName, the following error appears in the logs. 

![image](https://github.com/MicrosoftDocs/entra-docs/assets/140333496/b0b497eb-273f-467e-bcd3-54b3e776e2e0)

The log seems to reference `RelativeDistinguishedName` which seems a bit misleading. 

**HybridSynchronizationInvalidOperationOnRelativeDistinguishedNameAttribute**

> Error message
> UnwillingToPerform-SvcErr: The server cannot handle directory requests.. ResultCode: UnwillingToPerform, HResult: -2146233088, responseType: System.DirectoryServices.Protocols.ModifyResponse, serializedResponse: {"RequestId":null,"MatchedDN":"","Controls":[],"ResultCode":53,"ErrorMessage":"00002016: SvcErr: DSID-031A126A, problem 5003 (WILL_NOT_PERFORM), data 0\n","Referral":[]}. The directory service cannot perform the requested operation on the RDN attribute of an object. \nError Details: Problem 5003 - WILL_NOT_PERFORM. This operation was retried 0 times. It will be retried again after this date: 2024-04-11T12:58:09.9985426Z UTC

Is this a bug or just the wrong use of this attribute? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12bbf2b1-94d1-803e-eb08-471942c336a5
* Version Independent ID: c84a8620-6aa2-2790-5cf5-cd4fec1d9a8f
* Content: [Quickstart API-driven inbound provisioning with Postman - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/inbound-provisioning-api-postman)
* Content Source: [docs/identity/app-provisioning/inbound-provisioning-api-postman.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/inbound-provisioning-api-postman.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @jenniferf-skc
* Microsoft Alias: **jfields**

**Comment by dankitch** [comment]
Not entirely sure if this is an LDAP limitation rather than an issue with the API provisioning.

**Comment by Naveenommi-MSFT** [comment]
@dankitch 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by dankitch** [comment]
@Naveenommi-MSFT thanks! 

Here is the link:
https://learn.microsoft.com/en-us/entra/identity/app-provisioning/inbound-provisioning-api-postman

This example is for Postman, but it is the same whether it is via PowerShell or Logic Apps. 

Overall concept:
https://learn.microsoft.com/en-us/entra/identity/app-provisioning/inbound-provisioning-api-concepts

**Comment by ManoharLakkoju-MSFT** [comment]
@dankitch 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dankitch 
I'm going to assign this to the document author so they can take a look at it accordingly.

@jenniferf-skc 
please review.

**Comment by jenniferf-skc** [comment]
Hi @SaibabaBalapur-MSFT, I'm looking into this. Thanks.
