### ISSUE TITLE
Does this document also apply to Azure B2C and Service Principals?

### ISSUE THREAD

**Issue by LockTar** [MicrosoftDocs/entra-docs#642]
I would like to know if this document:

1. Also apply for Azure B2C
2. Can this custom role also be applied to a service principal so that service principal is not limited to creating max 250 app registrations?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d59b2783-b3e8-1505-2cb2-ae0a3516e56f
* Version Independent ID: b265a449-4571-17c8-1acc-c3f20b6d093b
* Content: [Remove limits on creating app registrations - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/quickstart-app-registration-limits)
* Content Source: [docs/identity/role-based-access-control/quickstart-app-registration-limits.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/quickstart-app-registration-limits.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment]
@LockTar 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@LockTar 
I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by LockTar** [comment]
I don't know what Microsoft Teams has to do with this. [I asked the question on another forum](https://learn.microsoft.com/en-us/answers/questions/1656566/can-app-registration-limits-also-be-removed-on-azu).
