### ISSUE TITLE
What happens if the agent is inactive or you have uninstalled the agent?

### ISSUE THREAD

**Issue by calazlo** [MicrosoftDocs/entra-docs#644]
HI,

A lot of customers are asking "What happens if the agent is inactive or if you are uninstalling the agent?"
***Reference: https://learn.microsoft.com/en-us/answers/questions/1310381/unable-to-remove-old-azure-cloud-agent-from-aad-po
We have this section  documented under https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-connectors#maintenance
"You don't have to manually delete connectors that are unused. When a connector is running, it remains active as it connects to the service. Unused connectors are tagged as inactive and are removed after 10 days of inactivity."

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42038cf7-555b-5351-0380-b20ac50c4863
* Version Independent ID: 7267c4b4-0770-9fb4-4e45-e8342ca4a850
* Content: [Microsoft Entra Cloud Sync FAQ - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/reference-cloud-sync-faq)
* Content Source: [docs/identity/hybrid/cloud-sync/reference-cloud-sync-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/reference-cloud-sync-faq.yml)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@calazlo 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@calazlo 
Can you please check and add your comments on this request as applicable.

**Comment by calazlo** [comment]
Dear @AjayBathini-MSFT,

Can you please mention what should I check? :)
I couldn't see anything added to the public article yet. 
***https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/reference-cloud-sync-faq

Thank you :-)

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
