### ISSUE TITLE
SSO for Slack - AuthnContextClassRef cause issues for AAD registered devices - docs need updating?

### ISSUE THREAD

**Issue by DavidAtImpactCubed** [MicrosoftDocs/entra-docs#645]
When implementing SSO for Slack with Entra, some (but not all) users were presented with AADSTS75011 errors when signing in.

According to https://learn.microsoft.com/en-us/troubleshoot/azure/entra/entra-id/app-integration/error-code-AADSTS75011-auth-method-mismatch
This occurs for users on AD Registered or Joined devices, where the user doesn't need to re-enter a password.

According to this: https://techcommunity.microsoft.com/t5/enterprise/sso-issue-with-slack-on-azure-ad-joined-machine/m-p/857770
The answer is to edit the Slack SSO configuration and change the 'AuthnContextClassRef' and set it to 'Don't send this value'. 

If this is the correct approach to support AD joined devices, the tutorial probably needs updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 919ac673-c2e9-6768-1071-7607c5c6a5c9
* Version Independent ID: 7620fb9f-2085-ab9b-60dd-7e5a73355c0d
* Content: [Tutorial: Microsoft Entra SSO integration with Slack - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/slack-tutorial)
* Content Source: [docs/identity/saas-apps/slack-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/slack-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by TPavanBalaji** [comment]
@DavidAtImpactCubed 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@DavidAtImpactCubed 
Thank you for bringing this to our attention.
I've delegated this to content author @jeevansd, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@jeevansd 
Could you please review add comments on this, update as appropriate.

**Comment by jeevansd** [comment]
Hi @DavidAtImpactCubed Yes, this is correct and we can add a note into the article. 
I am tagging @v-pugoe  and @v-hgampala who can help add this note here in this article.

**Comment by v-hgampala** [comment]
@DavidAtImpactCubed, thanks for the issue!
we're updating the document accordingly about AuthnContextClassRef .
#please-close
