### ISSUE TITLE
ASP.NET Core Web API Authorization Code Tutorial Fails with HTTP 403 Result

### ISSUE THREAD

**Issue by MikeyCSharpDude** [MicrosoftDocs/entra-docs#646]
Using Visual Studio 2022 Enterprise edition, I followed all of the steps, stemming from the following Tutorial: https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-api-dotnet-register-app

The end result is that on the last step in the following tutorial page, 'Call web API with access token', I get a 403 Forbidden response: https://learn.microsoft.com/en-us/entra/identity-platform/howto-call-a-web-api-with-curl?tabs=dotnet6&pivots=api#call-web-api-with-access-token

The response from the Web API server:

```
HTTP/1.1 403 Forbidden
Content-Length: 0
Date: Fri, 12 Apr 2024 12:28:55 GMT
Server: Kestrel
```

This is considering I followed all of the tutorial steps, exactly, as laid out on the MS Learn pages, twice:

Web API Authentication Tutorial - ASP.NET Core - Register your API: https://learn.microsoft.com/en-us/entra/identity-platform/index-web-api

1) Tutorial: Register a web API with the Microsoft identity platform
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-api-dotnet-register-app

2) Tutorial: Create and configure an ASP.NET Core project for authentication
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-api-dotnet-prepare-app?tabs=visual-studio

3) Tutorial: Implement a protected endpoint to your API
https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-web-api-dotnet-protect-endpoint?tabs=visual-studio

4) Call an ASP.NET Core web API with cURL using Grant, Authorization Code
https://learn.microsoft.com/en-us/entra/identity-platform/howto-call-a-web-api-with-curl?tabs=dotnet6&pivots=api

Almost all MS Learn tutorials don't work, despite having followed all steps and pages exactly, carefully. This has become increasingly frustrating that I have to work to get most tutorials to work properly. It seems most are outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7d0268f-c285-ef3c-bc48-8570b4d7367b
* Version Independent ID: 962c2c10-568e-29d7-b33b-35324133b81b
* Content: [Call an ASP.NET Core web API with cURL - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/howto-call-a-web-api-with-curl?tabs=dotnet6)
* Content Source: [docs/identity-platform/howto-call-a-web-api-with-curl.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/howto-call-a-web-api-with-curl.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by MikeyCSharpDude** [comment]
Closed

**Comment by ManoharLakkoju-MSFT** [comment]
@MikeyCSharpDude 
Glad to know issue got resolved. If there are further questions regarding this topic, please do let us know and we will gladly continue the discussion.
