### ISSUE TITLE
Better Feedback on onboarding and offboarding license requirements

### ISSUE THREAD

**Issue by mwilliams7247e** [MicrosoftDocs/entra-docs#65]
We have had a large discussion around what is the actual requirement for a company of 100 users that expect a turnover of 350 employees. It is not clear if I need 351 or 701 licenses to cover a turnover of an employee. 

If someone leaves, we need to replace that person. Is that 1 license or 2? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c48d98ed-5170-140d-59cc-344c755311cc
* Version Independent ID: 0ace47ad-ae37-5b99-0bc0-63f0d05f8ed6
* Content: [Microsoft Entra ID Governance licensing fundamentals - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/licensing-fundamentals)
* Content Source: [docs/id-governance/licensing-fundamentals.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/licensing-fundamentals.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@mwilliams7247e 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@mwilliams7247e 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
