### ISSUE TITLE
Tutorial: Call the Microsoft Graph API from a UWP App - XAML Code-behind Code does Not Work: Methods are Missing

### ISSUE THREAD

**Issue by MikeyCSharpDude** [MicrosoftDocs/entra-docs#650]
Using Visual Studio 2022 Enterprise edition, I create a new UWP (Basic) app in C# via this tutorial: https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-windows-uwp

It seems most of these tutorials are very old; in this case, it seems to require VS 2019.

The following methods are missing in the 'MainPage.xaml.cs' class file's 'MainPage' class and generate compilation exceptions: SignInAndInitializeGraphServiceClient, DisplayBasicTokenInfo, DisplayMessageAsync

Offending lines of code:

`GraphServiceClient graphClient = await SignInAndInitializeGraphServiceClient(scopes);`

`DisplayBasicTokenInfo(authResult);`

`await DisplayMessageAsync($"Error Acquiring Token:{System.Environment.NewLine}{msalEx}");`

Etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2333c6b-140e-6cc8-91ad-00e47935bc6b
* Version Independent ID: 738f87e1-d839-62f7-0c5c-6562b39e8d1c
* Content: [Tutorial: Create a Universal Windows Platform (UWP) app that uses the Microsoft identity platform for authentication - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/tutorial-v2-windows-uwp)
* Content Source: [docs/identity-platform/tutorial-v2-windows-uwp.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/tutorial-v2-windows-uwp.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by PesalaPavan** [comment]
@MikeyCSharpDude 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MikeyCSharpDude** [comment]
I got this to work by doing the following:

Replace this:
`                GraphServiceClient graphClient = await SignInAndInitializeGraphServiceClient(scopes);`

With this:
`var graphServiceClient = new GraphServiceClient(tokenCredential: DelegatedTokenCredential.Create((trx, ct) => new AccessToken(authResult.AccessToken, authResult.ExpiresOn)));`

Your tutorial is based on 2019 technology. We're now well into 2024.
