### ISSUE TITLE
Consent framework is "broken" for prompt=consent when app permissions include a scope that requires admin consent

### ISSUE THREAD

**Issue by fernando-almeida-sprinklr** [MicrosoftDocs/entra-docs#652]
With regard to "The application has been configured to require assignment. Individual user consent isn't currently supported for apps that require assignment; thus the permissions must be granted by an admin for the whole directory. If you configure an application to require assignment, be sure to also grant tenant-wide admin consent so that assigned user can sign-in.". If the developer sends prompt=consent the MS consent framework ALWAYS ASKS a non-admin user to require approval for the permissions despite these have already been approved by an admin and haven't changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27339f6f-c63d-d2cc-ec02-8727b5587bf0
* Version Independent ID: 8edacd13-bbd1-cfc7-e686-7ca7bf4cb2ad
* Content: [Unexpected consent prompt when signing in to an application - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/application-sign-in-unexpected-user-consent-prompt)
* Content Source: [docs/identity/enterprise-apps/application-sign-in-unexpected-user-consent-prompt.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/application-sign-in-unexpected-user-consent-prompt.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by PesalaPavan** [comment]
@fernando-almeida-sprinklr 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by fernando-almeida-sprinklr** [comment]
Hi,

Thanks for the reply.
My replies follow below in context.

________________________________

**Comment by ManoharLakkoju-MSFT** [comment]
@fernando-almeida-sprinklr 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
