### ISSUE TITLE
Need additional Powershell Module to run upate-mgdomain and get-mgdomain

### ISSUE THREAD

**Issue by gatewood502** [MicrosoftDocs/entra-docs#653]
The instructions do not mention that we need to run

Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement

In order to get the get-mgdomain and update-mgdomain cmdlets to cutover federation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b4eb058-63aa-900d-9e64-e28eabc225ff
* Version Independent ID: f3589424-d704-c815-e0b6-0d4441772b74
* Content: [Migrate Okta federation to Microsoft Entra ID-managed authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/migrate-okta-federation)
* Content Source: [docs/identity/enterprise-apps/migrate-okta-federation.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/migrate-okta-federation.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @Gargi-Sinha
* Microsoft Alias: **gasinh**

**Comment by PesalaPavan** [comment]
@gatewood502 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @gatewood502 it is true that you need to install the Microsoft Graph PowerShell module, the correct command to install the module is **Install-Module Microsoft.Graph**.

However, the command **Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement** is not necessary for the migration from Okta to Azure Active Directory. This command installs the Microsoft Graph Identity Directory Management module, which is used for managing identity-related tasks in Azure Active Directory, but it is not required for the migration process.

So, to summarize, the correct command to install the Microsoft Graph PowerShell module is **Install-Module Microsoft.Graph**, and the command **Install-Module -Name Microsoft.Graph.Identity.DirectoryManagement** is not necessary for the migration from Okta to Azure Active Directory.

When your organization is comfortable with the managed authentication experience, you can defederate your domain from Okta. To begin, use the following commands to connect to Microsoft Graph PowerShell. If you don't have the Microsoft Graph PowerShell module, download it by entering **Install-Module Microsoft.Graph.**
