### ISSUE TITLE
Example Feedback: Update multiple attributes for multiple users example in Powershell

### ISSUE THREAD

**Issue by Insight-UK-CurtisMilne** [MicrosoftDocs/entra-docs#654]
[Enter feedback here]

Hi Team,

It would be good to understand how to update multiple security attributes for multiple users.

Is this achievable?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43c892af-3e7a-7475-bea4-e49d33afc7a6
* Version Independent ID: 88355bde-bac2-943e-08f8-fd5f2ecf707b
* Content: [Assign, update, list, or remove custom security attributes for a user - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/users-custom-security-attributes?tabs=ms-powershell)
* Content Source: [docs/identity/users/users-custom-security-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/users-custom-security-attributes.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by PesalaPavan** [comment]
@Insight-UK-CurtisMilne 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @Insight-UK-CurtisMilne 
Yes, it is possible to update multiple security attributes for multiple users using PowerShell. Here is an example:

```powershell
# Define the attributes to update
$attributesUpdate = @{
    Engineering = @{
        "@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
        "Project@odata.type" = "#Collection(String)"
        Project = @("Alpine","Baker")
    }
    Sales = @{
        "@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
        "Region@odata.type" = "#Collection(String)"
        Region = @("North","South")
    }
}

# Define the list of user IDs to update
$userIds = @("dbb22700-a7de-4372-ae78-0098ee60e55e", "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6")

# Loop through the list of user IDs and update the attributes for each user
foreach ($userId in $userIds) {
    Set-AzureADMSUser -Id $userId -CustomSecurityAttributes $attributesUpdate
}
```

In this example, we define the attributes to update in the `$attributesUpdate` variable, and the list of user IDs to update in the `$userIds` variable. We then loop through the list of user IDs using a `foreach` loop, and call the `Set-AzureADMSUser` command for each user ID, passing in the `$attributesUpdate` variable to update the user's custom security attributes. Let me know if you have any further questions!

**Comment by Insight-UK-CurtisMilne** [comment]
Thanks @ManoharLakkoju-MSFT !

Would there be a way to enter multiple entries for a single set?

i.e

`$attributesUpdate = @{
    Engineering = @{
        "@odata.type" = "#Microsoft.DirectoryServices.CustomSecurityAttributeValue"
        "Project@odata.type" = "#Collection(String)"
         Project = @("Alpine","Baker")
        "Pod@odata.type" = "#Collection(String)"
         Pod= @("Bravo","Alpha")
    }`
