### ISSUE TITLE
Review usage of new sap common superdomain "cloud.sap"

### ISSUE THREAD

**Issue by diegoy84** [MicrosoftDocs/entra-docs#655]
PLease review the suage of the new URLs for point 8 to use the new superdomain cloud.sap

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e8629d0-8a5c-64ba-46f2-f8caa51b9126
* Version Independent ID: 9eab5faf-da99-3fca-d7fd-a2814c72b136
* Content: [Tutorial: Configure SAP Cloud Identity Services for automatic user provisioning with Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/sap-cloud-platform-identity-authentication-provisioning-tutorial)
* Content Source: [docs/identity/saas-apps/sap-cloud-platform-identity-authentication-provisioning-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/sap-cloud-platform-identity-authentication-provisioning-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @twimmers
* Microsoft Alias: **thwimmer**

**Comment by PesalaPavan** [comment]
@diegoy84 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @diegoy84 I appreciate your contribution to the docs! Can you provide more information in this GitHub issue?

**Comment by diegoy84** [comment]
Hello
Since SAP is migrating to a common Super Domain (cloud.sap.com) due to third-party cookie deprecation,  urls should be using this new CSD

3420345 - How to use common super domain(*.accounts.cloud.sap) for IAS tenant
https://me.sap.com/notes/3420345/E

https://help.sap.com/docs/SAP_SUCCESSFACTORS_RELEASE_INFORMATION/8e0d540f96474717bbf18df51e54e522/6125e93b4726429a98cf149121927154.html

https://me.sap.com/notes/3436066/E

**Comment by SaibabaBalapur-MSFT** [comment]
@diegoy84 
I'm going to assign this to the document author so they can take a look at it accordingly.
@twimmers 
please review.

**Comment by CelesteDG** [comment]
@twimmers @v-hgampala We are migrating all GitHub issues to ADO as we switch our feedback mechanism to UUF. Please either address the issue, or close and track it in ADO no later than June 10, 2024. Thank you.

**Comment by v-hgampala** [comment]
@diegoy84, we are working on the issue, will reflects the suggested changes into the main article soon.
#please-close
