### ISSUE TITLE
Require app protection policy vs Block Legacy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/entra-docs#656]
Hello,

It is a little bit unclear the scenario of the policy deployment.

In one of the articles, the recommendation is to Block the Legacy protocols:
https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-block-legacy

Now when using the Require App protection policy, it seems we must enable it and then set Exchange Active sync to require app policy:
https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-policy-approved-app-or-app-protection

So what should we do? Is it possible to request a review of the documentation of App Protection Policy + Legacy Authentication + Conditional Access scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5b96d45-d3ce-83c2-695c-5b528e32149d
* Version Independent ID: 1315e93b-f3e0-c4aa-d43a-2b9e59378a46
* Content: [Migrate approved client app to application protection policy in Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/migrate-approved-client-app)
* Content Source: [docs/identity/conditional-access/migrate-approved-client-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/migrate-approved-client-app.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@lightupdifire 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@lightupdifire 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
The policies are correct as written. The client app targets the basic authentication form of Exchange ActiveSync.

#please-close
