### ISSUE TITLE
Is 'Authentication Insights' correct?

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/entra-docs#657]
Hello,

would you kindly check if 'Authentication Insights' is correct in this string? "As deployments progress in readiness of preview, administrators and users might see passkey as a sign-in method across different Microsoft Entra surfaces, including the Admin center, Authenticator app, **Authentication Insights**, and so on."

We cannot find it in MS terminology nor any proper reference to it. I guess it shouldn't be 'Application Insights'?

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e251214c-f2d6-3167-ec55-1959714ea1c6
* Version Independent ID: e251214c-f2d6-3167-ec55-1959714ea1c6
* Content: [Sign in with passkeys in Authenticator for Android and iOS devices (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-sign-in-passkey-authenticator?tabs=iOS)
* Content Source: [docs/identity/authentication/how-to-sign-in-passkey-authenticator.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-sign-in-passkey-authenticator.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@QueryCoordinator 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@QueryCoordinator 
I'm going to assign this to the document author so they can take a look at it accordingly.

@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@QueryCoordinator thanks so much for flagging this. You're right, it should have referred to the Usage and insights report specifically. For more info about it, see https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-usage-insights-report?tabs=microsoft-entra-admin-center. We removed the reference in any case because rollouts are complete. #please-close
