### ISSUE TITLE
How to create app role for external ID tenant??

### ISSUE THREAD

**Issue by lukegreen001** [MicrosoftDocs/entra-docs#658]
Do you have any documentation on how to create an app role via the app manifest and then assign that role to a group?
When will the functionality that exists in Entra come to External ID where you just have the option to create app role via the UI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14e5e2e3-712e-79f5-e13c-9b5371941ef1
* Version Independent ID: 12b45a3f-c5ef-bf59-1153-a3d9ae579e0f
* Content: [Groups and app roles support in external tenants - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/reference-group-app-roles-support)
* Content Source: [docs/external-id/customers/reference-group-app-roles-support.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/reference-group-app-roles-support.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by PesalaPavan** [comment]
@lukegreen001 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @lukegreen001 
To create an app role for an external ID tenant, you can follow the same steps as creating an app role for any other Azure AD tenant. You can define app roles by using the Azure portal during the app registration process. App roles are defined on an application registration representing a service, app, or API. When a user signs in to the application, Azure AD emits a `roles` claim for each role that the user or service principal has been granted. This can be used to implement claim-based authorization. App roles can be assigned to a user or a group of users. App roles can also be assigned to the service principal for another application, or to the service principal for a managed identity.

To create an app role via the app manifest and then assign that role to a group, you can follow the steps described in this documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps. 

Regarding your question about the functionality that exists in Entra, I'm not sure what you are referring to. Could you please provide more information or clarify your question?

**Comment by ManoharLakkoju-MSFT** [comment]
@lukegreen001 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation

**Comment by lukegreen001** [comment]
I don't seem to have this option in apps I have created in my external
client. Why is that?

[image: image.png]
