### ISSUE TITLE
If a risk/detetion is deprecated, provide more information on replacement or guidance on changes

### ISSUE THREAD

**Issue by C-quintana** [MicrosoftDocs/entra-docs#66]
https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks#malware-linked-ip-address-deprecated

Specifically at this link. It would be handy to understand if another or newer detection (like Malicious IP address for example) is replacing this detection. 
Saying a detection is deprecated is fine, and that no more alerts will trigger is fine, but not providing more information to help identify if there will need to be some configuration change to make up for the deprecation makes this tricky. 

Looking at the page, an educated guess would lead me to think Malicious IP address is taking over the detection capability of Malware Linked IP address as they seem to offer similar detections based on name alone.

Can this please be clarified? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81a1385f-b90a-e7b4-8cbd-f25aeb8b3c49
* Version Independent ID: d468eb75-88a9-b1aa-7fb3-19ebb4faa179
* Content: [What are risks in Microsoft Entra ID Protection - Microsoft Entra ID Protection](https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks#verified-threat-actor-ip)
* Content Source: [docs/id-protection/concept-identity-protection-risks.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/concept-identity-protection-risks.md)
* Service: **active-directory**
* Sub-service: **identity-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by SaibabaBalapur-MSFT** [comment]
@C-quintana 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@C-quintana 

Thank you for bringing this to my attention. I understand that you are looking for more information on the deprecation of the Malware Linked IP Address detection in Azure AD Identity Protection.

While the documentation does not provide specific information on what detection is replacing Malware Linked IP Address, it does mention that the deprecation of this detection is part of a broader effort to improve the accuracy and relevance of Identity Protection detections.

That being said, the Verified Threat Actor IP detection is a similar detection that can help identify IP addresses that are associated with known threat actors. This detection can be used to help protect against attacks from known malicious actors.

If you have any further questions or concerns, please let me know.
