### ISSUE TITLE
Copilot for Microsoft 365 Service Plans/Plan IDs out of date

### ISSUE THREAD

**Issue by lornemaclen** [MicrosoftDocs/entra-docs#663]
Copilot for Microsoft 365 is not up-to-date.  There are 8 service plans.  Only 6 referenced on the page.
Here are the eight that I am able to get details on from our tenant.
Name, ServicePlanName, ServicePlanId
Graph Connectors in Microsoft 365 Copilot,GRAPH_CONNECTORS_COPILOT,82d30987-df9b-4486-b146-198b21d164c7;
Power Platform Connectors in Microsoft 365 Copilot,M365_COPILOT_CONNECTORS,89f1c4c8-0878-40f7-804d-869c9128ab5d;
Microsoft 365 Copilot in Productivity Apps,M365_COPILOT_APPS,a62f8878-de10-42f3-b68f-6149a25ceb97;
Microsoft 365 Copilot in Teams,M365_COPILOT_TEAMS,b95945de-b3bd-46db-8437-f2beb6ea2347;
Microsoft Copilot with Graph-grounded chat,M365_COPILOT_BUSINESS_CHAT,3f30311c-6b1e-48a4-ab79-725b469da960;
Intelligent Search,M365_COPILOT_INTELLIGENT_SEARCH,931e4a88-a67f-48b5-814f-16a5f1e6028d;
Copilot Studio in Copilot for M365,COPILOT_STUDIO_IN_COPILOT_FOR_M365,fe6c28b3-d468-44ea-bbd0-a10a5167435c;
Microsoft 365 Copilot for SharePoint,M365_COPILOT_SHAREPOINT,0aedf20c-091d-420b-aadf-30c042609612

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by PesalaPavan** [comment]
@lornemaclen 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@lornemaclen 
Thank you for bringing this to our attention.
I've delegated this to content author @Nicholak-MS, who will review it and offer their insightful opinions.

**Comment by Nicholak-MS** [comment]
Hi @lornemaclen thank you for sharing the above feedback. The Copilot SKU has been updated to reflect the two additional service plans. The online table and downloadable CSV will publish later today to reflect the changes. 

Thanks
Nick

#please-close
