### ISSUE TITLE
Example 3 for dynamic membership groups is incorrect

### ISSUE THREAD

**Issue by psignoret** [MicrosoftDocs/entra-docs#664]
Example 3 claims to illustrate how to select users without any assigned plans. If that is indeed the intent, the query is wrong. (It should probably say `assignedPlan.servicePlanId -eq null`, but someone from the dynamic membership team should confirm.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7a4070-1be8-5f1f-0092-68fb6b9e2305
* Version Independent ID: cd34312f-b507-affe-555e-1e0c63e7d494
* Content: [Rules for dynamically populated groups membership - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-membership#example-3)
* Content Source: [docs/identity/users/groups-dynamic-membership.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-dynamic-membership.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@psignoret 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@psignoret 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
