### ISSUE TITLE
Distribution groups can be assigned to an enterprise app in users and groups

### ISSUE THREAD

**Issue by ruaden94** [MicrosoftDocs/entra-docs#665]
I found that not only security groups and M365 groups, but also distribution groups can be assigned to enterprise apps under the users and groups section. This additional information could be added to the supported groups that can be assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 163a1f88-c268-18aa-a1e6-89b4a11bfb01
* Version Independent ID: 1136a613-48f8-fb67-39d3-d9abdd351a0f
* Content: [Manage users and groups assignment to an application - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/assign-user-or-group-access-portal?pivots=portal)
* Content Source: [docs/identity/enterprise-apps/assign-user-or-group-access-portal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/assign-user-or-group-access-portal.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by PesalaPavan** [comment]
@ruaden94 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@ruaden94 
Thank you for bringing this to our attention.
I've delegated this to content author @omondiatieno, who will review it and offer their insightful opinions.

**Comment by omondiatieno** [comment]
This issue has been addressed by updating the article to mention that distribution groups can also be assigned to users and groups - https://github.com/MicrosoftDocs/entra-docs-pr/pull/3418

#please-close
