### ISSUE TITLE
Troubleshooting Microsoft Entra B2B collaboration - Invitations have been disabled for directory - Suspect incorrect breadcrumb

### ISSUE THREAD

**Issue by SteveS72** [MicrosoftDocs/entra-docs#666]
On page:
"Troubleshooting Microsoft Entra B2B collaboration"
https://learn.microsoft.com/en-us/entra/external-id/troubleshoot

At subheading "Invitations have been disabled for directory"
https://learn.microsoft.com/en-us/entra/external-id/troubleshoot#invitations-have-been-disabled-for-directory

The breadcrumb starts with "Identity > Users ..."
Should the breadcrumb start with "Microsoft Entra ID > Users ... "?
The rest of the breadcrumb is correct.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f76cc85-8dc0-9be3-4071-217589ddef56
* Version Independent ID: e7bdba65-bacc-7fef-2c27-b3425f697b12
* Content: [Troubleshooting B2B collaboration - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/troubleshoot#invitations-have-been-disabled-for-directory)
* Content Source: [docs/external-id/troubleshoot.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/troubleshoot.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by PesalaPavan** [comment]
@SteveS72 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@SteveS72 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
