### ISSUE TITLE
Provide more information about verified_primary_email and verified_secondary_email

### ISSUE THREAD

**Issue by rmCredly** [MicrosoftDocs/entra-docs#67]
Looking for more information around these optional claims and how consumers should relying on them.

https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims-reference?source=docs#v10-and-v20-optional-claims-set

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3450bf5a-b689-4ea7-d4bd-67dcb6013a1e
* Version Independent ID: 75ccb0b2-4ca7-8761-c50e-8bc75b1b25a1
* Content: [Optional claims reference - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/optional-claims-reference?source=docs#v10-and-v20-optional-claims-set)
* Content Source: [docs/identity-platform/optional-claims-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/optional-claims-reference.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner*

**Comment by SaibabaBalapur-MSFT** [comment]
@rmCredly 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by rmCredly** [comment]
> @rmCredly It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

I've updated my post. Thanks for the quick reply

**Comment by Naveenommi-MSFT** [comment]
@rmCredly 
Thank you for bringing this to our attention.
I've delegated this to content author @cilwerner, who will review it and offer their insightful opinions.

**Comment by cilwerner** [comment]
Hi @rmCredly, I'll get clarification on this. Can you be more specific on "more information". Is it only for how customers should be relying on these claims or is there another thing you need to know about them?

**Comment by rmCredly** [comment]
@cilwerner Taking into consideration that these are optional claims, should app owners expect that these values are returned every time these claims are used? And specifically, when these claims are requested, and either is true, is it safe for app owners to trust the email during account creation within our apps?
