### ISSUE TITLE
Typo on the page

### ISSUE THREAD

**Issue by apcsb** [MicrosoftDocs/entra-docs#670]
> This feature requires Entra ID P2 licenses for reviewers and Workload ID Premium licenses for service **principles** that they want to set access reviews for

Should say "principals" not "principles"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2ed8dd-72be-b9b1-5a72-509a3c224758
* Version Independent ID: e53694fc-553a-d95b-3aae-e37280dd7263
* Content: [Microsoft Entra Workload ID license plans FAQ - Microsoft Entra Workload ID](https://learn.microsoft.com/en-us/entra/workload-id/workload-identities-faqs)
* Content Source: [docs/workload-id/workload-identities-faqs.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/workload-id/workload-identities-faqs.md)
* Service: **entra-workload-id**
* GitHub Login: @Gargi-Sinha
* Microsoft Alias: **gasinh**

**Comment by PesalaPavan** [comment]
@apcsb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@apcsb 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
