### ISSUE TITLE
Hybrid Identity Administrator role does not work for kerberos key roll over

### ISSUE THREAD

**Issue by palito1980** [MicrosoftDocs/entra-docs#672]
[Enter feedback here]

Hybrid Identity Administrator role causes error:
Uploading computer account information failed. Error message: Internal error: An error occurred during the 'DesktopSsoNumOfDomains' process.

Global Entra ID Administrator role is working fine.

Please update the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f01328-ebfa-31af-4e67-6de92c8f924e
* Version Independent ID: a990551f-e6c9-dede-308a-b5578fb7ee1e
* Content: [Microsoft Entra Connect - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sso-faq)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sso-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sso-faq.yml)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@palito1980 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by billmath** [comment]
Following up with engineering

**Comment by AjayBathini-MSFT** [comment]
@palito1980 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by billmath** [comment]
Thank for submitting this.  I have not heard back from engineering yet so I have created a work item to investigate this further. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
