### ISSUE TITLE
Clarification Request - Refresh Token Expiry for non-spa clients

### ISSUE THREAD

**Issue by seanke** [MicrosoftDocs/entra-docs#68]
I have read the 'Token Lifetime' section of this article and am wondering if the following is true:

If a client is not a single-page application (SPA), and a refresh of a refresh token is requested, the expiry date of the new refresh token will not be carried over from the previous refresh token. So it must be that the refresh token can be renewed indefinitely without requiring user interaction, unless timeouts or revocations occur (as mentioned in the 'Token Expiration' section of the same article).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b38c5bb-b6fd-ed73-e415-837a69a0a8e1
* Version Independent ID: 30bf75b4-a333-2def-a672-b45c83f06348
* Content: [Refresh tokens in the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/refresh-tokens)
* Content Source: [docs/identity-platform/refresh-tokens.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/refresh-tokens.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by SaibabaBalapur-MSFT** [comment]
@fadnavistanmay 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@seanke 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@cilwerner 
please review it.

**Comment by nickludwig** [comment]
Hey @seanke - that's correct. For non-SPA scenarios, the refresh token granted will have a fresh expiry (i.e., expiry is not carried over), thus enabling you to renew indefinitely while the refresh token is valid. Just remember to follow best practices surrounding refresh tokens (i.e., secure storage, delete old refresh tokens once you've obtained a new one). Also, there are a variety of scenarios where the refresh token can be revoked by the server if certain actions are performed (i.e., password reset) - a full list can be found at the bottom of the refresh token article you linked here. 

Let me know if this helps answer your question - if so, I'll go ahead and close the issue. Thanks!

**Comment by seanke** [comment]
Awesome, thank you so much. That answers my question perfectly.

**Comment by nickludwig** [comment]
No worries! Going to close the thread now

**Comment by nickludwig** [comment]
#please-close
