### ISSUE TITLE
Contradictory Enforce key restrictions text

### ISSUE THREAD

**Issue by rubens-tvt** [MicrosoftDocs/entra-docs#680]
In https://admin.microsoft.com/Adminportal/Home#/MessageCenter/:/messages/MC690185 the preview configuration indicates that Enforce Key Restrictions must be set to YES for device bound passkeys to work. However, in this article, it says nothing about this and instead indicates Enforce key restrictions can be set to NO and does not impact the public preview. It is unclear which setting is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 784337eb-25c8-e8b5-58ff-b5d3b32c6298
* Version Independent ID: 784337eb-25c8-e8b5-58ff-b5d3b32c6298
* Content: [Enable passkeys for your organization (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-enable-passkey-fido2#enable-passkey-fido2-authentication-method)
* Content Source: [docs/identity/authentication/how-to-enable-passkey-fido2.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-enable-passkey-fido2.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@rubens-tvt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Justinha** [comment]
@TPavanBalaji Sorry for the confusion. I can't see the message text in the Admin Center, but key restrictions are used to allow or block only specific AAGUIDs. The web topic is correct. If no key restrictions are set, then any device-bound passkey can be used for sign in. #please-close

**Comment by rubens-tvt** [comment]
I've pasted the text below from the message center and highlighted the contradictory text. If the help text is correct, then the notification should be corrected:

Updated February 19, 2024: We have updated the rollout timeline below. Thank you for your patience.

Beginning mid-March 2024, Microsoft Entra ID will support [device-bound passkeys](https://passkeys.dev/docs/reference/terms/#device-bound-passkey) stored on computers and mobile devices as an authentication method in preview, in addition to the existing support for FIDO2 security keys. This enables your users to perform phishing-resistant authentication using the devices that they already have.

We will be expanding the existing FIDO2 authentication methods policy and end user experiences to support this preview release. If your organization uses FIDO2 authentication or Windows Hello for Business, please continue reading to learn more and prepare for the upcoming changes.

Admin Configuration

In the Entra admin portal, we will be renaming “FIDO2 security keys” to “Passkeys (FIDO2)” within the authentication methods policy and Conditional Access authentication strengths policy.

For your organization to opt-in to this preview, you will need to enforce key restrictions to allow specified passkey providers in your FIDO2 policy. Here are the possible configuration states for FIDO2 key restrictions during the preview:

No key restrictions (FIDO2 policy default): Tenant allows all security key models. **Device-bound passkey providers on computers and mobile devices are not allowed.**
Key restrictions set to "Allow": Tenant only allows the explicitly added AAGUIDs. **To enable a device-bound passkey provider, add their AAGUID(s) to the key restrictions list.**
Key restrictions set to "Block": Tenant blocks the explicitly added AAGUIDs and allows all other security key models. Device-bound passkey providers on computers and mobile devices are not allowed.
