### ISSUE TITLE
products missing

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/entra-docs#681]
[Enter feedback here]

Following products are missing

GUID 3227bcb2-8448-4f81-b3c2-8c2074e15a2a
SkuPartNumber: Microsoft_Viva_Sales
DisplayName: Microsoft Sales Copilot

GUID c9d442fc-21fb-4bd7-89e0-a710d74987f6
SkuPartNumber: VIVA_LEARNING
DisplayName: Microsoft Viva Learning

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by TPavanBalaji** [comment]
@grzegorzwierzbicki 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@grzegorzwierzbicki 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by Nicholak-MS** [comment]
Hi @grzegorzwierzbicki the above products have now been added to the online table and the downloadable CSV. 

Thanks for sharing the feedback. 
Nick

#please-close
