### ISSUE TITLE
Android section omits reference to native Microsoft apps

### ISSUE THREAD

**Issue by rubens-tvt** [MicrosoftDocs/entra-docs#683]
This page has both iOS and Android tabs on it. In the iOS tab, there's a section for web, cross-device, native apps. In the Android section, it indicates web is not supported, covers cross-device, but completely omits references to native apps. It is unclear whether native Android apps are supported with passkeys, and if so what is the procedure to login using native Microsoft Android apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e251214c-f2d6-3167-ec55-1959714ea1c6
* Version Independent ID: e251214c-f2d6-3167-ec55-1959714ea1c6
* Content: [Sign in with passkeys in Authenticator for Android and iOS devices (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-sign-in-passkey-authenticator?tabs=iOS)
* Content Source: [docs/identity/authentication/how-to-sign-in-passkey-authenticator.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-sign-in-passkey-authenticator.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@rubens-tvt 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@rubens-tvt 
I'm going to assign this to the document author so they can take a look at it accordingly.

@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@rubens-tvt Thanks for the feedback! Native app support is coming soon. We added this and more info can be found at https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-compatibility#native-application-support-with-authentication-broker-preview
#please-close
