### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Aleis007891** [MicrosoftDocs/entra-docs#685]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a826ee6f-f457-7109-9f77-67c57977d4e7
* Version Independent ID: 11766f27-492e-a579-dced-8a42528cbb47
* Content: [Microsoft Entra authentication & authorization error codes - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes)
* Content Source: [docs/identity-platform/reference-error-codes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-error-codes.md)
* Service: **identity-platform**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by PesalaPavan** [comment]
@Aleis007891 
It would be great if you could add elaborate your query and a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by Naveenommi-MSFT** [comment]
@Aleis007891 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
