### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by vlijmenfileer** [MicrosoftDocs/entra-docs#686]
"WC3 WebAuthn standard" should probably be "W3C WebAuthn standard"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1d3d10a-690c-6744-53bf-3f1e75c79908
* Version Independent ID: e1d3d10a-690c-6744-53bf-3f1e75c79908
* Content: [How to enable passkeys in Microsoft Authenticator sign in for Microsoft Entra ID (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-enable-authenticator-passkey)
* Content Source: [docs/identity/authentication/how-to-enable-authenticator-passkey.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-enable-authenticator-passkey.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@vlijmenfileer 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@vlijmenfileer 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
https://github.com/MicrosoftDocs/entra-docs-pr/pull/3226
