### ISSUE TITLE
"Watch a short video that describes this process." not even relevant anymore

### ISSUE THREAD

**Issue by the-epoch** [MicrosoftDocs/entra-docs#687]
Under the heading Block and unblock users, the following video links aren't even relevant anymore:
 - [how to block and unblock users in your tenant](https://www.youtube.com/watch?v=WdeE1On4S1o)
 - [Watch a short video that describes this process.](https://www.youtube.com/watch?v=WdeE1On4S1o&feature=youtu.be)
 
The menu's have totally changed in Entra and the video's are totally wrongm now. Microsoft change Azure /Entra interface so often that even Microsoft can't keep up with the documentation. There might be a lesson here....?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84b26750-880c-8f14-1628-436293de915e
* Version Independent ID: 518b727f-79e8-b5c2-bcb3-ff4de3444c6f
* Content: [Configure Microsoft Entra multifactor authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-mfasettings#block-and-unblock-users)
* Content Source: [docs/identity/authentication/howto-mfa-mfasettings.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-mfasettings.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@the-epoch 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@the-epoch 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@Justinha 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Justinha** [comment]
@the-epoch Thanks for raising this. I'm removing the links to the stale videos because we don't have resources to update them.

**Comment by Justinha** [comment]
#please-close
