### ISSUE TITLE
Conflict content under "Enforce Conditional Access policies" and "MFA sign-in method required"

### ISSUE THREAD

**Issue by Melody7890** [MicrosoftDocs/entra-docs#689]
[Enter feedback here]
Under "Enforce Conditional Access policies", the doc states that Remote desktop using Windows Hello for Business authentication is available only for deployments that use a certificate trust model. It's currently not available for a key trust model.

However, under "MFA sign-in method required", it is stating that "Using Windows Hello for Business authentication during RDP is available for deployments that use a certificate trust model or key trust model."

According to our internal wiki https://supportability.visualstudio.com/AzureAD/_wiki/wikis/AzureAD/184126/Azure-AD-Sign-in-for-Azure-Windows-VMs?anchor=limitations, if the user signing in is subject to a conditional access policy that requires MFA and Windows Hello for Business cert trust model has not been deployed, the sign-in will be blocked until the "Azure Windows VM Sign-In" application is excluded from list of cloud apps that require MFA.

Therefore, the content under "MFA sign-in method required" is incorrect. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Sign in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@Melody7890 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Melody7890 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by Melody7890** [comment]
Thanks a lot!

Best regards,
Melody

**Comment by MicrosoftGuyJFlo** [comment]
The information is correct as written. If you arent using strong auth or you are per-user MFA you need to exclude the app from Conditional Access.

#please-close
