### ISSUE TITLE
Typo in Mapping expression

### ISSUE THREAD

**Issue by Cyraxwins** [MicrosoftDocs/entra-docs#69]
Missing required extra comma on mapping expression.

correct:  FormatDateTime([StatusHireDate], ,"yyyy-MM-ddzzz", "yyyyMMddHHmmss.fZ" )

incorrect:  FormatDateTime([StatusHireDate], "yyyy-MM-ddzzz", "yyyyMMddHHmmss.fZ" )

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53987154-8f6c-1ddd-ec02-2b811ae74818
* Version Independent ID: eaf44627-eddc-5aeb-7189-661d5dcb90fe
* Content: [How to synchronize attributes for Lifecycle workflows - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/how-to-lifecycle-workflow-sync-attributes)
* Content Source: [docs/id-governance/how-to-lifecycle-workflow-sync-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/how-to-lifecycle-workflow-sync-attributes.md)
* Service: **active-directory**
* Sub-service: **compliance**
* GitHub Login: @OWinfreyATL
* Microsoft Alias: **owinfrey**

**Comment by SaibabaBalapur-MSFT** [comment]
@Cyraxwins 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Cyraxwins 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
