### ISSUE TITLE
Wrong info on which directory role is required to perform group setting change

### ISSUE THREAD

**Issue by hharsunen** [MicrosoftDocs/entra-docs#693]
Groups Administrator role is not enough to edit all the mentioned settings, to be more specific, at least the "Users can create security groups in Azure portals, API or PowerShell" setting is not managed by the Groups Administrator role.

You need to be either Privileged Role Administrator or Global Administator to be able to set this policy
https://learn.microsoft.com/en-us/graph/api/authorizationpolicy-update?view=graph-rest-1.0&tabs=http#permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4404d856-2612-f4a2-ed5c-fff65761293a
* Version Independent ID: 35b07132-7d8a-2c29-3988-54a2ae8fcc25
* Content: [Set up self-service group management - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-self-service-management)
* Content Source: [docs/identity/users/groups-self-service-management.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-self-service-management.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@hharsunen 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@hharsunen 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.

**Comment by barclayn** [comment]
@hharsunen thank you for pointing this out. We will get the article updated. #please-close
