### ISSUE TITLE
Article is unfinished

### ISSUE THREAD

**Issue by Creddahornis** [MicrosoftDocs/entra-docs#695]
This entire article is unfinished. Whole sections are written in incomplete sentences, or aren't relevant to their headings. UPN change is a common issue with some significant impacts so it would be a very helpful article to have finished

Thanks :)
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e58beed-28f8-adac-fb79-6c0021aab7b9
* Version Independent ID: f075fb4c-c207-040c-a0f4-81cf7d786ac1
* Content: [Plan and troubleshoot User Principal Name changes in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/howto-troubleshoot-upn-changes)
* Content Source: [docs/identity/hybrid/connect/howto-troubleshoot-upn-changes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/howto-troubleshoot-upn-changes.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @Gargi-Sinha
* Microsoft Alias: **gasinh**

**Comment by TPavanBalaji** [comment]
@Creddahornis 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Gargi-Sinha** [comment]
Hi @Creddahornis - Thanks for your feedback. Could you please provide some specific examples where you think the information is incomplete, it will help us improve the doc.

**Comment by Creddahornis** [comment]
Sure

UPN and their changes - this section is incomplete and makes no sense
UPN change types - it's not clear what this is here for
UPNs in Active Directory - the link here isn't formatted properly
etc.

The entire article is dotted with minor spelling and grammar mistakes as well

**Comment by Gargi-Sinha** [comment]
Hi @Creddahornis - Thanks. We will update the doc based on your inputs.

**Comment by edmckillop** [comment]
PR 3293 created to address Issue 695.

**Comment by SaibabaBalapur-MSFT** [comment]
@edmckillop Thanks for creating PR.
@Creddahornis We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
