### ISSUE TITLE
Instructions for convert domain with staged rollout not complete!?

### ISSUE THREAD

**Issue by bniessink** [MicrosoftDocs/entra-docs#696]
Dear Mr/Mrs,

We are using staged rollout with PTA with success. We have only 1 federated domain.
We want to convert our federated domain to managed domain with PTA and seamless SSO.
Last week we followed the steps under:
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/migrate-from-federation-to-cloud-authentication#using-staged-rollout 

and

https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/migrate-from-federation-to-cloud-authentication#convert-domains-from-federated-to-managed

After we succesfully executed the Update-MgDomain -DomainId <domain name> -AuthenticationType "Managed" and removing one user from staged rollout, we discovered that this user could not sign using PTA as the Entra ID portal was still seeing PTA as disabled and Entra ID was handling the authentication request as cloud only (password in the cloud) . Only after we changed the signin method in Entra ID Connect and following the necessary steps the user eventually could signin successfully using PTA. The documentation is not mentioning these extra steps in Entra ID Connect. Shouldn't these be added to the documentation?
Or did we miss something in our approach?

Best regards,
Bob Niessink

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2314a6-398f-67a0-08b7-405340d87125
* Version Independent ID: b9ef26c7-1266-821c-a887-fad8401c1f6b
* Content: [Migrate from federation to cloud authentication in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/migrate-from-federation-to-cloud-authentication)
* Content Source: [docs/identity/hybrid/connect/migrate-from-federation-to-cloud-authentication.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/migrate-from-federation-to-cloud-authentication.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @Gargi-Sinha
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@bniessink 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @bniessink 

Based on your description, it seems that Entra ID Connect was still configured to handle authentication requests as cloud-only, even though you had successfully converted your domain to managed authentication with PTA. This could be due to a configuration issue or a delay in the synchronization of settings between Azure AD and Entra ID Connect.

To ensure that Entra ID Connect recognizes PTA as enabled after converting your domain to managed authentication, you may need to update the sign-in method settings in Entra ID Connect to reflect the changes. This can be done by following the steps outlined in the Entra ID Connect documentation for configuring PTA.

I agree that it would be helpful to include more detailed information on this topic in the Azure AD documentation for migrating from federation to cloud authentication using staged rollout with PTA.

Please go through this below link for your reference. It might be helpful.
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/choose-ad-authn#:~:text=Microsoft%20Entra%20pass%2Dthrough,pass%2Dthrough%20authentication.

**Comment by bniessink** [comment]
Thank you for your information and advice.
Our finding was exactly like you described. Our Entra ID Connect sign-in method was still configured as federated authentication. Our conclusion is that the convert command does not change any setting in Entra ID Connect. As soon as we changed the sign-in method to PTA we were able to login successfully.
I am not sure if this only applies to PTA, but it would be helpful for others when the documentation includes the step to check/change the signin method in Entra ID Connect after converting a domain to managed authentication.

Best regards,
Bob Niessink

Van: Naveenommi-MSFT ***@***.***>
Verzonden: donderdag 25 april 2024 08:18
Aan: MicrosoftDocs/entra-docs ***@***.***>
CC: bniessink ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MicrosoftDocs/entra-docs] Instructions for convert domain with staged rollout not complete!? (Issue #696)


Hello @bniessink<https://github.com/bniessink>

Based on your description, it seems that Entra ID Connect was still configured to handle authentication requests as cloud-only, even though you had successfully converted your domain to managed authentication with PTA. This could be due to a configuration issue or a delay in the synchronization of settings between Azure AD and Entra ID Connect.

To ensure that Entra ID Connect recognizes PTA as enabled after converting your domain to managed authentication, you may need to update the sign-in method settings in Entra ID Connect to reflect the changes. This can be done by following the steps outlined in the Entra ID Connect documentation for configuring PTA.

I agree that it would be helpful to include more detailed information on this topic in the Azure AD documentation for migrating from federation to cloud authentication using staged rollout with PTA.

Please go through this below link for your reference. It might be helpful.
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/choose-ad-authn#:~:text=Microsoft%20Entra%20pass%2Dthrough,pass%2Dthrough%20authentication<https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/choose-ad-authn#:~:text=Microsoft%20Entra%20pass-through,pass-through%20authentication>.

-

**Comment by Naveenommi-MSFT** [comment]
@bniessink 
Thank you for bringing this to our attention.
I've delegated this to content author @Gargi-Sinha, who will review it and offer their insightful opinions.

@Gargi-Sinha 
Please review it.

**Comment by CelesteDG** [comment]
@Gargi-Sinha @martincoetzer We are migrating all GitHub issues to ADO as we switch our feedback mechanism to UUF. Please either address the issue, or close and track it in ADO no later than June 10, 2024. Thank you.

**Comment by Gargi-Sinha** [comment]
Hi @bniessink - Thank you for your feedback, the doc is updated.

**Comment by Gargi-Sinha** [comment]
Hi @Naveenommi-MSFT - Could you please help close this request, doc is updated.  - PR https://github.com/MicrosoftDocs/entra-docs-pr/pull/3954

**Comment by Naveenommi-MSFT** [comment]
@bniessink 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close

**Comment by bniessink** [comment]
Thank you for updating the documentation. I have no further questions for now.
Feel free to close this thread.

Best regards,
Bob Niessink

Van: Naveenommi-MSFT ***@***.***>
Verzonden: vrijdag 7 juni 2024 06:07
Aan: MicrosoftDocs/entra-docs ***@***.***>
CC: bniessink ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [MicrosoftDocs/entra-docs] Instructions for convert domain with staged rollout not complete!? (Issue #696)


@bniessink<https://github.com/bniessink>
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close

-
