### ISSUE TITLE
typo; c. Seelct

### ISSUE THREAD

**Issue by fd185095** [MicrosoftDocs/entra-docs#697]
typo; c. Seelct 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb3dfdfb-4f4e-d464-79a3-7189659c80f2
* Version Independent ID: f2e8acf7-5622-b311-74a8-5fca8aa93aaf
* Content: [FortiGate deployment guide - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/media/fortigate-ssl-vpn-tutorial/fortigate-deployment-guide-converted)
* Content Source: [docs/identity/saas-apps/media/fortigate-ssl-vpn-tutorial/fortigate-deployment-guide-converted.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/media/fortigate-ssl-vpn-tutorial/fortigate-deployment-guide-converted.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by TPavanBalaji** [comment]
@fd185095 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@fd185095 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
