### ISSUE TITLE
SSPR on-prem DC down - what happens?

### ISSUE THREAD

**Issue by stefanminehan1991** [MicrosoftDocs/entra-docs#699]
Could do with some information as to what happens if the on-prem domain is down? - does SSPR work?

If it works and the password set violates the password policies on prem, when the on-prem DC returns to usual function  does the user then get prompted to change their password again? 

Cheers
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebc51bb0-dd9d-cb3f-3e3f-b9765b48f21d
* Version Independent ID: d597a70e-8fb1-0e4e-8ae0-e3cd87de1118
* Content: [On-premises password writeback with self-service password reset - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-writeback)
* Content Source: [docs/identity/authentication/concept-sspr-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-sspr-writeback.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@stefanminehan1991 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@stefanminehan1991 
If the on-premises domain is down, the Self-Service Password Reset (SSPR) feature in Azure Active Directory (AAD) may not work as expected. Specifically, if the user's password is stored on the on-premises Active Directory (AD) server and the server is down, the user may not be able to reset their password using SSPR.

However, if the user's password is stored in AAD (for example, if the user is a cloud-only user or if password writeback is enabled), SSPR should still work even if the on-premises domain is down. In this case, the user can reset their password using SSPR, and the new password will be written to AAD. When the on-premises domain comes back online, the new password will be synchronized to the on-premises AD server.

Regarding your question about password policies, if the user's password is reset using SSPR and the new password violates the password policies on-premises, the user may be prompted to change their password again when the on-premises domain comes back online. This depends on the specific password policies and synchronization settings configured in the on-premises AD server. If password writeback is enabled, the new password will be synchronized to the on-premises AD server, but it may be rejected if it violates the password policies. In this case, the user may be prompted to change their password again to comply with the policies.
