### ISSUE TITLE
Microsoft Entra ID for customers vs Microsoft Entra External ID

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [MicrosoftDocs/entra-docs#7]
Please clarify what is the difference between “Microsoft Entra ID for customers” vs “Microsoft Entra External ID”
Are you using them interchangeably? Is one of them temporary name and another official name? Which one is the recommended to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e407c207-e1d7-f901-e184-f0daa7bd3d02
* Version Independent ID: a503616f-3fb2-4530-589b-9c421fd829c0
* Content: [Frequently asked questions - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/faq-customers)
* Content Source: [docs/external-id/customers/faq-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/faq-customers.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@michael-freidgeim-webjet 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Flagging this for @msmimart - Michele, please see the customer question.

**Comment by msmimart** [comment]
Hi @michael-freidgeim-webjet, here's a summary:

- [Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/fundamentals/whatis) provides identity and access management for your internal employees.
- [Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview) provides identity and access management for external identities. This includes:
     - [Microsoft Entra External ID for customers](https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam): Customer identity and access management (CIAM) for apps you publish to external customers.
     - [B2B collaboration](https://learn.microsoft.com/en-us/entra/external-id/what-is-b2b): Identity access management (IAM) for external business guests your employees collaborate with.

I hope this helps, and thanks for bringing it up - we can add an entry to the FAQ doc you reference.

**Comment by msmimart** [comment]
#please-close
