### ISSUE TITLE
fadis3874@gmail.com

### ISSUE THREAD

**Issue by Fss2040506080** [MicrosoftDocs/entra-docs#70]
```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/entra-docs/issues/68
```

**Comment by SaibabaBalapur-MSFT** [comment]
@Fss2040506080 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by SaibabaBalapur-MSFT** [comment]
@Fss2040506080 please don't create spam cases.
