### ISSUE TITLE
REOPEN: Question about how many times you should run Update-AzureADSSOForest in a given timespan

### ISSUE THREAD

**Issue by withersravenel** [MicrosoftDocs/entra-docs#701]
In the section "How can I roll over the Kerberos decryption key of the `AZUREADSSO` computer account?" it states that "We highly recommend that you roll over the Kerberos decryption key at least every 30 days." but then at the bottom it states "Ensure that you don't run the Update-AzureADSSOForest command more than once per forest."  Should that say don't run it more than once per forest every x days/hours, or does it really mean don't run it more than once ever?  It sounded like we need to run "Update-AzureADSSOForest" at least every 30 days, but then it says not to run it more than once.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20f01328-ebfa-31af-4e67-6de92c8f924e
* Version Independent ID: a990551f-e6c9-dede-308a-b5578fb7ee1e
* Content: [Microsoft Entra Connect - Microsoft Entra ID](https://learn.microsoft.com/en-gb/entra/identity/hybrid/connect/how-to-connect-sso-faq#feedback)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sso-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sso-faq.yml)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@withersravenel 
The recommendation to roll over the Kerberos decryption key at least every 30 days is to ensure maximum security. However, you should not run the Update-AzureADSSOForest command more than once per forest. This command is used to update the Azure AD Seamless Single Sign-On configuration in your on-premises environment and should only be run when necessary, such as when you make changes to your on-premises Active Directory environment or when you need to troubleshoot an issue with Seamless SSO. Running this command more than once per forest can cause issues with your Seamless SSO configuration. So, to clarify, you should roll over the Kerberos decryption key at least every 30 days, but you should only run the Update-AzureADSSOForest command when necessary and not more than once per forest.

**Comment by withersravenel** [comment]
The instructions on how to roll over the Kerberos decryption key states:
"... 
2. Call Update-AzureADSSOForest -OnPremCredentials $creds. This command updates the Kerberos decryption key for the AZUREADSSO computer account in this specific AD forest and updates it in Microsoft Entra ID.
..."
Is there a way to roll over the Kerberos decryption key without running the Update-AzureADSSOForest command?

**Comment by withersravenel** [comment]
Well, I disagree.  Your document could be improved by making sense.  It says the way to roll over the key is to run the command Update-AzureADSSOForest at least every 30 days, then it says to not run that same Update-AzureADSSOForest command more than once.  How can you run it every 30 days and also not run it more than once?

**Comment by SaibabaBalapur-MSFT** [comment]
@withersravenel 
I'm going to assign this to the document author so they can take a look at it accordingly.

@billmath 
Can you please check and add your comments on this doc update request as applicable.

**Comment by billmath** [comment]
Thank you for the submission.  @SaibabaBalapur-MSFT is correct.  You should roll over the Kerberos decryption key at least every 30 days, but you should only run the Update-AzureADSSOForest not more than once per forest. 

Is there a way to roll over the Kerberos decryption key without running the Update-AzureADSSOForest command? - Not that I am aware of.  This document describes how to do it manually.  There are ways to script this so that it is automatic.

How many times you should run Update-AzureADSSOForest in a given timespan?  This is a question for support.  We currently do not recommend running it more than once per forest, every 30 days.

I have updated the documentation for clarity and it should be live later today.  

Thanks!

Bill

#please-close
