### ISSUE TITLE
Event Log location did not change with the Entra ID rename

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#702]
Someone was a bit overreacting with the rename for AAD to Entra ID.

In Event Viewer, open the Microsoft Entra Operational event logs. They're stored under Applications and Services Log > Microsoft > Windows > Microsoft Entra ID

This event log location does not exist and was not impacted by the rename, and should not have been changed in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9f81d74-8dcb-e644-9647-0d1d0817f975
* Version Independent ID: e249cc9d-2120-8868-dbca-bc3b85f38b4b
* Content: [Troubleshoot Microsoft Entra hybrid joined devices - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/troubleshoot-hybrid-join-windows-current)
* Content Source: [docs/identity/devices/troubleshoot-hybrid-join-windows-current.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/troubleshoot-hybrid-join-windows-current.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
#remove-label:"cxp"
#label:"assigned-to-author"
#reassign:@MicrosoftGuyJFlo
