### ISSUE TITLE
Image using outdated terminology (Azure AD)

### ISSUE THREAD

**Issue by minusX** [MicrosoftDocs/entra-docs#703]
The image still references "Azure AD" instead of Microsoft Entra ID 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d334036-b74e-acb9-f0af-a6e281e907dd
* Version Independent ID: 60fc83b6-9ba2-80f0-d94d-747104cf78df
* Content: [SCIM synchronization with Microsoft Entra ID - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/sync-scim)
* Content Source: [docs/architecture/sync-scim.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/sync-scim.md)
* Service: **entra**
* Sub-service: **architecture**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by SaibabaBalapur-MSFT** [comment]
@minusX 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@janicericketts 
Can you please check and add your comments on this doc update request as applicable.
