### ISSUE TITLE
Missing information on how to apply HRD Policy to an application using Microsoft Graph

### ISSUE THREAD

**Issue by mruss77** [MicrosoftDocs/entra-docs#704]
The "Azure AD Powershell" version of this page explains how to apply the HRD Policy to a Service Principal. The "Microsoft Graph" version of the instructions does not address this topic at all. The Graph instructions explain how to create a policy but not how to attach the policy to an application.

Do I need to use Azure AD Powershell to apply the HRD Policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc5a36a7-2acb-c7d5-4629-e8c1f026cad3
* Version Independent ID: 1749bb9d-766e-c639-20a2-c22749448822
* Content: [Configure sign-in auto-acceleration using Home Realm Discovery - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/configure-authentication-for-federated-users-portal)
* Content Source: [docs/identity/enterprise-apps/configure-authentication-for-federated-users-portal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/configure-authentication-for-federated-users-portal.md)
* Service: **entra-id**
* Sub-service: **enterprise-apps**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by TPavanBalaji** [comment]
@mruss77 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@mruss77 
To apply the Home Realm Discovery (HRD) policy to a service principal, you can use either Azure AD PowerShell or Microsoft Graph API. The instructions provided in the documentation page you mentioned are specific to each method.

The Azure AD PowerShell instructions explain how to apply the HRD policy to a service principal using the Add-AzureADServicePrincipalPolicy cmdlet. This method is useful if you prefer to use PowerShell to manage your Azure AD resources.

The Microsoft Graph API instructions explain how to create an HRD policy using the POST /policies endpoint. Once you have created the policy, you can apply it to a service principal using the POST /servicePrincipals/{id}/policies/$ref endpoint. This method is useful if you prefer to use REST APIs to manage your Azure AD resources.

Both methods are valid and can be used to apply the HRD policy to a service principal. You can choose the method that best suits your needs and preferences.

I hope this helps! If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by mruss77** [comment]
Thanks for the reply, @Naveenommi-MSFT !

This part is exactly the information I was looking for:  "Once you have created the policy, you can apply it to a service principal using the POST /servicePrincipals/{id}/policies/$ref endpoint."

I think it would be helpful to add that information to the article. The Graph instructions left me hanging with a policy created but no way to apply it to the app. Now I know, but others might have the same question.

**Comment by Naveenommi-MSFT** [comment]
@mruss77 
We will discuss with our PG Team, they will review it and update accordingly.

@omondiatieno
Please review it.
