### ISSUE TITLE
Required Roles / Permissions

### ISSUE THREAD

**Issue by jrg-jeff** [MicrosoftDocs/entra-docs#705]
This article doesn't provide guidance on the necessary roles and permissions to manage OATH tokens. It mentions that the actions can be performed by a Global Administrator, but is that the only role that can perform these actions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3580bf07-789b-a9c0-26c2-68d21eb66b70
* Version Independent ID: f61c354b-cac2-c3e2-881a-2f0540bdd8e1
* Content: [OATH tokens authentication method - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-oath-tokens)
* Content Source: [docs/identity/authentication/concept-authentication-oath-tokens.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-oath-tokens.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@jrg-jeff 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @jrg-jeff 
While the article does not provide specific guidance on roles and permissions required to manage OATH tokens, it does mention that a Global Administrator can upload and activate OATH tokens. However, it is important to note that Global Administrator is the highest level of administrative privilege in Azure AD, and it is recommended to limit the number of users who have this role. 

In general, the ability to manage OATH tokens is controlled by the "Authentication Administrator" role in Azure AD. This role allows users to manage authentication methods, including OATH tokens. Additionally, the "Privileged Authentication Administrator" role can manage authentication methods and also has access to sensitive authentication data. 

To assign these roles to users, you can use the Azure AD portal or PowerShell. For more information on managing roles and permissions in Azure AD, you can refer to the following documentation: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles

**Comment by ManoharLakkoju-MSFT** [comment]
@jrg-jeff 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
