### ISSUE TITLE
What License is required to use this feature?

### ISSUE THREAD

**Issue by ivratche** [MicrosoftDocs/entra-docs#706]
What License is required to use this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcc79933-58e1-66d1-81ae-f43802d41223
* Version Independent ID: 5be1fefc-356e-d1eb-ab97-8cbe5654ff43
* Content: [Filter for devices as a condition in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-condition-filters-for-devices)
* Content Source: [docs/identity/conditional-access/concept-condition-filters-for-devices.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-condition-filters-for-devices.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Conditional Access is a Microsoft Entra ID P1 feature. This is covered in the [Overview article](https://learn.microsoft.com/entra/identity/conditional-access/overview#license-requirements) and the [Deployment planning article](https://learn.microsoft.com/entra/identity/conditional-access/plan-conditional-access#prerequisites).

**Comment by MicrosoftGuyJFlo** [comment]
#label:"assigned-to-author", "product-question", "triaged"
#reassign:@MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
