### ISSUE TITLE
Roles / Permissions needed.

### ISSUE THREAD

**Issue by VortexGif** [MicrosoftDocs/entra-docs#708]
I am trying to enable MIP Labels in Entra using 
`Update-MgBetaDirectorySetting -DirectorySettingId ID -BodyParameter $params`

I am getting the following error:
```
Update-MgBetaDirectorySetting : Insufficient privileges to complete the operation.
Status: 403 (Forbidden)
ErrorCode: Authorization_RequestDenied
Date: 2024-04-23T14:16:44
```

I have the following scopes for MGGraph:

`"Directory.ReadWrite.All","Policy.ReadWrite.Authorization"`

Please could you advise what Roles/Permissions are needed to perform this action.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef84a3e0-879e-4312-a89d-7a3bb0cd9a51
* Version Independent ID: 43851f8a-b71f-0a0a-8b1f-629e3528972f
* Content: [Assign sensitivity labels to groups - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-assign-sensitivity-labels)
* Content Source: [docs/identity/users/groups-assign-sensitivity-labels.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-assign-sensitivity-labels.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@VortexGif 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by VortexGif** [comment]
Hi ,

Yeah sorry! 

Its from these docs - https://learn.microsoft.com/en-us/entra/identity/users/groups-assign-sensitivity-labels

**Comment by Naveenommi-MSFT** [comment]
Hello @VortexGif 
To perform this operation, you need to have the `Directory.ReadWrite.All` and `Policy.ReadWrite.Authorization` permissions, as you mentioned. However, you also need to have the appropriate role assignments in Azure AD to perform the operation.

To update directory settings in Azure AD, you need to have the `Directory.Settings.ReadWrite` role assigned to your account. This role allows you to read and modify directory settings, including MIP labels.

You can assign the `Directory.Settings.ReadWrite` role to your account using the Azure AD portal or Azure AD PowerShell. To assign the role using the Azure AD portal, follow these steps:

1. Sign in to the Azure AD portal with an account that has the `Global Administrator` or `Directory Administrator` role.
2. Navigate to the `Azure Active Directory` blade.
3. Click on `Roles and administrators`.
4. Click on `Add assignment`.
5. Select the `Directory.Settings.ReadWrite` role from the list of available roles.
6. Select the user or group that you want to assign the role to.
7. Click on `Add assignment` to complete the process.

Once you have assigned the `Directory.Settings.ReadWrite` role to your account, you should be able to perform the `Update-MgBetaDirectorySetting` operation without encountering the `Insufficient privileges` error.

I hope this helps! If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@VortexGif 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
