### ISSUE TITLE
Correct Reply URL for EU customers

### ISSUE THREAD

**Issue by fdicarlo** [MicrosoftDocs/entra-docs#710]
[Enter feedback here]
For European customers, **Reply URL** is different, it is not `https://app.chargebee.com/saml/<domainname>/acs` but `https://app.eu.chargebee.com/saml/<domainname>/acs` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59709a0c-9564-bed7-0086-1ecc959d1f4e
* Version Independent ID: 56c9e7cc-6b2a-8f1a-8263-e181bafb9cf2
* Content: [Tutorial: Microsoft Entra SSO integration with Chargebee - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/chargebee-tutorial)
* Content Source: [docs/identity/saas-apps/chargebee-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/chargebee-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by SaibabaBalapur-MSFT** [comment]
@fdicarlo You’re absolutely right. For European customers, the Reply URL for SAML configuration in Chargebee should indeed be https://app.eu.chargebee.com/saml/<domainname>/acs. This is to ensure that the service complies with European data protection regulations and provides optimized performance for users in that region.

When setting up SAML for Chargebee, it’s crucial to use the correct Reply URL that corresponds to your geographical location. If you need more detailed guidance on configuring SAML for Chargebee or have any other inquiries, please let me know, and I’d be happy to assist further!

**Comment by fdicarlo** [comment]
> @fdicarlo You’re absolutely right. For European customers, the Reply URL for SAML configuration in Chargebee should indeed be https://app.eu.chargebee.com/saml//acs. This is to ensure that the service complies with European data protection regulations and provides optimized performance for users in that region.
> 
> When setting up SAML for Chargebee, it’s crucial to use the correct Reply URL that corresponds to your geographical location. If you need more detailed guidance on configuring SAML for Chargebee or have any other inquiries, please let me know, and I’d be happy to assist further!

Hi @SaibabaBalapur-MSFT I just opened the issue in GitHub to have an updated documentation, luckily during a troubleshooting we realized this and everything works fine :)
