### ISSUE TITLE
Add Microsoft Identity Manager to the comparison table on Microsoft Entra Cloud Sync Page

### ISSUE THREAD

**Issue by AndrewCi** [MicrosoftDocs/entra-docs#711]
Microsoft provides 3 methods for inter-directory provisioning as explained in the link below:

https://learn.microsoft.com/en-us/entra/identity/hybrid/what-is-inter-directory-provisioning

It would be beneficial to expand the comparison table on Microsoft Entra Cloud Sync page to include Microsoft Identity Manager in addition to Microsoft Entra Connect to see the full comparison across the three options.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4488ab5f-81f4-eaf2-fe3d-e1de9f5b17af
* Version Independent ID: c089c188-c02c-6e64-b59b-bcbc6b79e030
* Content: [What is Microsoft Entra Cloud Sync? - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/what-is-cloud-sync)
* Content Source: [docs/identity/hybrid/cloud-sync/what-is-cloud-sync.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/what-is-cloud-sync.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@AndrewCi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@AndrewCi 
Thank you for bringing this to our attention.
I've delegated this to content author @billmath, who will review it and offer their insightful opinions.
