### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by FilipCop** [MicrosoftDocs/entra-docs#714]
The table under paragraph "Password validation outcome events" seems to contain an error.
On the line "Audit-only Pass (would have failed due to user name)" the first eventIDs are 10016 & 10017 but they should be 10024 & 10025.
10016 & 10017 apply in case of "Fail", not "Audit-only Pass".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23a4bc15-af79-3d85-105b-745c3e92511e
* Version Independent ID: 5e9a9849-9b97-b494-960b-a9601d1d9cfb
* Content: [Monitor on-premises Microsoft Entra Password Protection - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-ban-bad-on-premises-monitor)
* Content Source: [docs/identity/authentication/howto-password-ban-bad-on-premises-monitor.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-password-ban-bad-on-premises-monitor.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@FilipCop 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@FilipCop 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
