### ISSUE TITLE
Can't use EnrollmentProfile in CA "Filter for devices" section

### ISSUE THREAD

**Issue by dumitrurazvancosmin** [MicrosoftDocs/entra-docs#715]
Trying to create a simple CA Policy that:
- Applies to All Users
- Applies to All Cloud APPS
- Grant - Requires MFA
- Conditions - Filter for devices ->   device.enrollmentProfileName -eq "Profile 1" -or device.enrollmentProfileName -eq "Profile 2"   
- Session Control - Require re-auth every 1h

When trying to connect with an android device that has been enrolled with Profile 1 for example, the CA policy never applies. MFA is not required every 1h, in fact on the What If tool I can see that the problem is the filter is not matching.

It seems that EnrollmentProfileName filter doesn't seem to work on the CA Policy filters. The setting in available in the CA Policy settings as an option, but is not present on the Technical Article that list the available supported filters: https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-condition-filters-for-devices 

My question is: Why is this an option in the CA policies if it doesn't work? Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fcc79933-58e1-66d1-81ae-f43802d41223
* Version Independent ID: 5be1fefc-356e-d1eb-ab97-8cbe5654ff43
* Content: [Filter for devices as a condition in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-condition-filters-for-devices)
* Content Source: [docs/identity/conditional-access/concept-condition-filters-for-devices.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-condition-filters-for-devices.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@dumitrurazvancosmin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dumitrurazvancosmin 
For an issue like this, I'd recommend you create a [support ticket](https://azure.microsoft.com/support/create-ticket/) since the support team will be able to respond much more quickly and have a conversation with you to figure out what could be going on.

**Comment by dumitrurazvancosmin** [comment]
@SaibabaBalapur-MSFT 
I worked for Microsoft directly, as a Premier Support Engineer for 5.5 years. Contacting support has no added value in this scenario. The things are clear, you have an option in GUI that doesn't work, and that doesn't appear in the list of available/supported options in the technical documentation

**Comment by SaibabaBalapur-MSFT** [comment]
@dumitrurazvancosmin 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by MicrosoftGuyJFlo** [comment]
I agree with @SaibabaBalapur-MSFT this should be looked at by our support teams. They can troubleshoot this with you further.

#please-close
