### ISSUE TITLE
Incorrect event viewer path 

### ISSUE THREAD

**Issue by ben-oxley-fnc** [MicrosoftDocs/entra-docs#718]
The guidance says:

_RDP sign-in via Microsoft Entra accounts is captured in Event Viewer under the Applications and Services Logs\Windows\AAD\Operational event logs._

When I look in event viewer, I find the events in:

Applications and Services Logs\ **Microsoft** \Windows\AAD\Operational event logs in Windows Server 2022 Datacentre 21H2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Sign in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows#troubleshoot-sign-in-problems)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@ben-oxley-fnc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@ben-oxley-fnc 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

**Comment by Naveenommi-MSFT** [comment]
@ben-oxley-fnc 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
