### ISSUE TITLE
Missing error code

### ISSUE THREAD

**Issue by tvjust** [MicrosoftDocs/entra-docs#72]
When a user reports fraud during an azure sign in for example to portal.azure.com, an error code shows up on their page which looks like this 
Error Code: 500121
Request Id: 07hf610f-249-46sd-a1d7-3ccbdc5d6b00
Correlation Id: fde7a069-5cdf-4439-83a4-0899695ea5d2
Timestamp: 2023-12-01T01:01:11Z

This error code **500121** is not listed on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a826ee6f-f457-7109-9f77-67c57977d4e7
* Version Independent ID: 11766f27-492e-a579-dced-8a42528cbb47
* Content: [Microsoft Entra authentication & authorization error codes - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes)
* Content Source: [docs/identity-platform/reference-error-codes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-error-codes.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by SaibabaBalapur-MSFT** [comment]
@tvjust 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi@tvjust 
For your information The Error Code: 500121 indicates Authentication failed during strong authentication request. The user didn't complete the MFA prompt or they may have decided not to authenticate or timed out while doing other work, or has an issue with their authentication setup.

if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by ManoharLakkoju-MSFT** [comment]
@tvjust 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
