### ISSUE TITLE
Gov endpoints incorrect for AVD hosts

### ISSUE THREAD

**Issue by skorb-ucb** [MicrosoftDocs/entra-docs#720]
I'm reading it correctly, VMs in Azure gov should be hitting https://enterpriseregistration.microsoftonline.us/ for device registration.  However, when we deploy new AVD hosts and select the Entra ID domain join option, they are definitely reaching out to https://enterpriseregistration.windows.net/, which it seems should only be for commercial regions.

Not sure if this is a bug or if AVD hosts behave differently, but it would be nice if the correct endpoints were documented somewhere so future customers won't have to go digging through their firewall logs like we did.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Sign in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@skorb-ucb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@skorb-ucb 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
AVD can behave differently in some instances.

AVD Maintains a couple articles that cover their requirements:

https://learn.microsoft.com/azure/virtual-desktop/network-connectivity
https://learn.microsoft.com/azure/virtual-desktop/required-fqdn-endpoint?tabs=azure-for-us-government

#please-close
