### ISSUE TITLE
Missing Microsoft Teams EEA in csv file

### ISSUE THREAD

**Issue by kurgans0** [MicrosoftDocs/entra-docs#726]
[Enter feedback here]
There is a license missing in the file on the note below.
SKU name: Microsoft_Teams_EEA_New
SKU id: 7e74bd05-2c47-404e-829a-ba95c66fe8e5
with its service plans:
f0ff6ac6-297d-49cd-be34-6dfef97f0c28
199a5c09-e0ca-4e37-8f7c-b05d533e1ea2
3efbd4ed-8958-4824-8389-1321f8730af8
dcf9d2f4-772e-4434-b757-77a453cfbc02
afc06cb0-b4f4-4473-8286-d644f70d8faf
4495894f-534f-41ca-9d3b-0ebf1220a423
e95bec33-7c88-4a70-8e19-b10bd9d0c014
882e1d05-acd1-4ccb-8708-6ee03664b117
57ff2da0-773e-42df-b2af-ffb7a2317929
94065c59-bc8e-4e8b-89e5-5138d471eaff
159f4cd6-e380-449f-a816-af1a9ef76344
4a82b400-a79f-41a4-b4e2-e94f5787b113

Note: "This information last updated on March 19th, 2024.
You can also download a CSV version of this table [here](https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by TPavanBalaji** [comment]
@kurgans0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@kurgans0 
I'm going to assign this to the document author so they can take a look at it accordingly.

@Nicholak-MS 
Can you please check and add your comments on this doc update request as applicable.

**Comment by Nicholak-MS** [comment]
Hi @kurgans0 thanks for sharing the feedback. This SKU and Service Plan details has been published to the online table and the downloadable CSV. 

Thanks
Nick

#please-close
