### ISSUE TITLE
I need your advice

### ISSUE THREAD

**Issue by AttilaAts** [MicrosoftDocs/entra-docs#73]
Hello,

I've read a number of articles, including this, but not yet found the answer to my question. There is an IIS-based application that is run as some Windows services. It can use an Azure SQL database but currently as a computer account (DOMAIN_NAME\HOSTNAME$). We'd like it to be able to run as an Entra ID account and connect to the Azure SQL database as such. Is it possible to create a managed service account or managed identity in Microsoft Entra ID a Windows service can run as on a computer that is member to a Windows AD domain that is linked to Microsoft Entra ID? I know, it can run as a managed service account (domain\username$), no problem here, but what about running it as a Microsoft Entra ID account, is it possible?

Regards,

Attila

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72861cc1-7081-cf6e-b7f9-e700a16faa9a
* Version Independent ID: c870872d-0559-6b77-280f-f478e8c84776
* Content: [Managed identities for Azure resources - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview)
* Content Source: [docs/identity/managed-identities-azure-resources/overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/overview.md)
* Service: **active-directory**
* Sub-service: **msi**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by SaibabaBalapur-MSFT** [comment]
@AttilaAts 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@AttilaAts 
It is possible to use a managed identity to access Azure SQL Database from a Windows service running on a Windows VM. However, it is not possible to use a managed identity from a computer that is a member of a Windows AD domain that is linked to Microsoft Entra ID. Managed identities are only available for Azure resources, not for on-premises resources. 

In your case, you can use a managed service account to run the Windows service and connect to the Azure SQL database. Alternatively, you can use a service principal to authenticate to Azure SQL Database. 

To use a service principal, you need to create an Azure AD application and assign it the necessary permissions to access Azure SQL Database. You can then use the client ID and client secret of the Azure AD application to authenticate to Azure SQL Database. 

Here is a tutorial that walks you through the process of using a Windows VM system-assigned managed identity to access Azure SQL Database: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-sql. 

I hope this helps! Let me know if you have any further questions.

**Comment by AttilaAts** [comment]
Dear Saibaba,

Thank you for your response. The computer the application will run on is not an Azure VM, it is a physical computer or a local VM on the customer’s premises.

I’m sure you can help me with the below, too.
This article: Managed Service Accounts: Understanding, Implementing, Best Practices, and Troubleshooting | Microsoft Learn<https://learn.microsoft.com/en-us/archive/blogs/askds/managed-service-accounts-understanding-implementing-best-practices-and-troubleshooting> tells how to create a managed service account in AD and make a service run as this account by referencing it as DOMAINNAME\USERNAME$.
If our AD is integrated with Microsoft Entra ID, and the data are stored in an Azure SQL Database, and I want the application that is running on a physical computer to access those data, then may I do what is written in the article above, or do I have to create the gMSA in Entra ID? Or, as our AD and Entra ID are integrated and synchronized, does it not matter where I create the gMSA? If it exist in both or AD and Entra ID due to synchronization, may I reference it as DOMAINNAME\USERNAME$ when I configure a service to run as this account? I apologize for the ‘stupid’ questions but this subject is quite new to me.

Regards,

Attila

**Comment by SaibabaBalapur-MSFT** [comment]
@AttilaAts 
I'm going to assign this to the document author so they can take a look at it accordingly.

@barclayn 
Please review it.

**Comment by SaibabaBalapur-MSFT** [comment]
@AttilaAts 
I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
