### ISSUE TITLE
Conditional Access filters for devices mentioned instead of applications

### ISSUE THREAD

**Issue by dokessle** [MicrosoftDocs/entra-docs#730]
The site is about Conditional Access filters for applications but there is a note that talks about Conditional Access filters for devices which is wrong at this place.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea596b1a-7176-712b-453c-a5df7316db08
* Version Independent ID: cf645574-1664-5b67-c494-c4469e86413b
* Content: [Filter for applications in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-filter-for-applications)
* Content Source: [docs/identity/conditional-access/concept-filter-for-applications.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-filter-for-applications.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Naveenommi-MSFT** [comment]
Hi @dokessle 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

**Comment by dokessle** [comment]
[like]  Dominik Kessler reacted to your message:
________________________________

**Comment by Naveenommi-MSFT** [comment]
@dokessle 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
