### ISSUE TITLE
Request for correction of the explanation of the correctness or incorrectness of credentials in the detection of risks in Identity Protection

### ISSUE THREAD

**Issue by NatsukiNK** [MicrosoftDocs/entra-docs#733]
The following description differs from the actual behavior and should be clarified or corrected.

https://learn.microsoft.com/en-us/entra/id-protection/troubleshooting-identity-protection-faq#why-was-my-sign-in-blocked-but-id-protection-didnt-generate-a-risk-detection
***
Why was my sign-in blocked but ID Protection didn't generate a risk detection?
Sign-ins can be blocked for several reasons. It's important to note that ID Protection only generates risk detections when correct credentials are used in the authentication request. If a user provides incorrect credentials, it isn't flagged by ID Protection since there isn't of risk of credential compromise unless a bad actor uses the correct credentials. Some reasons a user can be blocked that don't generate an ID Protection detection include:

The IP can be blocked due to malicious activity from the IP address. The IP blocked message doesn't differentiate whether the credentials were correct or not. If the IP is blocked and correct credentials aren't used, it won't generate an ID Protection detection.
[Smart Lockout](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-password-smart-lockout) can block the account from signing-in after multiple failed attempts.
A Conditional Access policy can be enforced that uses conditions other than risk level to block an authentication request.
***

This Microsoft Learn says, the correct credentials must be required for Identity Protection to detect risks.
However, in reality, even in some verification environments, if the user account ID is correct, Identity Protection will detect the risk even if the password is incorrect (e.g. Anonymous IP address).  It does not match this description.
Also, I believe that when accessed from an anonymous IP address, only the risk is detected and not the access is blocked.
Therefore, if it is stated correctly, regardless of whether access is blocked by the IP address or not, my understanding is that if the IP address is at risk, whether the credentials are correct or not is ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 665863f8-00aa-155a-aa5d-9dc4254b60d4
* Version Independent ID: b898c3ed-651d-4fb0-814a-62a857082fd3
* Content: [FAQs for Microsoft Entra ID Protection - Microsoft Entra ID Protection](https://learn.microsoft.com/en-us/entra/id-protection/troubleshooting-identity-protection-faq#why-was-my-sign-in-blocked-but-id-protection-didnt-generate-a-risk-detection)
* Content Source: [docs/id-protection/troubleshooting-identity-protection-faq.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/troubleshooting-identity-protection-faq.yml)
* Service: **entra-id-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@NatsukiNK 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @NatsukiNK 
Although Identity Protection typically generates risk detections only when correct credentials are used, there are exceptions where risk detections can occur even with incorrect credentials. For instance, if a sign-in attempt originates from an anonymous IP address, Identity Protection may flag it as risky despite incorrect credentials. Similarly, sign-in attempts from known malicious IP addresses can trigger risk detections, irrespective of credential accuracy.

In terms of blocking access from anonymous IP addresses, Identity Protection doesn't directly block access in such cases. Instead, it raises a risk detection, which serves as a signal for further actions. These actions may include enforcing multi-factor authentication or implementing access controls via Conditional Access policies.

**Comment by Naveenommi-MSFT** [comment]
@NatsukiNK 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
