### ISSUE TITLE
Group Owner missing a right

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#735]
As a group owner, in a P2-enabled tenant, I can also enroll that group into PIM for groups. That right is missing from the list. There's also no control to prevent that right from being invoked by a group owner, and no method to reverse the enrollment action.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 510faed7-b79d-b8ec-f32f-e64d8773a30c
* Version Independent ID: 522e7e2e-ea93-5249-5e6f-5c984f1b6277
* Content: [Default user permissions - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/users-default-permissions)
* Content Source: [docs/fundamentals/users-default-permissions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/users-default-permissions.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dloder0 
I'm going to assign this to the document author so they can take a look at it accordingly.

@barclayn 
Can you please check and add your comments on this doc update request as applicable.

**Comment by barclayn** [comment]
@dloder0 thank you for pointing this out. We have created an internal work item to investigate and update the article. #please-close
