### ISSUE TITLE
Max latency time to see Entra logs

### ISSUE THREAD

**Issue by matteopasa** [MicrosoftDocs/entra-docs#738]
What is the guaranteed time for the availability of logs of Microsoft Entra?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d747163-9cfc-0816-68cf-371ebb584f44
* Version Independent ID: 2d747163-9cfc-0816-68cf-371ebb584f44
* Content: [Log latency for Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/reference-log-latency)
* Content Source: [docs/identity/monitoring-health/reference-log-latency.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/monitoring-health/reference-log-latency.md)
* Service: **entra-id**
* Sub-service: **monitoring-health**
* GitHub Login: @shlipsey3
* Microsoft Alias: **sarahlipsey**

**Comment by shlipsey3** [comment]
What do you mean by "guaranteed time"? Do you mean how long they're saved for? Or how long it takes for logs to update?

Either way - it varies by license and type of log. 

https://learn.microsoft.com/en-us/entra/identity/monitoring-health/reference-log-latency
https://learn.microsoft.com/en-us/entra/identity/monitoring-health/reference-reports-data-retention

**Comment by matteopasa** [comment]
@shlipsey3 thanks for the swift answer! What I mean is how much time after an Entra event happens, it's guaranteed that we will see it in the portal. For example if a user logs in, how much time after that log in we are sure we will be able to see/consume that log event

**Comment by shlipsey3** [comment]
Ahhh, that's tricky because we can't really "guarantee" anything. There are a lot of underlying processes that impact how long a long takes to appear. Because of these dependencies, it's difficult to come up with a number. Many logs and activities take longer than others.

But - we are trying to improve how we talk about latency because it's a common question. We've got a work item to take a closer look. Sorry I don't have a better answer!

**Comment by Naveenommi-MSFT** [comment]
@shlipsey3 
Thank you for your response.

@matteopasa 
If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@matteopasa 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
