### ISSUE TITLE
Zahidul Islam 

### ISSUE THREAD

**Issue by ZahidulbdEnterprise732** [MicrosoftDocs/entra-docs#739]
# zahidulislam372@yahoo.com**![IMG-20240429-WA0363.jpg](https://github.com/MicrosoftDocs/entra-docs/assets/161329600/9ef7c015-98ed-4442-b8c9-e68d3998fe4f)

- @zkat [](https://www.facebook.com/Zahidul.com1993- [ ] ?mibextid=ZbWKwL)**

**Comment by PesalaPavan** [comment]
@ZahidulbdEnterprise732 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by PesalaPavan** [comment]
@ZahidulbdEnterprise732 
We are going to close this thread but if there are any further questions, please tag me in your reply and we will be happy to continue the conversation.
