### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by icazemier** [MicrosoftDocs/entra-docs#74]
Hi team,

Shot in the dark maybe, but trying to reach help.

# Outdated docs
Here: https://learn.microsoft.com/en-us/entra/external-id/microsoft-account you guys show outdated documentation

It shows B2C images, while you advertise with External ID:
![image](https://github.com/MicrosoftDocs/entra-docs/assets/64091093/8b8e6b43-382a-4b13-aae3-0f373f2ad9b4)

# Invite external federated Microsoft account with MS Entra Extranal Id

When I try to invite a federated Microsoft account (private ...@outlook.com account) I can accept the invitation (got an email), awesome.
When I finish the user flow (accept permissions and filled in personal stuff), I land at : https://account.activedirectory.windowsazure.com/ ??

![image](https://github.com/MicrosoftDocs/entra-docs/assets/64091093/c9437575-16d0-421b-8ca3-482bec414743)

How to solve this, how to configure?
But In the users section of entra id, the user has been marked as "Accepted" invitation.

Then I try to login to our own application with the invited user email address.
But I can NOT login afterwards with the same email address.
![Screenshot 2023-12-14 at 16 03 28](https://github.com/MicrosoftDocs/entra-docs/assets/64091093/c20c4b27-ec52-4a55-b481-91c76c2e75da)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8c91376-cbbb-ec1b-4318-bc870622e9e1
* Version Independent ID: 2354aa2d-0271-f7c8-6639-06d65250effe
* Content: [Add Microsoft account (MSA) as an identity provider - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/microsoft-account)
* Content Source: [docs/external-id/microsoft-account.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/microsoft-account.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
Hi @icazemier 

I'm sorry to hear that you are experiencing issues with the Microsoft External Id feature.

Regarding the outdated documentation, thank you for bringing this to our attention. I will make sure to pass this feedback along to the appropriate team to update the documentation.

Regarding the issue with the user flow, it is possible that there is a misconfiguration in your Azure AD tenant that is causing the issue. I recommend checking the following:

Make sure that the user is added to the correct Azure AD tenant and that the tenant is configured to allow external users to sign in.
Check the Azure AD sign-in logs to see if there are any errors or issues with the user's sign-in attempts.
Make sure that your application is configured to allow external users to sign in and that it is properly configured to use the Microsoft External Id feature.
If you continue to experience issues, I'd recommend posting your question in https://azure.microsoft.com/en-us/support/community/. They will be able to help you troubleshoot the issue and provide guidance on how to resolve it.
