### ISSUE TITLE
Can We Make Some Other Portions Stand Out More?

### ISSUE THREAD

**Issue by RDukes425** [MicrosoftDocs/entra-docs#740]
As a support engineer for Government customers, we've been noticing a large volume of cases for B2B Cross Cloud Collab issues. In reviewing the documentation, we were hoping that we could suggest some portion of the document that can be bolded, highlighted or encased in a pink bubble to help stand out more when customer's are consuming the document. The length of the document could also be a slight factor in possibly overlooking some of the important pre-requisites for setting this up. 

For example: 
If you want to set up B2B collaboration with a partner organization in an external Microsoft Azure cloud, follow the steps in [Configure Microsoft cloud settings](https://learn.microsoft.com/en-us/entra/external-id/cross-cloud-settings). An admin in the partner organization needs to do the same for your tenant.

Another area is: 
![image](https://github.com/MicrosoftDocs/entra-docs/assets/66752282/2631f676-bf0e-42be-952b-760ff3fd2b09)

Reference Document: https://learn.microsoft.com/en-us/entra/external-id/cross-cloud-settings

We're hoping to improve the way our customers consume/digest documentation for our continued commitment to Customer Education. 

Thank you in Advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c150664-0126-912e-699b-f97c64ee6b4d
* Version Independent ID: 3a89e05c-e28c-2097-c76d-52d2b9240b2a
* Content: [Configure B2B collaboration cross-tenant access - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/cross-tenant-access-settings-b2b-collaboration)
* Content Source: [docs/external-id/cross-tenant-access-settings-b2b-collaboration.yml](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/cross-tenant-access-settings-b2b-collaboration.yml)
* Service: **entra-external-id**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by PesalaPavan** [comment]
@RDukes425 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msmimart** [comment]
@RDukes425 thanks so much for your suggestions. Updates are in the works, which will publish shortly. Thanks again!
