### ISSUE TITLE
Update Required URLs table

### ISSUE THREAD

**Issue by scottmassari** [MicrosoftDocs/entra-docs#741]
The auth cdn aadcdn.msauth.net appears required for a successful install of EntraID Connect Sync and should be added to the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21aea3e5-a060-ad61-549d-520a84877a14
* Version Independent ID: 289b99c9-87e0-6ff3-b102-fb44866a4225
* Content: [Microsoft Entra Connect: Troubleshoot Microsoft Entra connectivity issues - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/tshoot-connect-connectivity#connectivity-issues-in-the-installation-wizard)
* Content Source: [docs/identity/hybrid/connect/tshoot-connect-connectivity.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/tshoot-connect-connectivity.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@scottmassari 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by billmath** [comment]
This will need to be signed off by engineering.  Taking this in house to investigate.  I will updated this issue once I know more.  At this time we can close it.

#please-cllose

**Comment by billmath** [comment]
#please-close
