### ISSUE TITLE
Github 

### ISSUE THREAD

**Issue by abirfo** [MicrosoftDocs/entra-docs#742]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b27a01-622e-d980-83f2-1ed27060613b
* Version Independent ID: e6472e15-10d7-bd4a-da02-558f2774dbaf
* Content: [Passwordless security key sign-in to on-premises resources - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises#view-and-verify-the-azure-ad-kerberos-server)
* Content Source: [docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-passwordless-security-key-on-premises.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@abirfo 
It would be great if you could add more about your query to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by PesalaPavan** [comment]
@abirfo 
We are going to close this thread but if there are any further questions, please tag me in your reply and we will be happy to continue the conversation.
