### ISSUE TITLE
Link to documentation for CloudAP and WAM plugin framework?

### ISSUE THREAD

**Issue by petrsnm** [MicrosoftDocs/entra-docs#747]
Under Key terminology and components:

"Cloud Authentication Provider (CloudAP): CloudAP is the modern authentication provider for Windows sign in, that verifies users logging to a Windows 10 or newer device. CloudAP provides a plugin framework that identity providers can build on to enable authentication to Windows using that identity provider's credentials."

"Web Account Manager (WAM): WAM is the default token broker on Windows 10 or newer devices. WAM also provides a plugin framework that identity providers can build on and enable SSO to their applications relying on that identity provider."

Is there a link you could include that documents the CloudAP and WAM  "plugin framework that identity providers can build on"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d3bcf99-60c3-876c-c421-3351e507a81b
* Version Independent ID: c906978e-acf2-462c-d7ff-20221872a793
* Content: [Primary Refresh Token (PRT) and Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/concept-primary-refresh-token#key-terminology-and-components)
* Content Source: [docs/identity/devices/concept-primary-refresh-token.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/concept-primary-refresh-token.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@petrsnm 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@petrsnm 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by RevenantBob** [comment]
I am looking for the same documentation.

**Comment by MicrosoftGuyJFlo** [comment]
#label:"awaiting-product-team-response"

**Comment by MicrosoftGuyJFlo** [comment]
We have some doc updates planned for the future... 

In the meantime there is some detail covered in the following content:

https://learn.microsoft.com/entra/identity-platform/scenario-desktop-acquire-token-wam
https://learn.microsoft.com/windows/security/
https://learn.microsoft.com/windows/security/identity-protection/web-sign-in/?tabs=intune

Hope that helps.

#please-close
