### ISSUE TITLE
A typo: 'four' should be 'for'

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/entra-docs#753]
Hello,

please check this string: "If you have specified accidental delete prevention **four** group provisioning to Microsoft Entra ID, be aware this only prevents the group from being deleted."

I guess '**four**' should be '**for**' in the sentence.

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1cc4a0a1-a3b2-20b5-84b7-5432be86045e
* Version Independent ID: 71ff9b16-a139-5c35-d280-16515b82496d
* Content: [Microsoft Entra Cloud Sync accidental deletes - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-accidental-deletes)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-accidental-deletes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-accidental-deletes.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@QueryCoordinator 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@QueryCoordinator 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
