### ISSUE TITLE
Does not work.  Passkey preview is not available

### ISSUE THREAD

**Issue by markburgessstl** [MicrosoftDocs/entra-docs#756]
[Enter feedback here]
Does not work. Passkey preview is not available

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1d3d10a-690c-6744-53bf-3f1e75c79908
* Version Independent ID: e1d3d10a-690c-6744-53bf-3f1e75c79908
* Content: [How to enable passkeys in Microsoft Authenticator for Microsoft Entra ID (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-enable-authenticator-passkey)
* Content Source: [docs/identity/authentication/how-to-enable-authenticator-passkey.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-enable-authenticator-passkey.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@markburgessstl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @markburgessstl 
The Passkey feature is currently in preview and may not be available to everyone. If you are not able to see the Passkey feature, it may be because your administrator has not enabled it yet. You can try contacting your administrator to see if they can enable the feature for you. If you have any other questions, please let me know.

**Comment by ManoharLakkoju-MSFT** [comment]
@markburgessstl 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
