### ISSUE TITLE
Wrong object and wrong cmdline argument

### ISSUE THREAD

**Issue by essentialexch** [MicrosoftDocs/entra-docs#757]
The sample creates the wrong object type for the $messageInfo object and then sets the SendInvitationMessage to $true as if it were a boolean parameter - which it isn't, it's a switch. Both of these cause the sample to fail.

It should look like this instead:

```
$invitations = import-csv c:\bulkinvite\invitations.csv

$messageInfo = New-Object Microsoft.Graph.PowerShell.Models.MicrosoftGraphInvitedUserMessageInfo

$messageInfo.customizedMessageBody = "Hello. You are invited to the Contoso organization."

foreach ($email in $invitations) {
	New-MgInvitation -InvitedUserEmailAddress $email.InvitedUserEmailAddress `
		-InvitedUserDisplayName $email.Name `
		-InviteRedirectUrl https://myapplications.microsoft.com/?tenantid=abcdeff-acbd-abcd-abcd-dcbadcbadcba `
		-InvitedUserMessageInfo $messageInfo `
		-SendInvitationMessage
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8984951b-7ece-4964-ed6e-5266174d2ffb
* Version Independent ID: 163b743d-fd7f-9c50-f01c-79a4521c5236
* Content: [Tutorial for bulk inviting B2B collaboration users - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/bulk-invite-powershell)
* Content Source: [docs/external-id/bulk-invite-powershell.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/bulk-invite-powershell.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by essentialexch** [comment]
Note that this bug also applies to https://learn.microsoft.com/en-us/entra/external-id/code-samples?tabs=http

**Comment by PesalaPavan** [comment]
@essentialexch 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@essentialexch 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by csmulligan** [comment]
Hi @essentialexch thank you so much for pointing this out. I've moved this issue to an internal work item for tracking. I'll go ahead and close this issue, but changes to the article are in the works. Thanks again for helping us improve the documentation!
#please-close
