### ISSUE TITLE
Add Steps for Checking and Enable TLS 1.2 and .net 4.8 in the document

### ISSUE THREAD

**Issue by pdtech4** [MicrosoftDocs/entra-docs#758]
[Enter feedback here]

This is Patrick Douglas (Alias pdouglas) SE from the Identity team. Tyson Smith is my TA and Lisa Fewell is my manager.

ASK:
Multiple SSPR cases I've had recently were resolved with enabling TLS 1.2 or .net 4.8 or both and these steps are not in this doc. Would be very nice to add those as TS steps into this doc. I had a case yesterday mention would have been very helpful to have at least TLS 1.2 check and enable doc in this doc as a step. This could save customers time and increase CSAT scores

First priority - Powershell Script to check TLS 1.2 on AAD connect server.  _ Run in Admin Mode
[Azure AD Connect: TLS 1.2 enforcement for Azure Active Directory Connect - Microsoft Entra | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-tls-enforcement#powershell-script-to-check-tls-12)

2-Check .net version if less than 4.8 upgrade to 4.8 (try without a reboot first)
[Download .NET Framework 4.8 | Free official downloads (microsoft.com)](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48)

Patrick Douglas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6c7b290-3f3e-70c9-7524-80d7364dd763
* Version Independent ID: d12b324f-57b2-9fd8-a433-b25644424171
* Content: [Troubleshoot self-service password reset writeback - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/troubleshoot-sspr-writeback)
* Content Source: [docs/identity/authentication/troubleshoot-sspr-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/troubleshoot-sspr-writeback.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Naveenommi-MSFT** [comment]
@pdtech4 
Thank you for bringing this to our attention.
I've delegated this to content author @Justinha, who will review it and offer their insightful opinions.

**Comment by pdtech4** [comment]
Awesome thanks!

**Comment by Justinha** [comment]
@pdtech4 as we discussed today, we will follow up offline. #please-close
