### ISSUE TITLE
clarify the name of MPN ID/Partner ID/Partner One ID

### ISSUE THREAD

**Issue by morgangrobin** [MicrosoftDocs/entra-docs#759]
Is MPN ID the same as Partner ID? Is Partner ID the same as Partner One ID? Where do you go to find it? There is literally *no* documentation explaining this. I'd expect to find it on *this* page at the _very_ least. 

What if you don't see Partner ID in the Legal Info section of Partner Center? What are the troubleshooting steps? 

this one guy's two comments are the best source of information on this; that's embarrassing. 
https://learn.microsoft.com/en-us/answers/questions/1298990/where-do-i-find-my-microsoft-partner-network-ident
https://learn.microsoft.com/en-us/answers/questions/1118699/how-to-get-mpn-id-for-multi-tenent-app

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df11cb03-70da-7df3-4941-3c2f8ea022f8
* Version Independent ID: 96cd8eec-ed94-05bf-1288-86b6ef3db105
* Content: [Troubleshoot publisher verification - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/troubleshoot-publisher-verification)
* Content Source: [docs/identity-platform/troubleshoot-publisher-verification.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/troubleshoot-publisher-verification.md)
* Service: **identity-platform**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by PesalaPavan** [comment]
@morgangrobin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@morgangrobin 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by rwike77** [comment]
@morgangrobin  Hi.  Looks like the article has gotten a little out of date, we'll update it soon.

MPN ID was renamed to Partner ID, which is the PartnerGlobal identifier in the identifiers tab.  I'll have to look into whether Partner One ID is the same as Partner ID.  

Partner ID should always be linked to in the Legal Info section as long as you've registered with the Microsoft AI Cloud Partner Program.  Is that not the case?

I'm working with engineering to get this page updated.

**Comment by rwike77** [comment]
We are in the process of transferring to a new unified user feedback system, so I need to close this issue even though it's not resolved. I've opened an internal work item for the month of June so I won't lose it.

Thanks for your patience. #please-close
