### ISSUE TITLE
Please add Support for group writeback on the chart

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/entra-docs#76]
We recently added support for group writeback with the cloud sync agent :

https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory

This is not reflected in the chart on this page and needs to be added :

![image](https://github.com/MicrosoftDocs/entra-docs/assets/56908729/322eb50e-18aa-4472-99ca-f8455d53193b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4488ab5f-81f4-eaf2-fe3d-e1de9f5b17af
* Version Independent ID: c089c188-c02c-6e64-b59b-bcbc6b79e030
* Content: [What is Microsoft Entra Cloud Sync? - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/what-is-cloud-sync)
* Content Source: [docs/identity/hybrid/cloud-sync/what-is-cloud-sync.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/what-is-cloud-sync.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@tomdan-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@tomdan-MSFT 
Thanks for reporting this! We have created a PR for this issue once the author will review and approve the changes should go live soon.

**Comment by tomdan-MSFT** [comment]
What is the status?  It's been over a month and the web page is still not updated or accurate

**Comment by ManoharLakkoju-MSFT** [comment]
@tomdan-MSFT  
Thanks again this!. We have created a PR The update will go live in less than 24 hours.
