### ISSUE TITLE
Invalid GUIDs in CSV file

### ISSUE THREAD

**Issue by itsamaik** [MicrosoftDocs/entra-docs#761]
The [linked CSV](https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv) to [this page](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference) has been updated with invalid GUIDs.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/1707094/a19bd597-880c-4079-ba59-71acf7a8bd91)

I assume the GUID should be the same for the same product. 

Would it be possibe to do some validation before publishing, for example on data type or some formatting constraints like same GUID for same product?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by Nicholak-MS** [comment]
Hi Maik, 

Thanks for bringing this to our attention and apologies for the incorrect GUID's. These have been corrected and the latest version has been published. 

Thanks.

**Comment by Nicholak-MS** [comment]
#please-close
