### ISSUE TITLE
Add group to administrative group not working

### ISSUE THREAD

**Issue by elmidwill** [MicrosoftDocs/entra-docs#765]
The Invoke-MgGraphRequest cmdlet as is for adding groups to Administrative Groups does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43480033-c11c-c89d-bbaf-7d9790000782
* Version Independent ID: 4ff490a6-474c-1305-29b7-d728de56d7b2
* Content: [Add users, groups, or devices to an administrative unit - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/admin-units-members-add)
* Content Source: [docs/identity/role-based-access-control/admin-units-members-add.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/admin-units-members-add.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@elmidwill 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@elmidwill 
Thank you for bringing this to our attention.
I've delegated this to content author @rolyon, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@rolyon 
Please review it.

**Comment by rolyon** [comment]
Hi @elmidwill
Thanks for taking the time to provide feedback. We've updated the PowerShell commands for this doc. The updates will appear when docs are published tomorrow. Let us know if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
