### ISSUE TITLE
Add potential migration path from Azure AD B2C to Azure Entra External Id

### ISSUE THREAD

**Issue by stefan-schweiger** [MicrosoftDocs/entra-docs#768]
We are very interested in using Azure Entra External Id since our experience with AD B2C has been... bumpy. Any guides on how existing AD B2C tenants can be migrated to Entra External Id without making all users sign up again would be very appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7c61515-5609-a07c-f0b6-840a86851e73
* Version Independent ID: 4b443a57-720b-f4c9-7fbe-eee201997831
* Content: [Overview - External ID in external tenants - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam#about-azure-ad-b2c)
* Content Source: [docs/external-id/customers/overview-customers-ciam.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/overview-customers-ciam.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by AjayBathini-MSFT** [comment]
@stefan-schweiger 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@msmimart
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@stefan-schweiger 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by msmimart** [comment]
Hello @stefan-schweiger, thanks for reaching out; content for this scenario is in the works and will be released as soon as possible. I'll close this issue for now, but please stay tuned. Thanks again! #please-close
