### ISSUE TITLE
Missing/Incomplete code samples 

### ISSUE THREAD

**Issue by Dickson-Mwendia** [MicrosoftDocs/entra-docs#770]
As per https://github.com/MicrosoftDocs/azure-docs/issues/115494

The .NET code samples on this page refer to IDownstreamApi which isn't mentioned anywhere else in the documentation, nor are there any links to a sample git repository.

The documentation seems to imply that IDownStreamApi is a strongly typed http client, but doesn't specify if this is the only supported method (Can this be done with named clients?).

An example of a daemon API that calls another API might also be useful, rather than a console app that doesn't show the recommended approach for DI when using TokenAcquirerFactory.

Would a developer need to inject a TokenAcquirerFactory into a TypedHttpClient for example, or would it need injecting into a class that has a dependency on IDownStreamApi?

There's also no mention of the dependency on the [Microsoft.Identity.Web.DownstreamApi' package used in the code samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c18f989-2447-a35c-3870-e8de9d0da2a3
* Version Independent ID: 029e13c0-ff45-9321-3dfc-c9978b7fa95c
* Content: [How to call a downstream web API from a daemon app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-daemon-call-api?tabs=idweb)
* Content Source: [docs/identity-platform/scenario-daemon-call-api.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-daemon-call-api.md)
* Service: **identity-platform**
* GitHub Login: @Dickson-Mwendia
* Microsoft Alias: **dmwendia**

**Comment by AjayBathini-MSFT** [comment]
@Dickson-Mwendia 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@Dickson-Mwendia 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by cilwerner** [comment]
We are in the process of transferring to a new unified user feedback system. This issue is being triaged and added to the backlog where it will be addressed in an upcoming sprint.

#please-close
