### ISSUE TITLE
Include removing then re-adding the keychain group in troubleshooting section

### ISSUE THREAD

**Issue by Dickson-Mwendia** [MicrosoftDocs/entra-docs#771]
As per https://github.com/MicrosoftDocs/azure-docs/issues/115089

Update the "troubleshooting-keychain-access" section ...
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations#troubleshooting-keychain-access

To include removing then re-adding the keychain group...

private const string TeamIdKey = "DotNetTeamIDHint";
var queryRecord = new SecRecord(SecKind.GenericPassword)
{
Service = "",
Account = TeamIdKey,
Accessible = SecAccessible.Always
};

SecRecord match = SecKeyChain.QueryAsRecord(queryRecord, out SecStatusCode resultCode);

if (resultCode == SecStatusCode.ItemNotFound)
{
resultCode = SecKeyChain.Add(queryRecord);
if (resultCode == SecStatusCode.DuplicateItem)
{
resultCode = SecKeyChain.Remove(queryRecord);
resultCode = SecKeyChain.Add(queryRecord);
}
match = SecKeyChain.QueryAsRecord(queryRecord, out resultCode);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1612902-5577-0e73-64eb-0aaab018ad94
* Version Independent ID: 8e2638e5-b810-f9dc-2492-c0277d44acfd
* Content: [Xamarin iOS considerations (MSAL.NET) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/msal-net-xamarin-ios-considerations)
* Content Source: [docs/identity-platform/msal-net-xamarin-ios-considerations.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/msal-net-xamarin-ios-considerations.md)
* Service: **identity-platform**
* GitHub Login: @Dickson-Mwendia
* Microsoft Alias: **dmwendia**

**Comment by AjayBathini-MSFT** [comment]
@Dickson-Mwendia 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@Dickson-Mwendia 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by Dickson-Mwendia** [comment]
Closing this as we're tracking it internally.
