### ISSUE TITLE
Please correct the procedure of configuring SSO on BP side - it's documented, and support rarely need to help our users

### ISSUE THREAD

**Issue by sergem155** [MicrosoftDocs/entra-docs#773]
How to configure Azure SSO in BP:

https://help.brightpattern.com/latest:Tutorials-for-admins/Integrations/MicrosoftAzureAD#Configuration_in_Bright_Pattern

Our support rarely needs to help our customers with SSO configuration, most just follow the guide linked above

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eaeafdb8-f0f9-b6de-009c-bf98df1f010f
* Version Independent ID: 455bb4e4-42de-62d1-63b2-1ac228ba5956
* Content: [Tutorial: Microsoft Entra single sign-on (SSO) integration with Bright Pattern Omnichannel Contact Center - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/bright-pattern-omnichannel-contact-center-tutorial)
* Content Source: [docs/identity/saas-apps/bright-pattern-omnichannel-contact-center-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/bright-pattern-omnichannel-contact-center-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by TPavanBalaji** [comment]
@sergem155 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-hgampala** [comment]
@sergem155, we're updating tutorial according to the support article content, you can expect the changes within 3-4 working days.
#please-close
