### ISSUE TITLE
HybridSynchronizationActiveDirectoryCannotFindAttribute

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#774]
Another troubleshooting item I recently discovered with the PG that would be good to document.

Error code
HybridSynchronizationActiveDirectoryCannotFindAttribute

Error Message
This attribute name was not found in the Active Directory schema: attribute

Solution
If the attribute was recently added to Active Directory, restart the provisioning agent, as it caches the schema at startup time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaac29de-7f44-3c89-6710-a60850950247
* Version Independent ID: b8fc05c3-9734-3813-5e08-d38fa96d7e4a
* Content: [Troubleshoot user update issues with HR provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/hr-user-update-issues)
* Content Source: [docs/identity/app-provisioning/hr-user-update-issues.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/hr-user-update-issues.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @jenniferf-skc
* Microsoft Alias: **jfields**

**Comment by TPavanBalaji** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@dloder0 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by jenniferf-skc** [comment]
Closing. Moved to ADO BUG 265998 - https://dev.azure.com/msft-skilling/Content/_queries/edit/265998/?queryId=5fb4ec3c-f9d3-45e4-9ae8-3faad2fad915

**Comment by jenniferf-skc** [comment]
#please-close
