### ISSUE TITLE
proxy with SSO for an application deployed on multiple servers

### ISSUE THREAD

**Issue by Bob-HL** [MicrosoftDocs/entra-docs#775]
Can you please provide the instructions to confiture a proxy with SSO for an application deployed on multiple servers? In my case, we have internal application behind F5 (load balancer) without APM module.

A proxy can only have one SPN, an SPN can only pointing to a computer - how will it work with multiple servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 975ec66c-8a50-6933-cfe4-0b16697e6450
* Version Independent ID: 975ec66c-8a50-6933-cfe4-0b16697e6450
* Content: [Kerberos-based single sign-on (SSO) in Microsoft Entra ID with application proxy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-proxy/how-to-configure-sso-with-kcd)
* Content Source: [docs/identity/app-proxy/how-to-configure-sso-with-kcd.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-proxy/how-to-configure-sso-with-kcd.md)
* Service: **entra-id**
* Sub-service: **app-proxy**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by TPavanBalaji** [comment]
@Bob-HL 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @Bob-HL 
To configure a proxy with SSO for an application deployed on multiple servers behind an F5 load balancer without APM module, you can use Kerberos Constrained Delegation (KCD) with Azure Active Directory (Azure AD) Application Proxy. 

When you use KCD, the Application Proxy connector impersonates the user to get a Kerberos token to the application. The Kerberos token is then sent to the application, which validates it and grants access to the user. 

To configure KCD with Azure AD Application Proxy, you need to perform the following steps:

1. Configure the application to use Integrated Windows Authentication (IWA).
2. Configure KCD on the Application Proxy connector.
3. Configure KCD on the F5 load balancer.

Regarding your question about multiple servers, you can use a wildcard SPN to configure KCD for multiple servers. For example, the SPN could be `HTTP/*.example.com`. You still need to have the individual SPNs configured on your backend servers (for example, `HTTP/server1.example.com` and `HTTP/server2.example.com`).

To configure KCD on the F5 load balancer, you need to perform the following steps:

1. Create a new virtual server on the F5 load balancer for the application.
2. Configure the virtual server to use IWA.
3. Configure the virtual server to use KCD with the Application Proxy connector.

I hope this helps! Let me know if you have any further questions.

**Comment by ManoharLakkoju-MSFT** [comment]
@Bob-HL 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation

**Comment by Bob-HL** [comment]
Thanks for you informative response. I haven't got a chance to try it yet. But it looks convincing.
