### ISSUE TITLE
Update (FIDO) device keys documentation

### ISSUE THREAD

**Issue by BertinDEV** [MicrosoftDocs/entra-docs#776]
For the Role user admin

on line [2722](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/permissions-reference.md?plain=1#L2722) the more information states. that the role can **Update (FIDO) device keys** 

but then later on line [2729](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/permissions-reference.md?plain=1#L2729) it states **Cannot manage MFA.** 

on this [authentication-table](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/includes/authentication-table-include.md) it states that user admin Manage user's auth methods **no**

the same Fido key reference is made here in the [about-admin-roles.md](https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/admin/add-users/about-admin-roles.md?plain=1#L100)

if you look at the microsoft graph documentation for [List fido2AuthenticationMethod](https://learn.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&tabs=http)

the following 
For delegated scenarios where an admin is acting on another user, the administrator needs at least one of the following Microsoft Entra roles
Global Reader
Authentication Administrator
Privileged Authentication Administrator

and for [Delete fido2AuthenticationMethod](https://learn.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&tabs=http)

For delegated scenarios where an admin is acting on another user, the administrator needs at least the Authentication Administrator or Privileged Authentication Administrator

updating fido2 security key does not seem to be possible with user admin?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0767aac4-fcd9-eaac-2c30-8f17d8eadd92
* Version Independent ID: a380a828-03f9-e037-3a62-e4165fda7cb6
* Content: [Microsoft Entra built-in roles - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference)
* Content Source: [docs/identity/role-based-access-control/permissions-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/permissions-reference.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by Naveenommi-MSFT** [comment]
@BertinDEV 
Thank you for bringing this to our attention.
I've delegated this to content author @rolyon, who will review it and offer their insightful opinions.

**Comment by rolyon** [comment]
Hi @BertinDEV 
Thanks for taking the time to provide detailed feedback about the docs. Sorry for the delay. We think you are correct. We've sent a message to the team. We've also created a work item to track.
We are migrating to a new doc feedback tool, so we will close this GitHub issue. Let us know if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
