### ISSUE TITLE
Request body to disable Sign Up contains an error

### ISSUE THREAD

**Issue by javierginerTuring** [MicrosoftDocs/entra-docs#777]
On this page, the request body used to disable the sign up on a user flow contains an error. The "isSignUpAllowed" property should be boolean and not a string. 
I noticed this error testing the request on graph-explorer and gave me an error until I sent the property as a boolean.

```
{
    "@odata.type": "#microsoft.graph.externalUsersSelfServiceSignUpEventsFlow",
    "onInteractiveAuthFlowStart": {
        "@odata.type": "#microsoft.graph.onInteractiveAuthFlowStartExternalUsersSelfServiceSignUp",
        "isSignUpAllowed": "false"
    }
}
```

should be updated to 
```
{
    "@odata.type": "#microsoft.graph.externalUsersSelfServiceSignUpEventsFlow",
    "onInteractiveAuthFlowStart": {
        "@odata.type": "#microsoft.graph.onInteractiveAuthFlowStartExternalUsersSelfServiceSignUp",
        "isSignUpAllowed": false
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a5b75b2-1997-a166-40b6-243d0b1d8e66
* Version Independent ID: 53180cc2-558c-8861-6967-66de977ff8c4
* Content: [Create a sign-up and sign-in user flow - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-user-flow-sign-up-sign-in-customers)
* Content Source: [docs/external-id/customers/how-to-user-flow-sign-up-sign-in-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-user-flow-sign-up-sign-in-customers.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by TPavanBalaji** [comment]
@javierginerTuring 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@javierginerTuring 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
