### ISSUE TITLE
Small edit to the limits of a global reader

### ISSUE THREAD

**Issue by NaserQujaq** [MicrosoftDocs/entra-docs#778]
[Enter feedback here]
Following statement should be added under Global Reader and Users with this role cannot do the following: 

Cannot view Defender XDR Reports for other users 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0767aac4-fcd9-eaac-2c30-8f17d8eadd92
* Version Independent ID: a380a828-03f9-e037-3a62-e4165fda7cb6
* Content: [Microsoft Entra built-in roles - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference?source=docs#global-reader)
* Content Source: [docs/identity/role-based-access-control/permissions-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/permissions-reference.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by AjayBathini-MSFT** [comment]
@NaserQujaq 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by NaserQujaq** [comment]
***@***.*** Qoujaq (ESTARTA ***@***.***> for visibility

**Comment by rolyon** [comment]
Hi @NaserQujaq 
Thanks for your feedback. We've sent your feedback to the team to review. We'll update the docs based on their review.
We are migrating to a new doc feedback tool, so we will close this GitHub issue. Let us know if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
