### ISSUE TITLE
Mis-spelling?

### ISSUE THREAD

**Issue by pmmoss** [MicrosoftDocs/entra-docs#779]
Certificate Based Authentication (CBA) *.certauth.login.microsoftonline.com & *.certauth.login.mcirosoftonline.us.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80a8212c-02d2-8c43-cd01-8b0f4214afe3
* Version Independent ID: 8345a140-1501-ec5a-03a8-e50b6ce184b6
* Content: [How to configure Microsoft Entra certificate-based authentication - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-certificate-based-authentication#prerequisites)
* Content Source: [docs/identity/authentication/how-to-certificate-based-authentication.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-certificate-based-authentication.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @vimrang
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@pmmoss 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by pmmoss** [comment]
> @pmmoss It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

Sorry -   https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-certificate-based-authentication#prerequisites

**Comment by TPavanBalaji** [comment]
@pmmoss 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @pmmoss 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
