### ISSUE TITLE
Where can I ask questions about the contents of documentation?

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/entra-docs#78]
My question isn't so much about the documentation, more about the contents - is there somewhere Microsoft recommends we ask those?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 325a9114-36b2-a6b3-d0a4-19c522b7abf0
* Version Independent ID: cbd84d9f-fbfd-d97d-9826-26947f64d18a
* Content: [Tutorial - Configure LDAPS for Microsoft Entra Domain Services - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/domain-services/tutorial-configure-ldaps)
* Content Source: [docs/identity/domain-services/tutorial-configure-ldaps.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/domain-services/tutorial-configure-ldaps.md)
* Service: **active-directory**
* Sub-service: **domain-services**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaibabaBalapur-MSFT** [comment]
@catmanjan 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by catmanjan** [comment]
@SaibabaBalapur-MSFT https://learn.microsoft.com/en-us/entra/identity/domain-services/tutorial-configure-ldaps

**Comment by apcsb** [comment]
Best you can do is join the Entra Advisors community via https://aka.ms/joinccp - there are also LinkedIn and Discord communities.

**Comment by SaibabaBalapur-MSFT** [comment]
@apcsb Thanks for quick responses.

@catmanjan 
if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by SaibabaBalapur-MSFT** [comment]
@catmanjan 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
