### ISSUE TITLE
What are custom security attributes in Microsoft Entra ID?

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/entra-docs#780]
Hello,

It would be great to have the documentation also for:

* groups - how to add, manage, use, which groups supported (security, mail-enabled, distribution, etc.)
* devices - how to add, manage, use, which device type supported (android, ios, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2896aa11-53c5-722b-aabf-e59dda55cf38
* Version Independent ID: 7291a3a0-24d6-0e88-9105-29001f7e3ed1
* Content: [What are custom security attributes in Microsoft Entra ID? - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/custom-security-attributes-overview)
* Content Source: [docs/fundamentals/custom-security-attributes-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/custom-security-attributes-overview.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@lightupdifire 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@lightupdifire 
Here are the links to the documentation for managing groups and devices in Azure Active Directory:
[Manage groups in Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-groups-create-azure-portal)
[Add or delete devices using Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/devices/device-management-azure-portal)
These documents cover how to add, manage, and use groups and devices in Azure AD, as well as which types of groups and devices are supported. Let me know if you have any further questions!

**Comment by lightupdifire** [comment]
@SaibabaBalapur-MSFT 
I mean on how to apply and manage the custom security attributes to Groups and Devices.

**Comment by SaibabaBalapur-MSFT** [comment]
I apologize for the confusion earlier. Custom security attributes can be assigned to groups and devices in Azure AD using the Azure AD PowerShell module. Here are the steps to assign custom security attributes to groups and devices:

## Assign custom security attributes to a group

1. Install the Azure AD PowerShell module by running the following command in an elevated PowerShell session:

   ```
   Install-Module AzureAD
   ```

2. Connect to your Azure AD tenant by running the following command:

   ```
   Connect-AzureAD
   ```

3. Assign a custom security attribute to a group by running the following command:

   ```
   Set-AzureADGroupExtension -ObjectId <GroupObjectId> -ExtensionName "<AttributeName>" -ExtensionValue "<AttributeValue>"
   ```

   Replace `<GroupObjectId>` with the object ID of the group you want to assign the custom security attribute to, `<AttributeName>` with the name of the custom security attribute, and `<AttributeValue>` with the value of the custom security attribute.

## Assign custom security attributes to a device

1. Install the Azure AD PowerShell module by running the following command in an elevated PowerShell session:

   ```
   Install-Module AzureAD
   ```

2. Connect to your Azure AD tenant by running the following command:

   ```
   Connect-AzureAD
   ```

3. Assign a custom security attribute to a device by running the following command:

   ```
   Set-AzureADDeviceExtension -ObjectId <DeviceObjectId> -ExtensionName "<AttributeName>" -ExtensionValue "<AttributeValue>"
   ```

   Replace `<DeviceObjectId>` with the object ID of the device you want to assign the custom security attribute to, `<AttributeName>` with the name of the custom security attribute, and `<AttributeValue>` with the value of the custom security attribute.

I hope this helps! Let me know if you have any further questions.

**Comment by lightupdifire** [comment]
@SaibabaBalapur-MSFT
Thanks! So I was looking into this document (https://learn.microsoft.com/en-us/entra/fundamentals/custom-security-attributes-overview) and was searching documentation about how to manage custom security attributes for groups and devices,
If some document already exists, maybe can add into this document a hyperlink + note?
