### ISSUE TITLE
Using Graph API in a SAML flow.

### ISSUE THREAD

**Issue by linoman** [MicrosoftDocs/entra-docs#783]
With a user that belongs to more than 200 groups, a groups link is being returned with the SAML claims. However, that URL is only useful for authentication with OAuth since it requires a JWT.

https://learn.microsoft.com/en-us/entra/identity-platform/scenario-token-exchange-saml-oauth

This part of the documentation claims it is possible to set up stacked applications with OAuth and SAML, but I found it vague and unclear.

Is it possible to find an example with these scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0426f50b-e03b-4e77-4a8a-390b0ae08c62
* Version Independent ID: 0039b994-8481-1214-b42a-c2113b07fafc
* Content: [Microsoft identity platform token exchange scenario with SAML and OIDC/OAuth in Microsoft Entra ID - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-token-exchange-saml-oauth)
* Content Source: [docs/identity-platform/scenario-token-exchange-saml-oauth.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/scenario-token-exchange-saml-oauth.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by TPavanBalaji** [comment]
@linoman 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@linoman 
Thank you for bringing this to our attention.
I've delegated this to content author @OwenRichards1, who will review it and offer their insightful opinions.

**Comment by OwenRichards1** [comment]
Thanks for the feedback @linoman - I have taken this onboard and added to our product back log.

As we are moving to a new feedback mechanism, I am required to close this issue, but be assured that this feedback has been noted and will be addressed.

Thanks again for your contribution.

#please-close
