### ISSUE TITLE
Path to SQLCMD.exe incorrect based on Connect versions

### ISSUE THREAD

**Issue by BryanB-MSFT** [MicrosoftDocs/entra-docs#785]
Depending on the version of Entra Connect in use the path for the SQLCMD.exe may not be located in the path %ProgramFiles%\Microsoft SQL Server\110\Tools\Binn.
I am not sure of the path for all versions but with a fresh install of 2.3.8 the path is %ProgramFiles%\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b123ab46-7169-7f3d-9ac8-91ff435c22d5
* Version Independent ID: 49f5b604-5b7a-872b-0e13-30e6a8ebb3dd
* Content: [Microsoft Entra Connect: How to recover from LocalDB 10GB limit issue - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/tshoot-connect-recover-from-localdb-10gb-limit)
* Content Source: [docs/identity/hybrid/connect/tshoot-connect-recover-from-localdb-10gb-limit.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/tshoot-connect-recover-from-localdb-10gb-limit.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@BryanB-MSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@BryanB-MSFT 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
