### ISSUE TITLE
Documentation had some errors

### ISSUE THREAD

**Issue by Pompeoar** [MicrosoftDocs/entra-docs#787]
Some of this may have been me, but I found this page tough to use from the examples standpoint. 

- Variables needed $ before them.

- In step 4 it wasn't the object Id but the resource Id for that application. You can find the object Id in the portal but that's wrong. I had to run the command to get the resource Id. 

- The az rest at the end command failed. I just removed the forward slash precursors. So something like 
```powershell
$jsonBody = "{'principalId': '$oidForMI', 'resourceId': '$serverSPOID', 'appRoleId': '$roleguid'}"

az rest -m POST -u https://graph.microsoft.com/v1.0/servicePrincipals/$oidForMI/appRoleAssignments -b $jsonBody
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b01bcd94-4204-af22-46e4-ce45c449358c
* Version Independent ID: 2c0de090-f401-e819-ca19-18e2587f0fe3
* Content: [Assign a managed identity to an application role using Azure CLI - Managed identities for Azure resources](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-cli)
* Content Source: [docs/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-cli.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/how-to-assign-app-role-managed-identity-cli.md)
* Service: **entra-id**
* Sub-service: **managed-identities**
* GitHub Login: @xstof
* Microsoft Alias: **christoc**

**Comment by TPavanBalaji** [comment]
@Pompeoar 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@Pompeoar 
I have reproduced the same in my environment as per documentation, everything works successfully. check the below screenshot for the status. please recheck from your end.
![image](https://github.com/MicrosoftDocs/entra-docs/assets/129385121/b160017a-e057-4e0d-9e23-1b4bc0333faf)
whenever give the roleid's make sure to remove unnecessary spaces. If still getting any issues 
I'd recommend to utilise Microsoft Q & A platform. Kindly raise your query on [Microsoft Q&A Platform](https://docs.microsoft.com/en-us/answers/index.html)

**Comment by PesalaPavan** [comment]
@Pompeoar 
We are going to close this thread but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
