### ISSUE TITLE
About SSO

### ISSUE THREAD

**Issue by mirojs** [MicrosoftDocs/entra-docs#789]
[Enter feedback here]
Hello,

Is it possible to include the SSO code in the tutorial as in the React one (https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-single-page-app-react-sign-in-prepare-app)?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 693a6589-57b8-e3ed-57ec-e510d1710610
* Version Independent ID: 693a6589-57b8-e3ed-57ec-e510d1710610
* Content: [Tutorial: Prepare a Python Flask web application for authentication in an external tenant - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/tutorial-web-app-python-flask-sign-in-sign-out?tabs=windows)
* Content Source: [docs/external-id/customers/tutorial-web-app-python-flask-sign-in-sign-out.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/tutorial-web-app-python-flask-sign-in-sign-out.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @SHERMANOUKO
* Microsoft Alias: **shermanouko**

**Comment by TPavanBalaji** [comment]
@mirojs 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@mirojs 
Thank you for bringing this to our attention.
I've delegated this to content author @SHERMANOUKO, who will review it and offer their insightful opinions.

**Comment by SHERMANOUKO** [comment]
@mirojs thank you for your feedback.

In general, different apps probably do not share their login state; however, your browser will probably maintain its session cookie for the same login.microsoftonline.com site, so SSO can happen there, for free. (It means each app might still trigger its login experience, but the end user does not really need to type in their username and password again on login.microsoftonline.com.)

You can find more discussion on this here https://github.com/Azure-Samples/ms-identity-python-webapp/issues/146

**Comment by SHERMANOUKO** [comment]
#please-close
