### ISSUE TITLE
Missing Workload Identities Premium

### ISSUE THREAD

**Issue by tomatsue** [MicrosoftDocs/entra-docs#79]
Workload Identities Premium must be on the Microsoft online service products list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **active-directory**
* Sub-service: **enterprise-users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by SaibabaBalapur-MSFT** [comment]
@tomatsue 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Nicholak-MS** [comment]
I have added the details for Workload Identities Premium to both the online table and the downloadable CSV. 

Thanks for bringing this to our attention. 

#please-close
