### ISSUE TITLE
Reference example project is not up-to-date, using .NET core 3.1 framework

### ISSUE THREAD

**Issue by nielsvdc** [MicrosoftDocs/entra-docs#790]
On this page there is a reference link to the a Github project https://github.com/AzureAD/SCIMReferenceCode. This project is not a good example anymore, because it's using .NET core 3.1 framework and contains references to packages that are not supported anymore. Please reference a new up-to-date sample project.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b633a23e-8b4e-5f76-687b-d9c32ca482dc
* Version Independent ID: ed365cbe-971b-6010-21fe-e9ce987eac6c
* Content: [Build a SCIM endpoint for user provisioning to apps from Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-build-users-and-groups-endpoints?tabs=visual-studio)
* Content Source: [docs/identity/app-provisioning/use-scim-to-build-users-and-groups-endpoints.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/use-scim-to-build-users-and-groups-endpoints.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by TPavanBalaji** [comment]
@nielsvdc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@nielsvdc 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

@kenwith
Please review it.

**Comment by kenwith** [comment]
Moving feedback to content backlog.

#please-close
