### ISSUE TITLE
Dynamic user

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/entra-docs#791]
Hello,

Can you please add in the document how long it requires to wait until Dynamic sync for user or device runs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72bf3d35-e81f-adae-e9ae-c0dfa5dc4848
* Version Independent ID: 499bd02d-e05c-1ada-1541-efa0075ae205
* Content: [Manage users or devices for an administrative unit with dynamic membership rules (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/admin-units-members-dynamic)
* Content Source: [docs/identity/role-based-access-control/admin-units-members-dynamic.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/admin-units-members-dynamic.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@lightupdifire 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@lightupdifire 
Thank you for bringing this to our attention.
I've delegated this to content author @rolyon, who will review it and offer their insightful opinions.

**Comment by rolyon** [comment]
Hi @lightupdifire 
Thanks for your feedback. According to the following doc, the initial update of an administrative unit can take a few minutes depending on your tenant size and the current Microsoft Entra ID load.
https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/admin-units-faq-troubleshoot#dynamic-administrative-units--preview
We contacted the team to check for additional details they want to add about dynamic membership rule evaluation. We will update the docs based on their feedback.

We are migrating to a new doc feedback tool, so we will close this GitHub issue. Let us know if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
