### ISSUE TITLE
[General Motors Feedback] Please add information or a note on Company Portal

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/entra-docs#793]
GM understands that this article is not specific to Intune and that a customer could be using a different MDM/MAM solution other than Intune, but they request us to add a note somewhere that if using Intune and Intune policies, it is required to install Intune Company Portal for Shared Mode to work correctly and link it to more info on https://learn.microsoft.com/en-us/mem/intune/enrollment/android-kiosk-enroll. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0072c083-6b6c-2d36-d70f-4d63da44d178
* Version Independent ID: 9cc2ce29-7861-2886-c27b-b29da4d864ef
* Content: [Shared device mode for Android devices - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/msal-android-shared-devices)
* Content Source: [docs/identity-platform/msal-android-shared-devices.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/msal-android-shared-devices.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by TPavanBalaji** [comment]
@cadasi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@cadasi 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by henrymbuguakiarie** [comment]
Hello @cadasi,

We are tracking this work internally, I'll go ahead an close the GitHub issue.

Thank you for your feedback.

#please-close
