### ISSUE TITLE
"Not started" status not documented

### ISSUE THREAD

**Issue by jepperaskdk** [MicrosoftDocs/entra-docs#794]
Under the section "Check processing status for a rule" it mentions "The following status messages can be shown for Dynamic rule processing status:"

It does however not include "Not started", which my newly created dynamic group is now in:
<img width="553" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/10128260/933f0632-e841-4965-98a9-275db57306aa">

It would be good to know how long I should wait until it processes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24c25353-cfb3-811c-a970-2a04678eff6e
* Version Independent ID: 145d404a-f7ed-17f6-79a6-0204ab7ee70b
* Content: [Create or edit a dynamic group and get status - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-create-rule?WT.mc_id=Portal-fx#check-processing-status-for-a-rule)
* Content Source: [docs/identity/users/groups-create-rule.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-create-rule.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@jepperaskdk 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@jepperaskdk 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by barclayn** [comment]
@jepperaskdk thank you for pointing this out. We have created a work item to track this internally and make the necessary updates. #please-close
