### ISSUE TITLE
Clarification - Synced user conversion

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/entra-docs#795]
I don't get it why/how the conversation of synced users should be possible and what the usecases are... Is this a feature to make a hybrid identity to a cloud only user?
If so, is this only usable using Entra Cloud Sync to sync users? I can't imagine a way how to "unsync" a user using entra connect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 87999564-0514-26cf-1b85-86f4a59d4c69
* Version Independent ID: 87999564-0514-26cf-1b85-86f4a59d4c69
* Content: [Convert external users to internal users (Preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/convert-external-users-internal#synced-user-conversion)
* Content Source: [docs/identity/users/convert-external-users-internal.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/convert-external-users-internal.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@J-a-k-o-b 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by J-a-k-o-b** [comment]
Sorry, didn't recognized that this issue seems not to be linked to the article from where I've opened it. The docs site I'm talking about is this one: https://learn.microsoft.com/en-us/entra/identity/users/convert-external-users-internal#synced-user-conversion

**Comment by TPavanBalaji** [comment]
@J-a-k-o-b 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @J-a-k-o-b I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.[Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by J-a-k-o-b** [comment]
This is a general question which should be answered in general to avoid unnecessary support calls. Maybe you can answer it in a kind of requirements section.

**Comment by J-a-k-o-b** [comment]
Sorry, i don't get it. The article mentions that you can use this feature for synced users, which are hybrid identities. I don't get it what conversation could be done with that type of accounts?

> In this document, when we say 'Synced user', we mean users synced from on-premises. As these accounts are managed at the source, administrators are unable to specify the UPN for these users.

> Synced users where the tenant uses federated authentication
> If Password Hash Sync (PHS) is enabled, administrators are blocked from setting a new password during conversion.
> if the federated tenant doesn't have PHS enabled, administrators have the option to set a password.
> In cases where the tenant is managed, meaning it uses cloud authentication, administrators are required to specify a password during conversion.

**Comment by SaibabaBalapur-MSFT** [comment]
@J-a-k-o-b I apologize for any confusion. The article you mentioned is about converting external users to internal users in Entra AD, and it mentions that this feature can be used for synced users, which are hybrid identities. However, it does not mention anything about conversations with these types of accounts. Further I'm going to assign @barclayn this to the document author so they can take a look at it accordingly.

@barclayn
please review it.

**Comment by barclayn** [comment]
@J-a-k-o-b thank you for your post. We have created a work item to update the article. In the meantime, please contact support if you need further assistance with your question. #please-close
