### ISSUE TITLE
This article needs to be updated to use, or include, Az Cli commands

### ISSUE THREAD

**Issue by lsmith-apriva** [MicrosoftDocs/entra-docs#797]
This article needs to be updated to use, or include, Az Cli commands

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b20c1bb-dbfc-06db-b5b4-ce9d67c004cd
* Version Independent ID: acbdb973-4c76-db09-400d-013e364f2dba
* Content: [Create a role-assignable group in Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/groups-create-eligible?tabs=ms-powershell)
* Content Source: [docs/identity/role-based-access-control/groups-create-eligible.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/groups-create-eligible.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@lsmith-apriva 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by rolyon** [comment]
Hi @lsmith-apriva
Thanks for your feedback. Azure CLI isn't supported, but you should be able to use Microsoft Graph CLI.
https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&branch=main&tabs=cli#example-3-create-a-microsoft-365-group-that-can-be-assigned-to-a-microsoft-entra-role
We've sent your feedback to the team about including CLI. We created a work item to track.
We are migrating to a new doc feedback tool, so we will close this GitHub issue. Let us know if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
