### ISSUE TITLE
Path for combining existing AAD B2C features and new features using Entra External ID

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [MicrosoftDocs/entra-docs#8]
Can you in https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam#about-azure-ad-b2c  include scenario when we have existing AAD B2C Sign-in/sign up custom policies solution, but consider to add new features(such as social signin)?
If we will decide to wait until Entra External ID will be GA, can  functionality co-exist, e.g. one application will use AAD B2C and another Entra External ID with common existing B2C tenant?
Will existing AAD B2C tenant be compatible with new Entra External ID requirements https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam#create-a-dedicated-tenant-for-your-customer-scenarios?
Are you planning to have a document describing using in parallel AAD B2C and  Entra External ID solutions and also migration from AAD B2C to  Entra External ID solution?

 “Entra External ID “ documentation uses “user flow” term, how it is similar to B2C “user flow” vs “custom policy” concepts?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7c61515-5609-a07c-f0b6-840a86851e73
* Version Independent ID: 4b443a57-720b-f4c9-7fbe-eee201997831
* Content: [Overview - Customer identity access management (CIAM) - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam)
* Content Source: [docs/external-id/customers/overview-customers-ciam.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/overview-customers-ciam.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by yoelhor** [comment]
1. **Migration**: The next-generation platform is currently in public preview, and we remain fully committed to supporting your current Azure AD B2C solution. There are no requirements for Azure AD B2C customers to migrate at this time and no plans to discontinue the current Azure AD B2C service. As the next generation platform approaches GA, details will be made available to all our valued B2C customers on available options including migration to the new platform.

1. Considerations for **coexistence**: 
      1. Azure AD B2C and Entra external ID are to different token issuance (or identity providers). 
      2. Consider the impact on the session (two IDPs means two separate sessions), directory (users will have to create two separate accounts), user experience and more.
      3. Exiting applications can continue using B2C while new ones will use the Entra ID.  But you can also configure the app to trust both IDPs.
      4. There are some options that you can consider, such as add your Entra ID into the B2C as the ONLY identity provider. In this case exiting applications will continue to use the B2C but it will act as a middleware between the app the Entra ID. Use Graph API to migrate the accounts to Entra ID. Since you can't export the password, you can use email and one-time passcode and the authentication method or ask the user to go through the forgot password flow.
      5. We are in the early stages of defining the migration path, just wanted to share some insights with you.
1. **User flows**: B2C and Entra ID users flows look similar but not the same.

**Comment by msmimart** [comment]
@michael-freidgeim-webjet I hope this helps. We'll go ahead and close this issue, but feel free to let us know if you have further questions. Thank you! #please-close
