### ISSUE TITLE
Botskiy

### ISSUE THREAD

**Issue by romankulkovsf** [MicrosoftDocs/entra-docs#801]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83b07a9e-5e16-32ed-265e-32a32998ce37
* Version Independent ID: 09008259-4b53-2925-9679-ecad59cefe41
* Content: [Tutorial - Customize Microsoft Entra attribute mappings in Application Provisioning - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/customize-application-attributes#provisioning-a-role-to-a-scim-app)
* Content Source: [docs/identity/app-provisioning/customize-application-attributes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/customize-application-attributes.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by kenwith** [comment]
#please-close

**Comment by TPavanBalaji** [comment]
@romankulkovsf 
We are going to close this thread if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by romankulkovsf** [comment]
Hey
