### ISSUE TITLE
Possible incomplete errors explanations

### ISSUE THREAD

**Issue by 1944GPW** [MicrosoftDocs/entra-docs#802]
I was hoping this error explanation page would cover a resolution for "User invitation failed  Non-external user already exists with the given mail address and can't be invited." when I try sending an invite for either Member or Guest. I had previously created an internal user with the same email address then deleted it after the notifications said there was an existing member. I think I did allow time for the deletion to propagate in my test tenancy, even though it only has half a dozen users.
This was the page that came up when I searched for my error message, so I hope it's the right place where an explanation should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f76cc85-8dc0-9be3-4071-217589ddef56
* Version Independent ID: e7bdba65-bacc-7fef-2c27-b3425f697b12
* Content: [Troubleshooting B2B collaboration - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/troubleshoot)
* Content Source: [docs/external-id/troubleshoot.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/troubleshoot.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by TPavanBalaji** [comment]
@1944GPW 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@1944GPW 
Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.

**Comment by Cpcrook** [comment]
@1944GPW Did you end up finding a resolution to this?  I'm running into it with a B2C tenant as I'm trying to provision backup admin users.
