### ISSUE TITLE
Command to collect logs is in-correct

### ISSUE THREAD

**Issue by pathaksomesh06** [MicrosoftDocs/entra-docs#803]
[The command mentioned to collect logs is in-correct as it has an extra quote at end. It should be sudo log config --mode "level:debug,persist:debug" --subsystem com.apple.AppSSO]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0693f824-4a92-2ce2-f6ea-9f5a3759c1ff
* Version Independent ID: 0693f824-4a92-2ce2-f6ea-9f5a3759c1ff
* Content: [macOS Platform single sign-on known issues and troubleshooting - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/troubleshoot-macos-platform-single-sign-on-extension?tabs=macOS14)
* Content Source: [docs/identity/devices/troubleshoot-macos-platform-single-sign-on-extension.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/troubleshoot-macos-platform-single-sign-on-extension.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by TPavanBalaji** [comment]
@pathaksomesh06 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@pathaksomesh06 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

**Comment by TPavanBalaji** [comment]
@pathaksomesh06 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
