### ISSUE TITLE
Documentation is grossly inaccurate.

### ISSUE THREAD

**Issue by dreeves14** [MicrosoftDocs/entra-docs#807]
Administrators can exclude the entire Office 365 suite or specific Office 365 cloud apps from the Conditional Access policy.

You can no longer target individual apps of the 365 suite with CA. I used to be able to block Exchange, Teams, SharePoint, OneDrive etc which was huge for restricting contractors that may need just Teams or just Email, but we could give them an E3 so they had Office Suite and web apps tied to our tenant. Microsoft broke that without notice and created a whole mess and can't provide a similar solution. This was a rug pull.

Also the "Microsoft Teams Services" app doesn't allow you to pinhole teams if a users only needs Teams and not everything else. This is very much a great feature to have because some org don't want to fully open teams to anyone or add an entire domain for 1 or 2 contractors. Microsoft is either A: trying to force people to buy more licenses, or B: Had no idea what these changes were going to do to their client base. Either way it was a piss poor move.

![image](https://github.com/MicrosoftDocs/entra-docs/assets/55603935/d0843df3-140f-485b-aea6-33da1c77a588)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6d2ea9-04c9-d4e5-36b5-2ce7e17192e1
* Version Independent ID: eff8d31c-d3ce-f72c-22ab-53b415b221b0
* Content: [Cloud apps, actions, and authentication context in Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-conditional-access-cloud-apps)
* Content Source: [docs/identity/conditional-access/concept-conditional-access-cloud-apps.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-conditional-access-cloud-apps.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@dreeves14 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@dreeves14 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo,  who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@MicrosoftGuyJFlo 
Could you please review add comments on this, update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
I am able to exclude apps like Office 365 Exchange Online and Office 365 SharePoint Online from a policy including Office 365. I would recommend opening a support case if you are still experiencing issues. 

#please-close
