### ISSUE TITLE
Implicit flows no longer there. Instruction cannot be implemented?

### ISSUE THREAD

**Issue by apcsb** [MicrosoftDocs/entra-docs#81]
The item 3.2 requires to add an implicit flow
https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-get-started?tabs=entra-admin-center%2Chttp#32-enable-implicit-flow

As far as I know this is no longer possible in Entra ID - the functionality was deprecated with MSAL 2.0
At least, the UI is not there.

Same applies to the video 
https://www.youtube.com/watch?v=fxQGVIwX8_4&list=PL3ZTgFEc7Lythpts59O9KOVuEDLWJLLmA&index=7
(around 7.53)

Please update the guidance (unless I am mistaken).
Thanks!

P.S. Would be nice to provide JSON for Graph APIs call to create, register and configure all these entities - would make it more repeatable. Cheers!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef99966f-e466-d7fe-3f12-8e725ac0ce85
* Version Independent ID: 827894b5-38c5-7dac-0b90-8f839996c87d
* Content: [Get started with custom claims providers (preview) - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-get-started?tabs=entra-admin-center%2Chttp)
* Content Source: [docs/identity-platform/custom-extension-get-started.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/custom-extension-get-started.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by SaibabaBalapur-MSFT** [comment]
@apcsb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@apcsb 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by omondiatieno** [comment]
#reassign:cilwerner

**Comment by omondiatieno** [comment]
@cilwerner, I've reassigned this to you since you now own the topic. Kindly review and resolve this accordingly.

**Comment by apcsb** [comment]
I am using the Entra Admin center for testing/trying out, but for "proper" deployment Graph should be used, of course, to scale.

**Comment by cilwerner** [comment]
Implicit flow will still work with this because you are using the JWT app for testing. You are correct in your assumption that MSAL 2.0 doesn't permit implicit flow, but as this is a guide on implementing an Azure function and displaying the token value via an app designed to use implicit flow, this step is correct.

Of course for actual usage, use the recommended flow rather than implicit.

**Comment by cilwerner** [comment]
#please-close
