### ISSUE TITLE
Amazon instead of Google

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/entra-docs#810]
The page is about setting up federation with Google as an identity provider, but the sample code contains "Amazon" instead of "Google"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92ff7dd1-dbcc-02f1-fa68-198186b6e846
* Version Independent ID: 8c35551d-62a7-f2ad-0a1e-ff2eb2343063
* Content: [Add Google as an identity provider - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-google-federation-customers)
* Content Source: [docs/external-id/customers/how-to-google-federation-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-google-federation-customers.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by PesalaPavan** [comment]
@MatthewSteeples 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@MatthewSteeples 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
