### ISSUE TITLE
Invite a guest user to an app from the Access Panel (myapps mirosoft com )- not accurate - not possible

### ISSUE THREAD

**Issue by mlinar79** [MicrosoftDocs/entra-docs#813]
**Issue 1:** 
Invite guest users, step 4. 
The picture is not accurate. myapps.microsoft.com -  After clicking "manage your application," you will be redirected to"App assignment - Manage user - link). After clicking "manage users" you will be redirected to standard Entra portal for Group management.  So, you never get the prompt shown on the picture under step 4.

 
![image](https://github.com/MicrosoftDocs/entra-docs/assets/60464942/335f60c3-7fa3-43f7-a516-d0ad168779dc)
![image](https://github.com/MicrosoftDocs/entra-docs/assets/60464942/ad932985-35a0-4f4c-b3f3-82a7f2af0d42)

**Issue 2.** 
Invite guest users, step 4. 
You cannot directly invite guest accounts like it is explained and shown in the picture under step 4. 
Additional Explanation: 
Because you are redirected to the standard Entra page for Group management, from there, it is not possible to invite Guests. You can just add existing accounts - Direct Members (Guests or members). Guest need to be pre-invited through Azure. 
(all permissions have been checked, - owners allowed to invite, self-service application access enabled)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/60464942/d75a5d73-96a0-457a-bc29-463e461c9dac)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbdc24d-5bc5-54f0-208c-8574b19dfb40
* Version Independent ID: 09e9c6cf-8626-532b-8a59-640ec5d4798a
* Content: [Add B2B collaboration users as an information worker - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/add-users-information-worker)
* Content Source: [docs/external-id/add-users-information-worker.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/add-users-information-worker.md)
* Service: **entra-external-id**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by PesalaPavan** [comment]
@mlinar79 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@mlinar79 
I'm going to assign this to the document author so they can take a look at it accordingly.

@csmulligan 
Can you please check and add your comments on this doc update request as applicable.

**Comment by csmulligan** [comment]
Hi @mlinar79 thank you so much for pointing this out. I've moved this issue to an internal work item for tracking. I'll go ahead and close this issue, but changes to the article are in the works. Thanks again for helping us improve the documentation!
#please-close
