### ISSUE TITLE
Incorrect domain pattern on step 5b

### ISSUE THREAD

**Issue by richard-northumbria** [MicrosoftDocs/entra-docs#814]
I hit an issue with the integration and it was due to the details on step 5b which states:

b. In the Identifier (Entity ID) text box, type a value using the following pattern: `<subdomain>.zendesk.com`

Steps A and C indicate the use of the scheme is required within the config value and in my scenario the https was required to work

If you don't include the https:// you get the error message along the lines of "Misconfigured application. This could be due to one of the following: the client has not listed any permissions for 'AAD Graph' in the requested permissions in the client's application registration...... Client app ID: 8e17306b-5fc3-4b73-8e4c-76ec4156b163"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16ae6014-a5f6-03f3-4ad4-4425cfe5b6ca
* Version Independent ID: 1d3d0543-89f7-180a-e52a-b5668a314e6a
* Content: [Tutorial: Microsoft Entra SSO integration with Zendesk - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/zendesk-tutorial)
* Content Source: [docs/identity/saas-apps/zendesk-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/zendesk-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by PesalaPavan** [comment]
@richard-northumbria 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by v-hgampala** [comment]
@richard-northumbria, thanks for raising the issue!!
we're updating the document with correct Identifier value.
#please-close
