### ISSUE TITLE
No examples for ClaimsTransformations

### ISSUE THREAD

**Issue by nik-lazer** [MicrosoftDocs/entra-docs#816]
I am working on customizing my claim tokens and need to apply [ifEmpty function](https://learn.microsoft.com/en-us/entra/identity-platform/saml-claims-customization) for that. The description says that I need to provide one input parameter and two output parameters:
`Outputs an attribute or constant if the input is null or empty.
For example, if you want to output an attribute stored in an extension attribute if the employee ID for a given user is empty. To perform this function, configure the following values:
Parameter 1(input): user.employeeid
Parameter 2 (output): user.extensionattribute1
Parameter 3 (output if there's no match): user.employeeid`

I tried the following:
`{
  "ClaimsMappingPolicy": {
    "Version": 1,
    "IncludeBasicClaimSet": "true",
    "ClaimsSchema": [
      {
        "Source": "application",
        "ID": "objectid",
        "JwtClaimType": "prn1"
      },
      {
        "Source": "user",
        "ID": "userprincipalname",
        "JwtClaimType": "prn2"
      },
      {
        "Source": "transformation",
        "TransformationID": "userOrApp",
        "ID": "collibrasub",
        "JwtClaimType": "prn"
      },
      {
        "Source": "user",
        "ID": "usertype",
        "JwtClaimType": "prn31"
      },
      {
        "Source": "application",
        "ID": "displayname",
        "JwtClaimType": "prn41"
      }
    ],
    "ClaimsTransformations": [
      {
        "ID": "userOrApp",
        "TransformationMethod": "IfEmpty",
        "InputClaims": [
          {
            "ClaimTypeReferenceId": "userprincipalname",
            "TransformationClaimType": "inputClaim1"
          },
          {
            "ClaimTypeReferenceId": "objectid",
            "TransformationClaimType": "inputClaim2"
          },
          {
            "ClaimTypeReferenceId": "usertype",
            "TransformationClaimType": "inputClaim3"
          }
        ],
        "OutputClaims": [
          {
            "ClaimTypeReferenceId": "collibrasub",
            "TransformationClaimType": "outputClaim"
          }
        ]
      }
    ]
  }
}`

but I cannot figure out how the JSON definition has to be written to do it properly. Could you please give more details?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c350829-8476-71a7-f53b-6cf788917037
* Version Independent ID: fbab99b8-0e94-1075-cb38-11a972feba87
* Content: [Customize SAML token claims - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/saml-claims-customization)
* Content Source: [docs/identity-platform/saml-claims-customization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/saml-claims-customization.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by AjayBathini-MSFT** [comment]
@nik-lazer 

Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
