### ISSUE TITLE
Contradictory limit values for the same items.

### ISSUE THREAD

**Issue by LainRobertson** [MicrosoftDocs/entra-docs#818]
Hi, folks.

In the following two articles, contradictory values are specified for the maximum number of combined dynamic groups and administrative units.

- https://learn.microsoft.com/en-us/entra/identity/users/directory-service-limits-restrictions
- https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#microsoft-entra-id-limits

The "Groups" entry states:

_A Microsoft Entra organization can have a maximum of 15,000 dynamic groups and dynamic administrative units combined._

The "Administrative Units" entry states:

_A Microsoft Entra organization can have a maximum of 5,000 dynamic groups and dynamic administrative units combined._

The contradiction needs fixing.

And which is the limit these days? Still 5,000, or has it finally been raised to 15,000?

Cheers,
Lain

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42a0b4cb-1981-1cbc-ce2c-dbfd8af1527c
* Version Independent ID: d49c873c-9843-8428-a6d1-a1995067d13b
* Content: [Service limits and restrictions - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/directory-service-limits-restrictions)
* Content Source: [docs/identity/users/directory-service-limits-restrictions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/directory-service-limits-restrictions.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@LainRobertson 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @LainRobertson 
Thanks for your question. The maximum quota for dynamic groups and dynamic administrative units in Microsoft Entra organizations has been increased from 5,000 to 15,000. For example, you can now have a combination such as 5,000 dynamic groups and 10,000 dynamic AUs, or any other mix totaling up to 15,000.
Please refer this below document for your reference [Document](https://learn.microsoft.com/en-us/entra/fundamentals/whats-new#:~:text=General%20Availability%20%2D%20Dynamic,and%20restrictions.).

**Comment by LainRobertson** [comment]
Hi, @Naveenommi-MSFT.

Thanks for the clarification!

Is somebody going to update the two articles mentioned above, so that the "Administrative units" combined limit of 5,000 is updated to correctly reflect the figure of 15,000 mentioned in the "Groups" section as well as the URL you've quoted above?

Cheers,
Lain

**Comment by Naveenommi-MSFT** [comment]
@LainRobertson 
We have discussed with the content author, who will review and update as needed. We are closing this thread now. If you have further questions about the documentation, please tag me in your reply, and we will gladly continue the conversation.

#Please-close
