### ISSUE TITLE
Bulk Import of Existing Customers

### ISSUE THREAD

**Issue by MrHinsh** [MicrosoftDocs/entra-docs#82]
This document does not describe how to handle "bulk import" of existing customers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 418a623c-15d2-8e05-8b43-60072dc905e2
* Version Independent ID: 90e3a4e5-65fc-c31b-ebe0-6b2a735f61b0
* Content: [Add and manage customer accounts - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-manage-customer-accounts)
* Content Source: [docs/external-id/customers/how-to-manage-customer-accounts.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/how-to-manage-customer-accounts.md)
* Service: **active-directory**
* Sub-service: **ciam**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by SaibabaBalapur-MSFT** [comment]
@MrHinsh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@msmimart
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@MrHinsh 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by msmimart** [comment]
Hi @MrHinsh, I'm checking on current support for this feature for customer accounts and will post updates here. Thanks again for your feedback.

**Comment by msmimart** [comment]
@MrHinsh I appreciate you pointing this out. We created an internal work item to track the feature work and documentation updates that will need to be made. I'll go ahead and close out this GitHub issue, but feel free to add a comment if you have more info or feedback. Thanks again! #please-close
