### ISSUE TITLE
The wrong type of certificate is mentioned in point 7

### ISSUE THREAD

**Issue by roelrulezz** [MicrosoftDocs/entra-docs#820]
Point 7 indicates that the 'Certificate (Base64)' must be used, but the image indicates that 'PEM certificate download' must be used. If the Base64 certificate is used in Github Enterprise, you will receive an error message and if the PEM certificate is used, it works. Please adjust in the description that the PEM certificate must be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b718882-4334-9eab-a83a-76023d0ec2b2
* Version Independent ID: b8b7ca3b-8373-382d-00f1-06ca3a9c60fa
* Content: [Tutorial: Microsoft Entra single sign-on (SSO) integration with GitHub Enterprise Managed User - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/saas-apps/github-enterprise-managed-user-tutorial)
* Content Source: [docs/identity/saas-apps/github-enterprise-managed-user-tutorial.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/saas-apps/github-enterprise-managed-user-tutorial.md)
* Service: **entra-id**
* Sub-service: **saas-apps**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by PesalaPavan** [comment]
@roelrulezz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@roelrulezz 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by Harshita-130901** [comment]
@roelrulezz, we're creating a separate PR for your changes in our private repo, you may expect the updated doc within 2-3 working days.

#please-close
