### ISSUE TITLE
Diagram Product Name Incorrect

### ISSUE THREAD

**Issue by dingovvarrior** [MicrosoftDocs/entra-docs#821]
Diagram refers to On Premises Microsoft Entra. Suspect this should say Active Directory On Premises, which could cause confusion?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86ed5438-9076-fa6f-d42a-e9bef29beb6e
* Version Independent ID: f6490079-8f4a-f621-623b-d500b52abef8
* Content: [What is Microsoft Entra Connect and Connect Health. - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/whatis-azure-ad-connect)
* Content Source: [docs/identity/hybrid/connect/whatis-azure-ad-connect.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/whatis-azure-ad-connect.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@dingovvarrior 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@dingovvarrior 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by billmath** [comment]
@dingovvarrior thanks for catching this.  This has been fixed.  If you see any additional ones, let us know.  Thanks!

#please-close
