### ISSUE TITLE
Entra ID Cloud Sync Users?

### ISSUE THREAD

**Issue by tonycaidotcom** [MicrosoftDocs/entra-docs#822]
Will the ability to Cloud Sync users down to AD come soon?

Any API support to set this process up?

**Comment by PesalaPavan** [comment]
@tonycaidotcom 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by PesalaPavan** [comment]
@tonycaidotcom 
We are going to close this thread but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
