### ISSUE TITLE
Android Authenticator

### ISSUE THREAD

**Issue by Infinitecupcakes** [MicrosoftDocs/entra-docs#823]
This article states that Fido 140-3 on Android is currently in process, but multiple internal sources list it as compliant. Please resolve.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 542a9166-8457-dc1d-cfa4-850380480249
* Version Independent ID: 685603d9-f03d-8926-97bd-8ae25c80a622
* Content: [Microsoft Authenticator authentication method - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-authentication-authenticator-app#fips-140-compliant-for-microsoft-entra-authentication)
* Content Source: [docs/identity/authentication/concept-authentication-authenticator-app.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-authentication-authenticator-app.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@Infinitecupcakes 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Justinha** [comment]
@Infinitecupcakes Thanks for raising this. I confirmed Android is not yet compliant. You can email me directly justinha@microsoft.com for details about the internal sources. #please-close
