### ISSUE TITLE
No examples, very poor documentation

### ISSUE THREAD

**Issue by nik-lazer** [MicrosoftDocs/entra-docs#825]
All the ClaimsTransformation functions at the are poorly documented, so that they cannot be used for setting custom claims via power shell. I have never seen so horrible documentation. [My request](https://github.com/MicrosoftDocs/entra-docs/issues/816) for more examples was totally ignored. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c350829-8476-71a7-f53b-6cf788917037
* Version Independent ID: fbab99b8-0e94-1075-cb38-11a972feba87
* Content: [Customize SAML token claims - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/saml-claims-customization)
* Content Source: [docs/identity-platform/saml-claims-customization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/saml-claims-customization.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by PesalaPavan** [comment]
@nik-lazer 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@nik-lazer 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by nik-lazer** [comment]
Hello, I can just copy the content from my previous ticket:
I am working on customizing my claim tokens and need to apply [ifEmpty function](https://learn.microsoft.com/en-us/entra/identity-platform/saml-claims-customization) for that. The description says that I need to provide one input parameter and two output parameters:
Outputs an attribute or constant if the input is null or empty. For example, if you want to output an attribute stored in an extension attribute if the employee ID for a given user is empty. To perform this function, configure the following values: Parameter 1(input): user.employeeid Parameter 2 (output): user.extensionattribute1 Parameter 3 (output if there's no match): user.employeeid

I tried the following:
{ "ClaimsMappingPolicy": { "Version": 1, "IncludeBasicClaimSet": "true", "ClaimsSchema": [ { "Source": "application", "ID": "objectid", "JwtClaimType": "prn1" }, { "Source": "user", "ID": "userprincipalname", "JwtClaimType": "prn2" }, { "Source": "transformation", "TransformationID": "userOrApp", "ID": "collibrasub", "JwtClaimType": "prn" }, { "Source": "user", "ID": "usertype", "JwtClaimType": "prn31" }, { "Source": "application", "ID": "displayname", "JwtClaimType": "prn41" } ], "ClaimsTransformations": [ { "ID": "userOrApp", "TransformationMethod": "IfEmpty", "InputClaims": [ { "ClaimTypeReferenceId": "userprincipalname", "TransformationClaimType": "inputClaim1" }, { "ClaimTypeReferenceId": "objectid", "TransformationClaimType": "inputClaim2" }, { "ClaimTypeReferenceId": "usertype", "TransformationClaimType": "inputClaim3" } ], "OutputClaims": [ { "ClaimTypeReferenceId": "collibrasub", "TransformationClaimType": "outputClaim" } ] } ] } }

but I cannot figure out how the JSON definition has to be written to do it properly. Could you please give more details?

**Comment by nik-lazer** [comment]
The only examples in JSON format I was able to find [here](https://learn.microsoft.com/en-us/entra/identity-platform/claims-customization-powershell#use-a-claims-transformation-in-tokens). Unfortunately it is only for simple functions and ones with 3 parameters.

I would appreciate some examples  with complex functions such ifEmpty

**Comment by cilwerner** [comment]
We are in the process of transferring to a new unified user feedback system. This issue is being triaged and added to the backlog where it will be addressed in an upcoming sprint.

#please-close
