### ISSUE TITLE
Misleading information in security defaults documentation

### ISSUE THREAD

**Issue by M-Borer** [MicrosoftDocs/entra-docs#826]
The page falsely claims that security defaults can be disabled. However, Microsoft Entra will enable security defaults on its own.
If an option is ignored it is not an option at all.

Please update the docs to match the service provided or update the sevice to match its documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfac0ecf-e5a9-c5ff-f8c2-ce27789708f5
* Version Independent ID: 0f5e0cc9-a54f-a5c8-192d-d60a6a4db3ff
* Content: [Providing a default level of security in Microsoft Entra ID - Microsoft Entra](https://learn.microsoft.com/en-us/entra/fundamentals/security-defaults)
* Content Source: [docs/fundamentals/security-defaults.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/fundamentals/security-defaults.md)
* Service: **entra**
* Sub-service: **fundamentals**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@M-Borer 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@M-Borer 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
You can disable security defaults this is accurate still. #please-close
