### ISSUE TITLE
Tutorial instructs user to create a Windows Server 2016 VM. Should update to 2022.

### ISSUE THREAD

**Issue by scarson** [MicrosoftDocs/entra-docs#830]
In the "Create a Windows Server virtual machine" section, step 2 is "From **Get started**, choose **Windows Server 2016 Datacenter**." followed by a screenshot highlighting "Windows Server 2016 Datacenter" in the Azure Marketplace.

The tutorial should point users to a Windows Server OS that isn't 8 years old and coming up on end of support.

Nothing in the page besides that line and the Azure Marketplace screenshot immediately below have anything to do with Server 2016 specifically.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 038b3b50-317c-c0c1-cbee-c69f3f828f84
* Version Independent ID: 93810ce3-0817-c221-beb4-35de3f40d43e
* Content: [Join a Windows Server VM to a Microsoft Entra Domain Services managed domain - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/domain-services/join-windows-vm)
* Content Source: [docs/identity/domain-services/join-windows-vm.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/domain-services/join-windows-vm.md)
* Service: **entra-id**
* Sub-service: **domain-services**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@scarson Thanks for raising this! Revised to simply say choose a version of Windows Server. #please-close
