### ISSUE TITLE
Updating the public facing documentation indicating that the workbooks approach to ADAL visibility is no longer supported

### ISSUE THREAD

**Issue by BVictor535** [MicrosoftDocs/entra-docs#831]
[Enter feedback here]

Customers expecting these changing to be applied on the MS public facing Microsoft documentations - 
 
updating the signins workbook removing the ADAL option as it is no longer considered accurate.
updating their public facing documentation indicating that the workbooks approach to ADAL visibility is no longer supported. The document (Get a complete list of apps using ADAL in your tenant: https://learn.microsoft.com/en-us/entra/identity-platform/howto-get-list-of-all-auth-library-apps#step-3-identify-apps-that-use-adal) still references this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78002fb8-97c4-a4d0-a753-c5beda889457
* Version Independent ID: 5bad7377-c352-10f6-7748-a6eed9ee6a37
* Content: [How to: Get a complete list of all apps using Active Directory Authentication Library (ADAL) in your tenant - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/howto-get-list-of-all-auth-library-apps)
* Content Source: [docs/identity-platform/howto-get-list-of-all-auth-library-apps.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/howto-get-list-of-all-auth-library-apps.md)
* Service: **identity-platform**
* GitHub Login: @SHERMANOUKO
* Microsoft Alias: **shermanouko**

**Comment by SaibabaBalapur-MSFT** [comment]
@BVictor535 Thanks for helping here, particularly showing where to find the correct steps. I'm going to assign this to the document author so they can take a look at it accordingly.

@SHERMANOUKO
Can you please check and add your comments on this doc update request as applicable.

**Comment by SHERMANOUKO** [comment]
@BVictor535 thanks for the feedback. We'll look into this and update the doc as appropriate.

**Comment by SHERMANOUKO** [comment]
#please-close
