### ISSUE TITLE
Fayez alzahrani

### ISSUE THREAD

**Issue by Zahrafa302** [MicrosoftDocs/entra-docs#832]
I need to confirm my LinkedIn account

**Comment by Zahrafa302** [comment]
I need to confirm my LinkedIn account

**Comment by TPavanBalaji** [comment]
@Zahrafa302 
It looks like your issue is resolved since you closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
