### ISSUE TITLE
Code is invalid at section "Check the expiration policy for a password"

### ISSUE THREAD

**Issue by howe-ver-atwork** [MicrosoftDocs/entra-docs#834]
Hi guys. 

I would like to report a non-working issue in the article [Password policies and account restrictions in Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-policy#check-the-expiration-policy-for-a-password)

In the highlight section, the following code is given to evaluate all users from the tenant whether they are set as PasswordNeverExpires.
`Get-MgUser -All | Select-Object UserPrincipalName, @{N="PasswordNeverExpires";E={$_.PasswordPolicies -contains "DisablePasswordExpiration"}}`

Unfortunately, this will only return the result that all user have the **FALSE** value for the evaluation.
![f7b1c9db-39e5-42a4-88a6-7f490801147c](https://github.com/MicrosoftDocs/entra-docs/assets/152940955/b563e683-87d0-4313-8b30-b2f9349e510d)

I suspect that there is a missing scope `-Property UserPrinciplalName , PasswordPolicies`, so when the value import to the pipeline, there were no values were being evaluated. So the powershell will return False value for every user in the tenant.

After adding these parameters in front of the pipeline, result seems fine.
![image](https://github.com/MicrosoftDocs/entra-docs/assets/152940955/eb9e50b6-7603-4151-b9a5-6015547824e7)

Besides, in the M365 doc [Set an individual user's password to never expire](https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/set-password-to-never-expire?view=o365-worldwide#how-to-check-the-expiration-policy-for-a-password)
, they also use the parameters I mentioned above.

Please check if there is a mistype in this! Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1765376-03c9-829a-9e42-e72cc8a0daea
* Version Independent ID: 684c7d7c-09f4-8170-6f7a-132b2d79e1df
* Content: [Self-service password reset policies - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-sspr-policy#check-the-expiration-policy-for-a-password)
* Content Source: [docs/identity/authentication/concept-sspr-policy.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-sspr-policy.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@howe-ver-atwork 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @howe-ver-atwork 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated! If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
