### ISSUE TITLE
No instructions on how to apply ck_exclude_from_pci tag

### ISSUE THREAD

**Issue by festivus** [MicrosoftDocs/entra-docs#837]
There are no instructions on how to do the following:

For expected super identities, such as infrastructure admins, use the ck_exclude_from_pci and ck_exclude_from_reports tags.
ck_exclude_from_pci tag removes the identity from the authorization system’s PCI score calculation
ck_exclude_from_reports tag removes the identity from the Permissions Analytics Report, so it isn't called out as a super identity

How do we apply these tags? I can't find documentation on applying tags to users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cadc829a-df6d-72e8-94b8-bd9f2af9f679
* Version Independent ID: cadc829a-df6d-72e8-94b8-bd9f2af9f679
* Content: [Phase 2 Right-size permissions and automate the principle of least privilege by using Microsoft Entra Permissions Management - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/permissions-manage-ops-guide-two)
* Content Source: [docs/architecture/permissions-manage-ops-guide-two.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/permissions-manage-ops-guide-two.md)
* Service: **entra**
* GitHub Login: @jricketts
* Microsoft Alias: **jricketts**

**Comment by TPavanBalaji** [comment]
@festivus 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@festivus 
I'm going to assign this to the document author so they can take a look at it accordingly.

@janicericketts 
Can you please check and add your comments on this doc update request as applicable.

**Comment by CelesteDG** [comment]
@janicericketts Please migrate this feedback to ADO for tracking ASAP. We're changing feedback mechanism from GH issues to UUF and ADO tracking.

CC @martincoetzer

**Comment by janicericketts** [comment]
Thank you for your feedback. We will consider your request in a future update of the article. #please-close
