### ISSUE TITLE
Wrong deprecation date under the "Important" box, correct year is 2025

### ISSUE THREAD

**Issue by darrenCampos** [MicrosoftDocs/entra-docs#839]
[Enter feedback here]
Please update the first blue important box with the correct deprecation date of September 30, 2025, currently the page shows the wrong date as September 30, 2024

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cacc043b-aeec-5deb-e60f-b11e6381b0ba
* Version Independent ID: aa2be87c-296f-b3ff-9549-4407c46746d4
* Content: [Enable Microsoft Entra self-service password reset - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/tutorial-enable-sspr)
* Content Source: [docs/identity/authentication/tutorial-enable-sspr.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/tutorial-enable-sspr.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@darrenCampos thanks for raising this! Fixing now and update will appear tomorrow morning PST.

**Comment by TPavanBalaji** [comment]
@darrenCampos 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by Justinha** [comment]
@darrenCampos thanks for catching this! Fixed now. #please-close
