### ISSUE TITLE
Unable to create policy as per instructions.

### ISSUE THREAD

**Issue by zrivkis** [MicrosoftDocs/entra-docs#841]
The instructions recommend to include **all users**. When creating a policy that includes all users, all apps, device code flow and the action is **block**, the policy cannot be created as the error message "The configured policy will block all users, so it is not supported..." is displayed.

When creating the initial policy, you are presented with an option to either exclude the current user or "I understand that my account will be impacted...". If you select the latter, the policy still cannot be created.

The only way to create a policy is to exclude the user who is creating the original policy resulting in always having one user who is excluded from enforcement.
![OUTLOOK_1HiG6OuTBT](https://github.com/MicrosoftDocs/entra-docs/assets/66017948/ec1d744c-fb2c-4627-8050-8759f20ba69c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0710a99-ef99-1cff-c29f-6527e432a47d
* Version Independent ID: b0710a99-ef99-1cff-c29f-6527e432a47d
* Content: [Block authentication flows with Conditional Access policy - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/how-to-policy-authentication-flows?WT.mc_id=M365-MVP-9501)
* Content Source: [docs/identity/conditional-access/how-to-policy-authentication-flows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/how-to-policy-authentication-flows.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@zrivkis 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@zrivkis 
Thank you for bringing this to our attention.
I've delegated this to content author @MicrosoftGuyJFlo, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for the feedback. Working on a PR and will update this to include the emergency access/break glass example.

#please-close
