### ISSUE TITLE
404 on samples link

### ISSUE THREAD

**Issue by msft-raj** [MicrosoftDocs/entra-docs#842]
In the SPA section on Angular, none of the links work - all throw 404s. Also many links point to archived pages - not sure if intentional.

My microsoft alias is rbiswas@ if you need to reach out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b90331e5-cca5-b157-eaa1-6f8f90003b32
* Version Independent ID: 4b1b803d-e30d-10b2-90a1-3f0ccd8d7d44
* Content: [Code samples for Microsoft identity platform authentication and authorization - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/sample-v2-code?tabs=apptype)
* Content Source: [docs/identity-platform/sample-v2-code.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/sample-v2-code.md)
* Service: **identity-platform**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by TPavanBalaji** [comment]
@msft-raj 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@msft-raj 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by OwenRichards1** [comment]
@msft-raj Thanks for raising this - this was part of a code sample curation effort, please see the updated code sample page with the broken links removed! 

#please-close
