### ISSUE TITLE
Request for update | Table of FIDO2 security key vendors

### ISSUE THREAD

**Issue by vcommuri** [MicrosoftDocs/entra-docs#843]
Hi, I'm writing to you from Precision Biometric. May I request you to kindly help update 'Precision Biometric' 's entry in the table of FIDO2 security key vendors - indicating NFC support also please? We provide FIDO2 certified Biometric keys as well as NFC keys.

Have attached the certificate too, as evidence and for ready reference.

Thank you for your help.

Regards
Venkatesh

[FIDO2 CTAP2.0 L2 Delta Certificate Precision PK2100 FIDO20020230509003.pdf](https://github.com/MicrosoftDocs/entra-docs/files/15401183/FIDO2.CTAP2.0.L2.Delta.Certificate.Precision.PK2100.FIDO20020230509003.pdf)

![image](https://github.com/MicrosoftDocs/entra-docs/assets/164010235/46392168-6e83-4ba2-a25e-49dbe38db736)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2494bd0-3d61-f686-8a8e-fbbee3ca8b38
* Version Independent ID: cdb3d225-2df6-5766-b45d-f9ba5c7e19e1
* Content: [Become a Microsoft-Compatible FIDO2 Security Key Vendor for sign-in to Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-hardware-vendor)
* Content Source: [docs/identity/authentication/concept-fido2-hardware-vendor.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-fido2-hardware-vendor.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@vcommuri 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Justinha** [comment]
@vcommuri I added NFC support. Thanks again for catching this! Change will appear in about 3 hours or so. #please-close
