### ISSUE TITLE
No code in ms-identity-java-webapp-main

### ISSUE THREAD

**Issue by infobrixGit** [MicrosoftDocs/entra-docs#845]
[Enter feedback here]
The zip has read me file and default maven jars . No java files. Is that the expectation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4fbf8db-0fda-5d9d-a002-c61e7cb2f9c4
* Version Independent ID: b59cb021-3843-3331-01ad-adc7b7c0b047
* Content: [Quickstart: Sign in users and call the Microsoft Graph API from a Java web app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-web-app-java-sign-in)
* Content Source: [docs/identity-platform/quickstart-web-app-java-sign-in.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/quickstart-web-app-java-sign-in.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by TPavanBalaji** [comment]
@infobrixGit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @infobrixGit 
The `ms-identity-java-webapp-main` repository on GitHub is a template repository that contains the basic structure and configuration files for a Java web application that uses Microsoft Identity Platform for authentication and authorization. It does not contain any Java code or implementation details.

To create a Java web application that uses Microsoft Identity Platform, you can follow the steps outlined in the tutorial you referenced. The tutorial provides step-by-step instructions for creating a new Java web application project, adding the necessary dependencies, and configuring the application to use Microsoft Identity Platform for authentication and authorization.

Once you have completed the tutorial, you can use the `ms-identity-java-webapp-main` repository as a starting point for your own Java web application project. You can clone the repository and modify the files to fit your specific needs.

I hope this helps clarify the purpose of the `ms-identity-java-webapp-main` repository. If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@infobrixGit 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
