### ISSUE TITLE
Get-MgGroup not consistent

### ISSUE THREAD

**Issue by D-Loz** [MicrosoftDocs/entra-docs#847]
For consistency and to follow the instructions Get-MgGroup  should read Get-MgBetaGroup as they might only have beta installed as per the instructions to install graph beta (under the section "Enable staged rollout to test user sign-in with an email address")

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2d44d9-f737-c619-a0b9-cf48755cd2ca
* Version Independent ID: 2b6d043e-52fd-d066-d599-3eff99c47756
* Content: [Sign-in to Microsoft Entra ID with email as an alternate login ID - Microsoft Entra ID](https://learn.microsoft.com/en-gb/entra/identity/authentication/howto-authentication-use-email-signin?WT.mc_id=Portal-Microsoft_AAD_IAM)
* Content Source: [docs/identity/authentication/howto-authentication-use-email-signin.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-use-email-signin.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @calui
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@D-Loz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@D-Loz 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by huypub** [comment]
@PesalaPavan 
I am not the author. I reassign it to the author: @Justinha

**Comment by Justinha** [comment]
@PesalaPavan @D-Loz thanks for catching this! I submitted the fix. #please-close
