### ISSUE TITLE
Unlimited app creations: Incorrect permission in screenshot is misleading.

### ISSUE THREAD

**Issue by madansr7** [MicrosoftDocs/entra-docs#849]
Step #5 in the following doc asks the user to add 'microsoft.directory/applicatoins/create' permission. 
However, the screenshot shows 'microsoft.directory/application**Policies**/create' permission. The user is looking at the screenshot and adding the permission, which does not yield the desired results. 

https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/quickstart-app-registration-limits
![image](https://github.com/MicrosoftDocs/entra-docs/assets/31744939/608b4de6-fead-4e30-83ea-8207d2230498)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d59b2783-b3e8-1505-2cb2-ae0a3516e56f
* Version Independent ID: b265a449-4571-17c8-1acc-c3f20b6d093b
* Content: [Remove limits on creating app registrations - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/quickstart-app-registration-limits)
* Content Source: [docs/identity/role-based-access-control/quickstart-app-registration-limits.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/quickstart-app-registration-limits.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@madansr7 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@madansr7 
Thank you for bringing this to our attention.
I've delegated this to content author @rolyon, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@rolyon 
Please review it and update as appropriate.

**Comment by rolyon** [comment]
Hi @madansr7 
Thanks for noticing this. We have updated the screenshot. It will appear for the next doc publish.
thanks

**Comment by rolyon** [comment]
#please-close
