### ISSUE TITLE
Hard match or hard-match?

### ISSUE THREAD

**Issue by ricklarsen** [MicrosoftDocs/entra-docs#85]
In https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-existing-tenant, is `Hard Match` hyphenated or not? It appears both ways in the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4e9fbe-6e36-cfee-994a-91578b8a0683
* Version Independent ID: c3d29ce2-2620-328c-c45c-6f01d3cb71ec
* Content: [Microsoft Entra Connect: When you already have Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-existing-tenant)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-install-existing-tenant.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-install-existing-tenant.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by SaibabaBalapur-MSFT** [comment]
@ricklarsen 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@ricklarsen 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
