### ISSUE TITLE
Possibly expand the password reset table a little further?

### ISSUE THREAD

**Issue by msftmarysisko** [MicrosoftDocs/entra-docs#850]
I'm an SE who had a case in which the customer was a user admin and they could not view the auth methods or change the password for a security reader. Would security admins fall under one of the already listed categories or could we add a section for them?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb28e967-b483-087e-6060-227289c817e1
* Version Independent ID: 8dc8c4dd-e937-cf14-d12a-f2718042f1a2
* Content: [Privileged roles and permissions in Microsoft Entra ID (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/privileged-roles-permissions?tabs=admin-center#who-can-reset-passwords)
* Content Source: [docs/identity/role-based-access-control/privileged-roles-permissions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/privileged-roles-permissions.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@msftmarysisko 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@rolyon 
I'm going to assign this to the document author so they can take a look at it accordingly.

@msftmarysisko 
Can you please check and add your comments on this doc update request as applicable.

**Comment by rolyon** [comment]
Hi @msftmarysisko 
Thanks for your feedback. We've sent your feedback to the team about including the Security Administrator role in the Who can reset passwords table. We created a work item to track.
We are migrating to a new doc feedback tool, so we will close this GitHub issue. Let us know if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close
