### ISSUE TITLE
Need link to the group provisioning scenario doc

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#854]
This main page for group provisioning has a section on scoping but is missing a link to the crucial "Scenario - Using directory extensions with group provisioning to Active Directory" https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/tutorial-directory-extension-group-provisioning.

The section "Scope provisioning to specific groups" in step 5 should include one more link there to the Scenario doc.  The Scenario doc is hard to discover as none of the main document pages that cover scoping link to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba290a8-7b6e-a859-4f4d-70ea2d035424
* Version Independent ID: 1ba290a8-7b6e-a859-4f4d-70ea2d035424
* Content: [Configure - Provisioning Microsoft Entra ID to Active Directory using Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-configure-entra-to-active-directory.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by billmath** [comment]
David this is going in today and should be live later.  Thanks!

#please-close
