### ISSUE TITLE
Need link to the group provisioning scenario doc

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#855]
This main page for group provisioning scoping is missing a link to the crucial "Scenario - Using directory extensions with group provisioning to Active Directory" https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/tutorial-directory-extension-group-provisioning.

The section "Attribute scope filtering" should include a link there to the Scenario doc.  The Scenario doc is hard to discover as none of the main document pages that cover scoping link to it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10553754-e8fd-c93b-6a87-e204a16b97a3
* Version Independent ID: 10553754-e8fd-c93b-6a87-e204a16b97a3
* Content: [Attribute mapping - Microsoft Entra ID to Active Directory - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/how-to-attribute-mapping-entra-to-active-directory)
* Content Source: [docs/identity/hybrid/cloud-sync/how-to-attribute-mapping-entra-to-active-directory.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/how-to-attribute-mapping-entra-to-active-directory.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @dloder0 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
