### ISSUE TITLE
Leftover copy-paste sentences

### ISSUE THREAD

**Issue by dloder0** [MicrosoftDocs/entra-docs#856]
In the section "Create the CloudSyncCustomExtensionApp and service principal", steps 8 and 9 both end with a leftover sentence fragment "If you just created the app"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc45cfd9-188f-fdbf-207f-b9d8e11bc5ab
* Version Independent ID: bc45cfd9-188f-fdbf-207f-b9d8e11bc5ab
* Content: [Scenario - Using directory extensions with group provisioning to Active Directory - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/tutorial-directory-extension-group-provisioning)
* Content Source: [docs/identity/hybrid/cloud-sync/tutorial-directory-extension-group-provisioning.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/tutorial-directory-extension-group-provisioning.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@dloder0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@dloder0 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
