### ISSUE TITLE
Need to document how to revoke consent

### ISSUE THREAD

**Issue by Rick-Kirkham** [MicrosoftDocs/entra-docs#857]
The Office Add-in developer docs would like to link to the **Admin consent button** section of this article to avoid duplicating documentation. But we have a customer request to document how to **revoke** admin consent too. So, it makes sense to put that documentation in this article too. (I can find no other place in your docs where it would go.) 

I don't seem to have permissions to create a PR, so I'm making this an issue. 

Please put the following Markdown at the end of the **Admin consent button** section. It creates a subsection (level 4):

```
#### Revoke admin consent

To revoke consent for a permission, take the following steps:

1. In the **Configured permissions** table, go to the table row for the permission that you want to revoke and select the **...** button. 

1. On the menu that appears, select **Remove permission**. 

1. Repeat the last two steps for every permission that you want to revoke.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 006699d8-d208-ec2e-9b14-ec6c5d4bd71f
* Version Independent ID: b9ad346f-2140-8d7b-c5aa-b5e4d7bae866
* Content: [Quickstart: Configure an app to access a web API - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-configure-app-access-web-apis)
* Content Source: [docs/identity-platform/quickstart-configure-app-access-web-apis.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/quickstart-configure-app-access-web-apis.md)
* Service: **identity-platform**
* GitHub Login: @cilwerner
* Microsoft Alias: **cwerner**

**Comment by TPavanBalaji** [comment]
@Rick-Kirkham 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@Rick-Kirkham 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by Rick-Kirkham** [comment]
@cilwerner How can I "follow" or subscribe to this item in the backlog. I have a work item that is dependent on it.
