### ISSUE TITLE
[Azure Government] Specify that endpoint needs to be changed for PS cmdlet when requesting access token for sovereign clouds

### ISSUE THREAD

**Issue by calebberning** [MicrosoftDocs/entra-docs#859]
Modify MS Documentation - https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/tutorial-windows-vm-access-nonaad

Add note bubble that mentions changing the endpoint for sovereign clouds. 

In PS cmdlet calling ‘vault.azure.net’ (commercial endpoint) and not ‘vault.usgovcloudapi.net’ (gcc-h endpoint). 
$Response = Invoke-RestMethod -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net' -Method GET -Headers @{Metadata="true"}

Vs.

$Response = Invoke-RestMethod -Uri 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.usgovcloudapi.net' -Method GET -Headers @{Metadata="true"}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 294128ee-aa91-8f63-f2e1-04b1ec5db5bc
* Version Independent ID: 681f180d-73a6-0388-a49f-6b3cba481cf9
* Content: [Tutorial: Use a managed identity to access Azure Key Vault - Windows - Managed identities for Azure resources](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/tutorial-windows-vm-access-nonaad)
* Content Source: [docs/identity/managed-identities-azure-resources/tutorial-windows-vm-access-nonaad.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/managed-identities-azure-resources/tutorial-windows-vm-access-nonaad.md)
* Service: **entra-id**
* Sub-service: **managed-identities**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@calebberning 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@calebberning 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
