### ISSUE TITLE
Unclear how to leave a business org 

### ISSUE THREAD

**Issue by manuelra** [MicrosoftDocs/entra-docs#86]
### Scenario

- Using an hotmail.com email address
- Created an Azure Account & had also been granted access to business Azure accounts

Instructions within section "What organizations do I belong to?" do not work as described. Below I document the identified problems for three alternative values of tenantId:

1. If `tenantId` is not included within `https://myacount.microsoft.com` then hotmail.com user is not able to login 

2. If `tenantId` is used within `https://myacount.microsoft.com?tenantId=` with `tenantId` of Azure susbscrition for which hotmail.com user is a global admin, then:

- **Overview** section only displays a truncated username (not person name) on top of left pane menu and not on the user details panel within the overview page.
- (contrary to what is stated within page) **Organizations** section does not present business tenants
- (contrary to what is stated within page) **Organizations** section presents hotmail.com directory, as Default Directory, and showing user is signed in, BUT also presents "Leave" link (I did not try to leave as this could imply loss of access to my Azure Subscription)

3. If `tenantId ` is used within `https://myacount.microsoft.com?tenantId=` with `tenantId` of Azure susbscription which hotmail.com user intends to leave then user is able to login, and Organizations section presents tenant that user intends to leave (but not tenant which is global admin), and user is able to Leave that organization. 

Furthermore:

- the above description applies to the guid based tenantID, but does not work similarly with the qualified name tenantId
- the page could mention that tenantId can be identified by using Manage tenants page within Azure Portal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b448cfd0-b673-7d04-047b-71aa62bebc27
* Version Independent ID: 75118bff-94de-c9f9-7666-d2a6f4253b11
* Content: [Leave an organization as a guest user - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/leave-the-organization)
* Content Source: [docs/external-id/leave-the-organization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/leave-the-organization.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @csmulligan
* Microsoft Alias: **cmulligan**

**Comment by SaibabaBalapur-MSFT** [comment]
@manuelra 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@manuelra 

I'm sorry to hear that you are experiencing issues with leaving an organization in Azure using a hotmail.com email address.

Regarding the instructions in the "What organizations do I belong to?" section, it is possible that the documentation is outdated or incomplete. I apologize for any confusion this may have caused.

To leave an organization in Azure, you can follow these steps:

Sign in to the Azure portal using your hotmail.com email address.
Navigate to the "Azure Active Directory" section of the portal.
Click on "Users" and then select your user account.
Click on "Leave organization" in the "Organizations" section of the user details page.
Follow the prompts to confirm that you want to leave the organization.
If you are not seeing the correct organizations listed in the "Organizations" section, it is possible that there is an issue with your account or the Azure subscription. I'd recommend posting your question in https://azure.microsoft.com/en-us/support/community/. 

Regarding the use of the tenantId parameter in the URL, it is possible that the documentation is incomplete or outdated. I recommend using the Azure portal to manage your Azure Active Directory organizations and subscriptions, as this should provide the most up-to-date and accurate information.

If you have any further questions or concerns, please let me know and I will do my best to assist you further.

**Comment by manuelra** [comment]
Dear Ajay,

 

I submitted the feedback after being able to leave the organizations with which I no longer collaborate, using a variation of what is that described within the page I provided feedback on (the differences within the variation I used are the ones I described).

 

Except for asking feedback to the community, I tried the steps you proposed on your list before submitting my feedback, and they did not work. Also note that Azure Active Directory is now Microsoft Entra Id <https://learn.microsoft.com/en-us/entra/fundamentals/new-name> .

 

I am sad to see that although I took the time to figure out + document the exact aspects of what was misaligned / erroneous within the documentation (or product), those details are being considered a request for help to resolve my configuration, instead of being leveraged by you to improving Azure’s documentation and/or product. 

 

Best regards,

Manuel Rebello de Andrade

Mobile:   +351 911 076 696 <tel:%2B351%20911%20076%20696> 

***@***.***

**Comment by AjayBathini-MSFT** [comment]
@manuelra 
 I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by csmulligan** [comment]
@manuelra thank you for passing along your workaround for this scenario. We've opened an internal work item to add this to the next revision of the article. Because we're now tracking this internally, I'll close the issue. Thanks again for helping us improve the documentation!
#please-close
