### ISSUE TITLE
The link "Configuring SAML-based single sign-on for non-gallery applications" points to a page using gallery applications

### ISSUE THREAD

**Issue by edwardgaoyb** [MicrosoftDocs/entra-docs#865]
The link text says "Configuring SAML SSO for **non-gallery** applications", but the linked page used a **gallery** application. This is an obvious error, and the document is supposed to tell the readers how to create their own applications for SAML SSO. 

The correct link might be: https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/overview-application-gallery#create-your-own-application

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad11b236-1f86-c5e1-36ab-ede236b3d44a
* Version Independent ID: 832cabb7-8585-5d6f-e358-dda7b09cd6d2
* Content: [SAML authentication with Microsoft Entra ID - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/auth-saml)
* Content Source: [docs/architecture/auth-saml.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/auth-saml.md)
* Service: **entra**
* Sub-service: **architecture**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by TPavanBalaji** [comment]
@edwardgaoyb 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@edwardgaoyb 

In Microsoft enterprise applications there are some applications in the gallery those are gallery applications but some are need to search those are non-gallery applications.
There are number of ways to choose the applications either from Gallery or from Non-Gallery.
The Azure Active Directory (Azure AD) application gallery has SaaS applications that have been pre-integrated with Azure AD. There are thousands of applications that make it easy to deploy and configure SSO and automated user provisioning.
There are many applications which are still not in the gallery, and Azure AD allow you to create your own application or integrate any other application which is not part of the gallery to make a SAML based application.
As per providing document above, By integrating the application, the administrator can configure, secure, and monitor its use. This choice doesn’t provide a way to publish the application to the gallery. It does provide secure access to the application for users in your tenant.

**Comment by PesalaPavan** [comment]
@edwardgaoyb 
We are going to close this thread but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
