### ISSUE TITLE
Feedback for customer's actual testing is different from some points that the documentation mentions

### ISSUE THREAD

**Issue by Sandy66666666** [MicrosoftDocs/entra-docs#867]
Dear Author,

I am a support engineer who supports for Entra ID authentication. Recently we have met some cases that customer complains about the accuracy of our official documentation regarding passkeys. Really appreciate your any response or any suggestion regarding below points. 

1. Per our doc, it mentions that passkeys in Authenticator seems don't work on Android device, it also mentions Android does not support same device auth in a browser. But per my customer's testing, it is not that true, it did work at least on Edge. Is there any new update? 
https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-compatibility#web-browser-support
![image](https://github.com/MicrosoftDocs/entra-docs/assets/170903885/4f1b4ac0-0e2f-49a6-8fbb-685a9e0c752a)

https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-sign-in-passkey-authenticator?tabs=Android
![image](https://github.com/MicrosoftDocs/entra-docs/assets/170903885/d50c009e-f057-46d5-9a39-7332e0d50cdb)

2. Also, our doc mentions native app support for Fido2 not supported on Android yet, but my customer confirmed that it was working fine before. So, I 'd like to double confirm if it indeed not supported at all for native apps? 
Currently the behavior is that there is no security key sign in option when accessing native apps on Android. 
https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-compatibility#native-application-support
![image](https://github.com/MicrosoftDocs/entra-docs/assets/170903885/f30da972-8253-486e-9385-f988d1a81350)

BR,
Sandy
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9abd21e-a500-e23e-4a3f-fecaa77844b7
* Version Independent ID: f9abd21e-a500-e23e-4a3f-fecaa77844b7
* Content: [Support for FIDO2 authentication with Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-fido2-compatibility#web-browser-support)
* Content Source: [docs/identity/authentication/concept-fido2-compatibility.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-fido2-compatibility.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@Sandy66666666 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@Justinha 
Please review it, add your comments and update as appropriate.

**Comment by Justinha** [comment]
@Sandy66666666 thanks for raising this. A few others have reported similar experience, but we don't have official confirmation for Chrome just yet. We will update the docs when we get official word. Feel free to reach me directly if you would to discuss further. #please-close
