### ISSUE TITLE
Should the page mention Microsoft Entra External ID for Customers ?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [MicrosoftDocs/entra-docs#87]
Should the page mention Microsoft Entra External ID **for Customers** , even it is still in Preview ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed572d43-0c0e-4b91-7297-9d2158830575
* Version Independent ID: 6920706a-8de6-af57-7457-451171d53522
* Content: [Microsoft Entra External ID overview - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/external-identities-overview)
* Content Source: [docs/external-id/external-identities-overview.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/external-identities-overview.md)
* Service: **active-directory**
* Sub-service: **b2b**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by SaibabaBalapur-MSFT** [comment]
@michael-freidgeim-webjet 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@michael-freidgeim-webjet 
Thank you for bringing this to our attention.
I've delegated this to content author @msmimart, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@msmimart 
Could you please review add comments on this, update as appropriate.

**Comment by msmimart** [comment]
Hi @michael-freidgeim-webjet, updates to this page are underway and there we'll be incorporating the additional External ID features in the near future. Thanks again for your feedback! #please-close
