### ISSUE TITLE
Table "Authentication methods per encryption protocol" not up-to-date

### ISSUE THREAD

**Issue by stefandoh** [MicrosoftDocs/entra-docs#870]
In article it is given that following support matrix for Entra authentication methods upon encryption protocol is used:

> - Not all encryption protocols support all verification methods.
>    - **PAP** supports phone call, one-way text message, mobile app notification, and mobile app verification code
>    - **CHAPV2** and **EAP** support phone call and mobile app notification

However, setting up in a greenfield environment with obviously MS-CHAP-V2 as encryption protocol an mobile app verification code (MS Authenticator App OATH software token) is used.

Is there either an update to above by a curated list or is there even a way to tweak the Entra MFA extension for NPS Server?

**EDIT 2024-05-29:**

Is there either an update to above by a curated list or is there even a way **to force or remove usable authentication methods on the Entra MFA extension for NPS Server**?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a61a7e9a-44bf-7bdc-f810-87e2fd6792e1
* Version Independent ID: 71d11105-b83e-952e-d107-1ff9a7c8d107
* Content: [Use Microsoft Entra multifactor authentication with NPS - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-mfa-nps-extension)
* Content Source: [docs/identity/authentication/howto-mfa-nps-extension.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-mfa-nps-extension.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@stefandoh 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@stefandoh 
I'm going to assign this to the document author so they can take a look at it accordingly.

@Justinha 
Please review it.

**Comment by Justinha** [comment]
@stefandoh sorry for delay. Please contact Microsoft Support for help in this case. There's no further update for the topic pending from engineering. #please-close
