### ISSUE TITLE
Review of Known limitations is due?

### ISSUE THREAD

**Issue by DJHowellCA** [MicrosoftDocs/entra-docs#871]
The Known limitations section hasn't changed in a long time. I think this should be reviewed and updated, as hopefully some limitations are gone after review/testing. These two for sure should be reviewed:
- "The new Teams 2.1 preview client gets blocked after sign out due to a bug. This bug should be fixed in a future service update." - This client isn't Preview anymore - it is GA and the old Teams client will be out of support as of July 1, 2024. I'd sure hope this was fixed before going GA. My org is all new Teams client with a Token Protection CA policy on, and we've had no reports of this issue.
- "Windows-based Microsoft Teams Rooms (MTR) systems" - I submitted this originally as my org found it in our early testing. Now that MTRs have been upgraded to the new Teams client as of MTR v5.0.111.0 (see https://learn.microsoft.com/en-us/microsoftteams/rooms/rooms-release-note?tabs=Windows#501110-4242024), are they still unsupported? Someone should retest.

I also hope PowerQuery extension for Excel has been addressed or is on a backlog in the Excel team to be addressed soon. Please add a more specific status of it if not yet fixed, to acknowledge the Excel team will eventually deal with it.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec45091-ab65-7d9d-8915-26f5e56aa274
* Version Independent ID: 13a637da-8ded-72a0-464c-61efdef2a199
* Content: [Token protection in Microsoft Entra Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-token-protection)
* Content Source: [docs/identity/conditional-access/concept-token-protection.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-token-protection.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@DJHowellCA 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@DJHowellCA 
Thank you for your feedback! 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
