### ISSUE TITLE
CSV formatting has changed.

### ISSUE THREAD

**Issue by sofbkeller** [MicrosoftDocs/entra-docs#874]
The CSV download for this document has been updated in the last couple of days. There is a formatting error resulting in the  "Product_Display_Name" column being prepended with "???" when ingested with PowerShell. This is a _new issue_ and seems likely to be caused by an erroneous export or formatting bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by PesalaPavan** [comment]
@sofbkeller 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@Nicholak-MS
Can you please check and add your comments on this doc update request as applicable.

**Comment by Nicholak-MS** [comment]
Yes, I have a member of my team looking into this.

Thanks.

**Comment by sofbkeller** [comment]
Sorry, I should have added reproducibility steps.

This is the shortcut on the site to pull down the file:

![image](https://github.com/MicrosoftDocs/entra-docs/assets/107711487/d3bbe007-7a6e-4544-8848-52f0dc32a945)

This is the cmdlet I am using to pull down the file: 

`$licenseTable = (Invoke-WebRequest -Uri 'https://download.microsoft.com/download/e/3/e/e3e9faf2-f28b-490a-9ada-c6089a1fc5b0/Product%20names%20and%20service%20plan%20identifiers%20for%20licensing.csv' -UseBasicParsing).ToString() | ConvertFrom-Csv`


Expected result is:
```
Product_Display_Name               : Dynamics 365 for Team Members Enterprise Edition for Government
String_Id                             : DYN365_ENTERPRISE_TEAM_MEMBERS_GOV
GUID                                  : ba05762f-32ff-4fac-a096-55309b3700a3
Service_Plan_Name                     : FLOW_DYN_TEAM_GOV
Service_Plan_Id                       : 47bdde6a-959f-4c7f-8d59-3243e34f1cb3
```


What I am seeing is: 
```
???Product_Display_Name               : Dynamics 365 for Team Members Enterprise Edition for Government
String_Id                             : DYN365_ENTERPRISE_TEAM_MEMBERS_GOV
GUID                                  : ba05762f-32ff-4fac-a096-55309b3700a3
Service_Plan_Name                     : FLOW_DYN_TEAM_GOV
Service_Plan_Id                       : 47bdde6a-959f-4c7f-8d59-3243e34f1cb3

```

This only changed in this month. Prior to this it has worked for about 18 months.

**Comment by fruitninja3** [comment]
@sofbkeller I was unable to repro this with the latest version of the PS module. If you are still seeing this issue can you confirm your PS module version number.

**Comment by CelesteDG** [comment]
No additional response and no repro. Closing this issue.
