### ISSUE TITLE
Notifications for PIM for Groups

### ISSUE THREAD

**Issue by neok-g** [MicrosoftDocs/entra-docs#875]
I have the **eligable** owner role on tenant root group scope.

If someone activates an Azure resource role I receive a notification as it is documented for 'When a role activation request is completed' under section 'Notifications for Azure resource roles':

**Notifications for Azure resource roles**
Privileged Identity Management sends emails to Owners and User Access Administrators when the following events occur for Azure resource roles:

- When a role assignment is pending approval
- When a role is assigned
- When a role is soon to expire
- When a role is eligible to extend
- When a role is being renewed by an end user
- _**When a role activation request is completed**_

However for PIM group as an eligable Owner of the tenant root group I do not get any notifications when someone else activates the member of owner role despite the documentation:

**Notifications for PIM for Groups**
Privileged Identity Management sends emails to Owners only when the following events occur for PIM for Groups assignments:

- When an Owner or Member role assignment is pending approval
- When an Owner or Member role is assigned
- When an Owner or Member role is soon to expire
- When an Owner or Member role is eligible to extend
- When an Owner or Member role is being renewed by an end user
- **_When an Owner or Member role activation request is completed_**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5a932ce-6046-f6a9-9b85-188c8530174c
* Version Independent ID: 196cb921-fbf8-6819-e0e2-8cd03fda4505
* Content: [Email notifications in Privileged Identity Management (PIM) - Microsoft Entra ID Governance](https://learn.microsoft.com/en-us/entra/id-governance/privileged-identity-management/pim-email-notifications)
* Content Source: [docs/id-governance/privileged-identity-management/pim-email-notifications.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-governance/privileged-identity-management/pim-email-notifications.md)
* Service: **entra-id-governance**
* Sub-service: **privileged-identity-management**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@neok-g 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@neok-g 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@barclayn 
Please review it, and update document as appropriate.

**Comment by barclayn** [comment]
@neok-g Thank you for your feedback. We have created a work item to investigate and address. #please-close
