### ISSUE TITLE
Singular/ plural mismatch in phrase

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/entra-docs#876]
In the phrase:

“The resource owner can grant or deny your app (the client) access to the resources they own”

who is “they”?

(it seems it should be “he” or “she”, in singular, or “The resource owners”, in plural)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9abce49-5b87-65cf-8ef5-d3421619d535
* Version Independent ID: 25c74f8d-9265-cb29-a80c-eaff4cfc6ec3
* Content: [OAuth 2.0 and OpenID Connect protocols on the Microsoft identity platform - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols)
* Content Source: [docs/identity-platform/v2-protocols.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/v2-protocols.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by PesalaPavan** [comment]
@carlos-quintero 
Thanks for your feedback! We will investigate and update as appropriate.
