### ISSUE TITLE
Wrong information about the scope needed to change the authentication type for a domain

### ISSUE THREAD

**Issue by JK-MS1** [MicrosoftDocs/entra-docs#877]
[Enter feedback here]

To be able to convert a domain from Federated to Managed, the scope need to be  "Domain.ReadWrite.All", "Directory.AccessAsUser.All".

So the article need to be corrected as below : 

Connect-MGGraph -Scopes "Domain.ReadWrite.All", "Directory.AccessAsUser.All"
Update-MgDomain -DomainId "test.contoso.com" -BodyParameter @{AuthenticationType="Managed"}

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02c07bd2-01c5-77f4-11e0-6d942c5c0885
* Version Independent ID: f61490c2-0f18-4609-29f1-99ccb4215ad2
* Content: [Change subdomain authentication type using PowerShell and Graph - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/domains-verify-custom-subdomain)
* Content Source: [docs/identity/users/domains-verify-custom-subdomain.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/domains-verify-custom-subdomain.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@JK-MS1 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@JK-MS1 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
