### ISSUE TITLE
Enable non-azure Windows Server VMs to leverage Entra ID logons

### ISSUE THREAD

**Issue by HoCGeek** [MicrosoftDocs/entra-docs#88]
In the article you explain how to enable Entra ID login during the provisioning process. How do we do the same with on-premises VMs not provisioned through the Azure portal?  What needs to be installed, enabled, or configured in the server OS to enable Entra ID logins?

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c946fe0f-e18d-2529-2fbf-bce04759fbca
* Version Independent ID: 885a61d1-6096-5aa0-fe8d-f1ec8d55e542
* Content: [Log in to a Windows virtual machine in Azure by using Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/howto-vm-sign-in-azure-ad-windows)
* Content Source: [docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/howto-vm-sign-in-azure-ad-windows.md)
* Service: **active-directory**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by SaibabaBalapur-MSFT** [comment]
@HoCGeek 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@HoCGeek 

Thank you for your question.

To enable Azure AD sign-in for on-premises VMs that are not provisioned through the Azure portal, you can use Azure AD Connect to synchronize your on-premises Active Directory with Azure AD. This will allow you to use Azure AD credentials to sign in to your on-premises VMs.

Here are the high-level steps to enable Azure AD sign-in for on-premises VMs:

Install Azure AD Connect on a server in your on-premises environment.
Configure Azure AD Connect to synchronize your on-premises Active Directory with Azure AD.
Enable Azure AD Domain Services in your Azure AD tenant.
Join your on-premises VMs to the Azure AD Domain Services domain.
Configure the VMs to allow Azure AD sign-in.
For more detailed information on how to perform these steps, you can refer to the following documentation:

[Integrate your on-premises directories with Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-install-prerequisites)
[Azure AD Domain Services](https://docs.microsoft.com/en-us/azure/active-directory-domain-services/overview)
[Join a Windows VM to an Azure AD Domain Services managed domain](https://docs.microsoft.com/en-us/azure/active-directory-domain-services/manage-domain-join-windows-vm)
I hope this helps. Let me know if you have any further questions or concerns.
