### ISSUE TITLE
Authentication Administrator required to generate TAP

### ISSUE THREAD

**Issue by davidOFH** [MicrosoftDocs/entra-docs#882]
I believe the Entra role Authentication Administrator is required to generate a TAP. The page says that Authentication Policy Administrator is sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5eeab12d-7578-3f86-4461-10603274408b
* Version Independent ID: f4911928-14be-ecf6-0b02-cc80871ae365
* Content: [Configure a Temporary Access Pass in Microsoft Entra ID to register passwordless authentication methods - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-temporary-access-pass)
* Content Source: [docs/identity/authentication/howto-authentication-temporary-access-pass.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/howto-authentication-temporary-access-pass.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @tilarso
* Microsoft Alias: **justinha**

**Comment by PesalaPavan** [comment]
@davidOFH 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@davidOFH 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by MicrosoftGuyJFlo** [comment]
#reassign: @MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
The first section talks about enabling the policy and that requires at least Authentication Policy Administrator.

The second section is adding the TAP to a user and that requires at least Authentication Administrator.

#please-close
