### ISSUE TITLE
@De1gad0, we created a separate PR for your changes in our private repo by following the fixed format of our documentation template with the suggested changes. The changes will live within 2-3 working days.

### ISSUE THREAD

**Issue by De1gad0** [MicrosoftDocs/entra-docs#883]
@De1gad0, we created a separate PR for your changes in our private repo by following the fixed format of our documentation template with the suggested changes. The changes will live within 2-3 working days.
_Originally posted by @v-hgampala in https://github.com/MicrosoftDocs/entra-docs/issues/811#issuecomment-2114646856_

Good afternoon @v-hgampala - it looks like some, but not all of our changes were carried over into the new PR you created. Are we able to re-open this PR, or do I need to open a new PR? Are you able to explain why all of our changes did not make it in the PR you created? I have provided screenshots of what was not updated. 

![881_Change02_MDfile](https://user-images.githubusercontent.com/49171254/334967902-d671179c-dcb6-4da2-a183-bd9433cdc9df.jpg)
![881_Change02_Live](https://user-images.githubusercontent.com/49171254/334967904-7adfe71e-9907-4fed-b08e-464c8dc7d041.jpg)
![881_Change01_Live](https://user-images.githubusercontent.com/49171254/334967906-f6367f04-f657-48b0-b7eb-87c8dc574b52.jpg)
![881_Change01_MDfile](https://user-images.githubusercontent.com/49171254/334967907-12c0d804-7050-4154-bcf6-9563b268a234.jpg)

Thank you!

**Comment by Naveenommi-MSFT** [comment]
@De1gad0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@v-hgampala  Please Provide a comprehensive review and offer insights on the PR.
