### ISSUE TITLE
This is a good help page - please assign the team who put this together to rewrite other help pages

### ISSUE THREAD

**Issue by thecatfix** [MicrosoftDocs/entra-docs#884]
Finally! A help page for Entra that doesn't send down a thousand different hyperlinks loaded with marketing BS. Thank you for clear instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9f81d74-8dcb-e644-9647-0d1d0817f975
* Version Independent ID: e249cc9d-2120-8868-dbca-bc3b85f38b4b
* Content: [Troubleshoot Microsoft Entra hybrid joined devices - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/devices/troubleshoot-hybrid-join-windows-current?source=docs)
* Content Source: [docs/identity/devices/troubleshoot-hybrid-join-windows-current.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/devices/troubleshoot-hybrid-join-windows-current.md)
* Service: **entra-id**
* Sub-service: **devices**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by PesalaPavan** [comment]
@thecatfix 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @thecatfix 
Thanks for your contribution. Please add your feedback in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)

**Comment by Naveenommi-MSFT** [comment]
@thecatfix 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
