### ISSUE TITLE
Missing clarification regarding verified domains under the same Entra ID Tenant

### ISSUE THREAD

**Issue by darrenCampos** [MicrosoftDocs/entra-docs#885]
[Enter feedback here]
Will be great to add to the document the same clarification as the one present here https://learn.microsoft.com/en-us/entra/external-id/cross-tenant-access-overview#direct-federation-for-microsoft-entra-id-verified-domains  "Ensure that the domain is not verified in the same tenant in which you are trying to set up the Direct federation configuration."

As this is our "Official Document" on how to set up SAML/Ws-Fed idp federation and it is not added into the documents "requirements or limitations"

Adding some confusion for customers trying to set up SAML idp with a verify domain in the same Entra ID Tenant
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1d9428-2dbb-c80b-c2cd-b4841d3d8bd3
* Version Independent ID: 20af5f8d-479c-66ec-aacd-d3f9cb79c814
* Content: [Federation with a SAML/WS-Fed identity provider (IdP) for B2B - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/direct-federation#step-3-configure-samlws-fed-idp-federation-in-azure-ad)
* Content Source: [docs/external-id/direct-federation.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/direct-federation.md)
* Service: **entra-external-id**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by PesalaPavan** [comment]
@darrenCampos 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@darrenCampos 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.
