### ISSUE TITLE
Will the difference between iPhone and Android for Passkeys in MS authenticator remain when it is time for GA?

### ISSUE THREAD

**Issue by LarsVidingSE** [MicrosoftDocs/entra-docs#887]
[Enter feedback here]
I have done some testing’s of passkeys in Microsoft Authenticator on iPhone and Android within my dev tenant. Unfortunately for now, in this preview, there are big differences between iPhone and Android in the handling. 

Because of the bad record when it comes to the passwordless feature “Phone sig-in” in MS authenticator on Android. This feature was launched in about two years ago. 
And for the very beginning you said that “support for more than one account in Android is coming soon. But nothing has happened ☹

I wonder, will the difference between iPhone and Android for Passkeys in MS authenticator remain when it is time for GA? As it has been for the passwordless feature in MS authenticator with only one account for phone sign in on an Android!

As it is today with Android and cross-device authentication. There are no way to edit my Android mobile (in the used computer) if I used some other computer for cross-device sign in. The only way I have found is to delete it within registry. Which is not an option for everyone.
But I love the sign in handeling when using Android in cross-device authentications, when I doe not need to scan QR code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e251214c-f2d6-3167-ec55-1959714ea1c6
* Version Independent ID: e251214c-f2d6-3167-ec55-1959714ea1c6
* Content: [Sign in with passkeys in Authenticator for Android and iOS devices (preview) - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-sign-in-passkey-authenticator?tabs=iOS)
* Content Source: [docs/identity/authentication/how-to-sign-in-passkey-authenticator.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/how-to-sign-in-passkey-authenticator.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayBathini-MSFT** [comment]
@LarsVidingSE 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by Justinha** [comment]
@LarsVidingSE Thanks for your patience! Support for Android was rolled out last week and the topic has been updated. #please-close
