### ISSUE TITLE
Article forgot a critical detail

### ISSUE THREAD

**Issue by ltjones12** [MicrosoftDocs/entra-docs#888]
[Enter feedback here]

So the command to check if this policy is enabled or not (Get-MgUser -UserId <User Object ID> -Property PasswordPolicies).PasswordPolicies... when I imported the graph module it created an enterprise app, however, the enterprise app doesn't have the needed permissions to run this command. I have no idea what permissions are required because the pre-requisite permissions are not specified in the article, which renders this article useless. Details details details... Kind of an important detail missed there :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cddbb200-e2f8-9b0e-09ca-c0da61116ef3
* Version Independent ID: fae3a656-ff75-7fea-1b2e-7174c231fb1a
* Content: [Implement password hash synchronization with Microsoft Entra Connect Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-password-hash-synchronization#password-expiration-policy)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-password-hash-synchronization.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-password-hash-synchronization.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@ltjones12 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ltjones12** [comment]
Additionally, the article states that if we don't have a 90 day expiration
on-prem (which we don't), we need to run the update-mgdomain command. But
toward the bottom is basically says "oh, by the way, if your domain is
federated the update-mgdomain command doesn't work". But the author simply
forgot to offer a solution if your domain is federated.
Our domain is federated, so we are at a loss here. Sorry to be rude, but
the author lacks attention to detail

[image: image.png]

**Comment by ManoharLakkoju-MSFT** [comment]
@ltjones12 
Thank you for bringing this to our attention.
I've delegated this to content author @billmath, who will review it and offer their insightful opinions.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
