### ISSUE TITLE
Asking clarification for a statement regarding Group writeback V1 and V2 (cloud sync)

### ISSUE THREAD

**Issue by kayasax** [MicrosoftDocs/entra-docs#889]
> Mail-enabled groups and DLs written back using Microsoft Entra Connect group writeback V1 or V2 aren't supported.

Please help understanding if the above statement is only about this migration doc or not supported at all in Cloud sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1da65039-05e7-474c-ee47-b1e62acb64b7
* Version Independent ID: 1da65039-05e7-474c-ee47-b1e62acb64b7
* Content: [Migrate Microsoft Entra Connect Sync group writeback V2 to Microsoft Entra Cloud Sync - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/cloud-sync/migrate-group-writeback)
* Content Source: [docs/identity/hybrid/cloud-sync/migrate-group-writeback.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/cloud-sync/migrate-group-writeback.md)
* Service: **entra-id**
* Sub-service: **hybrid-cloud-sync**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PesalaPavan** [comment]
@kayasax 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hello @kayasax 
It states that mail-enabled groups and DLs written back using Microsoft Entra Connect group writeback V1 or V2 aren't supported in the migration process. However, in general, mail-enabled groups and DLs can be written back using Azure AD Connect group writeback V1 or V2. It's important to note that the group writeback functionality is currently in public preview, and there may be some limitations or changes in the future. 

You can go through this below link for your reference.
https://learn.microsoft.com/en-us/entra/identity/hybrid/group-writeback-cloud-sync

This scenario is only for customers who are currently using Microsoft Entra Connect group writeback v2
Also, this scenario is only supported for:
cloud created [Security groups](https://learn.microsoft.com/en-us/entra/fundamentals/concept-learn-about-groups#group-types)
these groups are written back with the AD groups scope of [universal](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-groups#group-scope).
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-group-writeback-enable#optional-configuration.

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by Naveenommi-MSFT** [comment]
@kayasax 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
