### ISSUE TITLE
Log analytics queries for non-interactive sign-ins, but no for interactive sign-ins.

### ISSUE THREAD

**Issue by joibarr** [MicrosoftDocs/entra-docs#893]
In the documentation, the 2 queries for log analytics are for non-interactive sign-ins. I assume the idea is to show 1 query for non-interactive, and another query for interactive sign-ins.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec45091-ab65-7d9d-8915-26f5e56aa274
* Version Independent ID: 13a637da-8ded-72a0-464c-61efdef2a199
* Content: [Token protection in Microsoft Entra Conditional Access - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/conditional-access/concept-token-protection)
* Content Source: [docs/identity/conditional-access/concept-token-protection.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/conditional-access/concept-token-protection.md)
* Service: **entra-id**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TPavanBalaji** [comment]
@joibarr 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by MicrosoftGuyJFlo** [comment]
You can adjust the query to look at different logs. This is just showing one example.

#please-close
