### ISSUE TITLE
Wrong content in "Find gMSAs" section

### ISSUE THREAD

**Issue by exsitecMNK** [MicrosoftDocs/entra-docs#894]
Hi, When researching about gMSA I noticed that the "Find gMSAs" section states a PowerShell cmdlet to get gMSAs, but the snippet is a copy of the different commands that can be used to manage gMSA.

I suggest that the snippet could be replaced with this instead:
`Get-ADServiceAccount -Filter *`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b50bdb8-c331-4ce5-e391-e726f49a11d2
* Version Independent ID: f9b1d5db-9e91-ec5a-490c-d8ddbb71eb23
* Content: [Secure group managed service accounts - Microsoft Entra](https://learn.microsoft.com/en-us/entra/architecture/service-accounts-group-managed)
* Content Source: [docs/architecture/service-accounts-group-managed.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/architecture/service-accounts-group-managed.md)
* Service: **entra**
* Sub-service: **architecture**
* GitHub Login: @jricketts
* Microsoft Alias: **jricketts**

**Comment by PesalaPavan** [comment]
@exsitecMNK 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@exsitecMNK 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
#please-close
