### ISSUE TITLE
Assign owner of app to see app registration in My API

### ISSUE THREAD

**Issue by bpelikan** [MicrosoftDocs/entra-docs#897]
[Enter feedback here]

In [Add application permissions to allow access to a web API](https://learn.microsoft.com/en-us/entra/identity-platform/howto-call-a-web-api-with-curl?tabs=dotnet6&pivots=no-api#add-application-permissions-to-allow-access-to-a-web-api) I coudn't find `NewWebAPI1` in `API permissions > Add a permission > My APIs` until I assign my account as owner of `NewWebAPI1` (despite I'm `Global Administrator`) - maybe it should be mentioned in [Register the web API](https://learn.microsoft.com/en-us/entra/identity-platform/howto-call-a-web-api-with-curl?tabs=dotnet6&pivots=no-api#register-the-web-api)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f7d0268f-c285-ef3c-bc48-8570b4d7367b
* Version Independent ID: 962c2c10-568e-29d7-b33b-35324133b81b
* Content: [Call an ASP.NET Core web API with cURL - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/howto-call-a-web-api-with-curl?tabs=dotnet6)
* Content Source: [docs/identity-platform/howto-call-a-web-api-with-curl.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/howto-call-a-web-api-with-curl.md)
* Service: **identity-platform**
* GitHub Login: @henrymbuguakiarie
* Microsoft Alias: **henrymbugua**

**Comment by PesalaPavan** [comment]
@bpelikan 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@bpelikan 
I'm going to assign this to the document author so they can take a look at it accordingly.

@henrymbuguakiarie 
Can you please check and add your comments on this doc update request as applicable.

**Comment by henrymbuguakiarie** [comment]
Hello @bpelikan,

Thanks for your dedication to our documentation.

I've modified the steps in "Add application permissions to allow access to a web API" to avoid confusion and enhance clarity. The changes will be reflected later today.

Cc: @SaibabaBalapur-MSFT
