### ISSUE TITLE
Misspelling in JSON

### ISSUE THREAD

**Issue by dbranscome** [MicrosoftDocs/entra-docs#898]
At this location, the JSON has "authority1 misspelled:
https://learn.microsoft.com/en-us/entra/verified-id/helpdesk-with-verified-id#add-verification-flows-to-service-desk-solution 

  "acceptedIssuers": [ "<**authirity1**>", "<authority2>", "..." ], 
  
  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0c7bd53-316a-968e-95db-7b897349fb79
* Version Independent ID: a0c7bd53-316a-968e-95db-7b897349fb79
* Content: [Verified helpdesk with Microsoft Entra Verified ID - Microsoft Entra Verified ID](https://learn.microsoft.com/en-us/entra/verified-id/helpdesk-with-verified-id#add-verification-flows-to-service-desk-solution)
* Content Source: [docs/verified-id/helpdesk-with-verified-id.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/verified-id/helpdesk-with-verified-id.md)
* Service: **entra-verified-id**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by PesalaPavan** [comment]
@dbranscome 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@dbranscome 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
