### ISSUE TITLE
 new auth providers may no longer be created

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/entra-docs#904]
We have important message on this page https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-authprovider
![image](https://github.com/MicrosoftDocs/entra-docs/assets/3004057/a07f58e2-2f27-4856-9c74-9939e7b1048f)

>  Important
> 
> Effective September 1st, 2018 **new auth providers may no longer be created**. Existing auth providers may continue to be used and updated, but migration is no longer possible. Multifactor authentication will continue to be available as a feature in Microsoft Entra ID P1 or P2 licenses.

But on the same page, it says “You can't change the usage model (per enabled user or per authentication) after an MFA provider is created”, then how could I change the usage model if new provider can not be created. any conflicts here?

https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-authprovider#manage-your-mfa-provider

> Manage your MFA provider
> 
> **You can't change the usage model (per enabled user or per authentication) after an MFA provider is created**.
> 
> If you purchased enough licenses to cover all users that are enabled for MFA, you can delete the MFA provider altogether.
> 
> If your MFA provider isn't linked to a Microsoft Entra tenant, or you link the new MFA provider to a different Microsoft Entra tenant, user settings and configuration options aren't transferred. Also, existing Azure MFA Servers need to be reactivated using activation credentials generated through the MFA Provider.
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02d89c71-7566-2cd4-6a97-8c54bbdfae88
* Version Independent ID: 0c1251e2-52f5-34d7-4815-169d6bd8d873
* Content: [Microsoft Entra multifactor authentication providers - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-authprovider)
* Content Source: [docs/identity/authentication/concept-mfa-authprovider.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/authentication/concept-mfa-authprovider.md)
* Service: **entra-id**
* Sub-service: **authentication**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@chucklu 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Justinha** [comment]
@chucklu thanks for the question. I don't find the two statements to be orthogonal. What is the problem you are trying to solve?

**Comment by chucklu** [comment]
@Justinha new auth providers may no longer be created.  What does this actually mean? I did not get it

I think it conflicts with:
You can't change the usage model (per enabled user or per authentication) after an MFA provider is created.
As the usage model can not be changed, then we have to delete old one, and create a new one, right?

**Comment by Justinha** [comment]
@chucklu it's a very old topic and reference to years ago when tenants needed to specify MFA providers and pay for MFA separately. Today, we offer MFA as a free feature for all tenants. I'll take a look at removing the reference entirely since it's no longer relevant. But the two statements you cite aren't necessarily orthogonal. Are you configuring an MFA provider? If so, what problem are you running into?

**Comment by SaibabaBalapur-MSFT** [comment]
@Justinha Thanks for your quick responses.

@chucklu 
Since we have not heard back from you, we will now proceed to close this thread.If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
