### ISSUE TITLE
I have some issue relate one user one domain one business 

### ISSUE THREAD

**Issue by kachuy** [MicrosoftDocs/entra-docs#905]
[while setting up Bios Domain Name and user account"KACHUY" As use +administration privilege and kachuy.com as biosnet id realize Profile for kachuy mach  the Profile of nt AUTHORITY\system creating a chaos with my picts documents music etc cuase somewere file UP as system (kachuy can't see o modify it) wonder 🤔 any idea]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06c24fd7-43ce-1445-b734-ffd28410911f
* Version Independent ID: b835d64a-a78a-95d9-11a7-8b93a23944c8
* Content: [Self-service sign up for email-verified users - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/directory-self-service-signup)
* Content Source: [docs/identity/users/directory-self-service-signup.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/directory-self-service-signup.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@kachuy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@kachuy 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
