### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jsalian27** [MicrosoftDocs/entra-docs#907]
[Enter feedback here]

The positive filtering option requires two sync rules. You need one rule (or several) with the correct scope of objects to synchronize. You also need a second catch-all sync rule that filters out all objects that haven't yet been identified as an object that should be synchronized.

I think the paragraph end should read as "an object that should not be synchronized" instead of should be.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e7c4286a-5c62-c665-79fb-d89976394831
* Version Independent ID: 371d9e69-f806-6174-b93e-a951de8b50a8
* Content: [Microsoft Entra Connect Sync: Configure filtering - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-sync-configure-filtering)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-sync-configure-filtering.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-sync-configure-filtering.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@jsalian27 
Thanks for reporting this! PR has raised for this issue and the changes should go live soon.
