### ISSUE TITLE
Feature Comparison Incorrect

### ISSUE THREAD

**Issue by tsrob50** [MicrosoftDocs/entra-docs#908]
The feature comparison table shows that a managed domain supports a one-way trust only.  Managed domains now support a two-way trust.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff64a31-7310-b2e8-28ba-690790b9b00d
* Version Independent ID: bd83c309-bd2b-6211-8d86-6d9713822c2b
* Content: [Compare Microsoft directory-based services - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/domain-services/compare-identity-solutions)
* Content Source: [docs/identity/domain-services/compare-identity-solutions.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/domain-services/compare-identity-solutions.md)
* Service: **entra-id**
* Sub-service: **domain-services**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TPavanBalaji** [comment]
@tsrob50 
Thanks for reporting this! PR raised for this issue and the changes should go live soon.
