### ISSUE TITLE
Microsoft documentation page not visible

### ISSUE THREAD

**Issue by stephenosr** [MicrosoftDocs/entra-docs#91]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fd30f7f-e5ce-67d5-2536-ee1d115a573d
* Version Independent ID: 6979c76f-48f2-1d2a-1358-ab1b6998bfd3
* Content: [Quickstart: Get token & call Microsoft Graph in a console app - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-v2-netcore-daemon)
* Content Source: [docs/identity-platform/quickstart-v2-netcore-daemon.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/quickstart-v2-netcore-daemon.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @OwenRichards1
* Microsoft Alias: **owenrichards**

**Comment by ManoharLakkoju-MSFT** [comment]
@stephenosr 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ManoharLakkoju-MSFT** [comment]
@stephenosr 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
