### ISSUE TITLE
Microsoft Entra Connect Sync returns a 404 error

### ISSUE THREAD

**Issue by e2p2** [MicrosoftDocs/entra-docs#916]
Link to download the latest Microsoft Entra Connect Sync returns a 404 error.  I have searched for alternatives but every link I find returns a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 601beac1-1bc3-5cfe-0653-4c31917a5503
* Version Independent ID: acd6ceee-f4b9-8b92-4b71-5e8de0ffcfde
* Content: [Microsoft Entra Connect and Microsoft Entra Connect Health installation roadmap. - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-install-roadmap)
* Content Source: [docs/identity/hybrid/connect/how-to-connect-install-roadmap.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/hybrid/connect/how-to-connect-install-roadmap.md)
* Service: **entra-id**
* Sub-service: **hybrid-connect**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TPavanBalaji** [comment]
@e2p2 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by PesalaPavan** [comment]
@e2p2 
I have checked my end all links are working. Can you share the exact link which is not working, that will help to address the issue.

**Comment by e2p2** [comment]
It appears to be working correctly now.



Eugene Pressley
Coordinator, Infrastructure & Network Administration
Information Technology


A-B Tech Community College
340 Victoria Road
Asheville, NC 28801
Office: (828) 398-7477
***@***.******@***.***>


 A-B Tech’s Vision: Changing Lives. Strengthening Communities.

Under the NC Public Records Law (GS 115D-78), email messages and attachments that are sent to or received by this account may be considered public records subject to third-party review depending upon the subject matter of the message. Messages, portions of messages, and attachments regarding a particular student or employee are considered confidential under NC privacy laws and federal law. All emails are subject to review by Asheville-Buncombe Technical Community College.



________________________________

**Comment by PesalaPavan** [comment]
@e2p2 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
