### ISSUE TITLE
spelling error - "inforamtion"

### ISSUE THREAD

**Issue by OutOfScopeia** [MicrosoftDocs/entra-docs#919]
a misspelled word found in the text: "inforamtion".

**Comment by TPavanBalaji** [comment]
@OutOfScopeia 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by TPavanBalaji** [comment]
@OutOfScopeia 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

**Comment by TPavanBalaji** [comment]
@OutOfScopeia 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
