### ISSUE TITLE
Dynamic membership rules documentation error: Property 'objectid' cannot be applied to object 'Group'

### ISSUE THREAD

**Issue by TRezendes** [MicrosoftDocs/entra-docs#921]
Per the [Dynamic membership rules for groups in Microsoft Entra ID documentation](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-membership#properties-of-type-string), the following syntax will select all users who are members of the group with Object ID *value*: `user.memberof -any (group.objectId -in ['value'])`.

Attempting to use this rule syntax, however, raises the error
> Dynamic membership rule validation error: Wrong property applied.
> Property 'objectid' cannot be applied to object 'Group' 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7a4070-1be8-5f1f-0092-68fb6b9e2305
* Version Independent ID: cd34312f-b507-affe-555e-1e0c63e7d494
* Content: [Rules for dynamically populated groups membership - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/groups-dynamic-membership#properties-of-type-string)
* Content Source: [docs/identity/users/groups-dynamic-membership.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/groups-dynamic-membership.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by TPavanBalaji** [comment]
@TRezendes 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@TRezendes 
Thank you for bringing this to our attention.
I've delegated this to content author @barclayn, who will review it and offer their insightful opinions.

**Comment by barclayn** [comment]
@TRezendes have you tried user.memberOf -any (group.objectId -eq 'value') #please-close
