### ISSUE TITLE
Add ItalyNorth to the list of unsupported regions

### ISSUE THREAD

**Issue by marcelloformica** [MicrosoftDocs/entra-docs#93]
Hello,
based on tests, federated identity credentials seem to be unavailable also in ItalyNorth:
trying to create them with:
`az identity federated-credential create  --name 'federated-identity-credential' --identity-name 'testidentity' --resource-group 'rg-test' --issuer "${AKS_OIDC_ISSUER}" --subject system:serviceaccount:default:workload-identity-sa --audience api://AzureADTokenExchange`
gives:
`(MethodNotAllowed) The request format was unexpected : Support for federated identity credentials not enabled`

It works, instead, if `testidentity` is created, for example, in WestEurope.

If confirmed, can you please update the list of unsupported regions to clarify this limitation? 
Thank you
best regards,
Marcello Formica

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65d09367-0e52-f540-637a-13eb1c094173
* Version Independent ID: ce84db4f-e1a1-799d-b34a-4f750ec34c14
* Content: [Workload identity federation for app considerations - Microsoft Entra Workload ID](https://learn.microsoft.com/en-us/entra/workload-id/workload-identity-federation-considerations?source=docs#unsupported-regions-user-assigned-managed-identities)
* Content Source: [docs/workload-id/workload-identity-federation-considerations.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/workload-id/workload-identity-federation-considerations.md)
* Service: **active-directory**
* Sub-service: **workload-identities**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by ManoharLakkoju-MSFT** [comment]
@marcelloformica 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
@marcelloformica 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
