### ISSUE TITLE
Simulate Workload Identities Risk Learning Period

### ISSUE THREAD

**Issue by fooz88** [MicrosoftDocs/entra-docs#930]
Can it be noted that in order to simulate the leaked credentials risk detection for workload identities that an initial learning period of x days is required prior to testing? Similar to how its mentioned for other detections in the same article for:
- [Unfamiliar Sign-In Properties](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/howto-identity-protection-simulate-risk.md#unfamiliar-sign-in-properties)
> Completing the following procedure requires you to use a user account that has:
> At least a 30-day sign-in history
- [Atypical Travel](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/howto-identity-protection-simulate-risk.md#atypical-travel)
> Additionally, the algorithm requires a sign-in history of 14 days or 10 logins of the user before it begins generating risk detections.

doc section: https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/howto-identity-protection-simulate-risk.md#leaked-credentials-for-workload-identities

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8fb752e-47bb-f0cd-9a2a-d7e1edb8c663
* Version Independent ID: 11c931ea-bafa-3ac9-9dfa-efaace749c46
* Content: [Simulating risk detections in Microsoft Entra ID Protection - Microsoft Entra ID Protection](https://learn.microsoft.com/en-us/entra/id-protection/howto-identity-protection-simulate-risk)
* Content Source: [docs/id-protection/howto-identity-protection-simulate-risk.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/id-protection/howto-identity-protection-simulate-risk.md)
* Service: **entra-id-protection**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @fooz88 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
