### ISSUE TITLE
 Inconsistent IDs in Example 7 of "Assign custom admin roles using the Microsoft Graph API in Microsoft Entra ID" Document

### ISSUE THREAD

**Issue by pikapi25** [MicrosoftDocs/entra-docs#931]
I noticed an inconsistency in the "Example 7: Get a role assignment by ID" section of the “Assign custom admin roles using the Microsoft Graph API in Microsoft Entra ID” (https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-assign-graph) document. The id in the command and the id in the response do not match, which can cause confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 29286aff-a419-c24b-17ab-c7d3d3112b19
* Version Independent ID: 0049d924-32c0-9506-e63e-df8feb923131
* Content: [Assign Microsoft Entra admin roles with Microsoft Graph API - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-assign-graph)
* Content Source: [docs/identity/role-based-access-control/custom-assign-graph.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/role-based-access-control/custom-assign-graph.md)
* Service: **entra-id**
* Sub-service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by TPavanBalaji** [comment]
@pikapi25 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@pikapi25 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by rolyon** [comment]
Hi @pikapi25 
Thanks for noticing this inconsistent ID. We have updated the doc and it will appear in our next publish.
thanks

**Comment by rolyon** [comment]
#please-close
