### ISSUE TITLE
Inconsistent statement for SAML/WS-Fed identity provider configuration of required claims

### ISSUE THREAD

**Issue by devrony** [MicrosoftDocs/entra-docs#932]
The SAML/WS-Fed article for setting up an external Identity Provider (IdP) for guest users states in the section "Required SAML 2.0 attributes and claims" shows the the "Attribute Name" as "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" and the "Value" as "emailaddress".

Reference Page - "Required SAML 2.0 attributes and claims"
https://learn.microsoft.com/en-us/entra/external-id/direct-federation#step-3-configure-samlws-fed-idp-federation-in-microsoft-entra-id

But on the example page in the "Configure AD FS for SAML 2.0 federation" section it shows the opposite.  I believe the example page is incorrect.  My understanding is the SAML token should have the Attribute name as "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" and the value at runtime should be the actual email address of the authenticated user.   That should be clearly stated as well as the documentation makes it seem like the value is hard coded.

Example Page - "Configure AD FS for SAML 2.0 federation"
https://learn.microsoft.com/en-us/entra/external-id/direct-federation-adfs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1d9428-2dbb-c80b-c2cd-b4841d3d8bd3
* Version Independent ID: 20af5f8d-479c-66ec-aacd-d3f9cb79c814
* Content: [Federation with a SAML/WS-Fed identity provider (IdP) for B2B - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/direct-federation#step-3-configure-samlws-fed-idp-federation-in-microsoft-entra-id)
* Content Source: [docs/external-id/direct-federation.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/direct-federation.md)
* Service: **entra-external-id**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by TPavanBalaji** [comment]
@devrony 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
@devrony Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue.

#please-close
