### ISSUE TITLE
previousDayDateTime24hrs included example but not explained

### ISSUE THREAD

**Issue by jonesy5090** [MicrosoftDocs/entra-docs#941]
https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/sap-successfactors-integration-reference.md#how-incremental-sync-works

The above document references two variables the URL snippet:

- previousDayDateTime24hrs
- previousDayDateStartTime24hrs

However it's not clear what these should be set to.

---
#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: 56401d85-b771-94ed-5505-c0ba929ba27b
* Version Independent ID: d7a38614-2897-1c94-5d24-120431cb018a
* Content: [Microsoft Entra ID and SAP SuccessFactors integration reference - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/sap-successfactors-integration-reference)
* Content Source: [docs/identity/app-provisioning/sap-successfactors-integration-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/sap-successfactors-integration-reference.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by TPavanBalaji** [comment]
@jonesy5090 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by TPavanBalaji** [comment]
@jonesy5090 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TPavanBalaji** [comment]
@jonesy5090 
Thank you for bringing this to our attention.
I've delegated this to content author, who will review it and offer their insightful opinions.

**Comment by kenwith** [comment]
Moving this to DevOps backlog work item. Thank you for the feedback.

#please-close

**Comment by kenwith** [comment]
@jonesy5090 - there is a different process for making the change and you can work with the product team by emailing them at aaduserprovisioning at microsoft com.
