### ISSUE TITLE
AppID is ambiguous on External ID Custom Authentication Extension instructions

### ISSUE THREAD

**Issue by NickFadz** [MicrosoftDocs/entra-docs#942]
On the "Prefilled values" tab of https://learn.microsoft.com/en-us/entra/identity-platform/custom-extension-attribute-collection?tabs=start-set-prefill-values%2Csubmit-continue#12-configure-the-http-trigger-for-onattributecollectionstart in the sample code section:

    // The form fields will load with these default values
    var inputs = new Dictionary<string, object>()
    {
        { "postalCode", "<your-prefill-value>" },
        { "streetAddress", "<your-prefill-value>" },
        { "city", "<your-prefill-value>" },
        { "extension_appId_mailingList", false },
        { "extension_appId_memberSince", 2023 }      
    };

For custom attributes, "appId" here has to be the Application (client) ID of the "b2c-extensions-app. Do not modify. Used by AADB2C for storing user data." application registration, as explained here: https://learn.microsoft.com/en-us/entra/external-id/customers/how-to-define-custom-attributes#find-the-application-id-for-the-extensions-app

This is not at all clear and should be described in more detail, to give better guidance.
```[tasklist]
### Tasks
```

**Comment by CelesteDG** [comment]
@NickFadz Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue.

#please-close
