### ISSUE TITLE
Possibly incorrect description for AADSTS50074 on "Microsoft Entra authentication and authorization error codes" page

### ISSUE THREAD

**Issue by clivesec** [MicrosoftDocs/entra-docs#943]
On page "[Microsoft Entra authentication and authorization error codes](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes)" the description for error code "AADSTS50074" is "UserStrongAuthClientAuthNRequiredInterrupt - Strong authentication is required and **the user did not pass the MFA challenge**."

The description states the user did not pass the MFA challenge; however, I believe error 50074 relates only to an MFA challenge being shown, and does not infer to success or failure of the challenge itself. I believe this is the case as:

1. The [error code lookup page](https://login.microsoftonline.com/error) for error 50074 does not mention that the MFA challenge failed, simply that the "User needs to perform multi-factor authentication ... ".
2. I performed testing of sign-ins with  both successful and failed MFA challenges. For both successful and failed MFA scenarios, a 50074 event was logged. For the MFA failure test, a separate 500121 event was logged. This event has the description of "The user didn't complete the MFA prompt ... " on the [error code lookup page](https://login.microsoftonline.com/error). Further, the document in question does not have any details for error code 500121. 

Please can you review this page. It is important that this error code is accurately described, since users may infer that a sign-in had failed when that may not have been the case. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a826ee6f-f457-7109-9f77-67c57977d4e7
* Version Independent ID: 11766f27-492e-a579-dced-8a42528cbb47
* Content: [Microsoft Entra authentication & authorization error codes - Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes)
* Content Source: [docs/identity-platform/reference-error-codes.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity-platform/reference-error-codes.md)
* Service: **identity-platform**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by PesalaPavan** [comment]
@clivesec 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@clivesec 
I'm going to assign this to the document author so they can take a look at it accordingly.

@rwike77 
Can you please check and add your comments on this doc update request as applicable.

**Comment by CelesteDG** [comment]
@rwike77 Please review. I verified that there's a disconnect between the two, per the GitHub issues comment. If needed, please open an ADO work item to track this while getting confirmation/additional info from engineering and PM. Thank you.

**Comment by rwike77** [comment]
We are in the process of transferring to a new unified user feedback system, so I need to close this issue even though it's not resolved. I'll need to get some help from engineering.  I've opened an internal work item for the month of June so I won't lose it.

Thanks for your patience. #please-close
