### ISSUE TITLE
Update Segment docs to add flag to the Tenant URL

### ISSUE THREAD

**Issue by muhammadatifjav** [MicrosoftDocs/entra-docs#949]
Our team at Segment has confirmed Microsoft Azure Entra ID (formerly Active Directory) is sending non-standard path value when issuing PATCH remove op. During testing, we tried out [the flag aadOptscim062020 indicated in this Microsoft article](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility), which actually fixes the issue. It will be the fix to make Azure compatible with Segment's SCIM v2 implementation.

In our docs, we directly point our customers to your docs which works well:  https://segment.com/docs/segment-app/iam/scim/#okta-set-up-guide

I'm opening this issue to see if the Tenant URL can be updated to "https://scim.segmentapis.com/scim/v2?aadOptscim062020" [in your SCIM tutorial/guide here](https://learn.microsoft.com/en-us/entra/identity/saas-apps/segment-provisioning-tutorial#step-2-configure-segment-to-support-provisioning-with-microsoft-entra-id)? I can also provide some details why this flag is needed.

This will ensure that the customers who are implementing the Entra ID SCIM setup  are set up correctly and don't run into this issue. We are also adding some info to our docs in the meantime, but I wanted to reach out and see if it can be updated in Microsoft Entra ID docs as well.

Thanks in adv!
Atif (from Segment Support Team) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09b8c472-3a4e-dd2c-11df-f05b05e5a642
* Version Independent ID: 834bcfe7-2e5c-97ed-eeb8-d5eed616188b
* Content: [Known issues with System for Cross-Domain Identity Management (SCIM) 2.0 protocol compliance - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility)
* Content Source: [docs/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by PesalaPavan** [comment]
@muhammadatifjav 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
@kenwith Can you please review and track and migrate in ADO? Thank you.

**Comment by kenwith** [comment]
Created a work item and sent email to PM team for review. I will get the change updated right away once they review. Thank you for the feedback.

#please-close
