### ISSUE TITLE
STEP4 Not Completely Described

### ISSUE THREAD

**Issue by zjorz** [MicrosoftDocs/entra-docs#95]
IS NOW:
    POST /servicePrincipals/resource-servicePrincipal-id/appRoleAssignedTo

    {
    "principalId": "3fbd929d-8c56-4462-851e-0eb9a7b3a2a5",
    "resourceId": "b0d9b9e3-0ecf-4bfd-8dab-9273dd055a94",
    "appRoleId": "00000000-0000-0000-0000-000000000000"
    }

SHOULD BE:
POST https://graph.microsoft.com/v1.0/servicePrincipals/b0d9b9e3-0ecf-4bfd-8dab-9273dd055a94/appRoleAssignedTo
Request body
{
	"resourceId": "b0d9b9e3-0ecf-4bfd-8dab-9273dd055a94",
	"principalId": "3fbd929d-8c56-4462-851e-0eb9a7b3a2a5",
	"appRoleId": "00000000-0000-0000-0000-000000000000"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1904fc-0df4-01e6-c1f8-8e92673b76ec
* Version Independent ID: 196471b9-4df4-d4a7-6bc5-a20ebc6f50e7
* Content: [Grant consent on behalf of a single user - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/grant-consent-single-user?pivots=ms-graph&source=docs)
* Content Source: [docs/identity/enterprise-apps/grant-consent-single-user.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/enterprise-apps/grant-consent-single-user.md)
* Service: **active-directory**
* Sub-service: **app-mgmt**
* GitHub Login: @omondiatieno
* Microsoft Alias: **jomondi**

**Comment by ManoharLakkoju-MSFT** [comment]
@zjorz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@zjorz 
Thank you for bringing this to our attention! We've initiated a pull request (PR) to address this issue. Once the author reviews the changes, they will be merged, and the updates should go live shortly. Your diligence is much appreciated!
