### ISSUE TITLE
Invalid JSON examples

### ISSUE THREAD

**Issue by sqlwatchmen** [MicrosoftDocs/entra-docs#954]
The following JSON example appears to be invalid due to a trailing comma:
"{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q...",
    "token_type": "Bearer",
    "expires_in": 3599,
    "scope": "https%3A%2F%2Fgraph.microsoft.com%2Fmail.read",
    "refresh_token": "AwABAAAAvPM1KaPlrEqdFSBzjqfTGAMxZGUTdM0t4B4...",
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIyZDRkMTFhMi1mODE0LTQ2YTctOD...",
}"

This appears to be the case in two places, one on line 275 and another on line 387.

https://github.com/MicrosoftDocs/entra-docs/blob/744ec8ddd948e5fab5050c98147b429cabe66e90/docs/identity-platform/v2-oauth2-auth-code-flow.md?plain=1#L275

https://github.com/MicrosoftDocs/entra-docs/blob/744ec8ddd948e5fab5050c98147b429cabe66e90/docs/identity-platform/v2-oauth2-auth-code-flow.md?plain=1#L387

If this is indeed an error, I would recommend the deletion of the erroneous commas so that users can more easily copy and paste them without having to make the change themselves after pasting the example.

**Comment by OwenRichards1** [comment]
Thanks for the vigilant feedback @sqlwatchmen - I have patched this file, and corrected the JSON. The changes will be visible upon our next publish!
