### ISSUE TITLE
Entra Permissions Management Region Availability

### ISSUE THREAD

**Issue by tomstone-neu** [MicrosoftDocs/entra-docs#963]
I just tried to start Entra Permissions Management trial in East US 2 and was told by support it is unavailable there.  Is there anyway to follow when Permissions Management will be available in certain regions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d223b814-76f8-ac48-eaef-33c508a3d15f
* Version Independent ID: 12948ab7-452b-2464-c3d9-0086cffb7758
* Content: [Frequently asked questions (FAQs) about Microsoft Entra Permissions Management - Microsoft Entra Permissions Management](https://learn.microsoft.com/en-us/entra/permissions-management/faqs)
* Content Source: [docs/permissions-management/faqs.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/permissions-management/faqs.md)
* Service: **entra-permissions-management**
* GitHub Login: @jenniferf-skc
* Microsoft Alias: **jfields**

**Comment by PesalaPavan** [comment]
@tomstone-neu 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by tomstone-neu** [comment]
I would think there should be something about supported regions in the FAQ:
https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/permissions-management/faqs.md

**Comment by PesalaPavan** [comment]
@tomstone-neu 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Thank you for your question. I've opened this question in our unified user feedback mechanism, where the issue will be tracked with an Azure DevOps work item.

#please-close
