### ISSUE TITLE
Clarify operational requirements when assigning entitlement packages to users

### ISSUE THREAD

**Issue by Bert-Proesmans** [MicrosoftDocs/entra-docs#967]
Following the documentation about access packages policies, specifically the "None" assignment; https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-access-package-request-policy#none-administrator-direct-assignments-only

There is a note added (see below) that does not clarify if the following intuitive process works or not;

1. Create package named ZPackage
2. Create second policy, named AdminPolicy, with none assignment
3. Remove first policy

My expectation is that me, in the role of Entra Global Administrator or Identity Governance Administrator or Catalog owner, can now assign any internal user to the package ZPackage using the documentation here; https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-access-package-assignments#directly-assign-a-user

1. Go to package ZPackage
2. Go to assignments
3. Click "new assignment"
4. Add assignment using policy AdminPolicy and internal existing user YUser

But that doesn't seem to work in my case, I receive API error: You don't meet policy requirements to request this entitlement.
**Is this error about the entitlement package policy?**
**Is this error about privileges/license of my admin user account?**
**Is this error about YUser?**
**Am I supposed to create another policy that applies to YUser I want to add manually as administrator?**

I understand the note as "there should not be another policy that applies to YUser, because if that policy enforces approval the admin assignment fails". But the note is not clearly worded like that, but also I have the situation like my interpratation (there are no other policies) and the manual admin assignment still doesn't work.

Both of the linked documentation pages have the following note;

> [!NOTE]
> When assigning users to an access package, administrators will need to verify that the users are eligible for that access package based on the existing policy requirements. Otherwise, the users won't successfully be assigned to the access package. If the access package contains a policy that requires user requests to be approved, users can't be directly assigned to the package without necessary approval(s) from the designated approver(s).

There are two commits adding both note at seperate times, this is one of them; https://github.com/MicrosoftDocs/entra-docs/commit/321c86e80998fa767363bc0c2807a73df8a7e234 Both commits lack additional context.

Additional context; The user performing execution of the above steps has the following properties;
* Entra P2 license assigned
* Global Admin and Governance ID Admin
* Catalog Owner
REF; https://learn.microsoft.com/en-us/entra/id-governance/entitlement-management-access-package-assignments#prerequisites

---
#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: e3d2e0b2-cba5-c6ca-fc37-100f3982eec0
* Version Independent ID: 6a0b4a02-a46d-8cd4-360b-54d77ff554b3
* Content: [Use Container Storage Interface (CSI) driver for Azure Blob storage on Azure Kubernetes Service (AKS) - Azure Kubernetes Service](https://learn.microsoft.com/en-us/azure/aks/azure-blob-csi?tabs=NFS#before-you-begin)
* Content Source: [articles/aks/azure-blob-csi.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/aks/azure-blob-csi.md)
* Service: **azure-kubernetes-service**
* Sub-service: **aks-storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by TPavanBalaji** [comment]
@Bert-Proesmans 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Bert-Proesmans** [comment]
Hi @TPavanBalaji, just letting you know that the (automatic) assignment of document details is incorrect. The service topic is Entra ID -> ID Governance -> Entitlement Management.

**Comment by ManoharLakkoju-MSFT** [comment]
@Bert-Proesmans 
Thank you for bringing this to our attention.
I've delegated this to content author @tamram, who will review it and offer their insightful opinions.

**Comment by CelesteDG** [comment]
Thank you, @Bert-Proesmans for your feedback.

We've moved to a unified user feedback system so I've notified our content dev about this issue and we'll be tracking it in Azure DevOps along with other feedback. Thank you.

#please-close
