### ISSUE TITLE
Entra Connector Times out

### ISSUE THREAD

**Issue by bigalnz** [MicrosoftDocs/entra-docs#969]
I am trying to get the entra connector to work on IIS  on Windows Server 2022.

I have followed all the steps listed and the connector is connected - but after authenticating it always times out. THis is for http://localhost/ - which works locally.

Any ideas?

---
#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: 2bfe7e36-297f-9496-8ace-8a750831c912
* Version Independent ID: afe86f38-e147-1061-3196-ed3432af0596
* Content: [How to configure connectors for Microsoft Entra Private Access - Global Secure Access](https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-configure-connectors#transport-layer-security-tls-requirements)
* Content Source: [docs/global-secure-access/how-to-configure-connectors.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/global-secure-access/how-to-configure-connectors.md)
* Service: **global-secure-access**
* Sub-service: **entra-private-access**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by TPavanBalaji** [comment]
@bigalnz 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by bigalnz** [comment]
This is the first guide : 
https://learn.microsoft.com/en-us/entra/global-secure-access/how-to-configure-connectors#transport-layer-security-tls-requirements. 

Thanks

**Comment by bigalnz** [comment]
PS: I have also been in touch with Azure support - but they do not seem to know what the issue is.

**Comment by TPavanBalaji** [comment]
@bigalnz 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by bigalnz** [comment]
Thanks - @kenwith please feel free to reach out :-)

**Comment by CelesteDG** [comment]
Thank you for your feedback. I've transferred the feedback to our unified user feedback mechanism, where the issue will be triaged and tracked as an Azure DevOps work item.

#please-close

**Comment by bigalnz** [comment]
Wait - I never herd from @kenwith or anyone else? 
Every ticket I have opened with MS Support has been unable to resolve. Am I going in circles here?

**Comment by kenwith** [comment]
@bigalnz - sorry, missed this and it was lost in the doc feedback. MS Support should be able to resolve and they should escalate. You can loop me into the support thread and let's try to get it escalated. There is a troubleshooting article that support engineering mostly owns and it might be helpful. It is here: https://learn.microsoft.com/en-us/entra/global-secure-access/troubleshoot-connectors  My email at Microsoft is the same as my github.
