### ISSUE TITLE
Supported MFA options in External Microsoft Entra Tenants

### ISSUE THREAD

**Issue by dangibbons-xlab** [MicrosoftDocs/entra-docs#977]
We have a Microsoft Entra External tenant that contains an app that's used by our business customers.

New users don't sign up for the app, their accounts are created by admins from within our app and this is done using the Microsoft Graph API.

We also have a conditional access policy in place to enforce MFA when logging into the app.

Although we're having issues configuring MFA for certain account types.

I've outlined below the account types that we are using and the types where MFA is working and not working

1. External business customers with local accounts (Creation type = `Local account`)

- Can have the email authentication method configured for their user and can login to our app as expected using MFA

2. Internal employees who are members and have directory roles in the external tenant and have been invited from our company workforce tenant (Creation type = `Invitation` & Identity = `ExternalAzureAD`)

- Can configure an authenticator app at https://mysignins.microsoft.com/security-info and can login to our app as expected using MFA

3. External business customers who are guests in our external tenant and have been invited from their home tenant (Creation type = `Invitation` & Identity = `ExternalAzureAD`)

- Encounter a blank white screen when they visit https://mysignins.microsoft.com/security-info and switch to our external tenant, so can’t configure their authenticator app
- When we configure the email authentication method for their account they can enter their email and password which brings them to the screen which tells them they've had an OTP sent to their email, although when they enter the code they end up in an infinite retry loop where they appear back at the same screen and each time they get another OTP sent to their email
- When we configure the mobile (SMS) authentication method for their account they can login to our app as expected using MFA (although SMS isn't suitable for these customers, so we can't use this a a long term option)

The closest related documentation we've found regarding MFA options is here : https://learn.microsoft.com/en-us/entra/external-id/customers/concept-supported-features-customers#identity-providers-and-authentication-methods (but there doesn't look to be anything in the documentation regarding what MFA options are supported for our 3rd customer account type outlined above)

Please could you give guidance on why Email OTP MFA isn't working for our 3rd customer account type outlined above?

---
#### Document Details
 
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*
 
* ID: b05f311f-f88c-e54c-7b40-ecd7a1056656
* Version Independent ID: f5a5a217-9681-8732-2212-e740dfc02092
* Content: [Supported features in external tenants - Microsoft Entra External ID](https://learn.microsoft.com/en-us/entra/external-id/customers/concept-supported-features-customers#identity-providers-and-authentication-methods)
* Content Source: [docs/external-id/customers/concept-supported-features-customers.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/external-id/customers/concept-supported-features-customers.md)
* Service: **entra-external-id**
* Sub-service: **customers**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by TPavanBalaji** [comment]
@dangibbons-xlab 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@dangibbons-xlab 
Thank you for bringing this to our attention.
I've delegated this to content author @msmimart, who will review it and offer their insightful opinions.

**Comment by CelesteDG** [comment]
Thank you, @dangibbons-xlab, for the feedback.

We've moved to a unified feedback mechanism and will no longer be using GitHub issues. I've captured your feedback and we'll be opening an Azure DevOps work item to track the request. Thank you.

#please-close
