### ISSUE TITLE
Private DNS option missing in Entra Private access 

### ISSUE THREAD

**Issue by vbakshi123** [MicrosoftDocs/entra-docs#978]
Has anyone else seen that the "Private DNS" tab is missing on the Entra Global Secure Access (now in GA) Quick Access Application. It only shows the "Add Quick Access Application Segement"

![image](https://github.com/MicrosoftDocs/entra-docs/assets/20863238/1d0d2ee8-ca54-4e0a-90d0-f64fa1ea362d)

**Comment by TPavanBalaji** [comment]
@vbakshi123 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by Twikki** [comment]
Good day,

I am also missing this tab. I don't see it in my tenant either. I set up an Enterprise application, and tested with RDP. it works fine. But I cannot find the tab Private DNS, as shown in John Savill's video for example:
https://youtu.be/qdNzvy5U3Sw?t=568

**Comment by vbakshi123** [comment]
> @vbakshi123 It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks! Don't see

Added a screenshot which is there in some of the other websites where they say to enable private DNS
<img width="694" alt="image" src="https://github.com/MicrosoftDocs/entra-docs/assets/20863238/1b9fb5d4-204b-46de-9a8f-8f6b6420c327">

**Comment by TPavanBalaji** [comment]
@vbakshi123 
Could you please add a link to the documentation you are following for better understanding. So, we can assist you further.

**Comment by andres-canello** [comment]
Private DNS is still in Private Preview, that's why it's not visible on the portal.

**Comment by CelesteDG** [comment]
Answer provided: Private DNS is still in Private Preview and therefore not available in all tenants. Thank you.

#please-close
