### ISSUE TITLE
Some service plans are missing in some Microsoft Teams Rooms licenses.

### ISSUE THREAD

**Issue by chkoide** [MicrosoftDocs/entra-docs#979]
This issue is about https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference.

1. Add the service plan below to the CSV file. Microsoft Teams Rooms Basic for EDU license has some service plans, but one of them is missing.
    - Office 365 Global  Teams Rooms Basic  Teams Rooms Basic  c8529366-cffd-4415-ab8f-be0144a33ab1  Teams_Rooms_Basic

2. About Microsoft Teams Rooms Basic license, there are 3 service plans missing. Missing service plans are "Teams Rooms Basic", "Teams Rooms Test1" and "Teams Rooms Test2". Add these service plans to the document.In the current document, only other 3 service plans are displayed.

    - Microsoft Teams Rooms Basic   Microsoft_Teams_Rooms_Basic 6af4b3d6-14bb-4a2a-960c-6c902aad34f3

        - MCOMEETADV (3e26ee1f-8a5f-4d52-aee2-b81ce45c8f40)
        - TEAMS1 (57ff2da0-773e-42df-b2af-ffb7a2317929)
        - WHITEBOARD_PLAN3 (4a51bca5-1eff-43f5-878c-177680f191af)

        - Microsoft 365 Audio Conferencing (3e26ee1f-8a5f-4d52-aee2-b81ce45c8f40)
        - Microsoft Teams (57ff2da0-773e-42df-b2af-ffb7a2317929)
        - Whiteboard (プラン 3) (4a51bca5-1eff-43f5-878c-177680f191af)

3. About Teams_Room_Basic and Teams_Room_Pro service plans, the displayname is different. In some licenses, Teams_Room_Basic is used, but in other licenses, Teams Rooms Test 1 is used. These are same service plan id, so I would be appreciated if you modify  Teams_Room_Basic and Teams_Room_Pro  to the below.[14]()
    - Teams Rooms Test 1 (8081ca9c-188c-4b49-a8e5-c23b5e9463a8)
    - Teams Rooms Test 2 (ec17f317-f4bc-451e-b2da-0167e5c260f9)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c245452-161d-89a1-c026-99a0721cf071
* Version Independent ID: 16dec59a-eb83-1837-4efd-4645e7aeaed2
* Content: [Product names and service plan identifiers for licensing - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference)
* Content Source: [docs/identity/users/licensing-service-plan-reference.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/users/licensing-service-plan-reference.md)
* Service: **entra-id**
* Sub-service: **users**
* GitHub Login: @Nicholak-MS
* Microsoft Alias: **nicholak**

**Comment by PesalaPavan** [comment]
@chkoide 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by Nicholak-MS** [comment]
@PesalaPavan can you assign this to @fruitninja3 please? She will address the change.

**Comment by Naveenommi-MSFT** [comment]
@MicrosoftGuyJFlo 
Could you please review add comments on this, update as appropriate.

**Comment by MicrosoftGuyJFlo** [comment]
@Nicholak-MS, @fruitninja3 needs to complete their GitHub setup to be assigned tasks.

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred the feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue. Have notified PM as well.

#please-close
