### ISSUE TITLE
There is no process to revert the SCIM Provisioning Mode to "Manual"

### ISSUE THREAD

**Issue by alexfca** [MicrosoftDocs/entra-docs#992]
The SCIM documentation details the process to enable Provisioning in many places.
eg.
https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups

However in the event where SCIM should be turned off completely and disconnected, there is no documentation and no obvious way to achieve this.

After following the guides and enabling Automatic Provisioning, setting this back to Manual is not allowed in the UI.
![image](https://github.com/MicrosoftDocs/entra-docs/assets/75228224/f68d5c93-b5f3-418d-bda1-7b5a1170b141)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 271dc426-fb47-7441-d627-ec11f8c7a6ea
* Version Independent ID: 4cb8bfc8-4748-e501-425a-e4c2da0f5f5a
* Content: [Tutorial - Develop a SCIM endpoint for user provisioning to apps from Microsoft Entra ID - Microsoft Entra ID](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups)
* Content Source: [docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md](https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/identity/app-provisioning/use-scim-to-provision-users-and-groups.md)
* Service: **entra-id**
* Sub-service: **app-provisioning**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by PesalaPavan** [comment]
@alexfca 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by CelesteDG** [comment]
Thank you for your feedback. Please note that I transferred this feedback to UUF as we're moving away from GitHub issues and into a unified user feedback mechanism. That feedback will be triaged and an ADO work item opened and added to our queue.

#please-close
