### ISSUE TITLE
Permissions for Verified ID and LCW are missing

### ISSUE THREAD

**Issue by axlrod86** [MicrosoftDocs/entra-docs#995]
There are no tasks for some features such as Life Cycle workflows, Entitlement Management integrations with Verified ID and Logic Apps

**Comment by PesalaPavan** [comment]
@axlrod86 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by PesalaPavan** [comment]
@axlrod86 
We are going to close this thread but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
